// Decor pack. Floor Lamp, Wall Lamp, Rug. Permanent ids 1100-1105.
import { registerPack } from '../registry.js'

const blocks = [
  [1100, 'floorLampOff', 'wrap_floorLampOff', 'Fl', null],
  [1101, 'floorLampOn', 'wrap_floorLampOn', 'Fo', null],
  [1102, 'wallLampOff', 'wrap_wallLampOff', 'Wl', null],
  [1103, 'wallLampOn', 'wrap_wallLampOn', 'Wo', null],
  [1104, 'rugAnchor', 'wrap_rugAnchor', 'Ra', null],
  [1105, 'rugPart', 'wrap_rugPart', 'Rp', null],
]

const items = [
  { key: 'floorLamp', def: { svg: 'floorLamp', letter: 'Fl', base: 0, sell: false, stack: 1 } },
  { key: 'wallLamp', def: { svg: 'wallLamp', letter: 'Wl', base: 0, sell: false, stack: 1 } },
  { key: 'rug', def: { svg: 'rug', letter: 'Ru', base: 0, sell: false, stack: 1 } },
]

const recipes = [
  { id: 'floorLamp', at: 'woodshop', in: [['ironIngot', 1], ['glass', 1], ['stick', 1]], out: ['floorLamp', 1], secs: 4 },
  { id: 'wallLamp', at: 'woodshop', in: [['ironIngot', 1], ['glass', 1]], out: ['wallLamp', 1], secs: 3 },
  { id: 'rug', at: 'woodshop', in: [['woolBlue', 4]], out: ['rug', 1], secs: 5, wool: true },
]

registerPack({
  id: 'decor',
  v: 1,
  blocks,
  items,
  recipes,
  strings: {
    en: {
      floorLamp: 'Floor Lamp',
      wallLamp: 'Wall Lamp',
      rug: 'Rug',
      placeOnWall: 'Place on a wall',
      decorJust: 'Just make',
      decorDesign: 'Design it',
      lampHeight: 'Height',
      lampShort: 'Short',
      lampStandard: 'Standard',
      lampTall: 'Tall',
      shadeNatural: 'Natural',
      shadeCream: 'Cream',
      shadeTeal: 'Teal',
      rugMain: 'Main',
      rugTrim: 'Trim',
      decorNeedTools: 'Hang 4 tools first',
      decorNeedWool: 'Need 4 Wool',
      decorNeedItem: 'Need {n} {item}',
      decorMeasureLamp: 'Measure the shade. It sits about one block up.',
      decorMeasureRug: 'Measure both colours. The rug is two blocks wide.',
    },
    uk: {
      floorLamp: 'Підлогова лампа',
      wallLamp: 'Настінна лампа',
      rug: 'Килим',
      placeOnWall: 'Постав на стіну',
      decorJust: 'Просто зроби',
      decorDesign: 'Спроектуй',
      lampHeight: 'Висота',
      lampShort: 'Низька',
      lampStandard: 'Стандартна',
      lampTall: 'Висока',
      shadeNatural: 'Натуральний',
      shadeCream: 'Кремовий',
      shadeTeal: 'Бірюзовий',
      rugMain: 'Основний',
      rugTrim: 'Оздоблення',
      decorNeedTools: 'Спочатку повісь 4 інструменти',
      decorNeedWool: 'Потрібні 4 вовни',
      decorNeedItem: 'Потрібно {n} {item}',
      decorMeasureLamp: 'Спершу заміряй. Абажур сидить приблизно на блок угорі.',
      decorMeasureRug: 'Заміряй обидва кольори. Килим завширшки два блоки.',
    },
    ru: {
      floorLamp: 'Напольная лампа',
      wallLamp: 'Настенная лампа',
      rug: 'Ковёр',
      placeOnWall: 'Поставь на стену',
      decorJust: 'Просто сделай',
      decorDesign: 'Спроектируй',
      lampHeight: 'Высота',
      lampShort: 'Низкая',
      lampStandard: 'Стандартная',
      lampTall: 'Высокая',
      shadeNatural: 'Натуральный',
      shadeCream: 'Кремовый',
      shadeTeal: 'Бирюзовый',
      rugMain: 'Основной',
      rugTrim: 'Отделка',
      decorNeedTools: 'Сначала повесь 4 инструмента',
      decorNeedWool: 'Нужны 4 шерсти',
      decorNeedItem: 'Нужно {n} {item}',
      decorMeasureLamp: 'Сначала измерь. Абажур стоит примерно на блок выше.',
      decorMeasureRug: 'Измерь оба цвета. Ковёр шириной в два блока.',
    },
    es: {
      floorLamp: 'Lámpara de pie',
      wallLamp: 'Lámpara de pared',
      rug: 'Alfombra',
      placeOnWall: 'Coloca en una pared',
      decorJust: 'Solo hacer',
      decorDesign: 'Diseñarlo',
      lampHeight: 'Altura',
      lampShort: 'Corta',
      lampStandard: 'Estándar',
      lampTall: 'Alta',
      shadeNatural: 'Natural',
      shadeCream: 'Crema',
      shadeTeal: 'Verde azulado',
      rugMain: 'Principal',
      rugTrim: 'Borde',
      decorNeedTools: 'Cuelga 4 herramientas primero',
      decorNeedWool: 'Hacen falta 4 de lana',
      decorNeedItem: 'Hace falta {n} {item}',
      decorMeasureLamp: 'Mide primero. La pantalla queda a un bloque de alto.',
      decorMeasureRug: 'Mide los dos colores. La alfombra mide dos bloques.',
    },
    ar: {
      floorLamp: 'مصباح أرضي',
      wallLamp: 'مصباح جداري',
      rug: 'سجادة',
      placeOnWall: 'ضعه على الحائط',
      decorJust: 'اصنع فقط',
      decorDesign: 'صممه',
      lampHeight: 'الارتفاع',
      lampShort: 'قصير',
      lampStandard: 'قياسي',
      lampTall: 'طويل',
      shadeNatural: 'طبيعي',
      shadeCream: 'كريمي',
      shadeTeal: 'أزرق مخضر',
      rugMain: 'رئيسي',
      rugTrim: 'حافة',
      decorNeedTools: 'علّق 4 أدوات أولاً',
      decorNeedWool: 'يلزم 4 صوف',
      decorNeedItem: 'يلزم {n} {item}',
      decorMeasureLamp: 'قس أولاً. الغطاء يرتفع حوالي بلوك واحد.',
      decorMeasureRug: 'قس اللونين. السجادة عرضها بلوكين.',
    },
    'fa-AF': {
      floorLamp: 'چراغ زمینی',
      wallLamp: 'چراغ دیواری',
      rug: 'فرش',
      placeOnWall: 'روی دیوار بگذار',
      decorJust: 'فقط بساز',
      decorDesign: 'طراحی کن',
      lampHeight: 'بلندی',
      lampShort: 'کوتاه',
      lampStandard: 'استاندارد',
      lampTall: 'بلند',
      shadeNatural: 'طبیعی',
      shadeCream: 'کرم',
      shadeTeal: 'فیروزه‌ای',
      rugMain: 'اصلی',
      rugTrim: 'حاشیه',
      decorNeedTools: 'اول ۴ ابزار را بیاویز',
      decorNeedWool: '۴ پشم لازم است',
      decorNeedItem: '{n} {item} لازم است',
      decorMeasureLamp: 'اول اندازه بگیر. کلاهک حدود یک بلوک بالا است.',
      decorMeasureRug: 'هر دو رنگ را اندازه بگیر. فرش دو بلوک پهنا دارد.',
    },
    rw: {
      floorLamp: 'Itara ryo hasi',
      wallLamp: 'Itara ryo ku rukuta',
      rug: 'Umusambi',
      placeOnWall: 'Shyira ku rukuta',
      decorJust: 'Kora gusa',
      decorDesign: 'Shushanya',
      lampHeight: 'Uburebure',
      lampShort: 'Bugufi',
      lampStandard: 'Bisanzwe',
      lampTall: 'Burebure',
      shadeNatural: 'Kamere',
      shadeCream: 'Ikirem',
      shadeTeal: 'Icyatsi',
      rugMain: 'Icyambere',
      rugTrim: 'Impera',
      decorNeedTools: 'Banza uhanike ibikoresho 4',
      decorNeedWool: 'Ukeneye ubwoya 4',
      decorNeedItem: 'Ukeneye {n} {item}',
      decorMeasureLamp: 'Banza upime. Igipfukisho kiri ku gipimo cya block imwe.',
      decorMeasureRug: 'Pima amabara yombi. Umusambi ufite ubugari bwa block ebyiri.',
    },
    ti: {
      floorLamp: 'ናይ መሬት መብራህቲ',
      wallLamp: 'ናይ ግድሚ መብራህቲ',
      rug: 'መንጸፍ',
      placeOnWall: 'ኣብ ግድሚ ግበሮ',
      decorJust: 'ግበር ጥራይ',
      decorDesign: 'ንድፊ ግበር',
      lampHeight: 'ቁመት',
      lampShort: 'ሓጺር',
      lampStandard: 'መደበኛ',
      lampTall: 'ነዊሕ',
      shadeNatural: 'ተፈጥሮኣዊ',
      shadeCream: 'ክሬም',
      shadeTeal: 'ቲል',
      rugMain: 'ቀንዲ',
      rugTrim: 'ጫፍ',
      decorNeedTools: 'መጀመርታ 4 መሳርሒታት ሰቅል',
      decorNeedWool: '4 ጥምጢ የድሊ',
      decorNeedItem: '{n} {item} የድሊ',
      decorMeasureLamp: 'መጀመርታ ለክዕ። መከደኒ ኣስታት ሓንቲ ብሎክ ልዕሊ ይቐመጥ።',
      decorMeasureRug: 'ክልቲ ሕብርታት ለክዕ። መንጸፍ ስፍሓት ክልተ ብሎክ እዩ።',
    },
  },
})