#!/usr/bin/env python3
"""Bertopia asset pack generator. Deterministic: same inputs -> same bytes.
Inputs : Kenney Voxel Pack (CC0) unzipped at $KENNEY_VOXEL (default /tmp/kpack/voxel), registry_src.py
Outputs: textures/{blocks,items,sprites,minimap}/*.png, atlas/{terrain,alpha,items}.png + .json, registry.json,
         dex/bertodex-en.json, manifest rows (tools/_manifest_tex.csv) consumed by check_pack.py / MANIFEST.csv.
Style  : 32 px, flat colours, 2x2 pixel clusters, 1 px dark outline on items, glare-safe (no pure #FFFFFF).
"""
import os, sys, json, math, hashlib, csv
import numpy as np
from PIL import Image, ImageDraw, ImageFilter
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE); import registry_src as R
KV = os.environ.get('KENNEY_VOXEL', '/tmp/kpack/voxel')
S = 32
KENNEY_URL = 'https://kenney.nl/assets/voxel-pack'
ROWS = []  # manifest rows: id,type,file,size,source_url,license_as_stated,author,made_by,used_by
LIC_K = 'Creative Commons CC0 (as stated on kenney.nl page and License.txt in zip)'
LIC_G = 'Project-original (generated by tools/gen_pack.py; owner trebiluk); no third-party license'
GLARE = np.array([238, 243, 247])  # snow #EEF3F7 is the brightest allowed surface colour (WORLD-2 §4)

def rng(name):
    return np.random.default_rng(int(hashlib.sha1(name.encode()).hexdigest()[:8], 16))
def hexc(h):
    h = h.lstrip('#'); return np.array([int(h[i:i+2], 16) for i in (0, 2, 4)], dtype=float)
def kenney(name, folder='Tiles'):
    im = Image.open(f'{KV}/PNG/{folder}/{name}.png').convert('RGBA')
    return im.resize((S, S), Image.BOX)
def arr(im): return np.asarray(im.convert('RGBA')).astype(float)
def img(a): return Image.fromarray(np.clip(a, 0, 255).astype(np.uint8), 'RGBA')
def deglare(a):
    """Clamp every opaque pixel so no channel set reaches pure white; brightest = #EEF3F7."""
    rgb = a[..., :3]; lum = rgb.mean(-1, keepdims=True)
    hot = (rgb > GLARE).any(-1, keepdims=True)
    a[..., :3] = np.where(hot, np.minimum(rgb, GLARE), rgb)
    return a
def noise_tile(base, var=14, seed='x', cluster=2, lo=None):
    r = rng(seed); n = S // cluster
    v = r.normal(0, var, (n, n, 1)).repeat(cluster, 0).repeat(cluster, 1)
    a = np.zeros((S, S, 4)); a[..., :3] = hexc(base) + v; a[..., 3] = 255
    return a
def speckle(a, color, frac, seed, size=1):
    r = rng(seed); c = hexc(color)
    for _ in range(int(frac * S * S / (size * size))):
        x, y = r.integers(0, S - size + 1, 2); a[y:y+size, x:x+size, :3] = c + r.normal(0, 6, 3)
    return a
def bevel(a, d=18):
    a[0, :, :3] += d; a[:, 0, :3] += d; a[-1, :, :3] -= d; a[:, -1, :3] -= d; return a

# ---------- ore overlays: each ore has a distinct SHAPE (WORLD-1 §7), not only a colour ----------
def ov_dots(a, col, seed, n=7, r0=2):            # iron: round rusty dots
    im = img(a); d = ImageDraw.Draw(im); g = rng(seed)
    for _ in range(n):
        x, y = g.integers(3, S-4, 2); rr = r0 + int(g.integers(0, 2))
        d.ellipse([x-rr, y-rr, x+rr, y+rr], fill=tuple(hexc(col).astype(int)), outline=(70, 40, 30))
    return arr(im)
def ov_streaks(a, c1, c2, seed, n=4):             # copper: diagonal orange streaks with green tips
    im = img(a); d = ImageDraw.Draw(im); g = rng(seed)
    for _ in range(n):
        x, y = g.integers(0, S-10, 2); L = int(g.integers(6, 11))
        d.line([x, y, x+L, y+L//2], fill=tuple(hexc(c1).astype(int)), width=2)
        d.rectangle([x+L-1, y+L//2-1, x+L, y+L//2], fill=tuple(hexc(c2).astype(int)))
    return arr(im)
def ov_flakes(a, col, seed, n=10):                # zinc: thin grey-blue flakes (3x1 / 1x3)
    g = rng(seed); c = hexc(col)
    for i in range(n):
        x, y = g.integers(1, S-4, 2)
        if i % 2: a[y, x:x+4, :3] = c; a[y+1, x+1:x+3, :3] = c * 0.8
        else: a[y:y+4, x, :3] = c; a[y+1:y+3, x+1, :3] = c * 0.8
    return a
def ov_squares(a, col, seed, n=6):                # tin: dark brown squares with a light corner
    g = rng(seed); c = hexc(col)
    for _ in range(n):
        x, y = g.integers(1, S-5, 2); a[y:y+4, x:x+4, :3] = c; a[y, x, :3] = c + 60
    return a
def ov_spikes(a, col, seed, n=5):                 # quartz: white crystal spikes
    im = img(a); d = ImageDraw.Draw(im); g = rng(seed); c = tuple(hexc(col).astype(int))
    for _ in range(n):
        x, y = g.integers(4, S-4), g.integers(10, S-2); h = int(g.integers(5, 9))
        d.polygon([(x-2, y), (x, y-h), (x+2, y)], fill=c, outline=(150, 160, 170))
    return arr(im)
def ov_lines(a, col, seed, n=5):                  # silver: thin bright lines
    im = img(a); d = ImageDraw.Draw(im); g = rng(seed); c = tuple(hexc(col).astype(int))
    for _ in range(n):
        x, y = g.integers(0, S-8, 2); d.line([x, y, x+int(g.integers(5, 9)), y-int(g.integers(-2, 3))], fill=c, width=1)
    return arr(im)
def ov_vein(a, col, seed):                         # gold: one yellow wiggly vein in quartz-white rim
    im = img(a); d = ImageDraw.Draw(im); g = rng(seed)
    pts = [(0, 10 + int(g.integers(0, 12)))]
    for x in range(4, S + 4, 4): pts.append((x, int(np.clip(pts[-1][1] + g.integers(-4, 5), 3, S-4))))
    d.line(pts, fill=(226, 222, 210), width=4); d.line(pts, fill=tuple(hexc(col).astype(int)), width=2)
    return arr(im)
def ov_glow(a, col, seed, n=9):                    # glow moss: teal dots with a 1 px halo
    g = rng(seed); c = hexc(col)
    for _ in range(n):
        x, y = g.integers(2, S-3, 2)
        a[y-1:y+2, x-1:x+2, :3] = a[y-1:y+2, x-1:x+2, :3] * 0.5 + c * 0.5; a[y, x, :3] = c + 30
    return a
def ov_grains(a, col, seed, n=40):                 # black sand / ilmenite style grains
    return speckle(a, col, n / (S*S), seed)
def ov_flecks(a, col, seed, n=8):                  # platinum: silver-white rounded flecks, dark rim
    im = img(a); d = ImageDraw.Draw(im); g = rng(seed); c = tuple(hexc(col).astype(int))
    for _ in range(n):
        x, y = g.integers(3, S-4, 2); d.rectangle([x-1, y-1, x+1, y+1], fill=c, outline=(40, 40, 50))
    return arr(im)
def ov_layers(a, col, seed):                        # graphite: shiny stacked flakes
    g = rng(seed); c = hexc(col)
    for _ in range(6):
        x, y = g.integers(0, S-8), g.integers(2, S-3); a[y, x:x+8, :3] = c; a[y+1, x+1:x+7, :3] = c + 40
    return a

# ---------- machine family faces ----------
STEEL = '#8a929c'; FRAME = '#565d66'
ACCENT = {'power': '#e3b341', 'logistics': '#3fa7c2', 'network': '#7a5cc7', 'craft': '#d27a3c', 'fun': '#e05a8a', 'music': '#5bbf8a', 'town': '#b78a5a'}
def machine(seed, accent, glyph=None):
    a = noise_tile(STEEL, 6, seed); a[:2, :, :3] = a[-2:, :, :3] = a[:, :2, :3] = a[:, -2:, :3] = hexc(FRAME)
    for (x, y) in [(3, 3), (S-4, 3), (3, S-4), (S-4, S-4)]: a[y, x, :3] = hexc('#c9ced4')
    a[S-7:S-5, 6:S-6, :3] = hexc(ACCENT[accent])
    im = img(a); d = ImageDraw.Draw(im)
    if glyph: glyph(d)
    return arr(im)
def g_screen(col):
    return lambda d: (d.rectangle([7, 6, 24, 18], fill=(28, 40, 52), outline=(20, 24, 28)), d.line([9, 10, 18, 10], fill=col), d.line([9, 13, 15, 13], fill=col))
def g_fire(d):
    d.rectangle([8, 9, 23, 20], fill=(40, 30, 28)); d.polygon([(12, 20), (16, 11), (20, 20)], fill=(240, 150, 50)); d.polygon([(14, 20), (16, 15), (18, 20)], fill=(250, 220, 120))
def g_slots(n):
    def f(d):
        for i in range(n): d.rectangle([6 + i * 5, 8, 9 + i * 5, 18], fill=(36, 40, 46), outline=(110, 200, 220))
    return f
def g_bolt(d): d.polygon([(17, 6), (11, 16), (16, 16), (14, 23), (21, 12), (16, 12)], fill=(240, 200, 70))
def g_gear(d): d.ellipse([10, 8, 22, 20], outline=(230, 140, 70), width=2); d.ellipse([14, 12, 18, 16], fill=(230, 140, 70))
def g_net(d):
    for p in [(16, 8), (9, 18), (23, 18)]: d.ellipse([p[0]-2, p[1]-2, p[0]+2, p[1]+2], fill=(160, 130, 230))
    d.line([16, 8, 9, 18], fill=(160, 130, 230)); d.line([16, 8, 23, 18], fill=(160, 130, 230)); d.line([9, 18, 23, 18], fill=(160, 130, 230))
def wood_face(seed, glyph=None):
    a = arr(kenney('wood')); im = img(a); d = ImageDraw.Draw(im)
    if glyph: glyph(d)
    return arr(im)
def door_half(top, style):
    base = {'wood': '#a8743f', 'glass': '#9a6b3a', 'metal': '#7d8590', 'slide': '#b8c2cc', 'workshop': '#4f6fa8'}[style]
    a = np.zeros((S, S, 4)); x0, x1 = 6, 26
    a[:, x0:x1, :3] = hexc(base) + rng(style+str(top)).normal(0, 5, (S, x1-x0, 1)); a[:, x0:x1, 3] = 255
    a[:, x0, :3] -= 40; a[:, x1-1, :3] -= 40
    if style in ('glass', 'slide') and top: a[4:20, x0+3:x1-3, :3] = hexc('#a9d8e6'); a[4:20, x0+3:x1-3, 3] = 150
    if style == 'metal': a[6::8, x0+2:x1-2, :3] += 30
    if style == 'workshop': a[8:14, x0+5:x1-5, :3] = hexc('#e3b341')
    if not top: a[S-14, x1-6:x1-3, :3] = hexc('#e3c066')
    if top: a[0, x0:x1, :3] -= 30
    else: a[-1, x0:x1, :3] -= 30
    return a

def cross(draw_fn, seed):
    im = Image.new('RGBA', (S, S), (0, 0, 0, 0)); d = ImageDraw.Draw(im); draw_fn(d, rng(seed)); return arr(im)
def bush(leaf, fruit, shape='dots'):
    def f(d, g):
        for i in range(7):
            x = 4 + i * 4; d.line([x, S-1, x + int(g.integers(-3, 4)), 10 + int(g.integers(0, 8))], fill=tuple(hexc(leaf).astype(int)), width=2)
        for _ in range(7 if shape == 'dots' else 4):
            x, y = int(g.integers(4, S-5)), int(g.integers(6, 20))
            if shape == 'dots': d.ellipse([x-2, y-2, x+2, y+2], fill=tuple(hexc(fruit).astype(int)))
            elif shape == 'cob': d.rectangle([x-1, y-3, x+2, y+4], fill=tuple(hexc(fruit).astype(int)), outline=(120, 100, 30))
            elif shape == 'flower':
                c = tuple(hexc(fruit).astype(int))
                for dx, dy in [(-2, 0), (2, 0), (0, -2), (0, 2)]: d.ellipse([x+dx-1, y+dy-1, x+dx+1, y+dy+1], fill=c)
                d.point((x, y), fill=(240, 200, 60))
    return f

def T(name):  # texture recipes (block faces)
    k = name
    # --- live atlas order (indices 0..20 identical names to bloxbert-src/assets/atlas.json) ---
    if k in ('grass_top', 'dirt_grass', 'dirt', 'stone', 'greystone', 'stone_coal', 'sand', 'gravel_stone', 'brick_red',
             'brick_grey', 'wood', 'trunk_top', 'trunk_side', 'cotton_blue', 'cotton_green', 'cotton_red', 'cotton_tan',
             'snow', 'ice', 'redsand', 'dirt_snow', 'trunk_white_side', 'trunk_white_top', 'water', 'lava'):
        a = arr(kenney(k))
        if k == 'snow': a[..., :3] = a[..., :3] * 0.94 + hexc('#e3ecf2') * 0.06
        if k == 'ice': a[..., :3] = a[..., :3] * 0.9 + hexc('#bfe6ef') * 0.1
        if k == 'water': a[..., 3] = 170
        return a, 'kenney:' + k
    if k == 'leaves': return arr(kenney('leaves_transparent')), 'kenney:leaves_transparent'
    if k == 'glass': return arr(kenney('glass_frame')), 'kenney:glass_frame'
    if k.startswith('wheat_stage'): return arr(kenney(k)), 'kenney:' + k
    stone = lambda: arr(kenney('stone'))
    G = None
    ores = {
        'ore_iron': lambda: ov_dots(stone(), '#b0643a', k), 'ore_copper': lambda: ov_streaks(stone(), '#d9813e', '#4fae8c', k),
        'ore_zinc': lambda: ov_flakes(stone(), '#8fa3bd', k), 'ore_tin': lambda: ov_squares(stone(), '#4b3a2e', k),
        'ore_quartz': lambda: ov_spikes(stone(), '#e6e8ea', k), 'ore_silver': lambda: ov_lines(stone(), '#e8eef4', k),
        'ore_gold': lambda: ov_vein(stone(), '#e8b923', k), 'glow_moss': lambda: ov_glow(noise_tile('#2f4d45', 10, k), '#4fe0c8', k),
        'ore_ilmenite': lambda: ov_squares(arr(kenney('greystone')), '#22252b', k, 7),
        'ore_platinum': lambda: ov_flecks(noise_tile('#3e3a44', 8, 'basalt'), '#d9dde3', k),
        'ore_graphite': lambda: ov_layers(noise_tile('#4a4d52', 8, k), '#2a2c30', k),
    }
    if k in ores: return ores[k](), 'generated'
    plain = {
        'coreplate': ('#3b3f47', 6), 'clay': ('#8e9fae', 5), 'clay_boundary': ('#b9a48a', 5), 'basalt': ('#3e3a44', 8),
        'granite': ('#b9b2ab', 10), 'red_soil': ('#a5522f', 10), 'bauxite': ('#b5653f', 12), 'salt_crust': ('#e8e4da', 6),
        'sand_black': ('#2b2a2e', 10), 'sand_quartz': ('#e2d6b5', 9), 'gravel_panned': ('#8d8a85', 8),
        'molten': ('#ff8a2a', 18), 'leaf_pile': ('#c4662f', 16), 'concrete': ('#a7a9ab', 5), 'plywood': ('#c9a46b', 6),
        'copper_block': ('#c27a43', 6), 'steel_block': ('#8e969f', 5), 'cut_stone': ('#9a9ea3', 5),
    }
    if k in plain:
        a = noise_tile(*plain[k], seed=k)
        if k == 'granite': a = speckle(speckle(a, '#5b5552', .06, k + '1'), '#e0d6cc', .05, k + '2')
        if k == 'bauxite': a = ov_dots(a, '#8a3f22', k, 9, 1)
        if k == 'sand_black': a = speckle(a, '#5a5f66', .08, k)
        if k == 'sand_quartz': a = speckle(a, '#f0ece2', .06, k)
        if k == 'salt_crust': a = ov_lines(a, '#c8c2b4', k, 7)
        if k == 'clay_boundary': a[14:18, :, :3] -= 25
        if k == 'gravel_panned': a = speckle(a, '#6d6a66', .1, k, 2)
        if k in ('cut_stone', 'concrete', 'copper_block', 'steel_block'): a = bevel(a)
        if k == 'cut_stone': a[15, :, :3] -= 25; a[:15, 15, :3] -= 25; a[16:, 7, :3] -= 25; a[16:, 23, :3] -= 25
        if k == 'plywood': a[::4, :, :3] -= 14
        if k == 'molten': a = speckle(a, '#ffd36a', .08, k, 2)
        return a, 'generated'
    if k == 'leaves_birch': a = arr(kenney('leaves_transparent')); a[..., :3] = a[..., :3] * 0.6 + hexc('#9fd36a') * 0.4; return a, 'kenney:leaves_transparent (recoloured)'
    if k == 'leaves_spruce': a = arr(kenney('leaves_transparent')); a[..., :3] = a[..., :3] * 0.55 + hexc('#1f4d3a') * 0.45; return a, 'kenney:leaves_transparent (recoloured)'
    if k in ('trunk_spruce_side', 'trunk_spruce_top'):
        a = arr(kenney(k.replace('spruce_', ''))); a[..., :3] *= np.array([0.7, 0.62, 0.58]); return a, 'kenney:' + k.replace('spruce_', '') + ' (recoloured)'
    if k == 'dirt_grass_snow': return arr(kenney('dirt_snow')), 'kenney:dirt_snow'
    if k == 'glass_tinted': a = arr(kenney('glass_frame')); a[..., :3] = a[..., :3] * 0.6 + hexc('#4b5f73') * 0.4; a[..., 3] = np.maximum(a[..., 3], 120); return a, 'kenney:glass_frame (tinted)'
    if k == 'glass_frosted': a = arr(kenney('glass_frame')); a[..., :3] = a[..., :3] * 0.5 + hexc('#d7e4ea') * 0.5; a[..., 3] = np.maximum(a[..., 3], 190); return a, 'kenney:glass_frame (frosted)'
    if k == 'glass_pane': a = arr(kenney('glass_frame')); return a, 'kenney:glass_frame'
    if k == 'mirror': a = noise_tile('#b8c6d0', 4, k); a[4:-4, 4:-4, :3] = hexc('#cfe0ea'); a[6:10, 6:20, :3] = GLARE; a = bevel(a, 30); return a, 'generated'
    # --- stations (live) ---
    if k == 'workbench_top': return wood_face(k, lambda d: (d.rectangle([4, 4, 27, 27], outline=(90, 60, 30)), d.line([8, 10, 20, 10], fill=(150, 150, 160), width=2), d.line([10, 20, 22, 20], fill=(90, 60, 30), width=2))), 'generated (on kenney:wood)'
    if k == 'workbench_side': return wood_face(k, lambda d: d.rectangle([3, 14, 28, 17], fill=(110, 75, 40))), 'generated (on kenney:wood)'
    if k == 'oven_front': return machine(k, 'craft', g_fire), 'generated'
    if k == 'oven_side': return machine(k, 'craft'), 'generated'
    if k == 'oven_top': return machine(k, 'craft', lambda d: d.ellipse([10, 10, 21, 21], outline=(60, 60, 66), width=2)), 'generated'
    if k == 'machine_side': return machine(k, 'logistics'), 'generated'
    if k == 'machine_top': return machine(k, 'logistics', lambda d: d.rectangle([9, 9, 22, 22], outline=(70, 76, 84))), 'generated'
    if k == 'vend_front': return machine(k, 'town', g_slots(4)), 'generated'
    if k == 'store_front': return wood_face(k, lambda d: (d.rectangle([4, 6, 27, 14], fill=(60, 120, 150)), d.ellipse([12, 18, 19, 25], fill=(214, 140, 60), outline=(120, 70, 30)))), 'generated (on kenney:wood)'
    if k == 'store_top': return wood_face(k), 'kenney:wood'
    if k == 'bunk_top': a = arr(kenney('cotton_blue')); a[2:10, 4:28, :3] = hexc('#e6e2d8'); return a, 'generated (on kenney:cotton_blue)'
    if k == 'bunk_side': return wood_face(k, lambda d: (d.rectangle([2, 8, 29, 14], fill=(70, 110, 170)), d.rectangle([2, 22, 29, 25], fill=(110, 75, 40)))), 'generated (on kenney:wood)'
    if k in ('box_front', 'box_side', 'box_top', 'overflow_front', 'cabinet_front', 'cabinet_glass_front', 'apple_crate_side', 'apple_crate_top', 'drafting_top', 'labbench_top', 'labbench_side'):
        def gl(d):
            d.rectangle([1, 1, 30, 30], outline=(96, 62, 30), width=2)
            if k in ('box_front', 'overflow_front'): d.rectangle([13, 12, 18, 17], fill=(200, 170, 80), outline=(80, 60, 20))
            if k == 'overflow_front': d.polygon([(10, 4), (22, 4), (16, 10)], fill=(63, 167, 194))
            if k == 'box_top': d.line([2, 16, 29, 16], fill=(96, 62, 30), width=2)
            if k == 'cabinet_front': d.line([16, 3, 16, 28], fill=(96, 62, 30), width=2); d.point([(14, 16), (18, 16)], fill=(220, 190, 90))
            if k == 'cabinet_glass_front': d.rectangle([5, 5, 26, 26], fill=(150, 200, 215), outline=(96, 62, 30))
            if k == 'apple_crate_top':
                for i in range(9): d.ellipse([4 + (i % 3) * 8, 4 + (i // 3) * 8, 10 + (i % 3) * 8, 10 + (i // 3) * 8], fill=(200, 50, 45))
            if k == 'apple_crate_side': d.line([2, 11, 29, 11], fill=(96, 62, 30), width=2); d.line([2, 21, 29, 21], fill=(96, 62, 30), width=2)
            if k == 'drafting_top': d.rectangle([5, 5, 26, 24], fill=(220, 226, 232)); d.line([8, 9, 20, 9], fill=(63, 120, 194)); d.line([8, 13, 23, 20], fill=(63, 120, 194))
            if k == 'labbench_top': d.rectangle([4, 4, 27, 27], fill=(60, 64, 72)); d.ellipse([8, 9, 14, 20], outline=(79, 224, 200)); d.ellipse([18, 9, 24, 20], outline=(224, 90, 138))
            if k == 'labbench_side': d.rectangle([3, 3, 28, 7], fill=(60, 64, 72))
        return wood_face(k, gl), 'generated (on kenney:wood)'
    if k == 'smelter_front':
        a = arr(kenney('brick_grey')); im = img(a); g_fire(ImageDraw.Draw(im)); return arr(im), 'generated (on kenney:brick_grey)'
    if k in ('smelter_side', 'smelter_top'): return arr(kenney('brick_grey')), 'kenney:brick_grey'
    fam = {'fabricator_front': ('craft', g_gear), 'core_front': ('network', g_net), 'drivebay_front': ('network', g_slots(4)),
           'terminal_front': ('network', g_screen((160, 130, 230))), 'batterybox_front': ('power', g_bolt),
           'sorter_front': ('logistics', lambda d: [d.line([16, 8, x, 24], fill=(110, 200, 220), width=2) for x in (6, 12, 20, 26)]),
           'sorter_side': ('logistics', None), 'cleanbench_front': ('craft', g_screen((120, 220, 240))),
           'locker_front': ('town', lambda d: [d.line([8, y, 23, y], fill=(60, 66, 74)) for y in (6, 8, 10)]), 'locker_side': ('town', None),
           'jukebox_front': ('music', lambda d: (d.ellipse([8, 6, 23, 21], fill=(30, 30, 34), outline=(91, 191, 138), width=2), d.ellipse([14, 12, 17, 15], fill=(224, 90, 138)))),
           'jukebox_side': ('music', None), 'jukebox_top': ('music', lambda d: d.line([8, 15, 23, 15], fill=(30, 30, 34), width=2)),
           'disco_top': ('fun', lambda d: [d.rectangle([2 + (i % 4) * 7, 2 + (i // 4) * 7, 7 + (i % 4) * 7, 7 + (i // 4) * 7], fill=[(224, 90, 138), (63, 167, 194), (227, 179, 65), (122, 92, 199)][(i + i // 4) % 4]) for i in range(16)]),
           }
    if k in fam: a, gfn = fam[k]; return machine(k, a, gfn), 'generated'
    if k == 'solar_top':
        a = noise_tile('#24364f', 4, k); a[:, ::8, :3] = hexc('#8a929c'); a[::8, :, :3] = hexc('#8a929c'); a[1:3, 1:31, :3] += 30; return a, 'generated'
    if k == 'carved_front_blank':  # default face; a player-carved 16x16 face bitmap replaces the centre at runtime
        a = noise_tile('#e07a24', 8, 'pumpkin'); a[:, ::6, :3] -= 30; im = img(a); d = ImageDraw.Draw(im)
        d.rectangle([8, 8, 23, 23], outline=(170, 90, 30)); return arr(im), 'generated'
    if k in ('gift_top', 'gift_side'):
        a = noise_tile('#3a8f5a', 4, k); a[:, 14:18, :3] = hexc('#d94a4a')
        if k == 'gift_top': a[14:18, :, :3] = hexc('#d94a4a')
        return a, 'generated'
    if k in ('hay_top', 'hay_side'):
        a = noise_tile('#d6b25a', 10, k)
        if k == 'hay_side': a[:, ::3, :3] -= 18; a[9:11, :, :3] = hexc('#8a5a2a'); a[21:23, :, :3] = hexc('#8a5a2a')
        else: a = speckle(a, '#b08a3a', .15, k)
        return a, 'generated'
    if k == 'tile_ornament':
        a = noise_tile('#24456b', 4, k); im = img(a); d = ImageDraw.Draw(im)
        for (x, y), c in zip([(8, 9), (22, 11), (12, 23), (24, 24)], [(217, 74, 74), (227, 179, 65), (79, 224, 200), (224, 90, 138)]): d.ellipse([x-4, y-4, x+4, y+4], fill=c); d.point((x-1, y-2), fill=(238, 243, 247))
        return arr(im), 'generated'
    if k == 'stripe_red':
        yy, xx = np.mgrid[0:S, 0:S]; a = np.zeros((S, S, 4)); a[..., 3] = 255
        a[..., :3] = np.where((((xx + yy) // 6) % 2 == 0)[..., None], hexc('#d94a4a'), hexc('#e8e4da')); return a, 'generated'
    if k in ('bounce_top', 'bounce_side'):
        a = noise_tile('#3fb27f', 6, k)
        if k == 'bounce_side': a[::6, :, :3] = hexc('#8a929c')
        else: a = bevel(a, 25)
        return a, 'generated'
    if k in ('note_top', 'note_side'):
        a = arr(kenney('wood_red')); im = img(a); d = ImageDraw.Draw(im)
        d.ellipse([10, 18, 16, 23], fill=(30, 30, 34)); d.line([15, 20, 15, 8], fill=(30, 30, 34), width=2); d.line([15, 8, 21, 10], fill=(30, 30, 34), width=2)
        return arr(im), 'generated (on kenney:wood_red)'
    if k in ('pumpkin_top', 'pumpkin_side', 'jack_front'):
        a = noise_tile('#e07a24', 8, 'pumpkin'); a[:, ::6, :3] -= 30
        if k == 'pumpkin_top': a[13:19, 13:19, :3] = hexc('#4f7a2a')
        if k == 'jack_front':
            im = img(a); d = ImageDraw.Draw(im)
            d.polygon([(7, 13), (11, 9), (13, 13)], fill=(255, 214, 102)); d.polygon([(19, 13), (21, 9), (25, 13)], fill=(255, 214, 102))
            d.arc([8, 14, 24, 26], 10, 170, fill=(255, 214, 102), width=3); a = arr(im)
        return a, 'generated'
    if k in ('tile_skull_pattern', 'tile_rangoli'):
        a = noise_tile('#3a2f4f' if k == 'tile_skull_pattern' else '#f2e6d0', 3, k); im = img(a); d = ImageDraw.Draw(im)
        if k == 'tile_rangoli':
            d.rectangle([3, 3, 28, 28], outline=(120, 110, 96), width=2); d.polygon([(16, 6), (26, 16), (16, 26), (6, 16)], outline=(120, 110, 96), width=2); d.rectangle([13, 13, 19, 19], fill=(150, 140, 124))
        else:
            d.ellipse([9, 7, 23, 20], fill=(232, 226, 214)); d.ellipse([11, 11, 14, 14], fill=(224, 90, 138)); d.ellipse([18, 11, 21, 14], fill=(63, 167, 194)); d.rectangle([12, 20, 20, 24], fill=(232, 226, 214))
            for x in (4, 27): d.ellipse([x-2, 26, x+2, 30], fill=(227, 179, 65))
        return arr(im), 'generated'
    if k in ('bamboo_side', 'bamboo_top'):
        a = noise_tile('#9cbf5a', 6, k)
        if k == 'bamboo_side': a[::8, :, :3] -= 40; a[:, ::8, :3] -= 15
        else: a[8:24, 8:24, :3] = hexc('#d8c88a')
        return a, 'generated'
    if k in ('cinder_side', 'cinder_top'):
        a = bevel(noise_tile('#9b9d9f', 6, k))
        if k == 'cinder_top': a[6:14, 6:26, :3] = a[18:26, 6:26, :3] = hexc('#4a4c4e')
        return a, 'generated'
    if k == 'roof_tile':
        a = noise_tile('#a4483a', 7, k)
        for y in range(0, S, 8): a[y + 6:y + 8, :, :3] -= 40; a[y:y + 8, (y // 8 % 2) * 8::16, :3] -= 18
        return a, 'generated'
    # --- alpha / cross / flat textures ---
    crosses = {
        'reed': bush('#5f9e4a', '#7a5a2e', 'cob'), 'corn_bush': bush('#5f9e4a', '#e8c43a', 'cob'), 'cotton_bush': bush('#4f8a3e', '#ece6dc', 'dots'),
        'flower_teal': bush('#4f8a3e', '#3fb6c9', 'flower'), 'flower_pink': bush('#4f8a3e', '#e05a8a', 'flower'), 'flower_yellow': bush('#4f8a3e', '#e8c43a', 'flower'),
        'marigold': bush('#4f8a3e', '#f08a24', 'flower'), 'corn_stalks': bush('#c9a65a', '#a07a3a', 'cob'),
    }
    if k in crosses: return cross(crosses[k], k), 'generated'
    if k == 'quartz_cluster':
        return cross(lambda d, g: [d.polygon([(x-3, S-1), (x, S-1-h), (x+3, S-1)], fill=(230, 232, 236), outline=(150, 160, 175)) for x, h in [(9, 14), (16, 22), (23, 12)]], k), 'generated'
    if k == 'cobweb':
        def f(d, g):
            for ang in range(0, 360, 45): d.line([16, 16, 16 + 15 * math.cos(math.radians(ang)), 16 + 15 * math.sin(math.radians(ang))], fill=(220, 224, 230, 200))
            for r_ in (5, 10, 14): d.ellipse([16-r_, 16-r_, 16+r_, 16+r_], outline=(220, 224, 230, 170))
        return cross(f, k), 'generated'
    if k == 'glow_strip': return cross(lambda d, g: (d.rectangle([2, 13, 29, 18], fill=(60, 64, 72)), d.rectangle([3, 14, 28, 17], fill=(160, 240, 230))), k), 'generated'
    if k == 'wire_copper': return cross(lambda d, g: (d.line([0, 16, 31, 16], fill=(194, 122, 67), width=3), d.line([16, 0, 16, 31], fill=(194, 122, 67), width=3), d.ellipse([13, 13, 19, 19], fill=(150, 90, 45))), k), 'generated'
    if k == 'papel_picado': return cross(lambda d, g: (d.line([0, 4, 31, 4], fill=(90, 90, 90)), [d.rectangle([1 + i * 8, 5, 6 + i * 8, 16], fill=[(224, 90, 138), (63, 167, 194), (227, 179, 65), (91, 191, 138)][i]) for i in range(4)]), k), 'generated'
    if k == 'string_lights': return cross(lambda d, g: (d.arc([0, -10, 31, 14], 20, 160, fill=(60, 60, 60)), [d.ellipse([x-2, y-2, x+2, y+2], fill=c) for (x, y), c in zip([(5, 8), (11, 11), (17, 12), (23, 11), (28, 8)], [(255, 214, 102), (224, 90, 138), (79, 224, 200), (255, 214, 102), (160, 130, 230)])]), k), 'generated'
    if k == 'winter_lights': return cross(lambda d, g: (d.arc([0, -10, 31, 14], 20, 160, fill=(40, 90, 50)), [d.ellipse([x-2, y-1, x+2, y+4], fill=c) for (x, y), c in zip([(5, 8), (11, 11), (17, 12), (23, 11), (28, 8)], [(217, 74, 74), (91, 191, 138), (227, 179, 65), (63, 120, 194), (217, 74, 74)])]), k), 'generated'
    if k == 'gourds': return cross(lambda d, g: (d.ellipse([3, 18, 15, 30], fill=(232, 196, 58), outline=(150, 120, 30)), d.ellipse([13, 14, 23, 30], fill=(91, 150, 80), outline=(50, 90, 40)), d.ellipse([20, 20, 30, 30], fill=(224, 122, 36), outline=(150, 70, 20)), d.line([18, 14, 19, 10], fill=(110, 80, 40), width=2)), k), 'generated'
    if k == 'bats_deco': return cross(lambda d, g: (d.line([0, 4, 31, 4], fill=(90, 90, 90)), [d.polygon([(x, y), (x - 6, y - 2), (x - 4, y + 2), (x - 2, y + 1), (x, y + 4), (x + 2, y + 1), (x + 4, y + 2), (x + 6, y - 2)], fill=(52, 40, 64)) for x, y in [(7, 9), (17, 14), (26, 9)]]), k), 'generated'
    if k == 'wreath': return cross(lambda d, g: (d.ellipse([3, 3, 28, 28], outline=(47, 110, 60), width=6), [d.ellipse([x-2, y-2, x+2, y+2], fill=(217, 74, 74)) for x, y in [(8, 9), (24, 10), (9, 23), (23, 23)]], d.polygon([(12, 26), (16, 22), (20, 26), (16, 30)], fill=(217, 74, 74))), k), 'generated'
    if k == 'bronze_plaque': return cross(lambda d, g: (d.rectangle([4, 8, 27, 23], fill=(176, 125, 66), outline=(110, 75, 35)), d.line([8, 13, 23, 13], fill=(110, 75, 35)), d.line([8, 18, 19, 18], fill=(110, 75, 35))), k), 'generated'
    if k.startswith('door_'):
        _, style, half = k.split('_'); return door_half(half == 'top', style), 'generated'
    return None, None

def outline(im, col=(30, 26, 36, 255)):
    a = im.split()[3]; grow = a.filter(ImageFilter.MaxFilter(3))
    bg = Image.new('RGBA', im.size, (0, 0, 0, 0)); ol = Image.new('RGBA', im.size, col)
    bg.paste(ol, (0, 0), grow); bg.alpha_composite(im); return bg

MAT = {'wood': '#a8743f', 'stone': '#8d9196', 'copper': '#d9813e', 'steel': '#9aa3ad', 'iron': '#a7a29c', 'zinc': '#8fa3bd',
       'tin': '#b8b9a8', 'bronze': '#b9853f', 'silver': '#dfe6ec', 'gold': '#e8b923', 'platinum': '#cfd6dd', 'aluminum': '#c3ccd4',
       'titanium': '#8e95a8', 'iridium': '#b7a9d6', 'rhodium': '#d6c9c0', 'alumina': '#e2e0dc', 'tio2': '#e6e6e0', 'quartz': '#e6e8ea',
       'silicon': '#5d6b7a', 'graphite': '#3a3d42', 'glow': '#4fe0c8', 'dye': '#e05a8a', 'empty': '#bfe0ea', 'herb': '#6fbf5a',
       'morph': '#a97ae0', 'fizz': '#9ad7ff', 'frost': '#bfe6ef', 'corn': '#e8c43a', 'cotton': '#ece6dc'}
def C(m): return tuple(hexc(MAT.get(m, m)).astype(int))
def icon(spec, key):
    im = Image.new('RGBA', (S, S), (0, 0, 0, 0)); d = ImageDraw.Draw(im); t, _, m = spec.partition(':'); src = 'generated'
    dk = lambda c, f=0.65: tuple(int(v * f) for v in c)
    if t == 'pick':
        d.line([9, 27, 22, 10], fill=(140, 96, 52), width=3)
        d.polygon([(6, 9), (16, 4), (27, 8), (27, 12), (17, 8), (8, 13)], fill=C(m), outline=dk(C(m)))
    elif t == 'stick': d.line([9, 26, 23, 6], fill=(150, 104, 58), width=3); d.point([(15, 17)], fill=(110, 75, 40))
    elif t == 'ingot': d.polygon([(4, 20), (10, 12), (27, 12), (21, 20)], fill=C(m), outline=dk(C(m))); d.polygon([(4, 20), (21, 20), (21, 24), (4, 24)], fill=dk(C(m), .8)); d.polygon([(21, 20), (27, 12), (27, 16), (21, 24)], fill=dk(C(m), .7)); d.line([11, 14, 22, 14], fill=tuple(min(255, v + 40) for v in C(m)))
    elif t == 'nugget': d.polygon([(8, 20), (11, 11), (19, 9), (25, 15), (22, 23), (13, 25)], fill=C(m), outline=dk(C(m))); d.point([(15, 14), (16, 14)], fill=(250, 250, 240))
    elif t == 'flake': [d.polygon([(x, y), (x + 4, y - 2), (x + 6, y + 2), (x + 2, y + 4)], fill=C(m), outline=dk(C(m))) for x, y in [(6, 10), (16, 16), (10, 22)]]
    elif t == 'dust': d.pieslice([5, 12, 27, 34], 180, 360, fill=C(m), outline=dk(C(m))); [d.point((x, y), fill=dk(C(m), .8)) for x, y in [(12, 18), (18, 16), (21, 20), (14, 21)]]
    elif t == 'crystal': [d.polygon([(x - 3, 27), (x, 27 - h), (x + 3, 27)], fill=C(m), outline=dk(C(m), .6)) for x, h in [(10, 13), (16, 21), (22, 11)]]
    elif t == 'coil': [d.ellipse([7 + i * 3, 8, 15 + i * 3, 24], outline=C(m), width=2) for i in range(4)]
    elif t == 'vial':
        d.rectangle([12, 4, 19, 8], fill=(150, 110, 70)); d.rounded_rectangle([9, 8, 22, 28], 4, fill=(200, 225, 232, 140), outline=(90, 110, 120))
        if m != 'empty': d.rounded_rectangle([11, 15, 20, 26], 3, fill=C(m))
    elif t == 'beam': d.polygon([(4, 12), (28, 6), (28, 10), (4, 16)], fill=C(m), outline=dk(C(m))); d.polygon([(4, 20), (28, 14), (28, 18), (4, 24)], fill=C(m), outline=dk(C(m))); d.line([10, 15, 10, 21], fill=dk(C(m)), width=3); d.line([22, 12, 22, 17], fill=dk(C(m)), width=3)
    elif t == 'cog':
        cx = cy = 16
        for ang in range(0, 360, 45): d.rectangle([cx + 11 * math.cos(math.radians(ang)) - 2, cy + 11 * math.sin(math.radians(ang)) - 2, cx + 11 * math.cos(math.radians(ang)) + 2, cy + 11 * math.sin(math.radians(ang)) + 2], fill=C(m))
        d.ellipse([6, 6, 26, 26], fill=C(m), outline=dk(C(m))); d.ellipse([13, 13, 19, 19], fill=(0, 0, 0, 0), outline=dk(C(m)))
    elif t == 'seed': d.ellipse([10, 12, 16, 20], fill=C(m)); d.ellipse([17, 10, 23, 18], fill=C(m)); d.ellipse([14, 19, 20, 27], fill=C(m))
    elif t == 'pack':
        col = [(180, 120, 70), (63, 120, 194), (91, 160, 100)][int(m) - 1]
        d.rounded_rectangle([7, 8, 25, 28], 4, fill=col, outline=dk(col)); d.arc([11, 2, 21, 14], 180, 360, fill=dk(col), width=2); d.rectangle([11, 16, 21, 22], outline=dk(col))
    elif t == 'drive': d.rounded_rectangle([7, 5, 25, 27], 3, fill=(60, 66, 76), outline=(30, 32, 38)); d.rectangle([10, 8, 22, 14], fill=(122, 92, 199)); d.text((13, 16), m.upper(), fill=(220, 226, 232))
    elif t == 'sprite': return sprite(m).resize((S, S), Image.NEAREST), 'generated'
    else:
        simple = {
            'pan': lambda: (d.ellipse([4, 10, 28, 24], fill=(168, 116, 63), outline=(100, 66, 30)), d.ellipse([9, 13, 23, 21], fill=(140, 96, 52))),
            'bucket': lambda: (d.polygon([(8, 10), (24, 10), (22, 27), (10, 27)], fill=(150, 156, 164), outline=(80, 86, 94)), d.arc([8, 2, 24, 18], 180, 360, fill=(80, 86, 94), width=2)),
            'bucket_water': lambda: (d.polygon([(8, 10), (24, 10), (22, 27), (10, 27)], fill=(150, 156, 164), outline=(80, 86, 94)), d.arc([8, 2, 24, 18], 180, 360, fill=(80, 86, 94), width=2), d.rectangle([9, 11, 23, 14], fill=(63, 167, 194))),
            'berry': lambda: [d.ellipse([x, y, x + 9, y + 9], fill=(200, 50, 90), outline=(120, 30, 60)) for x, y in [(7, 13), (15, 15), (11, 7)]],
            'flour': lambda: (d.rounded_rectangle([8, 7, 24, 28], 4, fill=(226, 218, 200), outline=(150, 140, 120)), d.text((12, 12), 'F', fill=(150, 140, 120))),
            'sugar': lambda: [d.rectangle([x, y, x + 6, y + 6], fill=(232, 230, 226), outline=(160, 160, 170)) for x, y in [(7, 15), (15, 18), (12, 9), (19, 10)]],
            'cupcake': lambda: (d.polygon([(9, 17), (23, 17), (21, 27), (11, 27)], fill=(200, 140, 70)), d.ellipse([7, 8, 25, 20], fill=(224, 90, 138)), d.ellipse([14, 4, 18, 8], fill=(200, 50, 60))),
            'bread': lambda: (d.rounded_rectangle([5, 12, 27, 24], 6, fill=(204, 146, 74), outline=(130, 85, 40)), d.line([11, 14, 13, 20], fill=(130, 85, 40)), d.line([18, 14, 20, 20], fill=(130, 85, 40))),
            'paint_dab': lambda: (d.ellipse([6, 10, 26, 26], fill=(224, 90, 138), outline=(150, 50, 90)), d.ellipse([20, 6, 25, 11], fill=(224, 90, 138))),
            'corn': lambda: (d.ellipse([11, 4, 21, 28], fill=(232, 196, 58), outline=(150, 120, 30)), d.polygon([(8, 28), (11, 12), (14, 28)], fill=(95, 158, 74)), d.polygon([(24, 28), (21, 12), (18, 28)], fill=(95, 158, 74))),
            'bioplastic': lambda: (d.rounded_rectangle([6, 9, 26, 23], 5, fill=(220, 236, 200, 220), outline=(120, 160, 90)), d.text((10, 10), 'BP', fill=(80, 120, 60))),
            'plastic_tube': lambda: (d.rounded_rectangle([12, 3, 20, 29], 4, fill=(210, 230, 236, 160), outline=(110, 140, 150)), d.line([14, 6, 14, 26], fill=(250, 250, 250, 180))),
            'leaf': lambda: (d.rectangle([8, 8, 24, 24], fill=C(m), outline=(150, 110, 20)), d.line([10, 22, 22, 10], fill=(250, 230, 150))),
            'chip': lambda: (d.rectangle([9, 9, 23, 23], fill=(40, 46, 56), outline=(20, 22, 28)), [d.line([x, 5, x, 9], fill=(200, 170, 80)) for x in (12, 16, 20)], [d.line([x, 23, x, 27], fill=(200, 170, 80)) for x in (12, 16, 20)], d.rectangle([13, 13, 19, 19], fill=(93, 107, 122))),
            'battery': lambda: (d.rectangle([9, 8, 23, 28], fill=(60, 64, 72), outline=(30, 32, 38)), d.rectangle([13, 4, 19, 8], fill=(200, 170, 80)), d.rectangle([9, 8, 23, 14], fill=(217, 129, 62)), d.rectangle([9, 22, 23, 28], fill=(143, 163, 189))),
            'spring': lambda: [d.arc([8, 4 + i * 5, 24, 12 + i * 5], 0, 360, fill=(154, 163, 173), width=2) for i in range(4)],
            'cotton': lambda: [d.ellipse([x, y, x + 10, y + 10], fill=(236, 230, 220), outline=(170, 160, 150)) for x, y in [(6, 12), (15, 12), (10, 5), (11, 17)]],
            'cloth': lambda: (d.polygon([(5, 10), (27, 7), (25, 24), (6, 26)], fill=(214, 200, 176), outline=(140, 125, 100)), [d.line([7, y, 25, y - 3], fill=(180, 165, 140)) for y in (14, 18, 22)]),
            'salt': lambda: (d.polygon([(8, 26), (12, 10), (20, 10), (24, 26)], fill=(232, 228, 218), outline=(150, 145, 135)), d.rectangle([12, 6, 20, 10], fill=(160, 160, 170))),
            'brush': lambda: (d.line([8, 26, 20, 12], fill=(150, 104, 58), width=3), d.polygon([(19, 13), (24, 6), (27, 9), (21, 15)], fill=(224, 90, 138))),
            'fob': lambda: (d.rounded_rectangle([10, 8, 22, 26], 5, fill=(63, 120, 194), outline=(30, 60, 110)), d.ellipse([13, 12, 19, 18], fill=(227, 179, 65)), d.ellipse([14, 2, 18, 8], outline=(150, 156, 164), width=2)),
            'hat': lambda: (d.ellipse([4, 20, 28, 26], fill=(122, 92, 199)), d.rounded_rectangle([9, 7, 23, 23], 3, fill=(122, 92, 199), outline=(70, 50, 120)), d.polygon([(14, 12), (18, 12), (16, 16)], fill=(227, 179, 65))),
            'disc': lambda: (d.ellipse([4, 4, 28, 28], fill=(30, 30, 34)), d.ellipse([12, 12, 20, 20], fill=(91, 191, 138)), d.arc([7, 7, 25, 25], 200, 250, fill=(120, 120, 130))),
            'key': lambda: (d.ellipse([5, 6, 15, 16], outline=(79, 224, 200), width=3), d.line([14, 14, 26, 26], fill=(79, 224, 200), width=3), d.line([22, 22, 25, 19], fill=(79, 224, 200), width=2)),
            'bandage': lambda: (d.rounded_rectangle([4, 12, 28, 20], 4, fill=(232, 210, 180), outline=(170, 140, 110)), d.rectangle([13, 12, 19, 20], fill=(250, 236, 220))),
            'medkit': lambda: (d.rounded_rectangle([5, 8, 27, 26], 3, fill=(230, 226, 220), outline=(150, 145, 140)), d.rectangle([14, 11, 18, 23], fill=(200, 50, 60)), d.rectangle([10, 15, 22, 19], fill=(200, 50, 60))),
            'bell': lambda: (d.pieslice([7, 6, 25, 30], 180, 360, fill=(227, 179, 65), outline=(150, 110, 30)), d.rectangle([7, 18, 25, 21], fill=(227, 179, 65)), d.ellipse([14, 21, 18, 25], fill=(150, 110, 30))),
            'jar': lambda: (d.rounded_rectangle([8, 8, 24, 28], 4, fill=(200, 225, 232, 140), outline=(90, 110, 120)), d.rectangle([9, 4, 23, 8], fill=(168, 116, 63)), d.ellipse([14, 16, 18, 20], fill=(255, 220, 90))),
            'cloak': lambda: (d.polygon([(10, 5), (22, 5), (27, 28), (5, 28)], fill=(91, 140, 80), outline=(50, 80, 40)), d.point([(12, 14), (19, 20), (15, 24)], fill=(140, 110, 70))),
            'magnet': lambda: (d.arc([6, 4, 26, 24], 180, 360, fill=(200, 50, 60), width=5), d.line([8, 14, 8, 26], fill=(200, 50, 60), width=5), d.line([24, 14, 24, 26], fill=(63, 120, 194), width=5)),
            'wand': lambda: (d.line([8, 26, 20, 12], fill=(150, 104, 58), width=3), d.ellipse([18, 4, 28, 14], fill=(255, 230, 140), outline=(220, 180, 60))),
            'rod': lambda: (d.line([8, 26, 22, 8], fill=(154, 163, 173), width=3), d.polygon([(22, 3), (19, 10), (24, 9), (21, 15)], fill=(227, 179, 65))),
            'scroll': lambda: (d.rectangle([7, 8, 25, 24], fill=(220, 226, 232), outline=(63, 120, 194)), d.line([10, 13, 22, 13], fill=(63, 120, 194)), d.line([10, 17, 19, 17], fill=(63, 120, 194)), d.ellipse([4, 6, 9, 26], fill=(190, 196, 204))),
            'flower': lambda: ([d.ellipse([16 + dx - 4, 13 + dy - 4, 16 + dx + 4, 13 + dy + 4], fill=(63, 182, 201)) for dx, dy in [(-5, 0), (5, 0), (0, -5), (0, 5)]], d.ellipse([13, 10, 19, 16], fill=(232, 196, 58)), d.line([16, 18, 16, 29], fill=(79, 138, 62), width=2)),
            'apple': None,
            'carver': lambda: (d.rounded_rectangle([5, 18, 15, 28], 3, fill=(63, 120, 194), outline=(30, 60, 110)), d.polygon([(14, 19), (27, 6), (28, 9), (16, 22)], fill=(170, 178, 188), outline=(90, 96, 104)), [d.line([18 + i * 2, 17 - i * 2, 19 + i * 2, 19 - i * 2], fill=(90, 96, 104)) for i in range(4)]),
            'chair': lambda: (d.rectangle([9, 4, 23, 16], fill=C(m) if m != 'spooky' else (52, 40, 64), outline=(40, 30, 30)), d.rectangle([7, 16, 25, 20], fill=C(m) if m != 'spooky' else (52, 40, 64), outline=(40, 30, 30)), d.line([9, 20, 9, 29], fill=(40, 30, 30), width=2), d.line([23, 20, 23, 29], fill=(40, 30, 30), width=2), (d.polygon([(3, 6), (9, 4), (9, 10)], fill=(122, 92, 199)) if m == 'spooky' else None), (d.polygon([(29, 6), (23, 4), (23, 10)], fill=(122, 92, 199)) if m == 'spooky' else None)),
            'stool': lambda: (d.ellipse([7, 8, 25, 14], fill=C(m), outline=(40, 30, 30)), d.line([10, 13, 8, 29], fill=(40, 30, 30), width=2), d.line([22, 13, 24, 29], fill=(40, 30, 30), width=2), d.line([16, 14, 16, 29], fill=(40, 30, 30), width=2), d.line([9, 22, 23, 22], fill=(40, 30, 30))),
            'table': lambda: (d.polygon([(3, 10), (29, 10), (27, 15), (5, 15)], fill=C(m), outline=(40, 30, 30)), d.line([6, 15, 6, 29], fill=(40, 30, 30), width=3), d.line([26, 15, 26, 29], fill=(40, 30, 30), width=3)),
            'bench': lambda: (d.rectangle([3, 8, 29, 13], fill=C(m), outline=(90, 60, 30)), d.rectangle([3, 16, 29, 20], fill=C(m), outline=(90, 60, 30)), d.line([6, 20, 6, 28], fill=(90, 60, 30), width=2), d.line([26, 20, 26, 28], fill=(90, 60, 30), width=2)),
            'seatpumpkin': lambda: (d.ellipse([4, 12, 28, 28], fill=(224, 122, 36), outline=(150, 70, 20)), [d.arc([x, 12, x + 8, 28], 90, 270, fill=(170, 85, 25)) for x in (10, 16)], d.rectangle([14, 8, 18, 12], fill=(79, 122, 42))),
            'scarecrow': lambda: (d.line([16, 10, 16, 31], fill=(120, 85, 45), width=2), d.line([4, 14, 28, 14], fill=(120, 85, 45), width=2), d.polygon([(9, 13), (23, 13), (21, 24), (11, 24)], fill=(63, 120, 194)), d.ellipse([11, 3, 21, 13], fill=(214, 178, 90)), d.polygon([(8, 5), (24, 5), (16, 0)], fill=(140, 96, 52)), [d.line([x, 14, x - 1, 18], fill=(214, 178, 90)) for x in (4, 28)]),
            'spookysign': lambda: (d.rectangle([14, 20, 18, 30], fill=(110, 76, 44), outline=(80, 54, 30)), d.rectangle([5, 7, 27, 20], fill=(150, 104, 60), outline=(90, 60, 35)), d.polygon([(10, 12), (13, 10), (16, 12), (19, 10), (22, 12), (19, 15), (16, 14), (13, 15)], fill=(52, 40, 64)), d.line([8, 18, 24, 18], fill=(110, 76, 44))),
            'snowpal': lambda: (d.ellipse([7, 15, 25, 30], fill=(232, 236, 240), outline=(150, 160, 170)), d.ellipse([10, 4, 22, 16], fill=(232, 236, 240), outline=(150, 160, 170)), d.point([(14, 9), (18, 9)], fill=(30, 30, 34)), d.polygon([(16, 11), (21, 12), (16, 13)], fill=(232, 140, 50)), d.line([9, 16, 23, 16], fill=(217, 74, 74), width=2)),
        }
        if spec == 'apple': return outline(kenney('apple', 'Items')), 'kenney:Items/apple'
        if spec not in simple and t not in simple: raise KeyError(spec)
        (simple.get(spec) or simple[t])()
    return outline(im), src

def sprite(k):
    """Front-facing 32x32 billboard sprites (rendered 1 block tall). Original shapes, project palette."""
    im = Image.new('RGBA', (S, S), (0, 0, 0, 0)); d = ImageDraw.Draw(im)
    if k == 'bot':
        d.rounded_rectangle([5, 9, 27, 27], 3, fill=(234, 140, 50), outline=(130, 70, 20)); d.rectangle([9, 13, 23, 19], fill=(40, 46, 56))
        d.ellipse([11, 14, 15, 18], fill=(79, 224, 200)); d.ellipse([17, 14, 21, 18], fill=(79, 224, 200)); d.line([16, 9, 16, 4], fill=(80, 86, 94), width=2); d.ellipse([14, 2, 18, 6], fill=(227, 179, 65))
        d.rectangle([7, 27, 12, 30], fill=(60, 64, 72)); d.rectangle([20, 27, 25, 30], fill=(60, 64, 72))
    elif k == 'drone':
        d.rounded_rectangle([10, 14, 22, 22], 3, fill=(63, 167, 194), outline=(30, 80, 100)); [d.line([x, 12, x + 8, 12], fill=(80, 86, 94), width=2) for x in (2, 22)]
        d.line([10, 15, 6, 12], fill=(80, 86, 94)); d.line([22, 15, 26, 12], fill=(80, 86, 94)); d.rectangle([12, 22, 20, 27], fill=(180, 120, 70), outline=(110, 70, 30))
    elif k == 'petrock':
        d.ellipse([5, 12, 27, 28], fill=(141, 145, 150), outline=(80, 84, 90)); d.ellipse([11, 17, 14, 20], fill=(30, 30, 34)); d.ellipse([18, 17, 21, 20], fill=(30, 30, 34)); d.arc([12, 19, 20, 24], 20, 160, fill=(30, 30, 34))
    elif k == 'firefly':
        d.ellipse([12, 10, 20, 18], fill=(60, 50, 40)); d.ellipse([12, 16, 20, 24], fill=(255, 230, 120)); d.ellipse([6, 8, 13, 14], fill=(220, 230, 240, 160)); d.ellipse([19, 8, 26, 14], fill=(220, 230, 240, 160))
    elif k == 'butterfly':
        for sx in (-1, 1): d.ellipse([16 + sx * 2 - (10 if sx < 0 else 0), 6, 16 + sx * 2 + (10 if sx > 0 else 0), 16], fill=(224, 120, 60)); d.ellipse([16 + sx * 2 - (7 if sx < 0 else 0), 15, 16 + sx * 2 + (7 if sx > 0 else 0), 24], fill=(232, 196, 58))
        d.line([16, 6, 16, 24], fill=(40, 30, 30), width=2)
    elif k == 'songbird':
        d.ellipse([7, 10, 23, 24], fill=(63, 120, 194)); d.ellipse([18, 7, 27, 16], fill=(63, 120, 194)); d.polygon([(27, 11), (31, 12), (27, 13)], fill=(232, 160, 50)); d.ellipse([22, 10, 24, 12], fill=(20, 20, 20)); d.ellipse([10, 16, 20, 23], fill=(232, 120, 60))
    elif k == 'frog':
        d.ellipse([6, 14, 26, 28], fill=(91, 170, 80), outline=(50, 100, 40)); d.ellipse([7, 8, 15, 16], fill=(91, 170, 80)); d.ellipse([17, 8, 25, 16], fill=(91, 170, 80)); d.ellipse([10, 10, 13, 13], fill=(20, 20, 20)); d.ellipse([20, 10, 23, 13], fill=(20, 20, 20))
    elif k == 'prairiedog':
        d.ellipse([10, 12, 22, 30], fill=(196, 150, 98)); d.ellipse([11, 4, 21, 14], fill=(196, 150, 98)); d.ellipse([13, 7, 15, 9], fill=(20, 20, 20)); d.ellipse([17, 7, 19, 9], fill=(20, 20, 20)); d.ellipse([13, 16, 19, 26], fill=(226, 200, 160))
    elif k == 'cat':
        d.ellipse([8, 14, 24, 29], fill=(120, 120, 128)); d.ellipse([9, 4, 23, 16], fill=(120, 120, 128)); d.polygon([(9, 7), (11, 1), (14, 5)], fill=(120, 120, 128)); d.polygon([(23, 7), (21, 1), (18, 5)], fill=(120, 120, 128))
        d.ellipse([12, 8, 14, 10], fill=(140, 220, 120)); d.ellipse([18, 8, 20, 10], fill=(140, 220, 120)); d.line([24, 26, 29, 18], fill=(120, 120, 128), width=3)
    return outline(im)

PAT = {}
def minimap(key, col, pat):
    a = np.zeros((16, 16, 4)); a[..., :3] = hexc(col); a[..., 3] = 255; dk = hexc(col) * 0.55
    yy, xx = np.mgrid[0:16, 0:16]
    m = {'dots': (xx % 4 == 1) & (yy % 4 == 1), 'crosshatch': ((xx + yy) % 6 == 0) | ((xx - yy) % 6 == 0), 'stripes': (yy % 4 == 0),
         'waves': ((yy + np.round(1.5 * np.sin(xx / 2.5))).astype(int) % 5 == 0), 'zigzag': ((yy + np.abs((xx % 8) - 4)) % 6 == 0),
         'checker': ((xx // 4 + yy // 4) % 2 == 0) & ((xx + yy) % 2 == 0), 'waves2': ((yy + np.round(1.5 * np.sin(xx / 2.5))).astype(int) % 3 == 0),
         'bricks': (yy % 4 == 0) | ((xx + (yy // 4 % 2) * 4) % 8 == 0)}[pat]
    a[m, :3] = dk; return img(a)

def main():
    for sub in ('textures/blocks', 'textures/items', 'textures/sprites', 'textures/minimap', 'atlas', 'dex'):
        os.makedirs(f'{ROOT}/{sub}', exist_ok=True)
    LIVE21 = ['grass_top', 'dirt_grass', 'dirt', 'stone', 'greystone', 'stone_coal', 'sand', 'gravel_stone', 'brick_red', 'brick_grey', 'wood',
              'trunk_top', 'trunk_side', 'leaves', 'cotton_blue', 'cotton_green', 'cotton_red', 'cotton_tan', 'snow', 'ice', 'redsand']
    names, alpha_names = list(LIVE21), []
    kinds = {}
    for b in R.BLOCKS:
        f = b[4]; faces = f.values() if isinstance(f, dict) else [f]
        for n in faces:
            if b[3] in ('alpha', 'cross', 'flat', 'model') or n in ('leaves',):
                if n not in alpha_names and n not in ('leaves',): alpha_names.append(n)
            elif n not in names: names.append(n)
            kinds[n] = b[3]
    # model blocks draw from item-style icons; their 'faces' key is an icon name, not a cube texture
    model_icons = sorted({(b[4] if isinstance(b[4], str) else None) for b in R.BLOCKS if b[3] == 'model'} - {None})
    alpha_names = [n for n in alpha_names if n not in model_icons]
    alpha_names = ['leaves', 'glass'] + [n for n in alpha_names if n not in ('glass',)] + ['wheat_stage1', 'wheat_stage2', 'wheat_stage3']
    names = [n for n in names if n not in ('glass',)]
    tex, src = {}, {}
    for n in names + alpha_names:
        a, s = T(n)
        if a is None: raise SystemExit(f'no recipe for texture {n}')
        a = deglare(a); tex[n] = img(a); src[n] = s
        p = f'textures/blocks/{n}.png'; tex[n].save(f'{ROOT}/{p}', optimize=True)
        k = s.startswith('kenney') or '(on kenney' in s
        ROWS.append([n, 'block-texture', p, '32x32', KENNEY_URL if k else '', LIC_K if s.startswith('kenney') else (LIC_K + ' base + ' + LIC_G if k else LIC_G), 'Kenney (kenney.nl)' if k else 'trebiluk project', 'sourced-derived' if k else 'generated', s])
    def strip(lst, fn):
        im = Image.new('RGBA', (S, S * len(lst)), (0, 0, 0, 0))
        for i, n in enumerate(lst): im.paste(tex[n], (0, i * S))
        im.save(f'{ROOT}/atlas/{fn}.png', optimize=True)
        json.dump({'tile': S, 'layout': 'vertical-strip (noa texture array)', 'names': lst, 'index': {n: i for i, n in enumerate(lst)}}, open(f'{ROOT}/atlas/{fn}.json', 'w'), indent=1)
    assert names[:21] == LIVE21 and len(names) <= 256, (names[:21], len(names))
    strip(names, 'terrain'); strip(alpha_names, 'alpha')
    # items + model-block icons + sprites
    icons = {}
    for it in R.ITEMS:
        im, s = icon(it[2], it[0]); icons[it[0]] = im; p = f'textures/items/{it[0]}.png'; im.save(f'{ROOT}/{p}', optimize=True)
        k = s.startswith('kenney'); ROWS.append([it[0], 'item-icon', p, '32x32', KENNEY_URL if k else '', LIC_K if k else LIC_G, 'Kenney (kenney.nl)' if k else 'trebiluk project', 'sourced-derived' if k else 'generated', it[3]])
    MODEL_ICON = {  # model blocks -> drawn icon (also used as the in-hand/Bag picture)
        'lever_off': 'rod', 'lever_on': 'rod', 'button_off': 'cog:steel', 'button_on': 'cog:glow', 'lantern': 'jar', 'charger': 'battery',
        'glow_pebble': 'nugget:glow', 'glow_stick': 'vial:glow', 'glow_jumbo': 'vial:dye', 'glow_cold': 'vial:frost', 'salt_pan': 'pan',
        'shelf_wall': 'beam:wood', 'shelf': 'beam:wood', 'side_table': 'pack:1', 'desk': 'pack:1', 'sign': 'scroll', 'tube_glass': 'plastic_tube',
        'tube_powered': 'coil:copper', 'tube_filter': 'plastic_tube', 'extractor': 'cog:steel', 'cable_network': 'coil:morph', 'storage_link': 'chip',
        'pad_teleport': 'cog:fizz', 'dock_drone': 'sprite:drone', 'pad_network': 'cog:morph', 'keyboard': 'chip', 'drumkit': 'disc', 'guitar': 'brush',
        'ghost_light': 'bell', 'pad_warp': 'key', 'sleeping_bag': 'cloth', 'crew_banner': 'scroll', 'game_flag': 'scroll',
        'dex_shelf': 'beam:wood', 'trophy_shelf': 'beam:wood', 'chair': 'chair:wood', 'bench': 'bench:wood', 'chair_spooky': 'chair:spooky',
        'snow_pal': 'snowpal', 'stool': 'stool:wood', 'table': 'table:wood', 'scarecrow': 'scarecrow', 'sign_spooky': 'spookysign', 'lantern_harvest': 'jar',
    }
    for b in R.BLOCKS:
        if b[3] == 'model' and isinstance(b[4], str):
            spec = MODEL_ICON.get(b[4]); im, s = icon(spec, b[1]); icons['block:' + b[1]] = im
            p = f'textures/items/block-{b[1]}.png'; im.save(f'{ROOT}/{p}', optimize=True)
            ROWS.append(['block:' + b[1], 'block-icon (placeholder shape)', p, '32x32', '', LIC_G, 'trebiluk project', 'generated', b[6]])
    for pk, pc in R.FURNITURE_PALETTE:
        MAT['pal_' + pk] = pc
        for fk in ('chair', 'stool', 'bench', 'table'):
            im, s = icon(f'{fk}:pal_{pk}', fk); key = f'block:{fk}@{pk}'; icons[key] = im
            p = f'textures/items/block-{fk}@{pk}.png'; im.save(f'{ROOT}/{p}', optimize=True)
            ROWS.append([key, 'block-icon (palette variant)', p, '32x32', '', LIC_G, 'trebiluk project', 'generated', 'storage-2'])
    for sp in R.SPRITES:
        im = sprite(sp[0]); p = f'textures/sprites/{sp[0]}.png'; im.save(f'{ROOT}/{p}', optimize=True)
        ROWS.append([sp[0], 'sprite', p, '32x32', '', LIC_G, 'trebiluk project', 'generated', sp[2]])
    for bk, nm, col, pat in R.BIOMES:
        p = f'textures/minimap/{bk}.png'; minimap(bk, col, pat).save(f'{ROOT}/{p}', optimize=True)
        ROWS.append(['biome:' + bk, 'minimap-pattern', p, '16x16', '', LIC_G, 'trebiluk project', 'generated', 'world-2'])
    keys = list(icons); cols = 16; rows_n = math.ceil(len(keys) / cols)
    sheet = Image.new('RGBA', (cols * S, rows_n * S), (0, 0, 0, 0))
    for i, k in enumerate(keys): sheet.paste(icons[k], ((i % cols) * S, (i // cols) * S))
    sheet.save(f'{ROOT}/atlas/items.png', optimize=True)
    json.dump({'tile': S, 'cols': cols, 'frames': {k: {'x': (i % cols) * S, 'y': (i // cols) * S} for i, k in enumerate(keys)}}, open(f'{ROOT}/atlas/items.json', 'w'), indent=1)
    # registry.json (ids match live 1..31)
    tix = {n: i for i, n in enumerate(names)}; aix = {n: i for i, n in enumerate(alpha_names)}
    def face_ref(n):
        return {'atlas': 'terrain', 'i': tix[n]} if n in tix else ({'atlas': 'alpha', 'i': aix[n]} if n in aix else {'atlas': 'items', 'key': n})
    reg = {'format': 'bertopia-registry', 'v': 1, 'liveIds': '1-31 frozen (2.5.42)', 'blocks': [], 'items': [], 'sprites': [], 'biomes': [], 'elements': []}
    for b in R.BLOCKS:
        f = b[4]; faces = {k_: face_ref(v) for k_, v in f.items()} if isinstance(f, dict) else {'all': face_ref(f)}
        if b[3] == 'model' and isinstance(f, str): faces = {'icon': {'atlas': 'items', 'key': 'block:' + b[1]}}
        reg['blocks'].append({'id': b[0], 'key': b[1], 'name': {'en': b[2]}, 'kind': b[3], 'faces': faces, 'handS': b[5], 'breakable': b[5] is not None,
                              'drop': b[1], 'stack': 64, 'milestone': b[6], 'availableFrom': b[7], 'natural': None,
                              'dex': {'cat': b[8], 'what': b[9], 'status': 'draft-curriculum-check'}})
    for it in R.ITEMS:
        reg['items'].append({'key': it[0], 'name': {'en': it[1]}, 'icon': {'atlas': 'items', 'key': it[0]}, 'stack': 1 if it[2].startswith(('pick', 'pack', 'sprite', 'drive', 'hat', 'key', 'pan', 'bucket', 'brush', 'fob')) else 64,
                             'milestone': it[3], 'availableFrom': it[4], 'dex': {'cat': it[5], 'what': it[6], 'status': 'draft-curriculum-check'}})
    reg['sprites'] = [{'key': s_[0], 'name': {'en': s_[1]}, 'file': f'textures/sprites/{s_[0]}.png', 'milestone': s_[2], 'dex': {'what': s_[3]}} for s_ in R.SPRITES]
    reg['biomes'] = [{'key': b_[0], 'name': {'en': b_[1]}, 'minimap': {'color': b_[2], 'pattern': b_[3], 'file': f'textures/minimap/{b_[0]}.png'}} for b_ in R.BIOMES]
    reg['furniturePalette'] = [{'key': k_, 'hex': v_} for k_, v_ in R.FURNITURE_PALETTE]
    reg['elements'] = [{'symbol': e[0], 'z': e[1], 'name': {'en': e[2]}} for e in R.ELEMENTS]
    json.dump(reg, open(f'{ROOT}/registry.json', 'w'), indent=1, ensure_ascii=False)
    dex = {b['key']: {'name': b['name']['en'], 'cat': b['dex']['cat'], 'what': b['dex']['what']} for b in reg['blocks']}
    dex.update({i['key']: {'name': i['name']['en'], 'cat': i['dex']['cat'], 'what': i['dex']['what']} for i in reg['items']})
    json.dump({'lang': 'en', 'status': 'DRAFT: Curriculum Bot checks facts + reading level before ship; other 7 languages filled by Build per brief', 'entries': dex}, open(f'{ROOT}/dex/bertodex-en.json', 'w'), indent=1, ensure_ascii=False)
    with open(f'{HERE}/_manifest_tex.csv', 'w', newline='') as fh: csv.writer(fh).writerows(ROWS)
    print(f'terrain {len(names)} alpha {len(alpha_names)} items+icons {len(keys)} sprites {len(R.SPRITES)} minimap {len(R.BIOMES)}')

if __name__ == '__main__': main()
