#!/usr/bin/env python3
"""Bertopia SFX: picks Kenney CC0 sounds (transcoded) + synthesizes the rest. Output: sfx/*.ogg + *.mp3, music/*.ogg + *.mp3.
Every sound is quiet-by-default (peak -6 dBFS, Kenney normalised to -16 LUFS-ish via loudnorm), mono 44.1 kHz, no harsh highs.
Each sound has a visual pair in the game (CORE-MECHANICS: never sound-only information)."""
import os, subprocess, glob, csv, wave, hashlib
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
K = os.environ.get('KENNEY_AUDIO', '/tmp/kpack')
SR = 44100; ROWS = []
URL = {'impact-sounds': 'https://kenney.nl/assets/impact-sounds', 'interface-sounds': 'https://kenney.nl/assets/interface-sounds',
       'music-jingles': 'https://kenney.nl/assets/music-jingles', 'rpg-audio': 'https://kenney.nl/assets/rpg-audio'}
LIC_K = 'Creative Commons CC0 (as stated on kenney.nl page and License.txt in zip)'
LIC_G = 'Project-original (generated by tools/gen_sfx.py; owner trebiluk); no third-party license'
PICK = {  # out name: (pack, file stem, used by)
 'mine_stone_1': ('impact-sounds', 'impactMining_000', 'mine hold tick stone'), 'mine_stone_2': ('impact-sounds', 'impactMining_001', 'mine hold tick stone'),
 'mine_wood': ('impact-sounds', 'impactWood_light_000', 'mine wood'), 'mine_soft': ('impact-sounds', 'impactSoft_medium_000', 'mine dirt/sand/cloth/leaves'),
 'mine_glass': ('impact-sounds', 'impactGlass_light_000', 'mine glass'), 'mine_metal': ('impact-sounds', 'impactMetal_light_000', 'mine machines/ore'),
 'break_stone': ('impact-sounds', 'impactMining_003', 'block breaks'), 'break_wood': ('impact-sounds', 'impactWood_medium_001', 'block breaks'),
 'break_glass': ('impact-sounds', 'impactGlass_medium_000', 'glass breaks'), 'place_block': ('impact-sounds', 'impactPlank_medium_000', 'Place'),
 'place_soft': ('impact-sounds', 'impactSoft_heavy_000', 'Place cloth/dirt'), 'place_metal': ('impact-sounds', 'impactPlate_light_000', 'Place machine'),
 'step_grass': ('impact-sounds', 'footstep_grass_000', 'footsteps'), 'step_stone': ('impact-sounds', 'footstep_concrete_000', 'footsteps'),
 'step_wood': ('impact-sounds', 'footstep_wood_000', 'footsteps'), 'step_snow': ('impact-sounds', 'footstep_snow_000', 'footsteps snow (world-2)'),
 'step_cloth': ('impact-sounds', 'footstep_carpet_000', 'footsteps cloth'),
 'door_open': ('rpg-audio', 'doorOpen_1', 'door open'), 'door_close': ('rpg-audio', 'doorClose_1', 'door close'),
 'lever': ('rpg-audio', 'metalLatch', 'lever flip'), 'button': ('rpg-audio', 'metalClick', 'push button'),
 'coins': ('rpg-audio', 'handleCoins', 'Cogs paid/received'), 'bag_open': ('rpg-audio', 'cloth1', 'Bag open'), 'pickup': ('rpg-audio', 'handleSmallLeather', 'pick up drop'),
 'box_open': ('rpg-audio', 'creak1', 'Box/Cabinet open'), 'book_open': ('rpg-audio', 'bookOpen', 'Bertodex open'), 'book_flip': ('rpg-audio', 'bookFlip1', 'Bertodex page'),
 'carve': ('rpg-audio', 'knifeSlice', 'pumpkin carve stroke'), 'smelt_pot': ('rpg-audio', 'metalPot1', 'Smelter/Forge done'),
 'ui_open': ('interface-sounds', 'open_001', 'panel open'), 'ui_close': ('interface-sounds', 'close_001', 'panel close'),
 'ui_confirm': ('interface-sounds', 'confirmation_001', 'craft ok'), 'ui_error': ('interface-sounds', 'error_004', 'refused (polite)'),
 'ui_select': ('interface-sounds', 'select_001', 'slot select'), 'ui_toggle': ('interface-sounds', 'toggle_001', 'settings toggle'),
 'ui_tick': ('interface-sounds', 'tick_001', 'scroll tick'), 'ui_drop': ('interface-sounds', 'drop_001', 'Q drop'), 'ui_back': ('interface-sounds', 'back_001', 'back'),
 'ui_pluck': ('interface-sounds', 'pluck_001', 'tap-to-slot'), 'ui_question': ('interface-sounds', 'question_001', 'hint'),
 'sting_first_craft': ('music-jingles', 'jingles_PIZZI00', 'first craft of a recipe'), 'sting_milestone': ('music-jingles', 'jingles_STEEL00', 'milestone / stamp'),
 'sting_daily_done': ('music-jingles', 'jingles_HIT00', 'Daily done'), 'sting_level': ('music-jingles', 'jingles_PIZZI04', 'tier unlock'),
 'sting_dex_new': ('music-jingles', 'jingles_STEEL04', 'new Bertodex entry'), 'sting_holiday': ('music-jingles', 'jingles_SAX02', 'holiday pack arrives'),
}
def find(pack, stem):
    m = [p for p in glob.glob(f'{K}/{pack}/**/*.ogg', recursive=True) if os.path.basename(p)[:-4] == stem]
    if not m: raise SystemExit(f'missing {pack}/{stem}')
    return m[0]
def enc(src, out, af='loudnorm=I=-18:TP=-6:LRA=7'):
    for ext, codec in (('ogg', ['-c:a', 'libvorbis', '-q:a', '3']), ('mp3', ['-c:a', 'libmp3lame', '-b:a', '96k'])):
        subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', src, '-ac', '1', '-ar', str(SR), '-af', af, '-map_metadata', '-1', '-fflags', '+bitexact', *codec, f'{out}.{ext}'], check=True)
def env(n, a=0.005, r=0.1):
    t = np.arange(n) / SR; e = np.minimum(1, t / a) * np.exp(-t / r); return e
def tone(f, d, wave_='sine', a=0.005, r=0.15, vib=0):
    n = int(SR * d); t = np.arange(n) / SR; ph = 2 * np.pi * np.cumsum(np.full(n, f) * (1 + vib * np.sin(2 * np.pi * 5 * t))) / SR
    s = {'sine': np.sin(ph), 'tri': 2 / np.pi * np.arcsin(np.sin(ph)), 'soft': np.sin(ph) + 0.3 * np.sin(2 * ph) + 0.1 * np.sin(3 * ph)}[wave_]
    return s * env(n, a, r)
def sweep(f0, f1, d, r=0.2, wave_='sine'):
    n = int(SR * d); f = np.geomspace(f0, f1, n); ph = 2 * np.pi * np.cumsum(f) / SR
    s = np.sin(ph) if wave_ == 'sine' else 2 / np.pi * np.arcsin(np.sin(ph)); return s * env(n, 0.005, r)
def noise(d, lp=4000, r=0.1, seed=1):
    n = int(SR * d); x = np.random.default_rng(seed).normal(0, 1, n); a = np.exp(-2 * np.pi * lp / SR); y = np.zeros(n)
    for i in range(1, n): y[i] = (1 - a) * x[i] + a * y[i - 1]
    return y / (np.abs(y).max() + 1e-9) * env(n, 0.003, r)
def cat(*xs, gap=0.0):
    out = []
    for x in xs: out += [x, np.zeros(int(SR * gap))]
    return np.concatenate(out)
def mix(*xs):
    n = max(len(x) for x in xs); o = np.zeros(n)
    for x in xs: o[:len(x)] += x
    return o
NOTE = lambda m: 440 * 2 ** ((m - 69) / 12)
SYN = {
 'crack_tick': (lambda: noise(0.06, 2500, 0.02, 2) * 0.6, 'mining crack stage tick (paired with crack overlay)'),
 'puff': (lambda: noise(0.25, 900, 0.08, 3), 'block break puff (paired with particles)'),
 'splash': (lambda: mix(noise(0.45, 1800, 0.15, 4), sweep(600, 200, 0.3, 0.1) * 0.3), 'enter water (world-1)'),
 'swim_stroke': (lambda: noise(0.3, 700, 0.12, 5) * 0.7, 'swimming (world-1)'),
 'pan_swirl': (lambda: noise(1.2, 600, 0.6, 6) * (0.6 + 0.4 * np.sin(2 * np.pi * 2.5 * np.arange(int(SR * 1.2)) / SR)), 'pan swirl (world-1)'),
 'first_find': (lambda: cat(tone(NOTE(76), .12, 'tri'), tone(NOTE(79), .12, 'tri'), tone(NOTE(84), .4, 'tri', r=.3)), 'first find of an ore/element (Bertodex chip)'),
 'glow_snap': (lambda: mix(noise(0.05, 5000, 0.02, 7), sweep(900, 1600, 0.4, 0.25) * 0.4), 'glow stick snap/activate'),
 'power_on': (lambda: sweep(220, 660, 0.25, 0.2, 'tri'), 'power connected (wire glows teal)'),
 'power_off': (lambda: sweep(660, 220, 0.25, 0.2, 'tri'), 'power lost'),
 'low_battery': (lambda: cat(tone(NOTE(72), .18, 'sine', r=.12), tone(NOTE(67), .3, 'sine', r=.2), gap=.06) * 0.5, 'polite low-battery tone (paired with steady amber ring)'),
 'tube_whoosh': (lambda: noise(0.35, 1200, 0.15, 8) * np.hanning(int(SR * 0.35)), 'item enters tube'),
 'teleport': (lambda: mix(sweep(300, 1200, 0.5, 0.3), sweep(450, 1800, 0.5, 0.3) * 0.5), 'teleport pad send (items only)'),
 'drone_hum': (lambda: (tone(110, 1.0, 'soft', a=.05, r=10) + 0.4 * tone(220.5, 1.0, 'sine', a=.05, r=10)) * 0.4, 'drone flying loop (loopable 1 s)'),
 'bot_beep': (lambda: cat(tone(NOTE(81), .07, 'tri', r=.05), tone(NOTE(86), .09, 'tri', r=.06), gap=.03), 'bot acknowledges'),
 'bot_stuck': (lambda: cat(tone(NOTE(74), .1, 'tri', r=.07), tone(NOTE(70), .14, 'tri', r=.1), gap=.04), 'bot cannot reach (paired with chip)'),
 'boing': (lambda: sweep(180, 520, 0.35, 0.25, 'tri'), 'Bounce Block (fun-1)'),
 'craft_hammer': (lambda: cat(*(noise(.08, 3000, .03, 9 + i) for i in range(3)), gap=.08), 'Workbench craft'),
 'smelt_whoosh': (lambda: noise(0.8, 500, 0.4, 12), 'Smelter start'),
 'fab_whirr': (lambda: tone(140, 0.8, 'soft', a=.05, r=.5, vib=.03) * 0.6, 'Fabricator craft'),
 'charge_tick': (lambda: tone(NOTE(88), .05, 'sine', r=.03) * 0.4, 'charger / battery box pip'),
 'warp': (lambda: mix(sweep(1200, 200, 0.6, 0.35), noise(0.6, 2000, 0.3, 13) * 0.2), 'Warp Key (effects-1)'),
 'effect_on': (lambda: cat(tone(NOTE(72), .1, 'sine'), tone(NOTE(76), .1, 'sine'), tone(NOTE(79), .2, 'sine', r=.2)), 'effect starts (paired with timer ring)'),
 'effect_off': (lambda: cat(tone(NOTE(79), .1, 'sine'), tone(NOTE(76), .1, 'sine'), tone(NOTE(72), .2, 'sine', r=.2)), 'effect ends'),
 'sit': (lambda: noise(0.2, 600, 0.08, 14), 'sit on chair/stool/bench'),
 'wind_loop': (lambda: noise(3.0, 300, 99, 15) * 0.35 * (0.7 + 0.3 * np.sin(2 * np.pi * np.arange(int(SR * 3)) / (SR * 3))), 'Frostspire wind loop (quiet; off in class mode)'),
 'waves_loop': (lambda: noise(4.0, 500, 99, 16) * 0.4 * (0.5 + 0.5 * np.sin(2 * np.pi * 0.5 * np.arange(int(SR * 4)) / SR) ** 2), 'sea waves loop (world-2)'),
 'salt_ding': (lambda: tone(NOTE(84), .4, 'sine', r=.25) * 0.5, 'Salt Pan made salt'),
 'lights_on': (lambda: cat(*(tone(NOTE(m), .07, 'sine', r=.06) for m in (79, 83, 86, 91)), gap=.02) * 0.5, 'holiday/string lights switch on'),
}
INSTR = {  # note-block / instrument samples at C4; the engine pitch-shifts (music-1)
 'inst_marimba': lambda f: tone(f, .6, 'soft', r=.18), 'inst_chime': lambda f: mix(tone(f * 2, 1.2, 'sine', r=.5), tone(f * 5.4, 1.2, 'sine', r=.2) * 0.2),
 'inst_steeldrum': lambda f: mix(tone(f, .8, 'sine', r=.3), tone(f * 2.02, .8, 'sine', r=.2) * .4, tone(f * 3.9, .8, 'sine', r=.1) * .2),
 'inst_bass': lambda f: tone(f / 2, .7, 'soft', r=.25), 'inst_pluck': lambda f: tone(f, .5, 'tri', a=.002, r=.12),
 'inst_drum_kick': lambda f: sweep(150, 45, .35, .15), 'inst_drum_snare': lambda f: mix(noise(.25, 5000, .08, 20), tone(190, .2, 'sine', r=.05) * .5),
 'inst_drum_hat': lambda f: noise(.12, 9000, .03, 21) * .5, 'inst_clap': lambda f: cat(noise(.02, 3000, .01, 22), noise(.02, 3000, .01, 23), noise(.15, 3000, .06, 24), gap=.01),
}
def write_wav(x, path):
    x = x / (np.abs(x).max() + 1e-9) * 0.5; x = (x * 32767).astype(np.int16)
    with wave.open(path, 'wb') as w: w.setnchannels(1); w.setsampwidth(2); w.setframerate(SR); w.writeframes(x.tobytes())
def main():
    os.makedirs(f'{ROOT}/sfx', exist_ok=True); os.makedirs(f'{ROOT}/music', exist_ok=True); tmp = '/tmp/bert_sfx'; os.makedirs(tmp, exist_ok=True)
    for name, (pack, stem, use) in PICK.items():
        sub = 'music' if name.startswith('sting_') else 'sfx'; src = find(pack, stem); enc(src, f'{ROOT}/{sub}/{name}')
        for ext in ('ogg', 'mp3'): ROWS.append([name, 'sfx-sting' if sub == 'music' else 'sfx', f'{sub}/{name}.{ext}', '', URL[pack], LIC_K, 'Kenney (kenney.nl)', 'sourced (transcoded+normalised)', f'{use}; orig {pack}/{stem}.ogg'])
    for name, (fn, use) in SYN.items():
        w = f'{tmp}/{name}.wav'; write_wav(fn(), w); enc(w, f'{ROOT}/sfx/{name}', 'volume=1.0')
        for ext in ('ogg', 'mp3'): ROWS.append([name, 'sfx', f'sfx/{name}.{ext}', '', '', LIC_G, 'trebiluk project', 'generated', use])
    for name, fn in INSTR.items():
        w = f'{tmp}/{name}.wav'; write_wav(fn(NOTE(60)), w); enc(w, f'{ROOT}/sfx/{name}', 'volume=1.0')
        for ext in ('ogg', 'mp3'): ROWS.append([name, 'sfx-instrument', f'sfx/{name}.{ext}', '', '', LIC_G, 'trebiluk project', 'generated', 'music-1 note block / instruments (C4 sample)'])
    with open(f'{HERE}/_manifest_sfx.csv', 'w', newline='') as fh: csv.writer(fh).writerows(ROWS)
    print(len(PICK), 'picked', len(SYN), 'synth', len(INSTR), 'instruments')
if __name__ == '__main__': main()
