#!/usr/bin/env python3
"""UI icons per RULE-icons: literal pictures, 24x24 viewBox, stroke 2, round caps/joins, currentColor, aria-hidden.
Always rendered with a visible text label beside it inside a >=44 px target (the label is in strings, not here)."""
import os, csv
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE); OUT = f'{ROOT}/icons/ui'
LIC = 'Project-original (generated by tools/gen_icons.py; owner trebiluk); no third-party license'
I = {
 'bag': '<path d="M6 8h12l1 12H5z"/><path d="M9 8a3 3 0 0 1 6 0"/>',
 'craft': '<path d="M14 4l6 6-3 3-6-6z"/><path d="M11 7L4 20"/>',
 'tools': '<path d="M5 19l8-8"/><path d="M11 5c3-1 6 1 8 3l-3 1-2 2-3-3z"/>',
 'jump': '<path d="M12 19V7"/><path d="M7 12l5-5 5 5"/><path d="M5 21h14"/>',
 'crouch': '<path d="M12 5v10"/><path d="M7 11l5 5 5-5"/><path d="M5 21h14"/>',
 'drop': '<path d="M12 4v10"/><path d="M8 10l4 4 4-4"/><rect x="6" y="17" width="12" height="4" rx="1"/>',
 'use': '<path d="M9 11V5a1.5 1.5 0 0 1 3 0v5"/><path d="M12 10V8.5a1.5 1.5 0 0 1 3 0V11"/><path d="M15 11a1.5 1.5 0 0 1 3 0v3a7 7 0 0 1-7 7c-2 0-3-1-4-2l-3-4a1.5 1.5 0 0 1 2.5-1.5L9 15"/>',
 'inspect': '<circle cx="10" cy="10" r="6"/><path d="M15 15l5 5"/>',
 'undo': '<path d="M9 7L4 12l5 5"/><path d="M4 12h10a6 6 0 0 1 0 12"/>',
 'redo': '<path d="M15 7l5 5-5 5"/><path d="M20 12H10a6 6 0 0 0 0 12"/>',
 'settings': '<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1L7 17M17 7l2.1-2.1"/>',
 'map': '<path d="M3 6l6-2 6 2 6-2v14l-6 2-6-2-6 2z"/><path d="M9 4v14M15 6v14"/>',
 'dex': '<path d="M5 4h11a3 3 0 0 1 3 3v13H8a3 3 0 0 1-3-3z"/><path d="M5 17a3 3 0 0 1 3-3h11"/>',
 'daily': '<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M4 10h16M8 3v4M16 3v4"/><path d="M9 15l2 2 4-4"/>',
 'music': '<path d="M9 18V6l10-2v12"/><circle cx="7" cy="18" r="2"/><circle cx="17" cy="16" r="2"/>',
 'power': '<path d="M13 3L6 13h5l-1 8 7-10h-5z"/>',
 'battery_low': '<rect x="3" y="8" width="16" height="9" rx="2"/><path d="M21 11v3"/><path d="M6 11v3"/>',
 'battery_full': '<rect x="3" y="8" width="16" height="9" rx="2"/><path d="M21 11v3"/><path d="M6 11v3M9 11v3M12 11v3M15 11v3"/>',
 'link': '<path d="M10 14a4 4 0 0 0 6 0l3-3a4 4 0 0 0-6-6l-1 1"/><path d="M14 10a4 4 0 0 0-6 0l-3 3a4 4 0 0 0 6 6l1-1"/>',
 'network': '<circle cx="12" cy="5" r="2"/><circle cx="5" cy="19" r="2"/><circle cx="19" cy="19" r="2"/><path d="M12 7v5M12 12l-6 5M12 12l6 5"/>',
 'filter': '<path d="M4 5h16l-6 7v6l-4 2v-8z"/>',
 'lock': '<rect x="5" y="11" width="14" height="10" rx="2"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/>',
 'unlock': '<rect x="5" y="11" width="14" height="10" rx="2"/><path d="M8 11V8a4 4 0 0 1 7.5-2"/>',
 'home': '<path d="M3 11l9-7 9 7"/><path d="M6 10v10h12V10"/><path d="M10 20v-5h4v5"/>',
 'teleport': '<ellipse cx="12" cy="19" rx="7" ry="2"/><path d="M8 16V8M16 16V8M12 15V4"/><path d="M10 6l2-2 2 2"/>',
 'drone': '<rect x="9" y="10" width="6" height="4" rx="1"/><path d="M3 7h6M15 7h6M9 11L6 7M15 11l3-4"/><path d="M10 14v3h4v-3"/>',
 'bot': '<rect x="5" y="8" width="14" height="11" rx="2"/><circle cx="9.5" cy="13" r="1"/><circle cx="14.5" cy="13" r="1"/><path d="M12 8V4"/><circle cx="12" cy="3" r="1"/>',
 'sort': '<path d="M7 4v16M4 17l3 3 3-3"/><path d="M14 6h6M14 11h4M14 16h2"/>',
 'search': '<circle cx="10" cy="10" r="6"/><path d="M15 15l5 5"/>',
 'close': '<path d="M6 6l12 12M18 6L6 18"/>',
 'back': '<path d="M15 5l-7 7 7 7"/>',
 'info': '<circle cx="12" cy="12" r="9"/><path d="M12 11v6"/><path d="M12 7.5v.5"/>',
 'sound_on': '<path d="M4 9h4l5-4v14l-5-4H4z"/><path d="M16 9a4 4 0 0 1 0 6M18.5 6.5a8 8 0 0 1 0 11"/>',
 'sound_off': '<path d="M4 9h4l5-4v14l-5-4H4z"/><path d="M17 9l5 6M22 9l-5 6"/>',
 'motion_off': '<circle cx="12" cy="12" r="8"/><path d="M6 6l12 12"/>',
 'slow_taps': '<path d="M12 4a2 2 0 0 1 2 2v6"/><path d="M10 12V6a2 2 0 0 1 2-2"/><circle cx="18" cy="17" r="4"/><path d="M18 15v2l1 1"/><path d="M10 12l-2 3c-1 2 0 5 3 6"/>',
 'connect_time': '<circle cx="12" cy="13" r="8"/><path d="M12 9v4l3 2"/><path d="M9 2h6"/>',
 'language': '<circle cx="12" cy="12" r="9"/><path d="M3 12h18"/><path d="M12 3a14 14 0 0 1 0 18a14 14 0 0 1 0-18"/>',
 'teacher': '<circle cx="12" cy="7" r="3"/><path d="M6 21v-3a6 6 0 0 1 12 0v3"/><path d="M3 4h4"/>',
 'workshop': '<path d="M3 21V9l9-6 9 6v12"/><path d="M9 21v-6h6v6"/><path d="M9 11h6"/>',
 'swim': '<path d="M3 17c2 0 2-1 4.5-1S10 17 12 17s2.5-1 4.5-1S19 17 21 17"/><circle cx="15" cy="7" r="2"/><path d="M5 13l5-4 4 2"/>',
 'pan': '<ellipse cx="12" cy="14" rx="9" ry="4"/><path d="M8 13c2 1 6 1 8 0"/>',
 'bucket': '<path d="M5 9h14l-2 11H7z"/><path d="M6 9a6 6 0 0 1 12 0"/>',
 'glow': '<rect x="10" y="3" width="4" height="13" rx="2"/><path d="M12 16v5"/><path d="M5 8l2 1M19 8l-2 1M5 14l2-1M19 14l-2-1"/>',
 'light': '<path d="M9 18h6M10 21h4"/><path d="M8 14a6 6 0 1 1 8 0c-1 1-1 2-1 4H9c0-2 0-3-1-4z"/>',
 'wire': '<path d="M3 12h4l2-4 3 8 2-4h7"/>',
 'cog_coin': '<circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/><path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M5.6 18.4l2.1-2.1M16.3 7.7l2.1-2.1"/>',
 'gift': '<rect x="4" y="10" width="16" height="10" rx="1"/><path d="M3 7h18v3H3zM12 7v13"/><path d="M12 7c-2-4-6-3-5 0M12 7c2-4 6-3 5 0"/>',
 'star': '<path d="M12 3l2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1L3.2 9.5l6.1-.9z"/>',
 'trophy': '<path d="M8 4h8v5a4 4 0 0 1-8 0z"/><path d="M8 6H5a3 3 0 0 0 3 4M16 6h3a3 3 0 0 1-3 4"/><path d="M12 13v4M8 21h8M9 17h6v4H9z"/>',
 'scoreboard': '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 15v-3M12 15V8M17 15v-5"/>',
 'check': '<path d="M5 12l5 5 9-10"/>',
 'question': '<circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .8-1 1.5V14"/><path d="M12 17v.5"/>',
 'warning_amber': '<path d="M12 3l10 18H2z"/><path d="M12 10v5"/><path d="M12 18v.5"/>',
 'pickaxe': '<path d="M14 6L5 20"/><path d="M5 7c4-3 10-3 14 0"/>',
 'chest': '<rect x="3" y="8" width="18" height="12" rx="1"/><path d="M3 12h18"/><path d="M5 8a7 4 0 0 1 14 0"/><rect x="10" y="11" width="4" height="3"/>',
 'shelf': '<path d="M4 4v16M20 4v16M4 9h16M4 15h16"/>',
 'tube': '<rect x="3" y="9" width="18" height="6" rx="3"/><circle cx="9" cy="12" r="1"/><circle cx="14" cy="12" r="1"/>',
 'chip': '<rect x="7" y="7" width="10" height="10" rx="1"/><path d="M10 3v4M14 3v4M10 17v4M14 17v4M3 10h4M3 14h4M17 10h4M17 14h4"/>',
 'note_block': '<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M11 16V8l5-1v7"/><circle cx="10" cy="16" r="1.5"/>',
 'jukebox': '<path d="M5 21V10a7 7 0 0 1 14 0v11z"/><circle cx="12" cy="11" r="3"/><path d="M8 17h8"/>',
 'pumpkin': '<path d="M12 7c5 0 8 3 8 7s-3 6-8 6-8-2-8-6 3-7 8-7z"/><path d="M12 7c-2 3-2 10 0 13M12 7c2 3 2 10 0 13"/><path d="M12 7c0-2 1-3 3-4"/>',
 'carve': '<path d="M12 7c5 0 8 3 8 7s-3 6-8 6-8-2-8-6 3-7 8-7z"/><path d="M8 12l2 1M16 12l-2 1M9 16c2 1 4 1 6 0"/>',
 'string_lights': '<path d="M2 6c5 5 15 5 20 0"/><path d="M6 9v2M12 11v2M18 9v2"/><circle cx="6" cy="13" r="1.5"/><circle cx="12" cy="15" r="1.5"/><circle cx="18" cy="13" r="1.5"/>',
 'chair': '<path d="M7 3v18M7 13h10v8M7 13V3"/><path d="M17 13v-2"/>',
 'paint': '<path d="M4 20c4 0 4-4 8-4l6-10-2-2-10 6c0 4-4 4-2 10z"/>',
 'biome': '<path d="M3 20l6-10 4 6 3-4 5 8z"/><circle cx="17" cy="6" r="2"/>',
 'flag': '<path d="M5 21V4"/><path d="M5 4h12l-3 4 3 4H5"/>',
}
def main():
    os.makedirs(OUT, exist_ok=True); rows = []
    for k, body in I.items():
        svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">{body}</svg>\n'
        open(f'{OUT}/{k}.svg', 'w').write(svg); rows.append([f'ui:{k}', 'ui-icon', f'icons/ui/{k}.svg', '24x24 svg', '', LIC, 'trebiluk project', 'generated', 'HUD/panels (label always visible)'])
    with open(f'{HERE}/_manifest_icons.csv', 'w', newline='') as fh: csv.writer(fh).writerows(rows)
    print(len(I), 'icons')
if __name__ == '__main__': main()
