# Machine Panel "Inside" tab lines (CRAFTING-AND-MACHINE-UI §3). Status: unchecked until Curriculum checks.
# GM = text from GameMaster's doc; others written by Debugzy (grade 5-6, true).
GM = {'smelter'}
INSIDE = {
 'workbench': 'A lever arm and a firm table let your hands push harder and cut straighter.',
 'oven': 'Heat makes dough rise and bake. Much hotter heat melts sand into glass.',
 'vend': 'A coin slot checks size and weight to tell coins apart.',
 'bunk': 'Sleep lets your body and brain rest and repair.',
 'box': 'A box is a frame that spreads weight into its corners.',
 'lever': 'A switch closes a gap in a circuit so power can flow.',
 'leverOn': 'A switch closes a gap in a circuit so power can flow.',
 'pushButton': 'A spring pushes the button back, so the circuit opens again.',
 'pushButtonOn': 'A spring pushes the button back, so the circuit opens again.',
 'smelter': 'Heat melts metal from rock. Carbon from coal pulls oxygen away from the metal.',
 'fabricator': 'Small motors move a tool along three directions to build a part step by step.',
 'lantern': 'An LED turns electricity into light. It wastes much less energy as heat than an old bulb.',
 'charger': 'A charger pushes electricity back into a battery to refill its stored energy.',
 'glowPebble': 'Two chemicals react and give off energy as light, with almost no heat.',
 'glowStick': 'Bending the stick breaks a glass tube inside, so two chemicals mix and glow.',
 'jumboGlow': 'The dye takes the energy from the reaction and gives it off as its own color.',
 'coldGlowVial': 'Cold makes molecules move slower, so the reaction is slower and lasts longer.',
 'solarPanel': 'Sunlight knocks electrons loose in silicon. The loose electrons flow as electricity.',
 'glowStrip': 'Many small LEDs in a row share one wire, so one strip lights a long line.',
 'copperWireBlock': 'Electrons move easily through copper, so it carries power with little loss.',
 'saltPan': 'The Sun heats the water until it evaporates. The salt cannot evaporate, so it stays.',
 'wallShelf': 'Brackets carry the shelf weight into the wall.',
 'shelf': 'Each board holds weight across its supports, like a small bridge.',
 'sideTable': 'A drawer slides on rails, so it moves smoothly in and out.',
 'desk': 'Drawers slide on rails, so they move smoothly in and out.',
 'cabinet': 'A lock uses pins that only line up with the right key.',
 'glassCabinet': 'Glass lets light through, so you can see inside without opening it.',
 'steelLocker': 'Steel is strong and hard to bend, which protects what is inside.',
 'itemTube': 'A gentle push of air moves light things along a tube.',
 'poweredTube': 'Copper coils make a magnetic push that speeds items along.',
 'filterTube': 'A sensor reads each item and opens a gate only for a match.',
 'extractor': 'A small motor and arm pull one stack at a time on a timer.',
 'sorter': 'A sensor reads each item and flips a gate to send it the right way.',
 'networkCable': 'A cable carries signals as tiny changes in electricity.',
 'networkCore': 'A computer keeps a list of where every item is stored.',
 'driveBay': 'A drive stores information as tiny switches set to on or off.',
 'terminal': 'A search looks through an index, like the index at the back of a book.',
 'storageLink': 'A sensor counts what is in the box and reports it to the network.',
 'teleportPad': 'In Bertopia items jump between pads. Real teleporting of objects is not possible.',
 'droneDock': 'Contacts on the pad touch the drone and refill its battery.',
 'batteryBox': 'Batteries store energy as chemicals and give it back as electricity.',
 'networkPad': 'In Bertopia it links the pads to your network. Real teleporting of objects is not possible.',
 'noteBlock': 'Tapping makes the block vibrate. Faster vibrations make a higher pitch.',
 'keyboardBlock': 'Each pad plays a different pitch. Higher pads vibrate faster.',
 'drumKit': 'A drum skin vibrates when hit. A tighter skin makes a higher sound.',
 'guitar': 'A string vibrates when plucked. A shorter or tighter string sounds higher.',
 'jukebox': 'A speaker cone moves back and forth to push air and make sound waves.',
 'labBench': 'Scientists test one change at a time so they know what caused a result.',
 'warpPad': 'In Bertopia a Warp Key brings you here. Real teleporting of people is not possible.',
 'sleepingBag': 'Trapped air inside the bag slows heat loss and keeps you warm.',
 'crewBanner': 'A banner is a flag that helps a team find its meeting spot.',
 'gameZoneFlag': 'A boundary marks the edges so everyone knows where the game is.',
 'draftingTable': 'A drawing with exact measurements lets anyone build the same thing.',
 'cleanBench': 'Filters take dust out of the air. Dust can ruin tiny electronic parts.',
}
