# Bertopia registry source (data only). gen_pack.py turns this into registry.json + atlas maps.
# Block ids 1-31 are LIVE (bloxbert-src/src/main.js BLOCKS, 2.5.42) and must never change.
# New ids are proposals in milestone order; the Build chat uses them as-is (saves store a name palette too).
# faces: 'tex' for all faces, or dict(top=,side=,bottom=) / dict(front=,side=,top=). kind drives the mesh:
#   cube | alpha (see-through cube) | cross (plant/deco sprite) | flat (thin on a face) | model (non-cube, uses item icon + simple mesh)
# 'what' = Bertodex "What it is" line (DRAFT, Curriculum Bot checks before ship). from = availableFrom (WORLD-1 §6).
L = 'live'
BLOCKS = [
 # id, key, en name, kind, faces, hand_s, milestone, from, dexCat, what
 (1,'grass','Grass','cube',dict(top='grass_top',side='dirt_grass',bottom='dirt'),0.6,L,L,'Blocks','Grass on top of soil. Break it and you get Dirt.'),
 (2,'dirt','Dirt','cube','dirt',0.6,L,L,'Ores & Rocks','Soil: tiny bits of rock mixed with old plant matter.'),
 (3,'stone','Stone','cube','stone',3.0,L,L,'Ores & Rocks','Plain rock. Most of the underground is stone.'),
 (4,'slate','Slate','cube','greystone',3.5,L,L,'Ores & Rocks','A dark rock that splits into flat sheets.'),
 (5,'coal','Coal Ore','cube','stone_coal',3.5,L,L,'Ores & Rocks','Coal formed from plants buried and squeezed for millions of years. It is fuel.'),
 (6,'sand','Sand','cube','sand',0.5,L,L,'Ores & Rocks','Sand is mostly tiny grains of quartz. Bake 2 in the Oven for Glass.'),
 (7,'gravel','Gravel','cube','gravel_stone',0.7,L,L,'Ores & Rocks','Small rounded stones, often found in river beds.'),
 (8,'brickRed','Red Brick','cube','brick_red',4.0,L,L,'Blocks','Baked clay bricks. Strong when you push on them.'),
 (9,'brickGrey','Grey Brick','cube','brick_grey',4.0,L,L,'Blocks','Stone cut into bricks.'),
 (10,'planks','Planks','cube','wood',1.5,L,L,'Materials','Boards sawn from a log. 1 Log makes 4.'),
 (11,'log','Log','cube',dict(top='trunk_top',side='trunk_side',bottom='trunk_top'),2.0,L,L,'Plants & Critters','A piece of tree trunk. The rings show its age.'),
 (12,'leaves','Leaves','alpha','leaves',0.2,L,L,'Plants & Critters','Leaves make food for the tree from sunlight. Sometimes a Berry falls out.'),
 (13,'woolBlue','Blue Cloth Block','cube','cotton_blue',0.8,L,L,'Blocks','A soft block of dyed cloth.'),
 (14,'woolGreen','Green Cloth Block','cube','cotton_green',0.8,L,L,'Blocks','A soft block of dyed cloth.'),
 (15,'woolRed','Red Cloth Block','cube','cotton_red',0.8,L,L,'Blocks','A soft block of dyed cloth.'),
 (16,'woolTan','Tan Cloth Block','cube','cotton_tan',0.8,L,L,'Blocks','A soft block of undyed cloth.'),
 (17,'snow','Snow','cube','snow',0.3,L,L,'Ores & Rocks','Frozen water crystals. Lands soft.'),
 (18,'ice','Ice','cube','ice',0.5,L,L,'Ores & Rocks','Frozen water. In Bertopia it does not slide.'),
 (19,'redSand','Red Sand','cube','redsand',0.5,L,L,'Ores & Rocks','Sand stained red by iron. Bake it for Red Brick.'),
 (20,'glass','Glass','alpha','glass',0.4,L,L,'Materials','Sand melted and cooled until you can see through it.'),
 (21,'coreplate','Coreplate','cube','coreplate',None,L,L,'Places','The floor of the world at y -64. It never breaks.'),
 (22,'workbench','Workbench','cube',dict(top='workbench_top',side='workbench_side',bottom='wood'),None,L,L,'Items & Machines','A table for making things from wood, cloth and stone.'),
 (23,'oven','Oven','cube',dict(front='oven_front',side='oven_side',top='oven_top'),None,L,L,'Items & Machines','Bakes food and turns sand into glass.'),
 (24,'vend','Vending Counter','cube',dict(front='vend_front',side='machine_side',top='machine_top'),None,L,L,'Items & Machines','Sells your goods to townsfolk while you play.'),
 (25,'storeCounter','Store Counter','cube',dict(front='store_front',side='wood',top='store_top'),None,L,L,'Places','The town store. Restock things you have already found.'),
 (26,'bunk','Bunk','cube',dict(top='bunk_top',side='bunk_side',bottom='wood'),None,L,L,'Items & Machines','Tap it to set your home spot.'),
 (27,'box','Box','cube',dict(front='box_front',side='box_side',top='box_top'),None,L,L,'Items & Machines','Holds 18 stacks. Two side by side make a Double Box.'),
 (28,'wheat','Wheat','cross','wheat_stage4',0.4,L,L,'Plants & Critters','A grass whose seeds are ground into flour.'),
 (29,'reed','Reed','cross','reed',0.4,L,L,'Plants & Critters','A tall plant that grows by water. Here it gives sugar.'),
 (30,'door','Wood Door','model',dict(top='door_wood_top',bottom='door_wood_bottom'),1.5,L,L,'Blocks','A door made from 6 Planks. Tap to open.'),
 (31,'doorOpen','Wood Door (open)','model',dict(top='door_wood_top',bottom='door_wood_bottom'),1.5,L,L,'Blocks','An open wood door.'),
 # basics-1 (2.5.44)
 (32,'doorGlass','Glass Door','model',dict(top='door_glass_top',bottom='door_glass_bottom'),None,'basics-1',L,'Blocks','A door with glass panes. Tap to open.'),
 (33,'doorGlassOpen','Glass Door (open)','model',dict(top='door_glass_top',bottom='door_glass_bottom'),None,'basics-1',L,'Blocks','An open glass door.'),
 (34,'doorMetal','Metal Door','model',dict(top='door_metal_top',bottom='door_metal_bottom'),None,'basics-1',L,'Blocks','A steel door. Only a button, lever or power opens it.'),
 (35,'doorMetalOpen','Metal Door (open)','model',dict(top='door_metal_top',bottom='door_metal_bottom'),None,'basics-1',L,'Blocks','An open metal door.'),
 (36,'doorSliding','Sliding Lab Door','model',dict(top='door_slide_top',bottom='door_slide_bottom'),None,'basics-1',L,'Blocks','Slides open when powered and someone walks up.'),
 (37,'doorSlidingOpen','Sliding Lab Door (open)','model',dict(top='door_slide_top',bottom='door_slide_bottom'),None,'basics-1',L,'Blocks','An open sliding door.'),
 (38,'lever','Lever','model','lever_off',None,'basics-1',L,'Items & Machines','Flip it to turn a circuit on or off.'),
 (39,'leverOn','Lever (on)','model','lever_on',None,'basics-1',L,'Items & Machines','A lever switched on.'),
 (40,'pushButton','Push Button','model','button_off',None,'basics-1',L,'Items & Machines','Press it for 1.5 seconds of power.'),
 (41,'pushButtonOn','Push Button (on)','model','button_on',None,'basics-1',L,'Items & Machines','A pressed button.'),
 (42,'smelter','Smelter','cube',dict(front='smelter_front',side='smelter_side',top='smelter_top'),None,'basics-1',L,'Items & Machines','Melts ore into metal. Its Forge tab shapes the metal.'),
 (43,'fabricator','Fabricator','cube',dict(front='fabricator_front',side='machine_side',top='machine_top'),None,'basics-1',L,'Items & Machines','Builds anything with a battery, silicon or a chip. Runs on charge.'),
 (44,'ironOre','Iron Ore','cube','ore_iron',5.0,'world-1','world-1','Ores & Rocks','Rusty rock full of iron. Most metal people use is iron.'),
 (45,'copperOre','Copper Ore','cube','ore_copper',4.5,'world-1','world-1','Ores & Rocks','Rock with copper in it. Copper carries electricity, so wires use it.'),
 (46,'zincOre','Zinc Ore','cube','ore_zinc',4.5,'world-1','world-1','Ores & Rocks','Rock with zinc. Zinc coats steel so it does not rust.'),
 (47,'lantern','LED Lantern','model','lantern',None,'basics-1',L,'Items & Machines','A battery light. Tap for Low, Medium or High.'),
 (48,'charger','Charger','model','charger',None,'basics-1',L,'Items & Machines','Like a wall outlet: it always gives power.'),
 # basics-2 (2.5.45)
 (49,'glowPebble','Glow Pebble','model','glow_pebble',None,'basics-2',L,'Items & Machines','A tiny glow. A little chemical makes a short light.'),
 (50,'glowStick','Glow Stick','model','glow_stick',None,'basics-2',L,'Items & Machines','A chemical light. Once it is used up, it is done.'),
 (51,'jumboGlow','Jumbo Glow','model','glow_jumbo',None,'basics-2',L,'Items & Machines','A big glow stick. A dye takes the energy and picks the color.'),
 (52,'coldGlowVial','Cold Glow Vial','model','glow_cold',None,'basics-2','world-2','Items & Machines','Cold slows the reaction, so it glows longer.'),
 (53,'glowMoss','Glow Moss','cube','glow_moss',0.3,'world-1','world-1','Plants & Critters','A cave moss that glows. Glowing fungi are real; glowing moss is a Bertopia idea.'),
 (54,'cornPlant','Corn Bush','cross','corn_bush',0.2,'basics-2',L,'Plants & Critters','Corn is a grain. Some plastics are made from corn.'),
 # basics-3 (2.5.46)
 (55,'solarPanel','Solar Panel','model',dict(top='solar_top',side='machine_side'),None,'basics-3',L,'Items & Machines','Turns sunlight into power. Its cell runs 2 strips through the night.'),
 (56,'glowStrip','LED Glow Strip','flat','glow_strip',None,'basics-3',L,'Items & Machines','A thin light that uses 1 charge a minute.'),
 (57,'copperWireBlock','Copper Wire','flat','wire_copper',None,'basics-3',L,'Items & Machines','Carries power from makers to users. Glows teal when powered.'),
 # world-1 (2.6.2-2.6.3)
 (58,'water','Water','alpha','water',None,'world-1','world-1','Places','In Bertopia water stays still and never floods a build.'),
 (59,'tinOre','Tin Ore','cube','ore_tin',4.5,'world-1','world-1','Ores & Rocks','Dark crystals of cassiterite. About 9 parts copper to 1 part tin makes bronze.'),
 (60,'quartzOre','Quartz Vein','cube','ore_quartz',4.5,'world-1','world-1','Ores & Rocks','White crystals of silica, the same stuff as most sand.'),
 (61,'quartzSand','Quartz Sand','cube','sand_quartz',0.5,'world-2','world-2','Ores & Rocks','Dune sand with quartz grains you can collect.'),
 (62,'clay','Clay','cube','clay',0.7,'world-1','world-1','Ores & Rocks','Soft, sticky earth found by water. Bake it into Brick.'),
 (63,'boundaryClay','Boundary Clay','cube','clay_boundary',0.7,'world-2','world-2','Places','A thin layer laid down all over Earth after a giant asteroid hit.'),
 (64,'silverOre','Silver Ore','cube','ore_silver',6.0,'world-1','world-1','Ores & Rocks','Silver reflects light better than any other metal.'),
 (65,'goldOre','Gold Ore','cube','ore_gold',7.0,'world-1','world-1','Ores & Rocks','Gold hides in quartz veins deep in hard rock.'),
 (66,'graphiteOre','Graphite','cube','ore_graphite',3.0,'world-2','world-2','Ores & Rocks','Soft, shiny carbon made when heat and pressure changed old rock.'),
 (67,'pannedGravel','Panned Gravel','cube','gravel_panned',0.7,'world-1','world-1','Ores & Rocks','Gravel you already panned. It has nothing left to find.'),
 (68,'molten','Molten Metal','alpha','molten',None,'later','later','Places','Metal so hot it flows. Here it bounces you back to safety.'),
 # world-2 (2.6.4-2.6.5)
 (69,'saltCrust','Salt Crust','cube','salt_crust',0.8,'world-2','world-2','Ores & Rocks','Salt left behind where an old lake dried up.'),
 (70,'blackSand','Black Sand','cube','sand_black',0.5,'world-2','world-2','Ores & Rocks','Beach sand full of heavy titanium minerals.'),
 (71,'bauxite','Bauxite','cube','bauxite',1.0,'world-2','world-2','Ores & Rocks','Red-brown earth rich in aluminum. It forms where rock weathers in warm, wet places.'),
 (72,'ilmeniteOre','Ilmenite Ore','cube','ore_ilmenite',6.0,'world-2','world-2','Ores & Rocks','A heavy black mineral that holds titanium.'),
 (73,'platinumOre','Platinum Ore','cube','ore_platinum',9.0,'world-2','world-2','Ores & Rocks','One of the rarest metals in the crust. Only deep under Emberdeep.'),
 (74,'basalt','Basalt','cube','basalt',3.0,'world-2','world-2','Ores & Rocks','Dark rock made when lava cools.'),
 (75,'snowGrass','Snowy Grass','cube',dict(top='snow',side='dirt_snow',bottom='dirt'),0.6,'world-2','world-2','Blocks','Soil with a cap of snow.'),
 (76,'cottonBush','Cotton Bush','cross','cotton_bush',0.2,'world-2',L,'Plants & Critters','Cotton fluff is plant fiber. 3 Cotton spin into 1 Cloth.'),
 (77,'flowerBush','Flowers','cross','flower_teal',0.2,'world-2','world-2','Plants & Critters','Flowers feed bees and butterflies. 1 Flower makes 2 Paint dabs.'),
 (78,'saltPan','Salt Pan','model','salt_pan',None,'world-2','world-2','Items & Machines','Sun dries seawater. The salt stays behind.'),
 # storage-1
 (79,'wallShelf','Wall Shelf','model','shelf_wall',None,'storage-1',L,'Items & Machines','Holds 3 things and shows all 3.'),
 (80,'shelf','Shelf','model','shelf',None,'storage-1',L,'Items & Machines','Holds 4 things and shows all 4.'),
 (81,'sideTable','Side Table','model','side_table',None,'storage-1',L,'Items & Machines','A table with 1 drawer: 6 slots.'),
 (82,'desk','Desk','model','desk',None,'storage-1',L,'Items & Machines','2 drawers, 12 slots, 1 thing on top.'),
 (83,'cabinet','Cabinet','cube',dict(front='cabinet_front',side='wood',top='wood'),None,'storage-1',L,'Items & Machines','24 slots behind a door you can lock.'),
 (84,'glassCabinet','Glass Cabinet','cube',dict(front='cabinet_glass_front',side='wood',top='wood'),None,'storage-1',L,'Items & Machines','24 slots, lockable, shows its top 4 things.'),
 (85,'steelLocker','Steel Locker','cube',dict(front='locker_front',side='locker_side',top='locker_side'),None,'storage-1',L,'Items & Machines','36 slots in steel, lockable.'),
 (86,'sign','Sign','model','sign',None,'storage-1',L,'Blocks','A label for a Box or a path.'),
 # storage-4
 (87,'itemTube','Item Tube','model','tube_glass',None,'storage-4',L,'Items & Machines','A clear tube that moves items 2 blocks a second.'),
 (88,'poweredTube','Powered Tube','model','tube_powered',None,'storage-4',L,'Items & Machines','A tube with copper rings: 6 blocks a second.'),
 (89,'filterTube','Filter Tube','model','tube_filter',None,'storage-4',L,'Items & Machines','Only lets in items that match its rule.'),
 (90,'extractor','Extractor','model','extractor',None,'storage-4',L,'Items & Machines','Pulls a stack out of storage every 2 seconds.'),
 (91,'sorter','Sorter','cube',dict(front='sorter_front',side='sorter_side',top='sorter_side'),None,'storage-4',L,'Items & Machines','Sends items down up to 4 outputs by rule.'),
 # storage-5
 (92,'networkCable','Network Cable','model','cable_network',None,'storage-5',L,'Items & Machines','Links storage into one network.'),
 (93,'networkCore','Network Core','cube',dict(front='core_front',side='machine_side',top='machine_top'),None,'storage-5',L,'Items & Machines','The brain of a storage network. 1 per player.'),
 (94,'driveBay','Drive Bay','cube',dict(front='drivebay_front',side='machine_side',top='machine_top'),None,'storage-5',L,'Items & Machines','Holds 4 Drives.'),
 (95,'terminal','Terminal','cube',dict(front='terminal_front',side='machine_side',top='machine_top'),None,'storage-5',L,'Items & Machines','A search engine for your stuff.'),
 (96,'storageLink','Storage Link','model','storage_link',None,'storage-5',L,'Items & Machines','Snaps onto a Box so the network can see inside.'),
 # storage-3 + storage-6
 (97,'teleportPad','Teleport Pad','model','pad_teleport',None,'storage-3',L,'Items & Machines','Sends items (never people) to its partner pad.'),
 (98,'droneDock','Drone Dock','model','dock_drone',None,'storage-3',L,'Items & Machines','Charges and launches your Delivery Drone.'),
 (99,'batteryBox','Battery Box','cube',dict(front='batterybox_front',side='machine_side',top='machine_top'),None,'storage-6',L,'Items & Machines','Stores 40 charges for the night.'),
 (100,'networkPad','Network Pad','model','pad_network',None,'storage-6',L,'Items & Machines','A teleport pad that talks to your network.'),
 # fun-1, music-1
 (101,'bounceBlock','Bounce Block','cube',dict(top='bounce_top',side='bounce_side',bottom='wood'),None,'fun-1',L,'Blocks','A spring pad. It stores energy when you land and gives it back.'),
 (102,'discoFloor','Disco Floor','cube',dict(top='disco_top',side='machine_side',bottom='machine_side'),None,'fun-1',L,'Blocks','Lights up where you step. Smooth fades, never strobe.'),
 (103,'noteBlock','Note Block','cube',dict(top='note_top',side='note_side',bottom='wood'),None,'music-1',L,'Items & Machines','Tap to raise the pitch. The block under it picks the instrument.'),
 (104,'keyboardBlock','Keyboard','model','keyboard',None,'music-1',L,'Items & Machines','An 8-pad keyboard you can play.'),
 (105,'drumKit','Drum Kit','model','drumkit',None,'music-1',L,'Items & Machines','An 8-pad drum kit.'),
 (106,'guitar','Guitar','model','guitar',None,'music-1',L,'Items & Machines','An 8-pad guitar.'),
 (107,'jukebox','Jukebox','cube',dict(front='jukebox_front',side='jukebox_side',top='jukebox_top'),None,'music-1',L,'Items & Machines','Plays Music Discs, including your own DJ Berty songs.'),
 # holidays-1: ONE 'Seasonal & Holiday' pile (Diego 2026-10-06): every item at once, no dates, one teacher switch
 (108,'pumpkin','Pumpkin','cube',dict(top='pumpkin_top',side='pumpkin_side',bottom='pumpkin_top'),None,'holidays-1',L,'Seasonal & Holiday','A squash that ripens in autumn.'),
 (109,'jackOLantern','Jack-o\'-Lantern','cube',dict(front='jack_front',side='pumpkin_side',top='pumpkin_top'),None,'holidays-1',L,'Seasonal & Holiday','A carved pumpkin with an LED inside, never a flame.'),
 (110,'cornStalks','Corn Stalks','cross','corn_stalks',None,'holidays-1',L,'Seasonal & Holiday','Dried corn stalks tied in a bundle.'),
 (111,'leafPile','Leaf Pile','cube','leaf_pile',None,'holidays-1',L,'Seasonal & Holiday','Autumn leaves raked into a pile.'),
 (112,'appleCrate','Apple Crate','cube',dict(top='apple_crate_top',side='apple_crate_side',bottom='wood'),None,'holidays-1',L,'Seasonal & Holiday','A wooden crate of autumn apples.'),
 (113,'ghostLight','Friendly Ghost Light','model','ghost_light',None,'holidays-1',L,'Seasonal & Holiday','A soft smiling ghost-shaped light.'),
 (114,'cobweb','Cobweb Deco','cross','cobweb',None,'holidays-1',L,'Seasonal & Holiday','A fake cobweb for decoration.'),
 (115,'marigold','Marigolds','cross','marigold',None,'holidays-1',L,'Seasonal & Holiday','Bright orange flowers that bloom from summer into autumn.'),
 (116,'papelPicado','Papel Picado Banner','flat','papel_picado',None,'holidays-1',L,'Seasonal & Holiday','Cut-paper banners in bright colors.'),
 (117,'skullPatternTile','Marigold Pattern Tile','cube','tile_skull_pattern',None,'holidays-1',L,'Seasonal & Holiday','A tile with a bright marigold flower pattern.'),
 (119,'rangoliTile','Pattern Floor Tile','cube','tile_rangoli',None,'storage-2',L,'Blocks','A floor tile with a simple geometric pattern. Paint it any colour.'),
 (120,'stringLights','String Lights','flat','string_lights',None,'holidays-1',L,'Seasonal & Holiday','A strand of small LED lights.'),
 # near-term stations, effects, progression (briefs not written yet)
 (121,'labBench','Lab Bench','cube',dict(top='labbench_top',side='labbench_side',bottom='wood'),None,'effects-1',L,'Items & Machines','Where Wonder Lab gadgets and effects are made.'),
 (122,'warpPad','Warp Pad','model','pad_warp',None,'effects-1',L,'Items & Machines','A player-size pad you can warp to with a Warp Key.'),
 (123,'sleepingBag','Sleeping Bag','model','sleeping_bag',None,'effects-1',L,'Items & Machines','Tap to set where you come back.'),
 (124,'crewBanner','Crew Banner','model','crew_banner',None,'effects-1',L,'Items & Machines','A shared spawn spot for your crew.'),
 (125,'gameZoneFlag','Game Zone Flag','model','game_flag',None,'effects-1',L,'Items & Machines','Marks a play zone for Hide-and-Seek and mini-games.'),
 (126,'workshopDoor','Workshop Door','model',dict(top='door_workshop_top',bottom='door_workshop_bottom'),None,'worlds-1',L,'Places','Teacher-flag door to the Build world.'),
 (127,'draftingTable','Drafting Table','cube',dict(top='drafting_top',side='wood',bottom='wood'),None,'ladder-1',L,'Items & Machines','Read Blueprint Scrolls here to unlock new materials.'),
 (128,'cleanBench','Clean Bench','cube',dict(front='cleanbench_front',side='machine_side',top='machine_top'),None,'ladder-1',L,'Items & Machines','A dust-free bench for the finest materials.'),
 (129,'copperBlock','Copper Block','cube','copper_block',5.0,'ladder-1',L,'Blocks','A solid block of copper.'),
 (130,'steelBlock','Steel Block','cube','steel_block',7.5,'ladder-1',L,'Blocks','A solid block of steel.'),
 (131,'mirror','Mirror','alpha','mirror',None,'ladder-1',L,'Blocks','Polished silver behind glass reflects light.'),
 (132,'dexShelf','Dex Shelf','model','dex_shelf',None,'world-3',L,'Blocks','A trophy for filling half the Bertodex.'),
 (133,'trophyShelf','Trophy Shelf','model','trophy_shelf',None,'later',L,'Blocks','Shows the trophies you earned.'),
 (134,'bamboo','Bamboo Pole','cube',dict(top='bamboo_top',side='bamboo_side',bottom='bamboo_top'),1.0,'ladder-1',L,'Materials','A light, hollow grass stem. Strong for its weight.'),
 (135,'plywood','Plywood','cube','plywood',1.5,'ladder-1',L,'Materials','Thin wood layers glued with the grain crossing.'),
 (136,'cutStone','Cut Stone','cube','cut_stone',3.0,'ladder-1',L,'Materials','Stone cut into neat blocks.'),
 (137,'cinderBlock','Cinder Block','cube',dict(top='cinder_top',side='cinder_side',bottom='cinder_top'),3.0,'ladder-1',L,'Materials','A hollow concrete block, like real building blocks.'),
 (138,'concrete','Concrete','cube','concrete',3.0,'ladder-1',L,'Materials','Strong when pushed, cracks when pulled.'),
 (139,'roofTile','Roof Tile','cube','roof_tile',2.0,'ladder-1',L,'Materials','Overlapping tiles shed rain.'),
 (140,'tintedGlass','Tinted Glass','alpha','glass_tinted',0.4,'ladder-1',L,'Materials','Translucent: lets some light through.'),
 (141,'frostedGlass','Frosted Glass','alpha','glass_frosted',0.4,'ladder-1',L,'Materials','Lets light through but blurs what is behind it.'),
 (142,'glassPane','Glass Pane','flat','glass_pane',0.4,'ladder-1',L,'Materials','A thin sheet of glass.'),
 (143,'quartzCrystal','Quartz Crystal','cross','quartz_cluster',1.0,'world-2','world-2','Blocks','A cluster of quartz crystals.'),
 (144,'overflowBox','Overflow Box','cube',dict(front='overflow_front',side='box_side',top='box_top'),None,'2.6.0',L,'Places','Holds what did not fit. Take-only, never deleted.'),
 (145,'bronzePlaque','Bronze Plaque','flat','bronze_plaque',None,'later',L,'Blocks','A plaque cast in bronze.'),
 (146,'granite','Granite','cube','granite',3.0,'world-2','world-2','Ores & Rocks','Speckled rock made from slowly cooled magma.'),
 (147,'redSoil','Red Soil','cube','red_soil',0.6,'world-2','world-2','Ores & Rocks','Soil weathered for a long time in a warm, wet climate.'),
 (148,'birchLog','Birch-like Log','cube',dict(top='trunk_white_top',side='trunk_white_side',bottom='trunk_white_top'),2.0,'world-2','world-2','Plants & Critters','A tree with pale bark.'),
 (149,'birchLeaves','Birch-like Leaves','alpha','leaves_birch',0.2,'world-2','world-2','Plants & Critters','Light green leaves.'),
 (150,'spruceLog','Spruce-like Log','cube',dict(top='trunk_spruce_top',side='trunk_spruce_side',bottom='trunk_spruce_top'),2.0,'world-2','world-2','Plants & Critters','A tree that keeps its needles all winter.'),
 (151,'spruceLeaves','Spruce-like Needles','alpha','leaves_spruce',0.2,'world-2','world-2','Plants & Critters','Needle leaves that shed snow.'),
 (152,'flowerBushPink','Flowers (pink)','cross','flower_pink',0.2,'world-2','world-2','Plants & Critters','Flowers feed bees and butterflies.'),
 (153,'flowerBushYellow','Flowers (yellow)','cross','flower_yellow',0.2,'world-2','world-2','Plants & Critters','Flowers feed bees and butterflies.'),
 (154,'seaWater','Sea Water','alpha','water',None,'world-2','world-2','Places','Still seawater. A Salt Pan beside it makes salt.'),
 (155,'hayBale','Hay Bale','cube',dict(top='hay_top',side='hay_side',bottom='hay_top'),None,'holidays-1',L,'Seasonal & Holiday','Dried grass pressed into a bale, used to feed animals.'),
 (156,'gourds','Gourds','cross','gourds',None,'holidays-1',L,'Seasonal & Holiday','Gourds are cousins of pumpkins and squash, in many shapes.'),
 (157,'scarecrow','Scarecrow','model','scarecrow',None,'holidays-1',L,'Seasonal & Holiday','A straw figure farmers use to keep birds off crops.'),
 (158,'batsDeco','Bat Garland','flat','bats_deco',None,'holidays-1',L,'Seasonal & Holiday','Paper bats. Real bats eat lots of insects at night.'),
 (159,'carvedPumpkin','Carved Pumpkin','cube',dict(front='carved_front_blank',side='pumpkin_side',top='pumpkin_top'),None,'holidays-1',L,'Seasonal & Holiday','A pumpkin with a face you carved yourself. An LED inside makes it glow.'),
 (166,'spookySign','Spooky Sign','model','sign_spooky',None,'holidays-1',L,'Seasonal & Holiday','A wooden sign with a bat cut-out. Write a friendly message on it.'),
 (167,'harvestLantern','Autumn Lantern','model','lantern_harvest',None,'holidays-1',L,'Seasonal & Holiday','A hanging lantern with an LED glow, never a flame.'),
 (168,'chair','Chair','model','chair',None,'storage-2',L,'Blocks','A seat for a table. Use it to sit; move to get up.'),
 (169,'stool','Stool','model','stool',None,'storage-2',L,'Blocks','A seat with no back. Use it to sit; move to get up.'),
 (170,'bench','Bench','model','bench',None,'storage-2',L,'Blocks','A long seat for 2. Use it to sit; move to get up.'),
 (171,'table','Table','model','table',None,'storage-2',L,'Blocks','A table. Put chairs, stools or a bench next to it.'),
 (160,'winterLights','Winter Lights','flat','winter_lights',None,'holidays-1',L,'Seasonal & Holiday','LED string lights. Steady, or a slow twinkle when Motion is on. Never flashes.'),
 (161,'wreath','Wreath','flat','wreath',None,'holidays-1',L,'Seasonal & Holiday','A ring of evergreen branches.'),
 (162,'giftBox','Gift Box Deco','cube',dict(top='gift_top',side='gift_side',bottom='gift_side'),None,'holidays-1',L,'Seasonal & Holiday','A wrapped box for decoration. It holds nothing.'),
 (163,'snowPal','Snow Pal','model','snow_pal',None,'holidays-1',L,'Seasonal & Holiday','A friendly snow figure. It never melts here.'),
 (164,'ornamentTile','Ornament Tile','cube','tile_ornament',None,'holidays-1',L,'Seasonal & Holiday','A tile with shiny round ornaments.'),
 (165,'stripeBlock','Peppermint Stripe Block','cube','stripe_red',None,'holidays-1',L,'Seasonal & Holiday','A red and white striped block.'),
]
# Items without a block. key, en name, icon generator, milestone, from, dexCat, what
ITEMS = [
 ('woodTool','Wood Pick','pick:wood','live',L,'Items & Machines','Mines every block 2x faster than a hand. Never wears out.'),
 ('stoneTool','Stone Pick','pick:stone','live',L,'Items & Machines','Mines 3x faster than a hand.'),
 ('copperPick','Copper Pick','pick:copper','basics-1',L,'Items & Machines','Mines 4x faster than a hand.'),
 ('steelPick','Steel Pick','pick:steel','basics-1',L,'Items & Machines','Mines 6x faster than a hand.'),
 ('stick','Stick','stick','basics-1',L,'Materials','2 Planks make 4 Sticks.'),
 ('pan','Pan','pan','world-1','world-1','Items & Machines','A wooden pan. Swirl river gravel to find heavy gold flakes.'),
 ('bucket','Bucket','bucket','world-1','world-1','Items & Machines','Scoops 1 block of still water.'),
 ('waterBucket','Water Bucket','bucket_water','world-1','world-1','Items & Machines','Places 1 block of still water.'),
 ('berry','Berry','berry','live',L,'Plants & Critters','A small fruit. Leaves sometimes drop one.'),
 ('flour','Flour','flour','live',L,'Materials','Ground wheat seeds.'),
 ('sugar','Sugar','sugar','live',L,'Materials','Sweet crystals from plant juice.'),
 ('cupcake','Cupcake','cupcake','live',L,'Materials','Flour, sugar and berries, baked.'),
 ('bread','Bread','bread','live',L,'Materials','Baked flour.'),
 ('paintDab','Paint dab','paint_dab','basics-2',L,'Materials','People made the first paints from plants and berries. The color comes from pigments.'),
 ('corn','Corn','corn','basics-2',L,'Plants & Critters','Corn kernels. Cook 2 in the Oven for Bioplastic.'),
 ('cornSeed','Corn Seed','seed:corn','basics-2',L,'Plants & Critters','Plant it on Dirt or Grass.'),
 ('bioplastic','Bioplastic','bioplastic','basics-2',L,'Materials','Some plastics are made from plants, like corn.'),
 ('plasticTube','Plastic Tube','plastic_tube','basics-2',L,'Materials','A clear tube for glow sticks and machines.'),
 ('glowMix','Glow Mix','vial:glow','basics-2',L,'Materials','The two chemicals of a glow stick, ready to react.'),
 ('boosterDye','Booster Dye','vial:dye','basics-2',L,'Materials','Takes the reaction energy and glows. The dye picks the color.'),
 ('glassVial','Glass Vial','vial:empty','basics-1',L,'Materials','A small glass bottle. 1 Glass makes 2.'),
 ('rawCopper','Raw Copper','nugget:copper','world-1','world-1','Ores & Rocks','Copper straight from the rock. Smelt it into an ingot.'),
 ('copperDust','Copper dust','dust:copper','basics-2',L,'Materials','Crushed copper. 1 Raw Copper makes 2.'),
 ('copperIngot','Copper Ingot','ingot:copper','basics-1',L,'Materials','Smelted copper. 1 makes 4 Copper Wire.'),
 ('copperWire','Copper Wire','coil:copper','basics-1',L,'Materials','Thin copper that carries electricity.'),
 ('ironIngot','Iron Ingot','ingot:iron','basics-1',L,'Materials','Smelted iron, ready to become steel.'),
 ('steel','Steel','ingot:steel','basics-1',L,'Materials','Iron with a little carbon. Springs back until pushed too far.'),
 ('zincIngot','Zinc Ingot','ingot:zinc','basics-1',L,'Materials','Smelted zinc.'),
 ('tinIngot','Tin Ingot','ingot:tin','world-1','world-1','Materials','Smelted tin.'),
 ('bronzeIngot','Bronze Ingot','ingot:bronze','world-1','world-1','Materials','About 9 parts copper to 1 part tin, like real tin bronze.'),
 ('silverIngot','Silver Ingot','ingot:silver','world-1','world-1','Materials','Smelted silver.'),
 ('goldFlake','Gold Flake','flake:gold','world-1','world-1','Ores & Rocks','A tiny flake from a river. 9 make a Gold Nugget.'),
 ('goldNugget','Gold Nugget','nugget:gold','world-1','world-1','Ores & Rocks','A lump of gold.'),
 ('goldIngot','Gold Ingot','ingot:gold','world-1','world-1','Materials','Smelted gold.'),
 ('goldLeaf','Gold Leaf','leaf:gold','world-1','world-1','Materials','Gold beaten very thin. 1 Ingot makes 16.'),
 ('quartz','Quartz','crystal:quartz','world-1','world-1','Ores & Rocks','A silica crystal.'),
 ('silicon','Silicon','crystal:silicon','basics-3',L,'Materials','Sand and quartz are silica. Heating them with carbon pulls out silicon.'),
 ('logicChip','Logic Chip','chip','basics-3',L,'Materials','A tiny silicon circuit.'),
 ('batteryCell','Battery Cell','battery','basics-1',L,'Materials','Copper and zinc make a battery cell.'),
 ('spring','Spring','spring','basics-1',L,'Materials','Steel coiled so it springs back.'),
 ('wireRope','Wire Rope','coil:steel','ladder-1',L,'Materials','Steel wires twisted together. Pull-only, very strong.'),
 ('steelBeam','Steel Beam','beam:steel','ladder-1',L,'Materials','An I-shaped steel beam.'),
 ('timberBeam','Timber Beam','beam:wood','ladder-1',L,'Materials','A wooden beam. 2 Planks make 1.'),
 ('cotton','Cotton','cotton','storage-1',L,'Plants & Critters','Plant fiber. 3 make 1 Cloth.'),
 ('cottonSeed','Cotton Seed','seed:cotton','storage-1',L,'Plants & Critters','Plant it on Dirt or Grass.'),
 ('cloth','Cloth','cloth','storage-1',L,'Materials','Woven cotton.'),
 ('salt','Salt','salt','world-2','world-2','Materials','Sodium chloride: the salt on food.'),
 ('platinumGrain','Platinum Grain','flake:platinum','world-2','world-2','Ores & Rocks','A grain of platinum from an Emberdeep river.'),
 ('platinumNugget','Platinum Nugget','nugget:platinum','world-2','world-2','Ores & Rocks','A lump of platinum.'),
 ('platinumIngot','Platinum Ingot','ingot:platinum','later','later','Materials','Platinum melts at 1,768 C, so it needs the Embercore upgrade.'),
 ('alumina','Alumina','dust:alumina','world-2','world-2','Materials','White powder from bauxite. It needs lots of electricity to become aluminum.'),
 ('aluminumIngot','Aluminum Ingot','ingot:aluminum','world-2','world-2','Materials','Light metal. Common, but it costs lots of electricity.'),
 ('aluminumBeam','Aluminum Beam','beam:aluminum','ladder-1',L,'Materials','About the same job as steel at about a third of the weight.'),
 ('titaniumDioxide','Titanium Dioxide','dust:tio2','world-2','world-2','Materials','White powder refined from black sand.'),
 ('titaniumIngot','Titanium Ingot','ingot:titanium','world-2','world-2','Materials','Titanium is not rare. It is hard to refine.'),
 ('graphite','Graphite','crystal:graphite','world-2','world-2','Ores & Rocks','Soft carbon flakes.'),
 ('rhodiumSpeck','Rhodium Speck','flake:rhodium','world-3','world-3','Ores & Rocks','A very rare metal. It never tarnishes.'),
 ('iridiumSpeck','Iridium Speck','flake:iridium','world-3','world-3','Ores & Rocks','The legendary find. Iridium is one of the two densest elements.'),
 ('paintBrush','Paint Brush','brush','storage-2',L,'Items & Machines','Free colors, looks only.'),
 ('satchel','Satchel','pack:1','storage-1',L,'Items & Machines','+6 slots.'),
 ('backpack','Backpack','pack:2','storage-1',L,'Items & Machines','+12 slots.'),
 ('expeditionPack','Expedition Pack','pack:3','storage-1',L,'Items & Machines','+18 slots. Max carry 33.'),
 ('fob','Fob','fob','bot-cargo',L,'Items & Machines','The fob sends a radio signal; the bot follows the strongest signal.'),
 ('botH1','Berty\'s Bot H1','sprite:bot','bot-cargo',L,'Items & Machines','A little bot that follows you and carries your stuff.'),
 ('driveS','Drive S','drive:s','storage-5',L,'Items & Machines','8 kinds, 512 items.'),
 ('driveM','Drive M','drive:m','storage-5',L,'Items & Machines','32 kinds, 2,048 items.'),
 ('driveL','Drive L','drive:l','storage-5',L,'Items & Machines','64 kinds, 8,192 items.'),
 ('deliveryDrone','Delivery Drone','sprite:drone','storage-3',L,'Items & Machines','Slow, cheap and visible. Carries 4 stacks.'),
 ('petRock','Pet Rock','sprite:petrock','fun-1',L,'Plants & Critters','A rock has no motor. That is why it is so slow.'),
 ('gravityHat','Gravity Hat','hat','fun-1',L,'Items & Machines','Gravity pulls everything down. The hat pushes back a little, for a little while.'),
 ('musicDisc','Music Disc','disc','music-1',L,'Items & Machines','Plays a song in a Jukebox.'),
 ('warpKey','Warp Key','key','effects-1',L,'Effects','Warps you to your own Warp Pad.'),
 ('bandage','Bandage','bandage','effects-1',L,'Effects','Basic first aid.'),
 ('herbTonic','Herb Tonic','vial:herb','effects-1',L,'Effects','A plant drink for resting up.'),
 ('medKit','Med Kit','medkit','effects-1',L,'Effects','First aid for you and your crew.'),
 ('whistleBell','Whistle Bell','bell','effects-1',L,'Effects','Calls your Pet Rock and Bot.'),
 ('critterJar','Critter Jar','jar','effects-1',L,'Effects','Releases friendly critters for a while.'),
 ('morphVial','Morph Vial','vial:morph','effects-1',L,'Effects','Mimicry: copy the look of a block or critter.'),
 ('camoCloak','Camo Cloak','cloak','effects-1',L,'Effects','Camouflage: match the background.'),
 ('magnetWand','Magnet Wand','magnet','effects-1',L,'Effects','Magnets pull iron and steel.'),
 ('lightWand','Light Wand','wand','effects-1',L,'Effects','A floating light orb.'),
 ('fizzVial','Fizz Vial','vial:fizz','effects-1',L,'Effects','A gas plus a liquid makes foam.'),
 ('frostVial','Frost Vial','vial:frost','effects-1','world-2','Effects','Freezes still water so you can walk on it.'),
 ('sparkRod','Spark Rod','rod','effects-1',L,'Effects','Remote-powers your own circuit for a few seconds.'),
 ('blueprintScroll','Blueprint Scroll','scroll','ladder-1',L,'Items & Machines','Read it at the Drafting Table to unlock a material.'),
 ('cogCopper','Copper Cog','cog:copper','live',L,'Items & Machines','The everyday coin.'),
 ('cogSilver','Silver Cog','cog:silver','ladder-1',L,'Items & Machines','A rarer coin.'),
 ('cogGold','Gold Cog','cog:gold','ladder-1',L,'Items & Machines','A rare coin.'),
 ('cogPlatinum','Platinum Cog','cog:platinum','ladder-1',L,'Items & Machines','A very rare coin.'),
 ('cogIridium','Iridium Cog','cog:iridium','world-3',L,'Items & Machines','The legendary coin.'),
 ('flower','Flower','flower','world-2','world-2','Plants & Critters','1 Flower makes 2 Paint dabs.'),
 ('apple','Apple','apple','holidays-1',L,'Plants & Critters','An autumn fruit.'),
 ('carvingTool','Carving Scoop','carver','holidays-1',L,'Items & Machines','A safe scoop, not a knife. Use it on a Pumpkin to carve a face.'),
]
SPRITES = [  # mobs, bots, critters: key, en name, milestone, what
 ('bot','Berty\'s Bot H1','bot-cargo','A little bot that follows you and carries your stuff.'),
 ('drone','Delivery Drone','storage-3','Flies 3 blocks above the tallest block on its route.'),
 ('petrock','Pet Rock','fun-1','A rock has no motor. That is why it is so slow.'),
 ('firefly','Firefly','effects-1','A beetle that makes its own light.'),
 ('butterfly','Butterfly','effects-1','Visits flowers for nectar.'),
 ('songbird','Songbird','effects-1','Sings to talk to other birds.'),
 ('frog','Frog','effects-1','Jumps far with long back legs.'),
 ('prairiedog','Prairie Dog','effects-1','Digs burrows with many rooms.'),
 ('cat','Cat','effects-1','Lands on its feet.'),
]
ELEMENTS = [  # symbol, Z, name (Bertodex Elements v1, ORE-TABLE §6.2)
 ('C',6,'Carbon'),('O',8,'Oxygen'),('Na',11,'Sodium'),('Al',13,'Aluminum'),('Si',14,'Silicon'),('Cl',17,'Chlorine'),
 ('Ti',22,'Titanium'),('Fe',26,'Iron'),('Cu',29,'Copper'),('Zn',30,'Zinc'),('Rh',45,'Rhodium'),('Ag',47,'Silver'),
 ('Sn',50,'Tin'),('Ir',77,'Iridium'),('Pt',78,'Platinum'),('Au',79,'Gold'),
]
BIOMES = [  # key, en name, minimap color, pattern
 ('commons','Bertyville Commons','#5fbf6a','dots'),('glasswood','Glasswood','#9fb7a8','crosshatch'),
 ('rustflats','Rustflats','#d9a36a','stripes'),('tidewell','Tidewell Cliffs','#e3cf8f','waves'),
 ('frostspire','Frostspire Highlands','#cfe3ee','zigzag'),('emberdeep','Emberdeep','#5a4f5c','checker'),
 ('sea','Sea','#3fa7c2','waves2'),('town','Bertyville town','#b78a5a','bricks'),
]

FURNITURE_PALETTE = [  # Paint Brush colours for furniture (looks only), WCAG-safe names, no pure white
 ('oak','#a8743f'),('walnut','#6b4a2b'),('birch','#d9c49a'),('teal','#2f9e9a'),('berty','#7a5cc7'),('sunny','#e3b341'),('coral','#e0705a'),('slate','#5d6b7a'),
]
