const KEY="housekit-v1",DAYS=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const uid=()=>Math.random().toString(36).slice(2,10);
const today=()=>new Date().toISOString().slice(0,10);
const monthKey=()=>today().slice(0,7);
function addDays(iso,n){const d=new Date(iso+"T12:00:00");d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function defaultState(){return{bigType:false,darkMode:true,houseName:"Home",people:[{id:uid(),name:"Me"}],shop:[{id:uid(),name:"Milk",aisle:"Dairy",qty:1,store:"",done:false},{id:uid(),name:"Paper towels",aisle:"Paper",qty:1,store:"",done:false}],jobs:[{id:uid(),name:"Take out trash",who:"Me",due:today(),repeat:"week",done:false}],stock:[{id:uid(),name:"Toilet paper",qty:6,min:2,room:"Bath"},{id:uid(),name:"Dish soap",qty:1,min:1,room:"Kitchen"}],bills:[{id:uid(),name:"Electric",amount:0,dueDay:15,paid:false,paidMonth:""}],meals:{Mon:"",Tue:"",Wed:"",Thu:"",Fri:"",Sat:"",Sun:""},recipes:[],dates:[],contacts:[],fixes:[],notes:[],driveUrl:"",lastSync:"",myName:"Me",autoSync:true,updatedAt:0,updatedBy:""}}
function load(){try{const raw=localStorage.getItem(KEY);if(!raw)return defaultState();const s={...defaultState(),...JSON.parse(raw)};s.bills=(s.bills||[]).map(b=>b.paid&&b.paidMonth&&b.paidMonth!==monthKey()?{...b,paid:false}:b);return s}catch{return defaultState()}}
let state=load(),tab="home",morePage="menu",shopFilter="open",jobFilter="open",pushTimer=null,pulling=false,shopQ="",stockQ="";
const $=id=>document.getElementById(id);
function save(){state.updatedAt=Date.now();state.updatedBy=state.myName||"Me";localStorage.setItem(KEY,JSON.stringify(state));if(state.autoSync&&state.driveUrl)schedulePush()}
function toast(msg){const t=document.createElement("div");t.className="toast";t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&","<":"<",">":">",'"':'"',"'":"&#39;"}[c]))}
function setTab(name){tab=name;if(name!=="more")morePage="menu";document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("on",b.dataset.tab===name));render();window.scrollTo(0,0)}
function applySkin(){document.body.classList.toggle("big",state.bigType);document.body.classList.toggle("light",!state.darkMode)}
function lowStock(){return state.stock.filter(s=>Number(s.qty)<=Number(s.min))}
function openShop(){return state.shop.filter(s=>!s.done)}
function openJobs(){return state.jobs.filter(j=>!j.done)}
function dueBills(){return state.bills.filter(b=>!b.paid)}
function overdueJobs(){const t=today();return openJobs().filter(j=>j.due&&j.due<t)}
function upcomingDates(){const t=today(),end=addDays(t,14);return(state.dates||[]).filter(d=>d.when>=t&&d.when<=end).sort((a,b)=>a.when.localeCompare(b.when))}
function render(){applySkin();const root=$("app");if(tab==="home")root.innerHTML=viewHome();if(tab==="shop")root.innerHTML=viewShop();if(tab==="jobs")root.innerHTML=viewJobs();if(tab==="stock")root.innerHTML=viewStock();if(tab==="more")root.innerHTML=viewMore();bind()}
function viewHome(){const low=lowStock(),late=overdueJobs(),soon=upcomingDates(),dow=DAYS[new Date().getDay()],meal=state.meals[dow]||"Not set";return `<div class="wrap"><h1>${esc(state.houseName)}</h1><p class="lede">${state.driveUrl?"Last save: "+esc(state.updatedBy||"—"):"Turn on sync in More when you are ready."}</p><div class="pills"><button type="button" class="pill" data-go="shop"><span>Shop</span><b>${openShop().length}</b></button><button type="button" class="pill" data-go="jobs"><span>Jobs</span><b>${openJobs().length}</b></button><button type="button" class="pill" data-go="stock"><span>Low</span><b>${low.length}</b></button><button type="button" class="pill" data-more="bills"><span>Bills</span><b>${dueBills().length}</b></button></div><div class="card pad"><div class="muted">${dow} dinner</div><div>${esc(meal)}</div></div>${late.length?`<p class="warnbox">Late: ${late.map(j=>esc(j.name)).join(", ")}</p>`:""}${low.length?`<p class="warnbox">Buy: ${low.map(s=>esc(s.name)).join(", ")}</p>`:""}${soon.length?`<div class="card">${soon.map(d=>`<div>${esc(d.when)} · ${esc(d.name)}</div>`).join("")}</div>`:""}</div>`}
function viewShop(){let list=shopFilter==="all"?state.shop:shopFilter==="done"?state.shop.filter(s=>s.done):openShop();if(shopQ){const q=shopQ.toLowerCase();list=list.filter(s=>(s.name+" "+(s.aisle||"")+" "+(s.store||"")).toLowerCase().includes(q))}return `<div class="wrap"><h1>Shop</h1><div class="chips"><button class="chip ${shopFilter==="open"?"on":""}" data-shopf="open">Need</button><button class="chip ${shopFilter==="done"?"on":""}" data-shopf="done">Got</button><button class="chip ${shopFilter==="all"?"on":""}" data-shopf="all">All</button></div><div class="addbar"><input id="shop-name" placeholder="Add item" autocomplete="off"><input id="shop-qty" class="qty" type="number" value="1" min="1"><button class="btn" id="shop-add">Add</button></div><button class="btn ghost" id="shop-from-low">+ low stock</button><div class="card">${list.length?list.map(s=>`<div class="item ${s.done?"done":""}"><button class="check" data-shop-toggle="${s.id}"></button><div style="flex:1"><div class="name">${esc(s.name)} ${s.qty>1?"×"+s.qty:""}</div><div class="muted">${esc([s.store,s.aisle].filter(Boolean).join(" · "))}</div></div><button class="btn ghost" data-shop-del="${s.id}">X</button></div>`).join(""):`<p class="muted">List is empty.</p>`}</div><button class="btn secondary wide" id="shop-clear-done">Clear checked items</button></div>`}
function viewJobs(){let list=jobFilter==="all"?state.jobs:jobFilter==="done"?state.jobs.filter(j=>j.done):openJobs();const people=state.people.map(p=>`<option>${esc(p.name)}</option>`).join(""),t=today();return `<div class="wrap"><h1>Jobs</h1><div class="chips"><button class="chip ${jobFilter==="open"?"on":""}" data-jobf="open">Open</button><button class="chip ${jobFilter==="done"?"on":""}" data-jobf="done">Done</button><button class="chip ${jobFilter==="all"?"on":""}" data-jobf="all">All</button></div><div class="addbar"><input id="job-name" placeholder="Add job" autocomplete="off"><button class="btn" id="job-add">Add</button></div><div class="grid2"><select id="job-who">${people}</select><input id="job-due" type="date" value="${t}"></div><select id="job-repeat" style="margin:8px 0 10px"><option value="none">Once</option><option value="week">Every week</option></select><div class="card">${list.length?list.map(j=>{const late=!j.done&&j.due&&j.due<t;return `<div class="item ${j.done?"done":""} ${late?"late":""}"><button class="check" data-job-toggle="${j.id}"></button><div style="flex:1"><div class="name">${esc(j.name)} ${late?'<span class="tag late">LATE</span>':""} ${j.repeat==="week"?'<span class="tag">WEEK</span>':""}</div><div class="muted">${esc(j.who)} · ${esc(j.due||"")}</div></div><button class="btn ghost" data-job-del="${j.id}">X</button></div>`}).join(""):`<p class="muted">No jobs.</p>`}</div></div>`}
function viewStock(){let list=state.stock;if(stockQ){const q=stockQ.toLowerCase();list=list.filter(s=>(s.name+" "+(s.room||"")).toLowerCase().includes(q))}return `<div class="wrap"><h1>Stock</h1><p class="lede">Low items show on Home.</p><div class="addbar"><input id="st-name" placeholder="Add supply" autocomplete="off"><button class="btn" id="st-add">Add</button></div><div class="grid2"><input id="st-qty" type="number" value="1"><input id="st-min" type="number" value="1"></div><input id="st-room" placeholder="Room" style="margin:8px 0 10px"><input id="stock-q" placeholder="Find" value="${esc(stockQ)}"><div class="card">${list.length?list.map(s=>`<div class="item"><div style="flex:1"><div>${esc(s.name)} ${Number(s.qty)<=Number(s.min)?'<span class="tag">LOW</span>':""}</div><div class="muted">${esc(s.room)} · have ${s.qty} · min ${s.min}</div></div><div class="stepper"><button class="btn ghost" data-st-minus="${s.id}">−</button><button class="btn ghost" data-st-plus="${s.id}">+</button></div><button class="btn ghost" data-st-buy="${s.id}">Buy</button><button class="btn ghost" data-st-del="${s.id}">X</button></div>`).join(""):`<p class="muted">No stock yet.</p>`}</div></div>`}
function viewMore(){if(morePage==="bills")return viewBills();if(morePage==="meals")return viewMeals();if(morePage==="recipes")return viewRecipes();if(morePage==="dates")return viewDates();if(morePage==="contacts")return viewContacts();if(morePage==="fixes")return viewFixes();if(morePage==="people")return viewPeople();if(morePage==="notes")return viewNotes();if(morePage==="sync")return viewSync();return `<div class="wrap"><h1>More</h1><button class="menu-btn" data-more="bills">Bills</button><button class="menu-btn" data-more="meals">Meals</button><button class="menu-btn" data-more="recipes">Recipes</button><button class="menu-btn" data-more="dates">Dates</button><button class="menu-btn" data-more="contacts">Contacts</button><button class="menu-btn" data-more="fixes">Fix / repair</button><button class="menu-btn" data-more="people">People</button><button class="menu-btn" data-more="notes">Notes</button><button class="menu-btn" data-more="sync">Two-person sync</button><div class="card" style="margin-top:14px"><label>House name</label><input id="house-name" value="${esc(state.houseName)}"><button class="btn secondary wide" id="save-house" style="margin-top:8px">Save name</button></div></div>`}
function viewBills(){const total=dueBills().reduce((n,b)=>n+Number(b.amount||0),0);return `<div class="wrap"><button class="btn ghost" data-more="menu">← More</button><h1>Bills</h1><p class="muted">Open this month: $${total.toFixed(2)}</p><div class="card"><label>Name</label><input id="bill-name" placeholder="Internet"><div class="grid2"><div><label>Amount</label><input id="bill-amt" type="number" step="0.01" value="0"></div><div><label>Due day</label><input id="bill-day" type="number" min="1" max="31" value="1"></div></div><button class="btn wide" id="bill-add" style="margin-top:10px">Add bill</button></div><div class="card">${state.bills.map(b=>`<div class="item ${b.paid?"done":""}"><button class="check" data-bill-toggle="${b.id}"></button><div style="flex:1"><div class="name">${esc(b.name)} · $${Number(b.amount||0).toFixed(2)}</div><div class="muted">Due day ${b.dueDay}</div></div><button class="btn ghost" data-bill-del="${b.id}">X</button></div>`).join("")||`<p class="muted">No bills.</p>`}</div></div>`}
function viewMeals(){return `<div class="wrap"><button class="btn ghost" data-more="menu">← More</button><h1>Meals</h1><div class="card">${["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=>`<label>${d}</label><input class="meal-in" data-day="${d}" value="${esc(state.meals[d]||"")}" placeholder="Dinner">`).join("")}<button class="btn wide" id="meal-save" style="margin-top:10px">Save week</button></div></div>`}
function viewRecipes(){return `<div class="wrap"><button class="btn ghost" data-more="menu">← More</button><h1>Recipes</h1><div class="card"><label>Name</label><input id="rc-name" placeholder="Taco night"><label>Parts</label><textarea id="rc-parts" placeholder="Tortillas, beef"></textarea><button class="btn wide" id="rc-add">Save recipe</button></div><div class="card">${(state.recipes||[]).map(r=>`<div class="item"><div style="flex:1"><div class="name">${esc(r.name)}</div><div class="muted">${esc(r.parts)}</div></div><button class="btn ghost" data-rc-shop="${r.id}">Shop</button><button class="btn ghost" data-rc-del="${r.id}">X</button></div>`).join("")||`<p class="muted">No recipes.</p>`}</div></div>`}
function viewDates(){const list=(state.dates||[]).slice().sort((a,b)=>(a.when||"").localeCompare(b.when||""));return `<div class="wrap"><button class="btn ghost" data-more="menu">← More</button><h1>Dates</h1><div class="card"><label>Name</label><input id="dt-name" placeholder="Dentist"><label>Day</label><input id="dt-when" type="date" value="${today()}"><button class="btn wide" id="dt-add" style="margin-top:10px">Add date</button></div><div class="card">${list.map(d=>`<div class="item"><div style="flex:1"><div class="name">${esc(d.name)}</div><div class="muted">${esc(d.when)}</div></div><button class="btn ghost" data-dt-del="${d.id}">X</button></div>`).join("")||`<p class="muted">No dates.</p>`}</div></div>`}
function viewContacts(){return `<div class="wrap"><button class="btn ghost" data-more="menu">← More</button><h1>Contacts</h1><div class="card"><label>Name</label><input id="ct-name"><label>Phone</label><input id="ct-phone"><label>Note</label><input id="ct-note"><button class="btn wide" id="ct-add" style="margin-top:10px">Add contact</button></div><div class="card">${(state.contacts||[]).map(c=>`<div class="item"><div style="flex:1"><div class="name">${esc(c.name)}</div><div class="muted">${esc(c.phone)}</div></div>${c.phone?`<a class="btn ghost" href="tel:${esc(c.phone)}">Call</a>`:""}<button class="btn ghost" data-ct-del="${c.id}">X</button></div>`).join("")||`<p class="muted">No contacts.</p>`}</div></div>`}
function viewFixes(){return `<div class="wrap"><button class="btn ghost" data-more="menu">← More</button><h1>Fix / repair</h1><div class="card"><label>What broke</label><input id="fx-name"><label>Note</label><textarea id="fx-note"></textarea><button class="btn wide" id="fx-add">Add</button></div><div class="card">${state.fixes.map(f=>`<div class="item ${f.done?"done":""}"><button class="check" data-fx-toggle="${f.id}"></button><div style="flex:1"><div class="name">${esc(f.name)}</div><div class="muted">${esc(f.note||"")}</div></div><button class="btn ghost" data-fx-del="${f.id}">X</button></div>`).join("")||`<p class="muted">Nothing to fix.</p>`}</div></div>`}
function viewPeople(){return `<div class="wrap"><button class="btn ghost" data-more="menu">← More</button><h1>People</h1><div class="card"><input id="p-name" placeholder="Sam"><button class="btn wide" id="p-add">Add person</button></div><div class="card">${state.people.map(p=>`<div class="item"><div style="flex:1">${esc(p.name)}</div><button class="btn ghost" data-p-del="${p.id}">X</button></div>`).join("")}</div></div>`}
function viewNotes(){return `<div class="wrap"><button class="btn ghost" data-more="menu">← More</button><h1>Notes</h1><div class="card"><textarea id="note-text"></textarea><button class="btn wide" id="note-add">Save note</button></div><div class="card">${state.notes.map(n=>`<div class="item"><div style="flex:1">${esc(n.text)}</div><button class="btn ghost" data-note-del="${n.id}">X</button></div>`).join("")||`<p class="muted">No notes.</p>`}</div></div>`}
function viewSync(){return `<div class="wrap"><button class="btn ghost" data-more="menu">← More</button><h1>Two-person sync</h1><p class="muted">Same script URL on both phones.</p><div class="card"><label>Your name</label><input id="my-name" value="${esc(state.myName)}"><label>Script URL</label><input id="drive-url" value="${esc(state.driveUrl)}" placeholder="https://script.google.com/macros/s/.../exec"><label class="row" style="margin-top:8px"><input id="auto-sync" type="checkbox" ${state.autoSync?"checked":""} style="width:auto;min-height:0"> Auto pull and push</label><button class="btn wide" id="save-sync" style="margin-top:10px">Save and pull now</button><div class="row" style="margin-top:8px"><button class="btn secondary" id="drive-pull" style="flex:1">Pull</button><button class="btn secondary" id="drive-push" style="flex:1">Push</button></div><p class="muted">${state.lastSync?"Last sync: "+esc(state.lastSync):"Not synced yet."}</p></div><div class="card"><button class="btn wide secondary" id="export-json">Download HouseKit.json</button><label>Import</label><input id="import-file" type="file" accept="application/json,.json"></div></div>`}
function bind(){
  $("dark-btn").textContent=state.darkMode?"Light":"Dark";
  $("mode-btn").onclick=()=>{state.bigType=!state.bigType;save();render()};
  $("dark-btn").onclick=()=>{state.darkMode=!state.darkMode;save();render()};
  document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
  document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>setTab(b.dataset.go));
  document.querySelectorAll("[data-more]").forEach(b=>b.onclick=()=>{tab="more";morePage=b.dataset.more;render()});
  document.querySelectorAll("[data-shopf]").forEach(b=>b.onclick=()=>{shopFilter=b.dataset.shopf;render()});
  document.querySelectorAll("[data-jobf]").forEach(b=>b.onclick=()=>{jobFilter=b.dataset.jobf;render()});
  const stockFind=$("stock-q");if(stockFind){stockFind.oninput=()=>{stockQ=stockFind.value};stockFind.onchange=()=>{stockQ=stockFind.value;render()}}
  const addShop=()=>{const name=($("shop-name")||{}).value;if(!name||!name.trim())return toast("Type an item.");state.shop.unshift({id:uid(),name:name.trim(),aisle:"",store:"",qty:Number(($("shop-qty")||{}).value||1),done:false});save();render();toast("Added.")};
  if($("shop-add"))$("shop-add").onclick=addShop;if($("shop-name"))$("shop-name").onkeydown=e=>{if(e.key==="Enter")addShop()};
  document.querySelectorAll("[data-shop-toggle]").forEach(b=>b.onclick=()=>{const it=state.shop.find(s=>s.id===b.dataset.shopToggle);if(it)it.done=!it.done;save();render()});
  document.querySelectorAll("[data-shop-del]").forEach(b=>b.onclick=()=>{state.shop=state.shop.filter(s=>s.id!==b.dataset.shopDel);save();render()});
  if($("shop-clear-done"))$("shop-clear-done").onclick=()=>{state.shop=state.shop.filter(s=>!s.done);save();render()};
  if($("shop-from-low"))$("shop-from-low").onclick=()=>{let n=0;lowStock().forEach(s=>{if(!state.shop.some(x=>!x.done&&x.name.toLowerCase()===s.name.toLowerCase())){state.shop.unshift({id:uid(),name:s.name,aisle:s.room,store:"",qty:1,done:false});n++}});save();render();toast(n?n+" added.":"Nothing new.")};
  if($("job-name"))$("job-name").onkeydown=e=>{if(e.key==="Enter"&&$("job-add"))$("job-add").click()};
  if($("job-add"))$("job-add").onclick=()=>{const name=$("job-name").value.trim();if(!name)return toast("Type a job.");state.jobs.unshift({id:uid(),name,who:$("job-who").value,due:$("job-due").value,repeat:$("job-repeat").value,done:false});save();render()};
  document.querySelectorAll("[data-job-toggle]").forEach(b=>b.onclick=()=>{const it=state.jobs.find(s=>s.id===b.dataset.jobToggle);if(!it)return;if(!it.done&&it.repeat==="week"){it.due=addDays(it.due||today(),7);toast("Next week set.")}else it.done=!it.done;save();render()});
  document.querySelectorAll("[data-job-del]").forEach(b=>b.onclick=()=>{state.jobs=state.jobs.filter(s=>s.id!==b.dataset.jobDel);save();render()});
  if($("st-add"))$("st-add").onclick=()=>{const name=$("st-name").value.trim();if(!name)return toast("Type a name.");state.stock.unshift({id:uid(),name,qty:Number($("st-qty").value||0),min:Number($("st-min").value||0),room:$("st-room").value.trim()});save();render()};
  document.querySelectorAll("[data-st-plus]").forEach(b=>b.onclick=()=>{const it=state.stock.find(s=>s.id===b.dataset.stPlus);if(it)it.qty=Number(it.qty)+1;save();render()});
  document.querySelectorAll("[data-st-minus]").forEach(b=>b.onclick=()=>{const it=state.stock.find(s=>s.id===b.dataset.stMinus);if(it)it.qty=Math.max(0,Number(it.qty)-1);save();render()});
  document.querySelectorAll("[data-st-buy]").forEach(b=>b.onclick=()=>{const it=state.stock.find(s=>s.id===b.dataset.stBuy);if(!it)return;state.shop.unshift({id:uid(),name:it.name,aisle:it.room,store:"",qty:1,done:false});toast("On shop list.");save()});
  document.querySelectorAll("[data-st-del]").forEach(b=>b.onclick=()=>{state.stock=state.stock.filter(s=>s.id!==b.dataset.stDel);save();render()});
  if($("save-house"))$("save-house").onclick=()=>{state.houseName=$("house-name").value.trim()||"Home";save();toast("Saved.")};
  if($("bill-add"))$("bill-add").onclick=()=>{const name=$("bill-name").value.trim();if(!name)return;state.bills.unshift({id:uid(),name,amount:Number($("bill-amt").value||0),dueDay:Number($("bill-day").value||1),paid:false,paidMonth:""});save();render()};
  document.querySelectorAll("[data-bill-toggle]").forEach(b=>b.onclick=()=>{const it=state.bills.find(s=>s.id===b.dataset.billToggle);if(!it)return;it.paid=!it.paid;it.paidMonth=it.paid?monthKey():"";save();render()});
  document.querySelectorAll("[data-bill-del]").forEach(b=>b.onclick=()=>{state.bills=state.bills.filter(s=>s.id!==b.dataset.billDel);save();render()});
  if($("meal-save"))$("meal-save").onclick=()=>{document.querySelectorAll(".meal-in").forEach(el=>{state.meals[el.dataset.day]=el.value});save();toast("Week saved.")};
  if($("rc-add"))$("rc-add").onclick=()=>{const name=$("rc-name").value.trim();if(!name)return;state.recipes.unshift({id:uid(),name,parts:$("rc-parts").value.trim()});save();render()};
  document.querySelectorAll("[data-rc-shop]").forEach(b=>b.onclick=()=>{const r=state.recipes.find(x=>x.id===b.dataset.rcShop);if(!r)return;(r.parts||"").split(",").map(p=>p.trim()).filter(Boolean).forEach(p=>state.shop.unshift({id:uid(),name:p,aisle:r.name,store:"",qty:1,done:false}));save();toast("Parts on shop list.")});
  document.querySelectorAll("[data-rc-del]").forEach(b=>b.onclick=()=>{state.recipes=state.recipes.filter(s=>s.id!==b.dataset.rcDel);save();render()});
  if($("dt-add"))$("dt-add").onclick=()=>{const name=$("dt-name").value.trim();if(!name)return;state.dates.unshift({id:uid(),name,when:$("dt-when").value});save();render()};
  document.querySelectorAll("[data-dt-del]").forEach(b=>b.onclick=()=>{state.dates=state.dates.filter(s=>s.id!==b.dataset.dtDel);save();render()});
  if($("ct-add"))$("ct-add").onclick=()=>{const name=$("ct-name").value.trim();if(!name)return;state.contacts.unshift({id:uid(),name,phone:$("ct-phone").value.trim(),note:$("ct-note").value.trim()});save();render()};
  document.querySelectorAll("[data-ct-del]").forEach(b=>b.onclick=()=>{state.contacts=state.contacts.filter(s=>s.id!==b.dataset.ctDel);save();render()});
  if($("fx-add"))$("fx-add").onclick=()=>{const name=$("fx-name").value.trim();if(!name)return;state.fixes.unshift({id:uid(),name,note:$("fx-note").value.trim(),done:false});save();render()};
  document.querySelectorAll("[data-fx-toggle]").forEach(b=>b.onclick=()=>{const it=state.fixes.find(s=>s.id===b.dataset.fxToggle);if(it)it.done=!it.done;save();render()});
  document.querySelectorAll("[data-fx-del]").forEach(b=>b.onclick=()=>{state.fixes=state.fixes.filter(s=>s.id!==b.dataset.fxDel);save();render()});
  if($("p-add"))$("p-add").onclick=()=>{const name=$("p-name").value.trim();if(!name)return;state.people.push({id:uid(),name});save();render()};
  document.querySelectorAll("[data-p-del]").forEach(b=>b.onclick=()=>{if(state.people.length<2)return toast("Keep at least one person.");state.people=state.people.filter(s=>s.id!==b.dataset.pDel);save();render()});
  if($("note-add"))$("note-add").onclick=()=>{const text=$("note-text").value.trim();if(!text)return;state.notes.unshift({id:uid(),text,at:today()});save();render()};
  document.querySelectorAll("[data-note-del]").forEach(b=>b.onclick=()=>{state.notes=state.notes.filter(s=>s.id!==b.dataset.noteDel);save();render()});
  if($("export-json"))$("export-json").onclick=exportJson;
  if($("import-file"))$("import-file").onchange=importJson;
  if($("drive-pull"))$("drive-pull").onclick=()=>drivePull(true);
  if($("drive-push"))$("drive-push").onclick=()=>drivePush(true);
  if($("save-sync"))$("save-sync").onclick=()=>{state.myName=($("my-name").value||"Me").trim();state.driveUrl=($("drive-url").value||"").trim();state.autoSync=$("auto-sync").checked;localStorage.setItem(KEY,JSON.stringify(state));if(state.driveUrl)drivePull(true);else toast("Saved on this phone only.")};
}
function exportJson(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="HouseKit.json";a.click()}
function importJson(e){const file=e.target.files&&e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{state={...defaultState(),...JSON.parse(r.result)};save();render();toast("Imported.")}catch{toast("Bad file.")}};r.readAsText(file)}
function schedulePush(){clearTimeout(pushTimer);pushTimer=setTimeout(()=>drivePush(false),800)}
async function drivePull(show){const url=(( $("drive-url")||{}).value||state.driveUrl||"").trim();if(!url){if(show)toast("Paste the script URL.");return}if(pulling)return;pulling=true;const keep={url,myName:state.myName,autoSync:state.autoSync,darkMode:state.darkMode,bigType:state.bigType};try{const res=await fetch(url+(url.includes("?")?"&":"?")+"t="+Date.now());const data=await res.json();if(data.error)throw new Error(data.error);if(data&&typeof data==="object")state={...defaultState(),...data};state.driveUrl=keep.url;state.myName=keep.myName;state.autoSync=keep.autoSync;state.darkMode=keep.darkMode;state.bigType=keep.bigType;state.lastSync=new Date().toLocaleString();localStorage.setItem(KEY,JSON.stringify(state));render();if(show)toast("Pulled from Drive.")}catch{if(show)toast("Pull failed.")}pulling=false}
async function drivePush(show){const url=(( $("drive-url")||{}).value||state.driveUrl||"").trim();if(!url){if(show)toast("Paste the script URL.");return}state.driveUrl=url;try{await fetch(url,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain"},body:JSON.stringify(state)});state.lastSync=new Date().toLocaleString();localStorage.setItem(KEY,JSON.stringify(state));if(show)toast("Pushed to Drive.")}catch{if(show)toast("Push failed.")}}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
render();
if(state.driveUrl&&state.autoSync)drivePull(false);
setInterval(()=>{if(state.driveUrl&&state.autoSync&&tab==="home")drivePull(false)},45000);
