/* DJ Berty words. English is the fallback. Never a blank, never a raw key.
   Shared chrome (Home, Menu, Close, Play, …) comes from KulibertI18n.t only.
   Song titles stay English. Note letters stay C D E G A.
   NEEDS NATIVE CHECK: every fa-AF, rw, and ti line in PACKS below.
   fa-AF is Dari (Afghan), not Iranian Persian. Do not ship these three as verified. */
(function (root) {
  var OK = { en: 1, simple: 1, uk: 1, ru: 1, es: 1, ar: 1, "fa-AF": 1, rw: 1, ti: 1 };
  var EN = {
    makeBeat: "Make a beat",
    mySongs: "My songs",
    songsH: "Songs",
    openOne: "Open one song. Score and drums work on that song.",
    start: "Start",
    blankStaff: "Blank staff",
    tempoKey: "Tempo and key",
    useThis: "Use this",
    openSongs: "Open songs",
    mySaves: "My saves",
    bringHead: "Bring a file in",
    djFile: "File · <bdi>DJ Berty</bdi>",
    abc: "ABC",
    midi: "MIDI",
    musicxml: "MusicXML",
    workOn: "Work on this song",
    makeSong: "Make a song",
    pickFeel: "Pick a feel. Then a speed. Then who plays.",
    speed: "Speed",
    startBuilding: "Start building",
    library: "Library",
    searchPh: "Search feel, instrument, or who",
    beat: "Beat",
    scoreDrums: "Score + drums",
    score: "Score",
    lights: "Lights",
    band: "Band",
    soundWord: "Sound",
    songs: "Songs",
    perform: "Perform",
    listenTurn: "Listen, then my turn",
    playAlong: "Play along",
    playingAlong: "Playing along",
    bringFile: "Bring a file in",
    go: "Go",
    songList: "Song list",
    blend: "Blend",
    both: "Both",
    drumsWord: "Drums",
    blendHint: "Left is the drums. Right is the score. The middle plays both.",
    title: "Title",
    picture: "Picture",
    effects: "Effects",
    fxHint: "Pick a sound. The pads use it.",
    synth: "Synth",
    brightness: "Brightness",
    length: "Length",
    echo: "Echo",
    wobble: "Wobble",
    oneLoop: "One loop",
    loopHint: "Optional. One loop, then the mic turns off.",
    micOnce: "Use the mic once",
    micNoHint: "You can say no. The pads still work.",
    startLoop: "Start the loop",
    notNow: "Not now",
    hearLoop: "Hear the loop",
    download: "Download",
    del: "Delete",
    assignHead: "Assign practice",
    assignHint: "Sign in as the student. The name comes from TechWorks. Then assign the practice.",
    hearFive: "Hear the five notes",
    readFinger: "Read each fingering",
    playFive: "Play the five notes into the song",
    assign: "Assign",
    downloadClass: "Download class file",
    openClass: "Open a class file",
    clearDrums: "Clear the drums",
    tapAgain: "Tap again to clear",
    saveFile: "Save a file",
    saveHint: "This Chromebook keeps the song. After Sign in, a finished beat sends the score.",
    teacher: "Teacher",
    privacy: "Privacy",
    newSong: "New song",
    yourSong: "Your song",
    tempo: "Tempo",
    save: "Save",
    share: "Share",
    record: "Record",
    recording: "Recording",
    more: "More ▾",
    saveSound: "Save as sound",
    soundOn: "Sound on",
    soundOff: "Sound off",
    soundBanner: "Sound is off.",
    turnSoundOn: "Turn sound on",
    pressPlay: "Press {play}. You can leave the sound off.",
    readMe: "Read it to me",
    stop: "Stop",
    rest: "Rest",
    beatLine: "Beat {n} · {heard}. You can leave the sound off.",
    howBoth: "The staff and the drums are this song. Tap a letter or a pad. Then press {play}.",
    howNotes: "Tap a letter. Then press {play}.",
    howBeat: "Tap a pad. Press {play}.",
    howDrums: "Tap Kick or Snare. Press {play}. Your tap is saved on that beat.",
    howLights: "Tap a picture. Then press {play}.",
    howBand: "Choose your instrument. Tap a note to see the fingering.",
    howSound: "Tap a note. Watch the wave. Then try Major or Minor.",
    pressStop: "Press {stop}.",
    hintBeat: "Tap a pad. Press {play}. The light shows the step.",
    hintBoth: "Score and drums together. A letter changes the staff. A pad changes the beat.",
    hintNotes: "The staff is the song. Tap a letter to change a note.",
    hintDrums: "Tap Kick or Snare. A tap is saved on that beat.",
    hintAlong: "Play along is on. Tap with the flash. The song stays the same.",
    hintLights: "Pick a picture. Press {play}.",
    hintBand: "Tap a note. The line under it is the fingering.",
    hintSound: "Tap a note. The wave matches the shape.",
    yourTurn: "Your turn. Tap the pads. You can leave the sound off.",
    yourTurnLesson: "Your turn. Tap the pads. The beats you tap stay in the song.",
    tapsStayed: "Your taps stayed in the song. You can leave the sound off.",
    hearAgain: "The class can hear your turn. Press {play} to hear it again.",
    soundOffMove: "Sound is off. The word and the picture still move.",
    soundOnWord: "Sound is on. The word still names the beat.",
    listenOnce: "Listen once. Each pad flashes. Then it says Your turn.",
    listenOff: "Listen. You can leave the sound off.",
    saved: "Saved",
    bringBack: "Bring it back",
    thatsSong: "That's the song",
    playAgain: "Play it again",
    backClass: "Back to class",
    talent: "Talent show",
    notYet: "Not yet",
    startBtn: "Start",
    ready: "Ready",
    bars: "bars",
    sharedFor: "Shared for {code}.",
    sharedBox: "Shared on this Chromebook.",
    sharedClass: "Shared with class. The link is under the pads.",
    sharedSign: "Shared on this Chromebook. Sign in to attach your class code.",
    midiSaved: "MIDI file saved. It opens again from Bring a file in.",
    wavFail: "That sound did not save. Press {play}, then try again.",
    pen_quarter: "1 beat",
    pen_eighth: "Fast",
    pen_tie: "Longer",
    pen_rest: "Rest",
    drum_kick: "Kick",
    drum_snare: "Snare",
    drum_hat: "Hat",
    drum_clap: "Clap",
    drum_tom: "Tom",
    drum_shaker: "Shaker",
    drum_rim: "Rim",
    drum_bell: "Bell",
    drum_tamb: "Tamb",
    drum_crash: "Crash",
    scene_storm: "Storm",
    scene_neon: "Neon",
    scene_soft: "Soft",
    scene_space: "Space",
    scene_fire: "Fire",
    scene_ocean: "Ocean",
    style_trap: "Trap",
    style_lofi: "Lo-fi",
    style_rock: "Rock",
    style_marching: "Marching",
    stepHint: "Tap a pad. It stays on that step.",
    scoreTools: "Score tools",
    addBar: "Add a bar",
    justStaff: "Just the staff",
    extraDrums: "Extra drums (Tom, Shaker…)",
    volSwing: "Volume, swing, patterns",
    swing: "Swing",
    addClick: "Add a click",
    bassFollow: "Bass follows the kick",
    bassOn: "Bass is on",
    major: "Major",
    minor: "Minor",
    oneByOne: "One by one",
    look_bars: "Bars",
    look_ribbon: "Ribbon",
    look_rings: "Rings",
    look_rain: "Rain",
    fx_plain: "Plain",
    fx_soft: "Soft",
    fx_bright: "Bright",
    fx_echo: "Echo",
    fx_room: "Room",
    fx_hall: "Hall",
    fx_robot: "Robot",
    fx_radio: "Radio",
    fx_space: "Space",
    fx_deep: "Deep",
    wave_sine: "Round",
    wave_triangle: "Soft",
    wave_square: "Bright",
    wave_sawtooth: "Buzz",
    clearAsk: "Tap clear one more time. Bring it back puts the drums back.",
    drumsClear: "The drums are clear. Bring it back is under the beat.",
    drumsBack: "The drums are back. Saved.",
    kickPulse: "A kick on beat 1 is the pulse. The picture jumps with it.",
    fxOn: "{name} is on. The pads use it.",
    waveOn: "{name} is the note shape. The drums stay drums.",
    countThen: "Count {n}. Then tap a note. The click is the metronome. It saves.",
    recOff: "That count is off. Taps still play. They are saved when Play along is off.",
    openBtn: "Open",
    remix: "Remix",
    trapRemix: "Trap remix",
    nothingSaved: "Nothing saved on this Chromebook yet.",
    onlyHere: "Only this Chromebook",
    classWord: "Class"
  };
  var SIMPLE = {
    scoreDrums: "Notes and drums",
    listenTurn: "Listen. Then me.",
    pressPlay: "Press {play}. Sound can stay off.",
    beatLine: "Beat {n} · {heard}. Sound can stay off.",
    howBoth: "Notes and drums. Tap a letter or a pad. Then {play}.",
    howBeat: "Tap a pad. Then {play}.",
    howNotes: "Tap a letter. Then {play}.",
    blendHint: "Left: drums. Right: notes. Middle: both.",
    loopHint: "One loop. Then the mic turns off.",
    assignHint: "Sign in. Then assign the practice.",
    saveHint: "This Chromebook keeps the song. After Sign in, the score is sent.",
    fxHint: "Pick a sound. Pads use it.",
    openOne: "Open one song. Notes and drums use that song.",
    pickFeel: "Pick a feel. Then speed. Then who plays.",
    micNoHint: "You can say no. Pads still work.",
    soundBanner: "Sound is off.",
    turnSoundOn: "Sound on",
    hintBoth: "Notes and drums together. A letter changes the notes. A pad changes the beat.",
    yourTurn: "Your turn. Tap the pads. Sound can stay off.",
    listenOff: "Listen. Sound can stay off.",
    clearAsk: "Tap clear again. Bring it back puts the drums back.",
    howDrums: "Tap Kick or Snare. Then {play}.",
    pressStop: "Press {stop}."
  };
  var PACKS = { en: EN, simple: SIMPLE };
  /* filled below */
  var MORE = {
    "uk": {
      "makeBeat": "Зроби біт",
      "mySongs": "Мої пісні",
      "songsH": "Пісні",
      "openOne": "Відкрий одну пісню. Ноти і барабани для неї.",
      "start": "Старт",
      "blankStaff": "Порожній стан",
      "tempoKey": "Темп і тональність",
      "useThis": "Ось це",
      "openSongs": "Відкрити пісні",
      "mySaves": "Мої збереження",
      "bringHead": "Принести файл",
      "djFile": "Файл · <bdi>DJ Berty</bdi>",
      "abc": "ABC",
      "midi": "MIDI",
      "musicxml": "MusicXML",
      "workOn": "Працюй над цією піснею",
      "makeSong": "Зроби пісню",
      "pickFeel": "Обери настрій. Потім швидкість. Потім хто грає.",
      "speed": "Швидкість",
      "startBuilding": "Почни збирати",
      "library": "Бібліотека",
      "searchPh": "Шукай настрій, інструмент або хто",
      "beat": "Біт",
      "scoreDrums": "Ноти і барабани",
      "score": "Ноти",
      "lights": "Світло",
      "band": "Бенд",
      "soundWord": "Звук",
      "songs": "Пісні",
      "perform": "Виступ",
      "listenTurn": "Слухай, потім я",
      "playAlong": "Грай разом",
      "playingAlong": "Граєш разом",
      "bringFile": "Принести файл",
      "go": "Йти",
      "songList": "Список пісень",
      "blend": "Суміш",
      "both": "Обидва",
      "drumsWord": "Барабани",
      "blendHint": "Ліворуч барабани. Праворуч ноти. Посередині грають обидва.",
      "title": "Назва",
      "picture": "Картинка",
      "effects": "Ефекти",
      "fxHint": "Обери звук. Пади його грають.",
      "synth": "Синт",
      "brightness": "Яскравість",
      "length": "Довжина",
      "echo": "Луна",
      "wobble": "Хитання",
      "oneLoop": "Одне коло",
      "loopHint": "Не обов'язково. Одне коло, тоді мікрофон вимкнеться.",
      "micOnce": "Мікрофон один раз",
      "micNoHint": "Можна сказати ні. Пади працюють.",
      "startLoop": "Почати коло",
      "notNow": "Не зараз",
      "hearLoop": "Почути коло",
      "download": "Завантажити",
      "del": "Видалити",
      "assignHead": "Задати вправу",
      "assignHint": "Увійди як учень. Ім'я з TechWorks. Потім задай вправу.",
      "hearFive": "Почуй п'ять нот",
      "readFinger": "Прочитай аплікатуру",
      "playFive": "Зіграй п'ять нот у пісню",
      "assign": "Задати",
      "downloadClass": "Завантажити файл класу",
      "openClass": "Відкрити файл класу",
      "clearDrums": "Очистити барабани",
      "tapAgain": "Торкнись ще раз, щоб стерти",
      "saveFile": "Зберегти файл",
      "saveHint": "Цей Chromebook тримає пісню. Після входу готовий біт надсилає бал.",
      "teacher": "Учитель",
      "privacy": "Приватність",
      "newSong": "Нова пісня",
      "yourSong": "Твоя пісня",
      "tempo": "Темп",
      "save": "Зберегти",
      "share": "Поділитись",
      "record": "Запис",
      "recording": "Йде запис",
      "more": "Ще ▾",
      "saveSound": "Зберегти як звук",
      "soundOn": "Звук увімкнено",
      "soundOff": "Звук вимкнено",
      "soundBanner": "Звук вимкнено.",
      "turnSoundOn": "Увімкнути звук",
      "pressPlay": "Натисни {play}. Звук можна лишити вимкненим.",
      "readMe": "Прочитай мені",
      "stop": "Стоп",
      "rest": "Пауза",
      "beatLine": "Біт {n} · {heard}. Звук можна лишити вимкненим.",
      "howBoth": "Нотний стан і барабани — це пісня. Торкнись літери або пада. Потім {play}.",
      "howNotes": "Торкнись літери. Потім {play}.",
      "howBeat": "Торкнись пада. Натисни {play}.",
      "howDrums": "Торкнись бочки або малого. Натисни {play}. Твій дотик зберігається на цьому біті.",
      "howLights": "Торкнись картинки. Потім {play}.",
      "howBand": "Обери інструмент. Торкнись ноти, щоб побачити пальці.",
      "howSound": "Торкнись ноти. Дивись на хвилю. Спробуй мажор або мінор.",
      "pressStop": "Натисни {stop}.",
      "hintBeat": "Торкнись пада. Натисни {play}. Світло показує крок.",
      "hintBoth": "Ноти і барабани разом. Літера міняє стан. Пад міняє біт.",
      "hintNotes": "Стан — це пісня. Торкнись літери, щоб змінити ноту.",
      "hintDrums": "Торкнись бочки або малого. Дотик зберігається на цьому біті.",
      "hintAlong": "Гра разом увімкнена. Торкайся спалаху. Пісня не змінюється.",
      "hintLights": "Обери картинку. Натисни {play}.",
      "hintBand": "Торкнись ноти. Рядок під нею — це пальці.",
      "hintSound": "Торкнись ноти. Хвиля повторює форму.",
      "yourTurn": "Твоя черга. Торкайся падів. Звук можна лишити вимкненим.",
      "yourTurnLesson": "Твоя черга. Торкайся падів. Біти, яких ти торкнувся, лишаються в пісні.",
      "tapsStayed": "Твої дотики лишились у пісні. Звук можна лишити вимкненим.",
      "hearAgain": "Клас може почути твою чергу. Натисни {play}, щоб почути ще раз.",
      "soundOffMove": "Звук вимкнено. Слово і картинка далі рухаються.",
      "soundOnWord": "Звук увімкнено. Слово далі називає біт.",
      "listenOnce": "Послухай раз. Кожен пад блимає. Потім буде твоя черга.",
      "listenOff": "Слухай. Звук можна лишити вимкненим.",
      "saved": "Збережено",
      "bringBack": "Повернути",
      "thatsSong": "Це і є пісня",
      "playAgain": "Зіграй ще раз",
      "backClass": "Назад до класу",
      "talent": "Концерт",
      "notYet": "Ще ні",
      "startBtn": "Старт",
      "ready": "Готово",
      "bars": "такти",
      "sharedFor": "Поділено для {code}.",
      "sharedBox": "Поділено на цьому Chromebook.",
      "sharedClass": "Поділено з класом. Посилання під падами.",
      "sharedSign": "Поділено на цьому Chromebook. Увійди, щоб додати код класу.",
      "midiSaved": "Файл MIDI збережено. Він знову відкриється з Принести файл.",
      "wavFail": "Цей звук не зберігся. Натисни {play} і спробуй ще.",
      "pen_quarter": "1 біт",
      "pen_eighth": "Швидко",
      "pen_tie": "Довше",
      "pen_rest": "Пауза",
      "drum_kick": "Бочка",
      "drum_snare": "Малий",
      "drum_hat": "Хет",
      "drum_clap": "Оплеск",
      "drum_tom": "Том",
      "drum_shaker": "Шейкер",
      "drum_rim": "Обідок",
      "drum_bell": "Дзвін",
      "drum_tamb": "Бубон",
      "drum_crash": "Креш",
      "scene_storm": "Шторм",
      "scene_neon": "Неон",
      "scene_soft": "М'яко",
      "scene_space": "Космос",
      "scene_fire": "Вогонь",
      "scene_ocean": "Океан",
      "style_trap": "Trap",
      "style_lofi": "Lo-fi",
      "style_rock": "Rock",
      "style_marching": "Марш",
      "stepHint": "Торкнись пада. Він лишається на цьому кроці.",
      "scoreTools": "Інструменти нот",
      "addBar": "Додати такт",
      "justStaff": "Лише стан",
      "extraDrums": "Ще барабани (том, шейкер…)",
      "volSwing": "Гучність, свінг, візерунки",
      "swing": "Свінг",
      "addClick": "Додати клік",
      "bassFollow": "Бас іде за бочкою",
      "bassOn": "Бас увімкнено",
      "major": "Мажор",
      "minor": "Мінор",
      "oneByOne": "По одній",
      "look_bars": "Смуги",
      "look_ribbon": "Стрічка",
      "look_rings": "Кільця",
      "look_rain": "Дощ",
      "fx_plain": "Просто",
      "fx_soft": "М'яко",
      "fx_bright": "Яскраво",
      "fx_echo": "Луна",
      "fx_room": "Кімната",
      "fx_hall": "Зала",
      "fx_robot": "Робот",
      "fx_radio": "Радіо",
      "fx_space": "Космос",
      "fx_deep": "Глибоко",
      "wave_sine": "Кругла",
      "wave_triangle": "М'яка",
      "wave_square": "Яскрава",
      "wave_sawtooth": "Дзижчання",
      "clearAsk": "Торкнись стерти ще раз. Повернути ставить барабани назад.",
      "drumsClear": "Барабани чисті. Повернути — під бітом.",
      "drumsBack": "Барабани повернулись. Збережено.",
      "kickPulse": "Бочка на біті 1 — це пульс. Картинка стрибає з нею.",
      "fxOn": "{name} увімкнено. Пади його грають.",
      "waveOn": "{name} — це форма ноти. Барабани лишаються барабанами.",
      "countThen": "Рахуй {n}. Потім торкнись ноти. Клік — це метроном. Він зберігає.",
      "recOff": "Цей рахунок вимкнено. Дотики ще грають. Вони зберігаються, коли Гра разом вимкнена.",
      "openBtn": "Відкрити",
      "remix": "Ремікс",
      "trapRemix": "Trap ремікс",
      "nothingSaved": "На цьому Chromebook ще нічого не збережено.",
      "onlyHere": "Лише цей Chromebook",
      "classWord": "Клас",
    },
    "ru": {
      "makeBeat": "Сделай бит",
      "mySongs": "Мои песни",
      "songsH": "Песни",
      "openOne": "Открой одну песню. Ноты и барабаны для неё.",
      "start": "Старт",
      "blankStaff": "Пустой стан",
      "tempoKey": "Темп и тональность",
      "useThis": "Вот это",
      "openSongs": "Открыть песни",
      "mySaves": "Мои сохранения",
      "bringHead": "Принести файл",
      "djFile": "Файл · <bdi>DJ Berty</bdi>",
      "abc": "ABC",
      "midi": "MIDI",
      "musicxml": "MusicXML",
      "workOn": "Работай над этой песней",
      "makeSong": "Сделай песню",
      "pickFeel": "Выбери настроение. Потом скорость. Потом кто играет.",
      "speed": "Скорость",
      "startBuilding": "Начни собирать",
      "library": "Библиотека",
      "searchPh": "Ищи настроение, инструмент или кто",
      "beat": "Бит",
      "scoreDrums": "Ноты и барабаны",
      "score": "Ноты",
      "lights": "Свет",
      "band": "Бэнд",
      "soundWord": "Звук",
      "songs": "Песни",
      "perform": "Выступление",
      "listenTurn": "Слушай, потом я",
      "playAlong": "Играй вместе",
      "playingAlong": "Играешь вместе",
      "bringFile": "Принести файл",
      "go": "Перейти",
      "songList": "Список песен",
      "blend": "Смесь",
      "both": "Оба",
      "drumsWord": "Барабаны",
      "blendHint": "Слева барабаны. Справа ноты. Посередине играют оба.",
      "title": "Название",
      "picture": "Картинка",
      "effects": "Эффекты",
      "fxHint": "Выбери звук. Пэды его играют.",
      "synth": "Синт",
      "brightness": "Яркость",
      "length": "Длина",
      "echo": "Эхо",
      "wobble": "Качание",
      "oneLoop": "Один круг",
      "loopHint": "Не обязательно. Один круг, потом микрофон выключится.",
      "micOnce": "Микрофон один раз",
      "micNoHint": "Можно сказать нет. Пэды работают.",
      "startLoop": "Начать круг",
      "notNow": "Не сейчас",
      "hearLoop": "Услышать круг",
      "download": "Скачать",
      "del": "Удалить",
      "assignHead": "Задать упражнение",
      "assignHint": "Войди как ученик. Имя из TechWorks. Потом задай упражнение.",
      "hearFive": "Услышь пять нот",
      "readFinger": "Прочитай аппликатуру",
      "playFive": "Сыграй пять нот в песню",
      "assign": "Задать",
      "downloadClass": "Скачать файл класса",
      "openClass": "Открыть файл класса",
      "clearDrums": "Очистить барабаны",
      "tapAgain": "Нажми ещё раз, чтобы стереть",
      "saveFile": "Сохранить файл",
      "saveHint": "Этот Chromebook хранит песню. После входа готовый бит отправляет балл.",
      "teacher": "Учитель",
      "privacy": "Конфиденциальность",
      "newSong": "Новая песня",
      "yourSong": "Твоя песня",
      "tempo": "Темп",
      "save": "Сохранить",
      "share": "Поделиться",
      "record": "Запись",
      "recording": "Идёт запись",
      "more": "Ещё ▾",
      "saveSound": "Сохранить как звук",
      "soundOn": "Звук включён",
      "soundOff": "Звук выключен",
      "soundBanner": "Звук выключен.",
      "turnSoundOn": "Включить звук",
      "pressPlay": "Нажми {play}. Звук можно оставить выключенным.",
      "readMe": "Прочитай мне",
      "stop": "Стоп",
      "rest": "Пауза",
      "beatLine": "Бит {n} · {heard}. Звук можно оставить выключенным.",
      "howBoth": "Нотный стан и барабаны — это песня. Нажми букву или пэд. Потом {play}.",
      "howNotes": "Нажми букву. Потом {play}.",
      "howBeat": "Нажми пэд. Нажми {play}.",
      "howDrums": "Нажми бочку или малый. Нажми {play}. Твоё нажатие сохранится на этом бите.",
      "howLights": "Нажми картинку. Потом {play}.",
      "howBand": "Выбери инструмент. Нажми ноту, чтобы увидеть пальцы.",
      "howSound": "Нажми ноту. Смотри на волну. Попробуй мажор или минор.",
      "pressStop": "Нажми {stop}.",
      "hintBeat": "Нажми пэд. Нажми {play}. Свет показывает шаг.",
      "hintBoth": "Ноты и барабаны вместе. Буква меняет стан. Пэд меняет бит.",
      "hintNotes": "Стан — это песня. Нажми букву, чтобы сменить ноту.",
      "hintDrums": "Нажми бочку или малый. Нажатие сохранится на этом бите.",
      "hintAlong": "Игра вместе включена. Нажимай вспышку. Песня не меняется.",
      "hintLights": "Выбери картинку. Нажми {play}.",
      "hintBand": "Нажми ноту. Строка под ней — это пальцы.",
      "hintSound": "Нажми ноту. Волна повторяет форму.",
      "yourTurn": "Твоя очередь. Нажимай пэды. Звук можно оставить выключенным.",
      "yourTurnLesson": "Твоя очередь. Нажимай пэды. Биты, которые ты нажал, остаются в песне.",
      "tapsStayed": "Твои нажатия остались в песне. Звук можно оставить выключенным.",
      "hearAgain": "Класс может услышать твою очередь. Нажми {play}, чтобы услышать ещё раз.",
      "soundOffMove": "Звук выключен. Слово и картинка всё ещё двигаются.",
      "soundOnWord": "Звук включён. Слово всё ещё называет бит.",
      "listenOnce": "Послушай раз. Каждый пэд мигает. Потом твоя очередь.",
      "listenOff": "Слушай. Звук можно оставить выключенным.",
      "saved": "Сохранено",
      "bringBack": "Вернуть",
      "thatsSong": "Вот и песня",
      "playAgain": "Сыграй ещё раз",
      "backClass": "Назад в класс",
      "talent": "Концерт",
      "notYet": "Ещё нет",
      "startBtn": "Старт",
      "ready": "Готово",
      "bars": "такты",
      "sharedFor": "Открыто для {code}.",
      "sharedBox": "Открыто на этом Chromebook.",
      "sharedClass": "Открыто классу. Ссылка под пэдами.",
      "sharedSign": "Открыто на этом Chromebook. Войди, чтобы добавить код класса.",
      "midiSaved": "Файл MIDI сохранён. Он снова откроется из Принести файл.",
      "wavFail": "Этот звук не сохранился. Нажми {play} и попробуй ещё.",
      "pen_quarter": "1 бит",
      "pen_eighth": "Быстро",
      "pen_tie": "Длиннее",
      "pen_rest": "Пауза",
      "drum_kick": "Бочка",
      "drum_snare": "Малый",
      "drum_hat": "Хет",
      "drum_clap": "Хлопок",
      "drum_tom": "Том",
      "drum_shaker": "Шейкер",
      "drum_rim": "Обод",
      "drum_bell": "Колокол",
      "drum_tamb": "Бубен",
      "drum_crash": "Крэш",
      "scene_storm": "Шторм",
      "scene_neon": "Неон",
      "scene_soft": "Мягко",
      "scene_space": "Космос",
      "scene_fire": "Огонь",
      "scene_ocean": "Океан",
      "style_trap": "Trap",
      "style_lofi": "Lo-fi",
      "style_rock": "Rock",
      "style_marching": "Марш",
      "stepHint": "Нажми пэд. Он остаётся на этом шаге.",
      "scoreTools": "Инструменты нот",
      "addBar": "Добавить такт",
      "justStaff": "Только стан",
      "extraDrums": "Ещё барабаны (том, шейкер…)",
      "volSwing": "Громкость, свинг, рисунки",
      "swing": "Свинг",
      "addClick": "Добавить клик",
      "bassFollow": "Бас идёт за бочкой",
      "bassOn": "Бас включён",
      "major": "Мажор",
      "minor": "Минор",
      "oneByOne": "По одной",
      "look_bars": "Полосы",
      "look_ribbon": "Лента",
      "look_rings": "Кольца",
      "look_rain": "Дождь",
      "fx_plain": "Просто",
      "fx_soft": "Мягко",
      "fx_bright": "Ярко",
      "fx_echo": "Эхо",
      "fx_room": "Комната",
      "fx_hall": "Зал",
      "fx_robot": "Робот",
      "fx_radio": "Радио",
      "fx_space": "Космос",
      "fx_deep": "Глубоко",
      "wave_sine": "Круглая",
      "wave_triangle": "Мягкая",
      "wave_square": "Яркая",
      "wave_sawtooth": "Жужжание",
      "clearAsk": "Нажми стереть ещё раз. Вернуть ставит барабаны назад.",
      "drumsClear": "Барабаны чистые. Вернуть — под битом.",
      "drumsBack": "Барабаны вернулись. Сохранено.",
      "kickPulse": "Бочка на бите 1 — это пульс. Картинка прыгает с ней.",
      "fxOn": "{name} включено. Пэды его играют.",
      "waveOn": "{name} — это форма ноты. Барабаны остаются барабанами.",
      "countThen": "Считай {n}. Потом нажми ноту. Клик — это метроном. Он сохраняет.",
      "recOff": "Этот счёт выключен. Нажатия ещё играют. Они сохраняются, когда Игра вместе выключена.",
      "openBtn": "Открыть",
      "remix": "Ремикс",
      "trapRemix": "Trap ремикс",
      "nothingSaved": "На этом Chromebook ещё ничего не сохранено.",
      "onlyHere": "Только этот Chromebook",
      "classWord": "Класс",
    },
    "es": {
      "makeBeat": "Haz un ritmo",
      "mySongs": "Mis canciones",
      "songsH": "Canciones",
      "openOne": "Abre una canción. La partitura y la batería van con ella.",
      "start": "Inicio",
      "blankStaff": "Pentagrama vacío",
      "tempoKey": "Tempo y tono",
      "useThis": "Usar esto",
      "openSongs": "Abrir canciones",
      "mySaves": "Mis guardados",
      "bringHead": "Traer un archivo",
      "djFile": "Archivo · <bdi>DJ Berty</bdi>",
      "abc": "ABC",
      "midi": "MIDI",
      "musicxml": "MusicXML",
      "workOn": "Trabaja esta canción",
      "makeSong": "Haz una canción",
      "pickFeel": "Elige un estilo. Luego la velocidad. Luego quién toca.",
      "speed": "Velocidad",
      "startBuilding": "Empieza a armar",
      "library": "Biblioteca",
      "searchPh": "Busca estilo, instrumento o quién",
      "beat": "Ritmo",
      "scoreDrums": "Partitura y batería",
      "score": "Partitura",
      "lights": "Luces",
      "band": "Banda",
      "soundWord": "Sonido",
      "songs": "Canciones",
      "perform": "Actuar",
      "listenTurn": "Escucha y luego yo",
      "playAlong": "Toca junto",
      "playingAlong": "Tocando junto",
      "bringFile": "Traer un archivo",
      "go": "Ir",
      "songList": "Lista de canciones",
      "blend": "Mezcla",
      "both": "Ambos",
      "drumsWord": "Batería",
      "blendHint": "A la izquierda, la batería. A la derecha, la partitura. En el medio suenan ambos.",
      "title": "Título",
      "picture": "Imagen",
      "effects": "Efectos",
      "fxHint": "Elige un sonido. Los pads lo usan.",
      "synth": "Sintetizador",
      "brightness": "Brillo",
      "length": "Duración",
      "echo": "Eco",
      "wobble": "Vaivén",
      "oneLoop": "Un ciclo",
      "loopHint": "Opcional. Un ciclo y el micrófono se apaga.",
      "micOnce": "Usar el micrófono una vez",
      "micNoHint": "Puedes decir no. Los pads siguen.",
      "startLoop": "Empezar el ciclo",
      "notNow": "Ahora no",
      "hearLoop": "Oír el ciclo",
      "download": "Descargar",
      "del": "Borrar",
      "assignHead": "Asignar práctica",
      "assignHint": "Entra como el estudiante. El nombre viene de TechWorks. Luego asigna la práctica.",
      "hearFive": "Oír las cinco notas",
      "readFinger": "Leer cada digitación",
      "playFive": "Tocar las cinco notas en la canción",
      "assign": "Asignar",
      "downloadClass": "Descargar archivo de clase",
      "openClass": "Abrir un archivo de clase",
      "clearDrums": "Borrar la batería",
      "tapAgain": "Toca otra vez para borrar",
      "saveFile": "Guardar un archivo",
      "saveHint": "Este Chromebook guarda la canción. Después de entrar, un ritmo listo envía la nota.",
      "teacher": "Maestro",
      "privacy": "Privacidad",
      "newSong": "Canción nueva",
      "yourSong": "Tu canción",
      "tempo": "Tempo",
      "save": "Guardar",
      "share": "Compartir",
      "record": "Grabar",
      "recording": "Grabando",
      "more": "Más ▾",
      "saveSound": "Guardar como sonido",
      "soundOn": "Sonido activado",
      "soundOff": "Sonido apagado",
      "soundBanner": "El sonido está apagado.",
      "turnSoundOn": "Activar el sonido",
      "pressPlay": "Pulsa {play}. Puedes dejar el sonido apagado.",
      "readMe": "Léemelo",
      "stop": "Parar",
      "rest": "Silencio",
      "beatLine": "Ritmo {n} · {heard}. Puedes dejar el sonido apagado.",
      "howBoth": "El pentagrama y la batería son esta canción. Toca una letra o un pad. Luego {play}.",
      "howNotes": "Toca una letra. Luego {play}.",
      "howBeat": "Toca un pad. Pulsa {play}.",
      "howDrums": "Toca el bombo o la caja. Pulsa {play}. Tu toque se guarda en ese tiempo.",
      "howLights": "Toca una imagen. Luego {play}.",
      "howBand": "Elige tu instrumento. Toca una nota para ver los dedos.",
      "howSound": "Toca una nota. Mira la onda. Luego prueba Mayor o Menor.",
      "pressStop": "Pulsa {stop}.",
      "hintBeat": "Toca un pad. Pulsa {play}. La luz muestra el paso.",
      "hintBoth": "Partitura y batería juntas. Una letra cambia el pentagrama. Un pad cambia el ritmo.",
      "hintNotes": "El pentagrama es la canción. Toca una letra para cambiar una nota.",
      "hintDrums": "Toca el bombo o la caja. El toque se guarda en ese tiempo.",
      "hintAlong": "Tocar junto está activo. Toca con el destello. La canción no cambia.",
      "hintLights": "Elige una imagen. Pulsa {play}.",
      "hintBand": "Toca una nota. La línea de abajo es la digitación.",
      "hintSound": "Toca una nota. La onda sigue la forma.",
      "yourTurn": "Tu turno. Toca los pads. Puedes dejar el sonido apagado.",
      "yourTurnLesson": "Tu turno. Toca los pads. Los tiempos que tocas se quedan en la canción.",
      "tapsStayed": "Tus toques se quedaron en la canción. Puedes dejar el sonido apagado.",
      "hearAgain": "La clase puede oír tu turno. Pulsa {play} para oírlo otra vez.",
      "soundOffMove": "El sonido está apagado. La palabra y la imagen siguen.",
      "soundOnWord": "El sonido está activado. La palabra sigue el ritmo.",
      "listenOnce": "Escucha una vez. Cada pad destella. Luego es tu turno.",
      "listenOff": "Escucha. Puedes dejar el sonido apagado.",
      "saved": "Guardado",
      "bringBack": "Traerlo",
      "thatsSong": "Esa es la canción",
      "playAgain": "Tócala otra vez",
      "backClass": "Volver a clase",
      "talent": "Show de talento",
      "notYet": "Todavía no",
      "startBtn": "Empezar",
      "ready": "Listo",
      "bars": "compases",
      "sharedFor": "Compartido para {code}.",
      "sharedBox": "Compartido en este Chromebook.",
      "sharedClass": "Compartido con la clase. El enlace está bajo los pads.",
      "sharedSign": "Compartido en este Chromebook. Entra para poner el código de clase.",
      "midiSaved": "Archivo MIDI guardado. Se abre otra vez desde Traer un archivo.",
      "wavFail": "Ese sonido no se guardó. Pulsa {play} y prueba otra vez.",
      "pen_quarter": "1 tiempo",
      "pen_eighth": "Rápida",
      "pen_tie": "Más larga",
      "pen_rest": "Silencio",
      "drum_kick": "Bombo",
      "drum_snare": "Caja",
      "drum_hat": "Charles",
      "drum_clap": "Palma",
      "drum_tom": "Tom",
      "drum_shaker": "Shaker",
      "drum_rim": "Aro",
      "drum_bell": "Campana",
      "drum_tamb": "Pandero",
      "drum_crash": "Crash",
      "scene_storm": "Tormenta",
      "scene_neon": "Neón",
      "scene_soft": "Suave",
      "scene_space": "Espacio",
      "scene_fire": "Fuego",
      "scene_ocean": "Océano",
      "style_trap": "Trap",
      "style_lofi": "Lo-fi",
      "style_rock": "Rock",
      "style_marching": "Marcha",
      "stepHint": "Toca un pad. Se queda en ese paso.",
      "scoreTools": "Herramientas de partitura",
      "addBar": "Añadir un compás",
      "justStaff": "Solo el pentagrama",
      "extraDrums": "Más batería (tom, shaker…)",
      "volSwing": "Volumen, swing, patrones",
      "swing": "Swing",
      "addClick": "Añadir un clic",
      "bassFollow": "El bajo sigue al bombo",
      "bassOn": "El bajo está activo",
      "major": "Mayor",
      "minor": "Menor",
      "oneByOne": "Una por una",
      "look_bars": "Barras",
      "look_ribbon": "Cinta",
      "look_rings": "Anillos",
      "look_rain": "Lluvia",
      "fx_plain": "Simple",
      "fx_soft": "Suave",
      "fx_bright": "Brillante",
      "fx_echo": "Eco",
      "fx_room": "Sala",
      "fx_hall": "Salón",
      "fx_robot": "Robot",
      "fx_radio": "Radio",
      "fx_space": "Espacio",
      "fx_deep": "Grave",
      "wave_sine": "Redonda",
      "wave_triangle": "Suave",
      "wave_square": "Brillante",
      "wave_sawtooth": "Zumbido",
      "clearAsk": "Toca borrar una vez más. Traerlo pone la batería de vuelta.",
      "drumsClear": "La batería está vacía. Traerlo está bajo el ritmo.",
      "drumsBack": "La batería volvió. Guardado.",
      "kickPulse": "Un bombo en el tiempo 1 es el pulso. La imagen salta con él.",
      "fxOn": "{name} está activo. Los pads lo usan.",
      "waveOn": "{name} es la forma de la nota. La batería sigue siendo batería.",
      "countThen": "Cuenta {n}. Luego toca una nota. El clic es el metrónomo. Guarda.",
      "recOff": "Esa cuenta está apagada. Los toques siguen. Se guardan cuando Tocar junto está apagado.",
      "openBtn": "Abrir",
      "remix": "Remix",
      "trapRemix": "Remix trap",
      "nothingSaved": "Todavía no hay nada guardado en este Chromebook.",
      "onlyHere": "Solo este Chromebook",
      "classWord": "Clase",
    },
    "ar": {
      "makeBeat": "اصنع إيقاعًا",
      "mySongs": "أغنياتي",
      "songsH": "أغانٍ",
      "openOne": "افتح أغنية واحدة. النوتة والطبول لها.",
      "start": "ابدأ",
      "blankStaff": "مدرج فارغ",
      "tempoKey": "السرعة والمقام",
      "useThis": "استخدم هذا",
      "openSongs": "افتح الأغاني",
      "mySaves": "حفظي",
      "bringHead": "أحضر ملفًا",
      "djFile": "ملف · <bdi>DJ Berty</bdi>",
      "abc": "ABC",
      "midi": "MIDI",
      "musicxml": "MusicXML",
      "workOn": "اعمل على هذه الأغنية",
      "makeSong": "اصنع أغنية",
      "pickFeel": "اختر إحساسًا. ثم السرعة. ثم من يعزف.",
      "speed": "السرعة",
      "startBuilding": "ابدأ البناء",
      "library": "المكتبة",
      "searchPh": "ابحث عن إحساس أو آلة أو من",
      "beat": "إيقاع",
      "scoreDrums": "نوتة وطبول",
      "score": "نوتة",
      "lights": "أضواء",
      "band": "فرقة",
      "soundWord": "صوت",
      "songs": "أغانٍ",
      "perform": "اعرض",
      "listenTurn": "استمع ثم دوري",
      "playAlong": "اعزف معًا",
      "playingAlong": "تعزف معًا",
      "bringFile": "أحضر ملفًا",
      "go": "اذهب",
      "songList": "قائمة الأغاني",
      "blend": "مزج",
      "both": "الاثنان",
      "drumsWord": "طبول",
      "blendHint": "اليسار للطبول. اليمين للنوتة. الوسط يعزف الاثنين.",
      "title": "العنوان",
      "picture": "صورة",
      "effects": "مؤثرات",
      "fxHint": "اختر صوتًا. الأزرار تستخدمه.",
      "synth": "سينث",
      "brightness": "السطوع",
      "length": "الطول",
      "echo": "صدى",
      "wobble": "تمايل",
      "oneLoop": "دورة واحدة",
      "loopHint": "اختياري. دورة واحدة ثم ينطفئ الميكروفون.",
      "micOnce": "استخدم الميكروفون مرة",
      "micNoHint": "يمكنك أن تقول لا. الأزرار تعمل.",
      "startLoop": "ابدأ الدورة",
      "notNow": "ليس الآن",
      "hearLoop": "اسمع الدورة",
      "download": "تنزيل",
      "del": "حذف",
      "assignHead": "عيّن تدريبًا",
      "assignHint": "ادخل كطالب. الاسم من TechWorks. ثم عيّن التدريب.",
      "hearFive": "اسمع النغمات الخمس",
      "readFinger": "اقرأ كل أصابع",
      "playFive": "اعزف النغمات الخمس في الأغنية",
      "assign": "تعيين",
      "downloadClass": "نزّل ملف الصف",
      "openClass": "افتح ملف صف",
      "clearDrums": "امسح الطبول",
      "tapAgain": "المس مرة أخرى للمسح",
      "saveFile": "احفظ ملفًا",
      "saveHint": "هذا الـ Chromebook يحتفظ بالأغنية. بعد الدخول، إيقاع جاهز يرسل النقطة.",
      "teacher": "المعلم",
      "privacy": "الخصوصية",
      "newSong": "أغنية جديدة",
      "yourSong": "أغنيتك",
      "tempo": "السرعة",
      "save": "حفظ",
      "share": "مشاركة",
      "record": "تسجيل",
      "recording": "يسجّل",
      "more": "المزيد ▾",
      "saveSound": "احفظ كصوت",
      "soundOn": "الصوت يعمل",
      "soundOff": "الصوت متوقف",
      "soundBanner": "الصوت متوقف.",
      "turnSoundOn": "شغّل الصوت",
      "pressPlay": "اضغط {play}. يمكنك ترك الصوت متوقفًا.",
      "readMe": "اقرأها لي",
      "stop": "قف",
      "rest": "سكتة",
      "beatLine": "إيقاع {n} · {heard}. يمكنك ترك الصوت متوقفًا.",
      "howBoth": "المدرج والطبول هما هذه الأغنية. المس حرفًا أو زرًا. ثم {play}.",
      "howNotes": "المس حرفًا. ثم {play}.",
      "howBeat": "المس زرًا. اضغط {play}.",
      "howDrums": "المس الطبلة الكبيرة أو الصغيرة. اضغط {play}. لمستك تُحفظ على هذا الزمن.",
      "howLights": "المس صورة. ثم {play}.",
      "howBand": "اختر آلتك. المس نغمة لترى الأصابع.",
      "howSound": "المس نغمة. شاهد الموجة. ثم جرّب الكبير أو الصغير.",
      "pressStop": "اضغط {stop}.",
      "hintBeat": "المس زرًا. اضغط {play}. الضوء يبيّن الخطوة.",
      "hintBoth": "نوتة وطبول معًا. الحرف يغيّر المدرج. الزر يغيّر الإيقاع.",
      "hintNotes": "المدرج هو الأغنية. المس حرفًا لتغيير نغمة.",
      "hintDrums": "المس الطبلة الكبيرة أو الصغيرة. اللمسة تُحفظ على هذا الزمن.",
      "hintAlong": "العزف معًا يعمل. المس مع الوميض. الأغنية لا تتغير.",
      "hintLights": "اختر صورة. اضغط {play}.",
      "hintBand": "المس نغمة. السطر تحتها هو الأصابع.",
      "hintSound": "المس نغمة. الموجة تتبع الشكل.",
      "yourTurn": "دورك. المس الأزرار. يمكنك ترك الصوت متوقفًا.",
      "yourTurnLesson": "دورك. المس الأزرار. الأزمنة التي تلمسها تبقى في الأغنية.",
      "tapsStayed": "لمساتك بقيت في الأغنية. يمكنك ترك الصوت متوقفًا.",
      "hearAgain": "الصف يسمع دورك. اضغط {play} لتسمعه مرة أخرى.",
      "soundOffMove": "الصوت متوقف. الكلمة والصورة ما زالتا تتحركان.",
      "soundOnWord": "الصوت يعمل. الكلمة ما زالت تسمي الإيقاع.",
      "listenOnce": "استمع مرة. كل زر يومض. ثم يأتي دورك.",
      "listenOff": "استمع. يمكنك ترك الصوت متوقفًا.",
      "saved": "تم الحفظ",
      "bringBack": "أرجعها",
      "thatsSong": "هذه هي الأغنية",
      "playAgain": "شغّلها مرة أخرى",
      "backClass": "العودة إلى الصف",
      "talent": "عرض مواهب",
      "notYet": "ليس بعد",
      "startBtn": "ابدأ",
      "ready": "جاهز",
      "bars": "موازير",
      "sharedFor": "تمت المشاركة لـ {code}.",
      "sharedBox": "تمت المشاركة على هذا الـ Chromebook.",
      "sharedClass": "تمت المشاركة مع الصف. الرابط تحت الأزرار.",
      "sharedSign": "تمت المشاركة على هذا الـ Chromebook. ادخل لإضافة رمز الصف.",
      "midiSaved": "حُفظ ملف MIDI. يفتح مرة أخرى من أحضر ملفًا.",
      "wavFail": "لم يُحفظ هذا الصوت. اضغط {play} ثم حاول مرة أخرى.",
      "pen_quarter": "زمن واحد",
      "pen_eighth": "سريعة",
      "pen_tie": "أطول",
      "pen_rest": "سكتة",
      "drum_kick": "كبيرة",
      "drum_snare": "صغيرة",
      "drum_hat": "هاي هات",
      "drum_clap": "تصفيق",
      "drum_tom": "توم",
      "drum_shaker": "شيكر",
      "drum_rim": "حافة",
      "drum_bell": "جرس",
      "drum_tamb": "دف",
      "drum_crash": "كراش",
      "scene_storm": "عاصفة",
      "scene_neon": "نيون",
      "scene_soft": "ناعم",
      "scene_space": "فضاء",
      "scene_fire": "نار",
      "scene_ocean": "محيط",
      "style_trap": "Trap",
      "style_lofi": "Lo-fi",
      "style_rock": "Rock",
      "style_marching": "مسير",
      "stepHint": "المس زرًا. يبقى على هذه الخطوة.",
      "scoreTools": "أدوات النوتة",
      "addBar": "أضف مازورة",
      "justStaff": "المدرج فقط",
      "extraDrums": "طبول إضافية (توم، شيكر…)",
      "volSwing": "الصوت، السوينغ، الأنماط",
      "swing": "سوينغ",
      "addClick": "أضف نقرة",
      "bassFollow": "البايس يتبع الطبلة الكبيرة",
      "bassOn": "البايس يعمل",
      "major": "كبير",
      "minor": "صغير",
      "oneByOne": "واحدة واحدة",
      "look_bars": "أشرطة",
      "look_ribbon": "شريط",
      "look_rings": "حلقات",
      "look_rain": "مطر",
      "fx_plain": "بسيط",
      "fx_soft": "ناعم",
      "fx_bright": "ساطع",
      "fx_echo": "صدى",
      "fx_room": "غرفة",
      "fx_hall": "قاعة",
      "fx_robot": "روبوت",
      "fx_radio": "راديو",
      "fx_space": "فضاء",
      "fx_deep": "عميق",
      "wave_sine": "مستديرة",
      "wave_triangle": "ناعمة",
      "wave_square": "ساطعة",
      "wave_sawtooth": "طنين",
      "clearAsk": "المس المسح مرة أخرى. أرجعها تعيد الطبول.",
      "drumsClear": "الطبول فارغة. أرجعها تحت الإيقاع.",
      "drumsBack": "عادت الطبول. تم الحفظ.",
      "kickPulse": "الطبلة الكبيرة على الزمن 1 هي النبض. الصورة تقفز معها.",
      "fxOn": "{name} يعمل. الأزرار تستخدمه.",
      "waveOn": "{name} شكل النغمة. الطبول تبقى طبولًا.",
      "countThen": "عُد {n}. ثم المس نغمة. النقرة هي المترونوم. وهي تُحفظ.",
      "recOff": "هذا العد متوقف. اللمسات ما زالت تعزف. تُحفظ حين يكون العزف معًا متوقفًا.",
      "openBtn": "افتح",
      "remix": "ريمكس",
      "trapRemix": "ريمكس Trap",
      "nothingSaved": "لا شيء محفوظ على هذا الـ Chromebook بعد.",
      "onlyHere": "هذا الـ Chromebook فقط",
      "classWord": "الصف",
    },
    "fa-AF": {
      "makeBeat": "یک بیت بساز",
      "mySongs": "آهنگ‌های من",
      "songsH": "آهنگ‌ها",
      "openOne": "یک آهنگ را باز کن. نت و درام برای همان آهنگ است.",
      "start": "شروع",
      "blankStaff": "خط نت خالی",
      "tempoKey": "تمپو و تون",
      "useThis": "از این استفاده کن",
      "openSongs": "آهنگ‌ها را باز کن",
      "mySaves": "ذخیره‌های من",
      "bringHead": "یک فایل بیاور",
      "djFile": "فایل · <bdi>DJ Berty</bdi>",
      "abc": "ABC",
      "midi": "MIDI",
      "musicxml": "MusicXML",
      "workOn": "روی این آهنگ کار کن",
      "makeSong": "یک آهنگ بساز",
      "pickFeel": "یک حس را انتخاب کن. بعد سرعت. بعد کی می‌نوازد.",
      "speed": "سرعت",
      "startBuilding": "ساختن را شروع کن",
      "library": "کتابخانه",
      "searchPh": "حس، آله یا کس را جستجو کن",
      "beat": "بیت",
      "scoreDrums": "نت و درام",
      "score": "نت",
      "lights": "چراغ‌ها",
      "band": "گروپ",
      "soundWord": "صدا",
      "songs": "آهنگ‌ها",
      "perform": "نمایش بده",
      "listenTurn": "بشنو، بعد نوبت من",
      "playAlong": "همراه بزن",
      "playingAlong": "همراه می‌زنی",
      "bringFile": "یک فایل بیاور",
      "go": "برو",
      "songList": "فهرست آهنگ‌ها",
      "blend": "مخلوط",
      "both": "هر دو",
      "drumsWord": "درام",
      "blendHint": "چپ درام است. راست نت است. وسط هر دو را می‌نوازد.",
      "title": "عنوان",
      "picture": "تصویر",
      "effects": "اثرها",
      "fxHint": "یک صدا را انتخاب کن. دکمه‌ها از آن استفاده می‌کنند.",
      "synth": "سینث",
      "brightness": "روشنی",
      "length": "درازی",
      "echo": "پژواک",
      "wobble": "لرزش",
      "oneLoop": "یک دور",
      "loopHint": "اختیاری. یک دور، بعد میکروفون خاموش می‌شود.",
      "micOnce": "یک بار میکروفون",
      "micNoHint": "می‌توانی نه بگویی. دکمه‌ها کار می‌کنند.",
      "startLoop": "دور را شروع کن",
      "notNow": "حالا نه",
      "hearLoop": "دور را بشنو",
      "download": "دانلود",
      "del": "حذف",
      "assignHead": "تمرین را بسپار",
      "assignHint": "مانند شاگرد داخل شو. نام از TechWorks می‌آید. بعد تمرین را بسپار.",
      "hearFive": "پنج نت را بشنو",
      "readFinger": "هر انگشت‌گذاری را بخوان",
      "playFive": "پنج نت را در آهنگ بزن",
      "assign": "بسپار",
      "downloadClass": "فایل صنف را دانلود کن",
      "openClass": "یک فایل صنف را باز کن",
      "clearDrums": "درام را پاک کن",
      "tapAgain": "برای پاک کردن دوباره بزن",
      "saveFile": "یک فایل ذخیره کن",
      "saveHint": "این Chromebook آهنگ را نگه می‌دارد. بعد از ورود، بیت تمام‌شده نمره را می‌فرستد.",
      "teacher": "معلم",
      "privacy": "محرمیت",
      "newSong": "آهنگ نو",
      "yourSong": "آهنگ تو",
      "tempo": "تمپو",
      "save": "ذخیره",
      "share": "شریک کن",
      "record": "ضبط",
      "recording": "در حال ضبط",
      "more": "بیشتر ▾",
      "saveSound": "مانند صدا ذخیره کن",
      "soundOn": "صدا روشن",
      "soundOff": "صدا خاموش",
      "soundBanner": "صدا خاموش است.",
      "turnSoundOn": "صدا را روشن کن",
      "pressPlay": "{play} را بزن. صدا می‌تواند خاموش بماند.",
      "readMe": "برایم بخوان",
      "stop": "ایست",
      "rest": "سکوت",
      "beatLine": "بیت {n} · {heard}. صدا می‌تواند خاموش بماند.",
      "howBoth": "خط نت و درام همین آهنگ است. یک حرف یا دکمه را بزن. بعد {play}.",
      "howNotes": "یک حرف را بزن. بعد {play}.",
      "howBeat": "یک دکمه را بزن. {play} را فشار بده.",
      "howDrums": "باس یا اسنر را بزن. {play} را فشار بده. زدن تو در همان بیت می‌ماند.",
      "howLights": "یک تصویر را بزن. بعد {play}.",
      "howBand": "آله‌ات را انتخاب کن. یک نت را بزن تا انگشت‌ها را ببینی.",
      "howSound": "یک نت را بزن. موج را ببین. بعد بزرگ یا کوچک را امتحان کن.",
      "pressStop": "{stop} را بزن.",
      "hintBeat": "یک دکمه را بزن. {play} را فشار بده. چراغ گام را نشان می‌دهد.",
      "hintBoth": "نت و درام با هم. حرف خط نت را عوض می‌کند. دکمه بیت را عوض می‌کند.",
      "hintNotes": "خط نت همان آهنگ است. یک حرف را بزن تا نت عوض شود.",
      "hintDrums": "باس یا اسنر را بزن. زدن در همان بیت می‌ماند.",
      "hintAlong": "همراه زدن روشن است. با چشمک بزن. آهنگ همان می‌ماند.",
      "hintLights": "یک تصویر را انتخاب کن. {play} را فشار بده.",
      "hintBand": "یک نت را بزن. خط زیر آن انگشت‌گذاری است.",
      "hintSound": "یک نت را بزن. موج شکل را دنبال می‌کند.",
      "yourTurn": "نوبت تو. دکمه‌ها را بزن. صدا می‌تواند خاموش بماند.",
      "yourTurnLesson": "نوبت تو. دکمه‌ها را بزن. بیت‌هایی که می‌زنی در آهنگ می‌مانند.",
      "tapsStayed": "زدن‌های تو در آهنگ ماند. صدا می‌تواند خاموش بماند.",
      "hearAgain": "صنف نوبت تو را می‌شنود. {play} را بزن تا دوباره بشنوی.",
      "soundOffMove": "صدا خاموش است. کلمه و تصویر هنوز حرکت می‌کنند.",
      "soundOnWord": "صدا روشن است. کلمه هنوز بیت را نام می‌برد.",
      "listenOnce": "یک بار بشنو. هر دکمه چشمک می‌زند. بعد نوبت تو است.",
      "listenOff": "بشنو. صدا می‌تواند خاموش بماند.",
      "saved": "ذخیره شد",
      "bringBack": "برگردان",
      "thatsSong": "همین آهنگ است",
      "playAgain": "دوباره بزن",
      "backClass": "برگشت به صنف",
      "talent": "نمایش استعداد",
      "notYet": "هنوز نه",
      "startBtn": "شروع",
      "ready": "آماده",
      "bars": "میزان‌ها",
      "sharedFor": "برای {code} شریک شد.",
      "sharedBox": "در این Chromebook شریک شد.",
      "sharedClass": "با صنف شریک شد. لینک زیر دکمه‌ها است.",
      "sharedSign": "در این Chromebook شریک شد. داخل شو تا کود صنف را بگذاری.",
      "midiSaved": "فایل MIDI ذخیره شد. دوباره از یک فایل بیاور باز می‌شود.",
      "wavFail": "این صدا ذخیره نشد. {play} را بزن و دوباره کوشش کن.",
      "pen_quarter": "۱ بیت",
      "pen_eighth": "تند",
      "pen_tie": "درازتر",
      "pen_rest": "سکوت",
      "drum_kick": "باس",
      "drum_snare": "اسنر",
      "drum_hat": "هت",
      "drum_clap": "کف",
      "drum_tom": "تام",
      "drum_shaker": "شیکر",
      "drum_rim": "لبه",
      "drum_bell": "زنگ",
      "drum_tamb": "دف",
      "drum_crash": "کرش",
      "scene_storm": "طوفان",
      "scene_neon": "نیون",
      "scene_soft": "نرم",
      "scene_space": "فضا",
      "scene_fire": "آتش",
      "scene_ocean": "بحر",
      "style_trap": "Trap",
      "style_lofi": "Lo-fi",
      "style_rock": "Rock",
      "style_marching": "مارش",
      "stepHint": "یک دکمه را بزن. در همان گام می‌ماند.",
      "scoreTools": "ابزار نت",
      "addBar": "یک میزان اضافه کن",
      "justStaff": "فقط خط نت",
      "extraDrums": "درام بیشتر (تام، شیکر…)",
      "volSwing": "بلندی، سوینگ، الگوها",
      "swing": "سوینگ",
      "addClick": "یک کلیک اضافه کن",
      "bassFollow": "بیس از باس پیروی می‌کند",
      "bassOn": "بیس روشن است",
      "major": "بزرگ",
      "minor": "خرد",
      "oneByOne": "یکی یکی",
      "look_bars": "خط‌ها",
      "look_ribbon": "نوار",
      "look_rings": "حلقه‌ها",
      "look_rain": "باران",
      "fx_plain": "ساده",
      "fx_soft": "نرم",
      "fx_bright": "روشن",
      "fx_echo": "پژواک",
      "fx_room": "اتاق",
      "fx_hall": "تالار",
      "fx_robot": "ربات",
      "fx_radio": "رادیو",
      "fx_space": "فضا",
      "fx_deep": "عمیق",
      "wave_sine": "گرد",
      "wave_triangle": "نرم",
      "wave_square": "روشن",
      "wave_sawtooth": "وزوز",
      "clearAsk": "پاک کردن را یک بار دیگر بزن. برگردان درام را پس می‌آورد.",
      "drumsClear": "درام خالی است. برگردان زیر بیت است.",
      "drumsBack": "درام برگشت. ذخیره شد.",
      "kickPulse": "باس در بیت ۱ نبض است. تصویر با آن می‌جهد.",
      "fxOn": "{name} روشن است. دکمه‌ها از آن استفاده می‌کنند.",
      "waveOn": "{name} شکل نت است. درام درام می‌ماند.",
      "countThen": "{n} را بشمار. بعد یک نت را بزن. کلیک مترونوم است. ذخیره می‌شود.",
      "recOff": "این شمارش خاموش است. زدن‌ها هنوز صدا می‌دهند. وقتی همراه زدن خاموش است ذخیره می‌شوند.",
      "openBtn": "باز کن",
      "remix": "ریمیکس",
      "trapRemix": "ریمیکس Trap",
      "nothingSaved": "در این Chromebook هنوز چیزی ذخیره نشده.",
      "onlyHere": "فقط همین Chromebook",
      "classWord": "صنف",
    },
    "rw": {
      "makeBeat": "Kora umurya",
      "mySongs": "Indirimbo zanjye",
      "songsH": "Indirimbo",
      "openOne": "Fungura indirimbo imwe. Inota n'ingoma ni iyo ndirimbo.",
      "start": "Tangira",
      "blankStaff": "Umurongo utagira ntacyo",
      "tempoKey": "Umuvuduko n'urufunguzo",
      "useThis": "Koresha iki",
      "openSongs": "Fungura indirimbo",
      "mySaves": "Ibyo nabitse",
      "bringHead": "Zana dosiye",
      "djFile": "Dosiye · <bdi>DJ Berty</bdi>",
      "abc": "ABC",
      "midi": "MIDI",
      "musicxml": "MusicXML",
      "workOn": "Kora kuri iyi ndirimbo",
      "makeSong": "Kora indirimbo",
      "pickFeel": "Hitamo uburyo. Hanyuma umuvuduko. Hanyuma uwo ukina.",
      "speed": "Umuvuduko",
      "startBuilding": "Tangira kubaka",
      "library": "Isomero",
      "searchPh": "Shakisha uburyo, igikoresho, cyangwa uwo",
      "beat": "Umurya",
      "scoreDrums": "Inota n'ingoma",
      "score": "Inota",
      "lights": "Amatara",
      "band": "Itsinda",
      "soundWord": "Ijwi",
      "songs": "Indirimbo",
      "perform": "Erekana",
      "listenTurn": "Umva. Hanyuma nanjye.",
      "playAlong": "Kina hamwe",
      "playingAlong": "Uri gukina hamwe",
      "bringFile": "Zana dosiye",
      "go": "Genda",
      "songList": "Urutonde rw'indirimbo",
      "blend": "Vanga",
      "both": "Byombi",
      "drumsWord": "Ingoma",
      "blendHint": "Ibumoso ni ingoma. Iburyo ni inota. Hagati bikina byombi.",
      "title": "Umutwe",
      "picture": "Ishusho",
      "effects": "Ingaruka",
      "fxHint": "Hitamo ijwi. Utudomo barukoresha.",
      "synth": "Sinti",
      "brightness": "Urumuri",
      "length": "Uburebure",
      "echo": "Isubirwamo",
      "wobble": "Kunyeganyega",
      "oneLoop": "Uruziga rumwe",
      "loopHint": "Si ngombwa. Uruziga rumwe, hanyuma mikoro irazimira.",
      "micOnce": "Koresha mikoro rimwe",
      "micNoHint": "Ushobora kuvuga oya. Utudomo birakora.",
      "startLoop": "Tangira uruziga",
      "notNow": "Si none",
      "hearLoop": "Umva uruziga",
      "download": "Kuramo",
      "del": "Siba",
      "assignHead": "Tanga imyitozo",
      "assignHint": "Injira nk'umunyeshuri. Izina riva muri TechWorks. Hanyuma tanga imyitozo.",
      "hearFive": "Umva inota eshanu",
      "readFinger": "Soma buri ntambwe y'intoki",
      "playFive": "Kina inota eshanu mu ndirimbo",
      "assign": "Tanga",
      "downloadClass": "Kuramo dosiye y'ishuri",
      "openClass": "Fungura dosiye y'ishuri",
      "clearDrums": "Siba ingoma",
      "tapAgain": "Kanda nanone kugira ngo usibe",
      "saveFile": "Bika dosiye",
      "saveHint": "Iyi Chromebook ibika indirimbo. Nyuma yo kwinjira, umurya urangiye wohereza amanota.",
      "teacher": "Umwarimu",
      "privacy": "Ibanga",
      "newSong": "Indirimbo nshya",
      "yourSong": "Indirimbo yawe",
      "tempo": "Umuvuduko",
      "save": "Bika",
      "share": "Sangira",
      "record": "Fata amajwi",
      "recording": "Irafata amajwi",
      "more": "Ibindi ▾",
      "saveSound": "Bika nk'ijwi",
      "soundOn": "Ijwi ririmo",
      "soundOff": "Ijwi ntirimo",
      "soundBanner": "Ijwi ntirimo.",
      "turnSoundOn": "Fungura ijwi",
      "pressPlay": "Kanda {play}. Ijwi rishobora kuguma ritariho.",
      "readMe": "Nsome",
      "stop": "Hagarara",
      "rest": "Kiruhuko",
      "beatLine": "Umurya {n} · {heard}. Ijwi rishobora kuguma ritariho.",
      "howBoth": "Umurongo n'ingoma ni iyi ndirimbo. Kanda inyuguti cyangwa utudomo. Hanyuma {play}.",
      "howNotes": "Kanda inyuguti. Hanyuma {play}.",
      "howBeat": "Kanda utudomo. Kanda {play}.",
      "howDrums": "Kanda ingoma nini cyangwa nto. Kanda {play}. Ukanda kwawe kubikwa kuri uwo murya.",
      "howLights": "Kanda ishusho. Hanyuma {play}.",
      "howBand": "Hitamo igikoresho cyawe. Kanda inota kugira ngo ubone intoki.",
      "howSound": "Kanda inota. Reba umukuba. Hanyuma gerageza nini cyangwa nto.",
      "pressStop": "Kanda {stop}.",
      "hintBeat": "Kanda utudomo. Kanda {play}. Urumuri rwereka intambwe.",
      "hintBoth": "Inota n'ingoma hamwe. Inyuguti ihindura umurongo. Utudomo duhindura umurya.",
      "hintNotes": "Umurongo ni indirimbo. Kanda inyuguti kugira ngo uhindure inota.",
      "hintDrums": "Kanda ingoma nini cyangwa nto. Ukanda kubikwa kuri uwo murya.",
      "hintAlong": "Gukina hamwe birakora. Kanda ukurikije urumuri. Indirimbo ntigahinduka.",
      "hintLights": "Hitamo ishusho. Kanda {play}.",
      "hintBand": "Kanda inota. Umurongo uri munsi ni intoki.",
      "hintSound": "Kanda inota. Umukuba ukurikiza ishusho.",
      "yourTurn": "Uruhare rwawe. Kanda utudomo. Ijwi rishobora kuguma ritariho.",
      "yourTurnLesson": "Uruhare rwawe. Kanda utudomo. Imiryago ukanda iguma mu ndirimbo.",
      "tapsStayed": "Ukanda kwawe kwagumye mu ndirimbo. Ijwi rishobora kuguma ritariho.",
      "hearAgain": "Ishuri rishobora kumva uruhare rwawe. Kanda {play} kugira ngo wongere wumve.",
      "soundOffMove": "Ijwi ntirimo. Ijambo n'ishusho biracyagenda.",
      "soundOnWord": "Ijwi ririmo. Ijambo riracyita umurya.",
      "listenOnce": "Umva rimwe. Buri tudomo twaka. Hanyuma ni uruhare rwawe.",
      "listenOff": "Umva. Ijwi rishobora kuguma ritariho.",
      "saved": "Byabitswe",
      "bringBack": "Byizane",
      "thatsSong": "Niyo ndirimbo",
      "playAgain": "Yikine nanone",
      "backClass": "Subira mu ishuri",
      "talent": "Igaragaza",
      "notYet": "Ntabwo",
      "startBtn": "Tangira",
      "ready": "Biteguye",
      "bars": "ibice",
      "sharedFor": "Byasangiwe {code}.",
      "sharedBox": "Byasangiwe kuri iyi Chromebook.",
      "sharedClass": "Byasangiwe n'ishuri. Ihuza iri munsi y'utudomo.",
      "sharedSign": "Byasangiwe kuri iyi Chromebook. Injira kugira ngo ushyire kode y'ishuri.",
      "midiSaved": "Dosiye ya MIDI yabitswe. Ifunguka nanone muri Zana dosiye.",
      "wavFail": "Iryo jwi ntiryabitswe. Kanda {play}, hanyuma ongera ugerageze.",
      "pen_quarter": "Umurya 1",
      "pen_eighth": "Vuba",
      "pen_tie": "Ndende",
      "pen_rest": "Kiruhuko",
      "drum_kick": "Nini",
      "drum_snare": "Nto",
      "drum_hat": "Hat",
      "drum_clap": "Amaraso",
      "drum_tom": "Tom",
      "drum_shaker": "Shaker",
      "drum_rim": "Urutuba",
      "drum_bell": "Inzogera",
      "drum_tamb": "Ingoma nto",
      "drum_crash": "Crash",
      "scene_storm": "Inkubi",
      "scene_neon": "Neyoni",
      "scene_soft": "Byoroshye",
      "scene_space": "Umwanya",
      "scene_fire": "Umuriro",
      "scene_ocean": "Inyanja",
      "style_trap": "Trap",
      "style_lofi": "Lo-fi",
      "style_rock": "Rock",
      "style_marching": "Ingendo",
      "stepHint": "Kanda utudomo. Tuguma kuri iyo ntambwe.",
      "scoreTools": "Ibikoresho by'inota",
      "addBar": "Ongeraho igice",
      "justStaff": "Umurongo gusa",
      "extraDrums": "Ingoma zindi (Tom, Shaker…)",
      "volSwing": "Ijwi, swing, imirongo",
      "swing": "Swing",
      "addClick": "Ongeraho ikilik",
      "bassFollow": "Basi ikurikira ingoma nini",
      "bassOn": "Basi irakora",
      "major": "Nini",
      "minor": "Nto",
      "oneByOne": "Imwe imwe",
      "look_bars": "Imirongo",
      "look_ribbon": "Urubande",
      "look_rings": "Imbariro",
      "look_rain": "Imvura",
      "fx_plain": "Bisanzwe",
      "fx_soft": "Byoroshye",
      "fx_bright": "Birabagirana",
      "fx_echo": "Isubirwamo",
      "fx_room": "Icyumba",
      "fx_hall": "Ihuriro",
      "fx_robot": "Robo",
      "fx_radio": "Radiyo",
      "fx_space": "Umwanya",
      "fx_deep": "Byimbitse",
      "wave_sine": "Izenguruka",
      "wave_triangle": "Yoroshye",
      "wave_square": "Irabagirana",
      "wave_sawtooth": "Ivuma",
      "clearAsk": "Kanda gusiba nanone. Byizane bisubiza ingoma.",
      "drumsClear": "Ingoma zirasekuye. Byizane biri munsi y'umurya.",
      "drumsBack": "Ingoma zasubiyeyo. Byabitswe.",
      "kickPulse": "Ingoma nini ku murya wa 1 ni umutima. Ishusho irasimbutsa.",
      "fxOn": "{name} irakora. Utudomo barukoresha.",
      "waveOn": "{name} ni ishusho y'inota. Ingoma iguma ingoma.",
      "countThen": "Bara {n}. Hanyuma kanda inota. Ikilik ni metoronome. Ibibika.",
      "recOff": "Iyo mibare irazimye. Ukanda gukora. Kubikwa iyo Gukina hamwe kuzimye.",
      "openBtn": "Fungura",
      "remix": "Remix",
      "trapRemix": "Remix ya trap",
      "nothingSaved": "Nta kintu kirabikwa kuri iyi Chromebook.",
      "onlyHere": "Iyi Chromebook gusa",
      "classWord": "Ishuri",
    },
    "ti": {
      "makeBeat": "ምት ግበር",
      "mySongs": "ደርፍታተይ",
      "songsH": "ደርፍታት",
      "openOne": "ሓንቲ ደርፊ ክፈት። ነጥቢን ከበሮን ናታ እዩ።",
      "start": "ጀምር",
      "blankStaff": "ባዶ መስመር",
      "tempoKey": "ፍጥነትን ቁልፍን",
      "useThis": "ነዚ ተጠቐም",
      "openSongs": "ደርፍታት ክፈት",
      "mySaves": "ዝዓቀብኩዎ",
      "bringHead": "ፋይል ኣምጽእ",
      "djFile": "ፋይል · <bdi>DJ Berty</bdi>",
      "abc": "ABC",
      "midi": "MIDI",
      "musicxml": "MusicXML",
      "workOn": "ኣብዛ ደርፊ ስራሕ",
      "makeSong": "ደርፊ ግበር",
      "pickFeel": "ስምዒት ምረጽ። ድሕሪኡ ፍጥነት። ድሕሪኡ መን ይጻወት።",
      "speed": "ፍጥነት",
      "startBuilding": "ምህናጽ ጀምር",
      "library": "ቤተ መጻሕፍቲ",
      "searchPh": "ስምዒት፣ መሳርሒ፣ ወይ መን ድለ",
      "beat": "ምት",
      "scoreDrums": "ነጥቢን ከበሮን",
      "score": "ነጥቢ",
      "lights": "መብራህቲ",
      "band": "ጉጅለ",
      "soundWord": "ድምጺ",
      "songs": "ደርፍታት",
      "perform": "ኣርኢ",
      "listenTurn": "ስማዕ። ድሕሪኡ ናተይ።",
      "playAlong": "ምሳኻ ተጻወት",
      "playingAlong": "ምሳኻ ትጻወት ኣለኻ",
      "bringFile": "ፋይል ኣምጽእ",
      "go": "ኪድ",
      "songList": "ዝርዝር ደርፍታት",
      "blend": "ሕውስውስ",
      "both": "ክልቲኡ",
      "drumsWord": "ከበሮ",
      "blendHint": "ጸጋም ከበሮ እዩ። የማን ነጥቢ እዩ። ማእኸል ክልቲኡ ይጻወት።",
      "title": "ኣርእስቲ",
      "picture": "ስእሊ",
      "effects": "ውጽኢታት",
      "fxHint": "ድምጺ ምረጽ። ቁልፍታት ይጥቀምዎ።",
      "synth": "ሲንት",
      "brightness": "ብርሃን",
      "length": "ንውሓት",
      "echo": "ተመላላሲ",
      "wobble": "ምንቅጥቃጥ",
      "oneLoop": "ሓንቲ ዙርያ",
      "loopHint": "ኣማራጺ። ሓንቲ ዙርያ፣ ድሕሪኡ ማይክሮፎን ይጠፍእ።",
      "micOnce": "ማይክሮፎን ሓንሳብ",
      "micNoHint": "ኣይፋልካን ክትብል ትኽእል። ቁልፍታት ይሰርሑ።",
      "startLoop": "ዙርያ ጀምር",
      "notNow": "ሕጂ ኣይኮነን",
      "hearLoop": "ዙርያ ስማዕ",
      "download": "ኣውርድ",
      "del": "ደምስስ",
      "assignHead": "ልምምድ ሃብ",
      "assignHint": "ከም ተማሃራይ እቶ። ስም ካብ TechWorks ይመጽእ። ድሕሪኡ ልምምድ ሃብ።",
      "hearFive": "ሓሙሽተ ነጥብታት ስማዕ",
      "readFinger": "ነፍሲ ወከፍ ኣጻብዕቲ ኣንብብ",
      "playFive": "ሓሙሽተ ነጥብታት ኣብቲ ደርፊ ጻውዕ",
      "assign": "ሃብ",
      "downloadClass": "ፋይል ክፍሊ ኣውርድ",
      "openClass": "ፋይል ክፍሊ ክፈት",
      "clearDrums": "ከበሮ ኣጽሪ",
      "tapAgain": "ንምጽራይ ደጊምካ ጠውቕ",
      "saveFile": "ፋይል ዓቅብ",
      "saveHint": "እዚ Chromebook ነቲ ደርፊ ይሕዞ። ድሕሪ ምእታው፣ ዝተዛዘመ ምት ነጥቢ ይሰድድ።",
      "teacher": "መምህር",
      "privacy": "ውልቃዊ",
      "newSong": "ሓድሽ ደርፊ",
      "yourSong": "ደርፍኻ",
      "tempo": "ፍጥነት",
      "save": "ዓቅብ",
      "share": "ኣካፍል",
      "record": "ቅዳሕ",
      "recording": "ይቕድሕ ኣሎ",
      "more": "ተወሳኺ ▾",
      "saveSound": "ከም ድምጺ ዓቅብ",
      "soundOn": "ድምጺ ይርከብ",
      "soundOff": "ድምጺ የለን",
      "soundBanner": "ድምጺ የለን።",
      "turnSoundOn": "ድምጺ ወልዕ",
      "pressPlay": "{play} ጠውቕ። ድምጺ ክጠፍእ ይኽእል።",
      "readMe": "ኣንብበለይ",
      "stop": "ደው",
      "rest": "ዕረፍቲ",
      "beatLine": "ምት {n} · {heard}. ድምጺ ክጠፍእ ይኽእል።",
      "howBoth": "መስመርን ከበሮን እዛ ደርፊ እያ። ፊደል ወይ ቁልፊ ጠውቕ። ድሕሪኡ {play}።",
      "howNotes": "ፊደል ጠውቕ። ድሕሪኡ {play}።",
      "howBeat": "ቁልፊ ጠውቕ። {play} ጠውቕ።",
      "howDrums": "ዓቢ ወይ ንእሽቶ ከበሮ ጠውቕ። {play} ጠውቕ። ምጥዋቕካ ኣብቲ ምት ይቕመጥ።",
      "howLights": "ስእሊ ጠውቕ። ድሕሪኡ {play}።",
      "howBand": "መሳርሒኻ ምረጽ። ነጥቢ ጠውቕ ንኽትሪኢ ኣጻብዕቲ።",
      "howSound": "ነጥቢ ጠውቕ። ማዕበል ርአ። ድሕሪኡ ዓቢ ወይ ንእሽቶ ፈትን።",
      "pressStop": "{stop} ጠውቕ።",
      "hintBeat": "ቁልፊ ጠውቕ። {play} ጠውቕ። መብራህቲ እቲ ስጉምቲ የርኢ።",
      "hintBoth": "ነጥቢን ከበሮን ብሓባር። ፊደል መስመር ይቅይር። ቁልፊ ምት ይቅይር።",
      "hintNotes": "መስመር እቲ ደርፊ እዩ። ነጥቢ ንምቕያር ፊደል ጠውቕ።",
      "hintDrums": "ዓቢ ወይ ንእሽቶ ከበሮ ጠውቕ። ምጥዋቕ ኣብቲ ምት ይቕመጥ።",
      "hintAlong": "ምሳኻ ምጽዋት ይሰርሕ። ምስ ብልጭታ ጠውቕ። እቲ ደርፊ ኣይቕየርን።",
      "hintLights": "ስእሊ ምረጽ። {play} ጠውቕ።",
      "hintBand": "ነጥቢ ጠውቕ። እቲ ኣብ ትሕቲ መስመር ኣጻብዕቲ እዩ።",
      "hintSound": "ነጥቢ ጠውቕ። ማዕበል ነቲ ቅርጺ ይስዕብ።",
      "yourTurn": "ናትካ ተራ። ቁልፍታት ጠውቕ። ድምጺ ክጠፍእ ይኽእል።",
      "yourTurnLesson": "ናትካ ተራ። ቁልፍታት ጠውቕ። እቶም እትጠውቖም ምትታት ኣብቲ ደርፊ ይቕመጡ።",
      "tapsStayed": "ምጥዋቕካ ኣብቲ ደርፊ ተሪፉ። ድምጺ ክጠፍእ ይኽእል።",
      "hearAgain": "ክፍሊ ንናትካ ተራ ክሰምዕ ይኽእል። ደጊምካ ንምስማዕ {play} ጠውቕ።",
      "soundOffMove": "ድምጺ የለን። ቃልን ስእልን ገና ይንቀሳቐሱ።",
      "soundOnWord": "ድምጺ ይርከብ። ቃል ገና ነቲ ምት ይሰይሞ።",
      "listenOnce": "ሓንሳብ ስማዕ። ነፍሲ ወከፍ ቁልፊ ይብልጭ። ድሕሪኡ ናትካ ተራ እዩ።",
      "listenOff": "ስማዕ። ድምጺ ክጠፍእ ይኽእል።",
      "saved": "ተዓቂቡ",
      "bringBack": "መልሶ",
      "thatsSong": "እዛ እያ እቲ ደርፊ",
      "playAgain": "ደጊምካ ጻውዓ",
      "backClass": "ናብ ክፍሊ ተመለስ",
      "talent": "ርእይቶ ክእለት",
      "notYet": "ገና ኣይኮነን",
      "startBtn": "ጀምር",
      "ready": "ድሉው",
      "bars": "ባራት",
      "sharedFor": "ን {code} ተካፊሉ።",
      "sharedBox": "ኣብዚ Chromebook ተካፊሉ።",
      "sharedClass": "ምስ ክፍሊ ተካፊሉ። እቲ ሊንክ ኣብ ትሕቲ ቁልፍታት እዩ።",
      "sharedSign": "ኣብዚ Chromebook ተካፊሉ። ኮድ ክፍሊ ንምሕባር እቶ።",
      "midiSaved": "ፋይል MIDI ተዓቂቡ። ካብ ፋይል ኣምጽእ ደጊሙ ይኽፈት።",
      "wavFail": "እቲ ድምጺ ኣይተዓቐበን። {play} ጠውቕ፣ ድሕሪኡ ደጊምካ ፈትን።",
      "pen_quarter": "1 ምት",
      "pen_eighth": "ቅልጡፍ",
      "pen_tie": "ነዊሕ",
      "pen_rest": "ዕረፍቲ",
      "drum_kick": "ዓቢ",
      "drum_snare": "ንእሽቶ",
      "drum_hat": "ሃት",
      "drum_clap": "ምጭብጣብ",
      "drum_tom": "ቶም",
      "drum_shaker": "ሸከር",
      "drum_rim": "ገምጋም",
      "drum_bell": "ደወል",
      "drum_tamb": "ከበሮ ንእሽቶ",
      "drum_crash": "ክራሽ",
      "scene_storm": "ዕንባባ",
      "scene_neon": "ኒዮን",
      "scene_soft": "ልስሉስ",
      "scene_space": "ጠፈር",
      "scene_fire": "ሓዊ",
      "scene_ocean": "ባሕሪ",
      "style_trap": "Trap",
      "style_lofi": "Lo-fi",
      "style_rock": "Rock",
      "style_marching": "ሰልፊ",
      "stepHint": "ቁልፊ ጠውቕ። ኣብቲ ስጉምቲ ይቕመጥ።",
      "scoreTools": "መሳርሒ ነጥቢ",
      "addBar": "ባር ወስኽ",
      "justStaff": "መስመር ጥራይ",
      "extraDrums": "ተወሳኺ ከበሮ (ቶም፣ ሸከር…)",
      "volSwing": "ድምጺ፣ ስዊንግ፣ ቅዲ",
      "swing": "ስዊንግ",
      "addClick": "ጠውቃዕ ወስኽ",
      "bassFollow": "ቤዝ ነቲ ዓቢ ከበሮ ይስዕብ",
      "bassOn": "ቤዝ ይሰርሕ",
      "major": "ዓቢ",
      "minor": "ንእሽቶ",
      "oneByOne": "ሓደ ሓደ",
      "look_bars": "መስመራት",
      "look_ribbon": "ናሕሲ",
      "look_rings": "ቀለቤታት",
      "look_rain": "ዝናብ",
      "fx_plain": "ቀሊል",
      "fx_soft": "ልስሉስ",
      "fx_bright": "ብሩህ",
      "fx_echo": "ተመላላሲ",
      "fx_room": "ክፍሊ",
      "fx_hall": "ኣዳራሽ",
      "fx_robot": "ሮቦት",
      "fx_radio": "ራድዮ",
      "fx_space": "ጠፈር",
      "fx_deep": "ዓሚቝ",
      "wave_sine": "ክብ",
      "wave_triangle": "ልስሉስ",
      "wave_square": "ብሩህ",
      "wave_sawtooth": "ዝዝምር",
      "clearAsk": "ምጽራይ ደጊምካ ጠውቕ። መልሶ ከበሮ ይመልስ።",
      "drumsClear": "ከበሮ ተጸሪጉ። መልሶ ኣብ ትሕቲ ምት እዩ።",
      "drumsBack": "ከበሮ ተመሊሱ። ተዓቂቡ።",
      "kickPulse": "ዓቢ ከበሮ ኣብ ምት 1 ሕበይ እዩ። ስእሊ ምስኡ ይነጥር።",
      "fxOn": "{name} ይሰርሕ። ቁልፍታት ይጥቀምዎ።",
      "waveOn": "{name} ቅርጺ ነጥቢ እዩ። ከበሮ ከበሮ ይቕጽል።",
      "countThen": "{n} ቁጽር። ድሕሪኡ ነጥቢ ጠውቕ። ጠውቃዕ ሜትሮኖም እዩ። ይዓቅብ።",
      "recOff": "እዚ ቁጽሪ ጠፊኡ። ምጥዋቕ ገና ይጻወት። ምሳኻ ምጽዋት ምስ ጠፍአ ይዓቅብ።",
      "openBtn": "ክፈት",
      "remix": "ሪሚክስ",
      "trapRemix": "ሪሚክስ Trap",
      "nothingSaved": "ኣብዚ Chromebook ገና ዝተዓቀበ የለን።",
      "onlyHere": "እዚ Chromebook ጥራይ",
      "classWord": "ክፍሊ",
    },
  };
  Object.keys(MORE).forEach(function (code) { PACKS[code] = MORE[code]; });

  function classic() {
    try {
      var q = new URLSearchParams(location.search);
      if (q.get("hub") === "classic" || q.get("theme") === "classic") return true;
      if (localStorage.getItem("tech-room-hub") === "classic") return true;
    } catch (e) {}
    return false;
  }
  function lang() {
    if (classic()) return "en";
    try {
      var q = new URLSearchParams(location.search).get("lang") || "";
      if (OK[q]) return q;
    } catch (e) {}
    try {
      if (root.KulibertPrefs && OK[root.KulibertPrefs.lang]) return root.KulibertPrefs.lang;
    } catch (e2) {}
    try {
      var raw = JSON.parse(localStorage.getItem("kulibert-prefs-v1") || "null");
      if (raw && OK[raw.lang]) return raw.lang;
    } catch (e3) {}
    return "en";
  }
  function shared(key, fallback) {
    try {
      var v = root.KulibertI18n && root.KulibertI18n.t && root.KulibertI18n.t(key);
      if (v) return v;
    } catch (e) {}
    return fallback || "";
  }
  function fill(s, vars) {
    var out = s;
    var bag = vars || {};
    if (out.indexOf("{play}") >= 0 && bag.play == null) bag = Object.assign({ play: shared("play", "Play") }, bag);
    if (out.indexOf("{stop}") >= 0 && bag.stop == null) {
      var stop = (PACKS[lang()] && PACKS[lang()].stop) || EN.stop;
      bag = Object.assign({ stop: stop }, bag);
    }
    Object.keys(bag).forEach(function (k) {
      out = out.split("{" + k + "}").join(String(bag[k]));
    });
    return out;
  }
  function t(key, vars) {
    var k = String(key || "");
    if (!k) return "";
    var code = lang();
    var pack = PACKS[code] || EN;
    var s = (pack && pack[k]) || EN[k] || "";
    if (!s) return "";
    return fill(s, vars);
  }
  function paint() {
    var code = lang();
    var html = document.documentElement;
    if (classic()) {
      html.lang = "en";
      html.dir = "ltr";
    } else {
      html.lang = code === "simple" ? "en" : code;
      html.dir = code === "ar" || code === "fa-AF" ? "rtl" : "ltr";
    }
    document.querySelectorAll("[data-mu]").forEach(function (node) {
      var v = t(node.getAttribute("data-mu"));
      if (v) node.textContent = v;
    });
    document.querySelectorAll("[data-mu-html]").forEach(function (node) {
      var v = t(node.getAttribute("data-mu-html"));
      if (v && v.indexOf("<script") < 0) node.innerHTML = v;
    });
    document.querySelectorAll("[data-mu-label]").forEach(function (node) {
      var v = t(node.getAttribute("data-mu-label"));
      if (v) node.setAttribute("aria-label", v);
    });
    document.querySelectorAll("[data-mu-ph]").forEach(function (node) {
      var v = t(node.getAttribute("data-mu-ph"));
      if (v) node.setAttribute("placeholder", v);
    });
    var menu = document.querySelector("#menu-btn [data-i18n='menu']");
    if (menu) {
      var word = shared("menu", "Menu");
      if (word) menu.textContent = word;
    }
    var close = document.getElementById("menu-close");
    if (close) {
      var c = shared("close", "Close");
      if (c) close.textContent = c;
    }
    if (typeof root.MuPaintLive === "function") {
      try { root.MuPaintLive(); } catch (e) {}
    }
  }
  function boot() { paint(); }
  function whenShared(cb) {
    if (root.KulibertI18n && root.KulibertI18n.ready) {
      root.KulibertI18n.ready(lang(), cb);
      return;
    }
    var n = 0;
    var timer = setInterval(function () {
      n += 1;
      if (root.KulibertI18n && root.KulibertI18n.ready) {
        clearInterval(timer);
        root.KulibertI18n.ready(lang(), cb);
      } else if (n > 50) clearInterval(timer);
    }, 40);
  }
  root.addEventListener("kulibert-lang", function (ev) {
    var code = ev && ev.detail && ev.detail.lang;
    if (root.KulibertI18n && root.KulibertI18n.ready) root.KulibertI18n.ready(code || lang(), paint);
    else paint();
  });
  root.addEventListener("storage", function (ev) {
    if (!ev || ev.key !== "kulibert-prefs-v1") return;
    whenShared(paint);
  });
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
  whenShared(paint);
  root.MuI18n = { t: t, paint: paint, lang: lang, shared: shared, packs: PACKS };
})(typeof window !== "undefined" ? window : globalThis);
