/* BertyBeatz words. English is the fallback. Song note letters stay English.
   fa-AF is Dari, not Iranian Persian.
   NEEDS NATIVE CHECK: every fa-AF, rw, and ti line. */
(function (root) {
  var EN = {
    gateLede: "Tap squares. Make a song. Watch it become light.",
    tapStart: "Tap to start",
    gateHint: "Needs one tap so Chromebook sound can play.",
    techRoom: "Tech Room",
    menu: "Menu",
    whatsNew: "What's new",
    whats: "BertyBeatz speaks your Hub language. Menu is top-left, and Play and Stop have names.",
    score: "Score",
    beats: "Beats",
    lights: "Lights",
    band: "Band",
    play: "Play",
    pause: "Pause",
    stop: "Stop",
    soundOn: "Sound on",
    muted: "Muted",
    stepsA: "Steps 1–8",
    stepsB: "Steps 9–16",
    nowIdle: "Press Play. Watch the column. Sound can stay off.",
    nowPlay: "Playing. Watch the column.",
    soundOff: "Sound is off.",
    beat: "Beat",
    rest: "rest",
    how: "How",
    learn: "Learn",
    look: "Look",
    title: "Title",
    tempo: "Tempo",
    swing: "Swing",
    human: "Human",
    vol: "Vol",
    time: "Time",
    clickOn: "Click on",
    clickOff: "Click off",
    record: "Record",
    recording: "Recording",
    pattern: "Pattern",
    loop: "Loop",
    song: "Song",
    mixer: "Mixer",
    mixHint: "Each row is one sound. Off hides it. Solo keeps only the rows you mark. Soft and Bright change the color. The song saves itself.",
    kit: "Kit",
    surprise: "Surprise me",
    starter: "Starter beats",
    pass: "Pass",
    exportBtn: "Export",
    importBtn: "Import",
    save: "Save",
    myBeats: "My beats",
    clear: "Clear",
    undo: "Undo",
    kick: "Kick",
    snare: "Snare",
    hats: "Hats",
    clap: "Clap",
    studio: "Studio",
    arcade: "Arcade",
    dream: "Dream",
    boom: "Boom",
    bright: "Bright",
    moody: "Moody",
    bars: "Bars",
    kaleido: "Kaleidoscope",
    clouds: "Clouds",
    stars: "Stars",
    code: "Code",
    rings: "Rings",
    ripple: "Ripple",
    tiles: "Tiles",
    orbit: "Orbit",
    rain: "Rain",
    tunnel: "Tunnel",
    ribbon: "Ribbon",
    bloom: "Bloom",
    fireworks: "Fireworks",
    soft: "Soft",
    norm: "Norm",
    solo: "Solo",
    offWord: "off",
    bpm: "BPM",
    firstBeat: "First Beat",
    clapClass: "Clap Class",
    recess: "Recess",
    nightWalk: "Night Walk",
    lockerBoom: "Locker Boom",
    blankPage: "Blank page",
    classBeat: "Class beat",
    seeMove: "See it move",
    noNames: "no names",
    teacher: "Teacher",
    privacy: "Privacy",
    howTitle: "How it works",
    help2: "Tap a square to turn a sound on. Tap again to turn it off.",
    help3: "Press Play. The moving column is the beat walking across the grid.",
    help4: "Top rows are drums. Bottom rows are notes that always fit the key.",
    help5: "Look chips change the pictures — Bars, Kaleidoscope, Clouds, Stars, Code. Same beat, different lights. Mute is OK.",
    help6: "Pass copies a code — no names — so the next Chromebook can load the same beat.",
    helpFoot: "Space bar plays and stops. Keys 1–5 switch Looks. Tap a row name to hear that sound. Title only, never a student name.",
    lesBeatT: "The beat",
    lesBeatB: "Press Play. Count the word: Beat 1, Beat 2, Beat 3, Beat 4. That steady count is the beat. Sound can stay off.",
    lesBeatM: "Press Play, then watch the word.",
    lesStrongT: "The strong beat",
    lesStrongB: "Beat 1 is the strong beat. It is the one you tap your foot on. Wait until the word says Beat 1.",
    lesStrongM: "Keep it playing until the word says Beat 1.",
    lesPulseT: "The pulse",
    lesPulseB: "Light the first Kick square. A kick on beat 1 is the pulse. The other drums sit around it.",
    lesPulseM: "Tap the first Kick square so it turns on.",
    lesTimeT: "Time",
    lesTimeB: "4/4 means four beats, then it starts over. Tap 3/4. Count 1, 2, 3. The bottom rows are notes: C, D, E, G, and A.",
    lesTimeM: "Tap 3/4 in the Time row.",
    lesTempoT: "Tempo",
    lesTempoB: "Move Tempo. Faster or slower is the tempo. You still count the same beats. Tempo is speed. Time is how many beats.",
    lesTempoM: "Move the Tempo slider.",
    gotIt: "Got it.",
    iDid: "I did this",
    done: "Done",
    skip: "Skip",
    lesson: "Lesson",
    of: "of",
    close: "Close",
    saveBeat: "Save beat"
  };

  var UK = {
    gateLede: "Торкайся квадратів. Зроби пісню. Дивись, як вона стає світлом.",
    tapStart: "Торкнись, щоб почати",
    gateHint: "Потрібен один дотик, щоб звук Chromebook заграв.",
    techRoom: "Техкімната",
    menu: "Меню",
    whatsNew: "Що нового",
    whats: "BertyBeatz говорить мовою Хаба. Меню зліва зверху, а в Грати і Стоп є назви.",
    score: "Ноти",
    beats: "Біти",
    lights: "Світло",
    band: "Гурт",
    play: "Грати",
    pause: "Пауза",
    stop: "Стоп",
    soundOn: "Звук є",
    muted: "Без звуку",
    stepsA: "Кроки 1–8",
    stepsB: "Кроки 9–16",
    nowIdle: "Натисни Грати. Дивись на стовпчик. Звук може бути вимкнений.",
    nowPlay: "Грає. Дивись на стовпчик.",
    soundOff: "Звук вимкнено.",
    beat: "Біт",
    rest: "тиша",
    how: "Як",
    learn: "Вчитись",
    look: "Вигляд",
    title: "Назва",
    tempo: "Темп",
    swing: "Свінг",
    human: "Живо",
    vol: "Гучність",
    time: "Розмір",
    clickOn: "Клік є",
    clickOff: "Клік вимкнено",
    record: "Запис",
    recording: "Записую",
    pattern: "Фраза",
    loop: "Петля",
    song: "Пісня",
    mixer: "Мікшер",
    mixHint: "Кожен рядок — один звук. Вимкнено ховає його. Соло лишає лише позначені рядки. М’яко і Яскраво змінюють колір. Пісня зберігається сама.",
    kit: "Набір",
    surprise: "Здивуй мене",
    starter: "Готові біти",
    pass: "Передай",
    exportBtn: "Експорт",
    importBtn: "Імпорт",
    save: "Зберегти",
    myBeats: "Мої біти",
    clear: "Очистити",
    undo: "Скасувати",
    kick: "Кік",
    snare: "Малий",
    hats: "Хети",
    clap: "Оплеск",
    studio: "Студія",
    arcade: "Аркада",
    dream: "Сон",
    boom: "Бум",
    bright: "Яскраво",
    moody: "Темно",
    bars: "Смуги",
    kaleido: "Калейдоскоп",
    clouds: "Хмари",
    stars: "Зорі",
    code: "Код",
    rings: "Кільця",
    ripple: "Кола",
    tiles: "Плитки",
    orbit: "Орбіта",
    rain: "Дощ",
    tunnel: "Тунель",
    ribbon: "Стрічка",
    bloom: "Квітка",
    fireworks: "Феєрверк",
    soft: "М’яко",
    norm: "Звично",
    solo: "Соло",
    offWord: "вимк",
    bpm: "BPM",
    firstBeat: "Перший біт",
    clapClass: "Клас оплесків",
    recess: "Перерва",
    nightWalk: "Нічна хода",
    lockerBoom: "Шафка бум",
    blankPage: "Порожня сторінка",
    classBeat: "Класний біт",
    seeMove: "Дивись, як рухається",
    noNames: "без імен",
    teacher: "Учитель",
    privacy: "Приватність",
    howTitle: "Як це працює",
    help2: "Торкнись квадрата, щоб увімкнути звук. Торкнись ще раз, щоб вимкнути.",
    help3: "Натисни Грати. Стовпчик, що рухається, — це біт, який іде по сітці.",
    help4: "Верхні рядки — барабани. Нижні — ноти, які завжди пасують до тональності.",
    help5: "Чіпи Вигляд змінюють картинки — Смуги, Калейдоскоп, Хмари, Зорі, Код. Той самий біт, інше світло. Без звуку теж можна.",
    help6: "Передай копіює код — без імен — щоб наступний Chromebook відкрив той самий біт.",
    helpFoot: "Пробіл грає і зупиняє. Клавіші 1–5 змінюють Вигляд. Торкнись назви рядка, щоб почути звук. Лише назва, ніколи ім’я учня.",
    lesBeatT: "Біт",
    lesBeatB: "Натисни Грати. Рахуй слово: Біт 1, Біт 2, Біт 3, Біт 4. Цей рівний рахунок і є біт. Звук може бути вимкнений.",
    lesBeatM: "Натисни Грати, потім дивись на слово.",
    lesStrongT: "Сильний біт",
    lesStrongB: "Біт 1 — сильний біт. На ньому ти тупаєш ногою. Чекай, поки слово скаже Біт 1.",
    lesStrongM: "Нехай грає, поки слово не скаже Біт 1.",
    lesPulseT: "Пульс",
    lesPulseB: "Засвіти перший квадрат Кік. Кік на біті 1 — це пульс. Інші барабани навколо нього.",
    lesPulseM: "Торкнись першого квадрата Кік, щоб він увімкнувся.",
    lesTimeT: "Розмір",
    lesTimeB: "4/4 означає чотири біти, потім знову. Торкнись 3/4. Рахуй 1, 2, 3. Нижні рядки — ноти: C, D, E, G і A.",
    lesTimeM: "Торкнись 3/4 у рядку Розмір.",
    lesTempoT: "Темп",
    lesTempoB: "Посунь Темп. Швидше чи повільніше — це темп. Біти ті самі. Темп — це швидкість. Розмір — скільки бітів.",
    lesTempoM: "Посунь повзунок Темп.",
    gotIt: "Вийшло.",
    iDid: "Я це зробив",
    done: "Готово",
    skip: "Пропустити",
    lesson: "Урок",
    of: "з",
    close: "Закрити",
    saveBeat: "Зберегти біт"
  };

  var RU = {
    gateLede: "Нажимай квадраты. Сделай песню. Смотри, как она становится светом.",
    tapStart: "Нажми, чтобы начать",
    gateHint: "Нужно одно нажатие, чтобы звук Chromebook заиграл.",
    techRoom: "Техкомната",
    menu: "Меню",
    whatsNew: "Что нового",
    whats: "BertyBeatz говорит на языке Хаба. Меню слева сверху, а у Играть и Стоп есть названия.",
    score: "Ноты",
    beats: "Биты",
    lights: "Свет",
    band: "Группа",
    play: "Играть",
    pause: "Пауза",
    stop: "Стоп",
    soundOn: "Звук есть",
    muted: "Без звука",
    stepsA: "Шаги 1–8",
    stepsB: "Шаги 9–16",
    nowIdle: "Нажми Играть. Смотри на столбик. Звук можно не включать.",
    nowPlay: "Играет. Смотри на столбик.",
    soundOff: "Звук выключен.",
    beat: "Бит",
    rest: "тишина",
    how: "Как",
    learn: "Учить",
    look: "Вид",
    title: "Название",
    tempo: "Темп",
    swing: "Свинг",
    human: "Живо",
    vol: "Громкость",
    time: "Размер",
    clickOn: "Клик есть",
    clickOff: "Клик выключен",
    record: "Запись",
    recording: "Записываю",
    pattern: "Фраза",
    loop: "Петля",
    song: "Песня",
    mixer: "Микшер",
    mixHint: "Каждая строка — один звук. Выкл прячет его. Соло оставляет только отмеченные строки. Мягко и Ярко меняют цвет. Песня сохраняется сама.",
    kit: "Набор",
    surprise: "Удиви меня",
    starter: "Готовые биты",
    pass: "Передай",
    exportBtn: "Экспорт",
    importBtn: "Импорт",
    save: "Сохранить",
    myBeats: "Мои биты",
    clear: "Очистить",
    undo: "Отменить",
    kick: "Кик",
    snare: "Малый",
    hats: "Хэты",
    clap: "Хлопок",
    studio: "Студия",
    arcade: "Аркада",
    dream: "Сон",
    boom: "Бум",
    bright: "Ярко",
    moody: "Темно",
    bars: "Полосы",
    kaleido: "Калейдоскоп",
    clouds: "Облака",
    stars: "Звёзды",
    code: "Код",
    rings: "Кольца",
    ripple: "Круги",
    tiles: "Плитки",
    orbit: "Орбита",
    rain: "Дождь",
    tunnel: "Тоннель",
    ribbon: "Лента",
    bloom: "Цветок",
    fireworks: "Салют",
    soft: "Мягко",
    norm: "Обычно",
    solo: "Соло",
    offWord: "выкл",
    bpm: "BPM",
    firstBeat: "Первый бит",
    clapClass: "Класс хлопков",
    recess: "Перемена",
    nightWalk: "Ночная прогулка",
    lockerBoom: "Шкафчик бум",
    blankPage: "Пустая страница",
    classBeat: "Классный бит",
    seeMove: "Смотри, как движется",
    noNames: "без имён",
    teacher: "Учитель",
    privacy: "Приватность",
    howTitle: "Как это работает",
    help2: "Нажми квадрат, чтобы включить звук. Нажми ещё раз, чтобы выключить.",
    help3: "Нажми Играть. Движущийся столбик — это бит, который идёт по сетке.",
    help4: "Верхние строки — барабаны. Нижние — ноты, которые всегда подходят к тональности.",
    help5: "Чипы Вид меняют картинки — Полосы, Калейдоскоп, Облака, Звёзды, Код. Тот же бит, другой свет. Без звука тоже можно.",
    help6: "Передай копирует код — без имён — чтобы следующий Chromebook открыл тот же бит.",
    helpFoot: "Пробел играет и останавливает. Клавиши 1–5 меняют Вид. Нажми имя строки, чтобы услышать звук. Только название, никогда имя ученика.",
    lesBeatT: "Бит",
    lesBeatB: "Нажми Играть. Считай слово: Бит 1, Бит 2, Бит 3, Бит 4. Этот ровный счёт и есть бит. Звук можно не включать.",
    lesBeatM: "Нажми Играть, потом смотри на слово.",
    lesStrongT: "Сильный бит",
    lesStrongB: "Бит 1 — сильный бит. На нём ты топаешь ногой. Жди, пока слово скажет Бит 1.",
    lesStrongM: "Пусть играет, пока слово не скажет Бит 1.",
    lesPulseT: "Пульс",
    lesPulseB: "Зажги первый квадрат Кик. Кик на бите 1 — это пульс. Остальные барабаны вокруг него.",
    lesPulseM: "Нажми первый квадрат Кик, чтобы он включился.",
    lesTimeT: "Размер",
    lesTimeB: "4/4 значит четыре бита, потом сначала. Нажми 3/4. Считай 1, 2, 3. Нижние строки — ноты: C, D, E, G и A.",
    lesTimeM: "Нажми 3/4 в строке Размер.",
    lesTempoT: "Темп",
    lesTempoB: "Двигай Темп. Быстрее или медленнее — это темп. Биты те же. Темп — это скорость. Размер — сколько битов.",
    lesTempoM: "Двигай ползунок Темп.",
    gotIt: "Получилось.",
    iDid: "Я это сделал",
    done: "Готово",
    skip: "Пропустить",
    lesson: "Урок",
    of: "из",
    close: "Закрыть",
    saveBeat: "Сохранить бит"
  };

  var ES = {
    gateLede: "Toca cuadrados. Haz una canción. Mira cómo se vuelve luz.",
    tapStart: "Toca para empezar",
    gateHint: "Hace falta un toque para que el sonido del Chromebook suene.",
    techRoom: "Sala tec",
    menu: "Menú",
    whatsNew: "Novedades",
    whats: "BertyBeatz habla el idioma del Hub. El menú está arriba a la izquierda, y Tocar y Parar tienen nombre.",
    score: "Partitura",
    beats: "Ritmos",
    lights: "Luces",
    band: "Banda",
    play: "Tocar",
    pause: "Pausa",
    stop: "Parar",
    soundOn: "Sonido sí",
    muted: "Sin sonido",
    stepsA: "Pasos 1–8",
    stepsB: "Pasos 9–16",
    nowIdle: "Pulsa Tocar. Mira la columna. El sonido puede quedar apagado.",
    nowPlay: "Sonando. Mira la columna.",
    soundOff: "El sonido está apagado.",
    beat: "Pulso",
    rest: "silencio",
    how: "Cómo",
    learn: "Aprender",
    look: "Aspecto",
    title: "Título",
    tempo: "Tempo",
    swing: "Swing",
    human: "Humano",
    vol: "Vol",
    time: "Compás",
    clickOn: "Clic sí",
    clickOff: "Clic no",
    record: "Grabar",
    recording: "Grabando",
    pattern: "Frase",
    loop: "Bucle",
    song: "Canción",
    mixer: "Mezcla",
    mixHint: "Cada fila es un sonido. Apagado lo esconde. Solo deja solo las filas que marcas. Suave y Brillante cambian el color. La canción se guarda sola.",
    kit: "Kit",
    surprise: "Sorpréndeme",
    starter: "Ritmos listos",
    pass: "Pasar",
    exportBtn: "Exportar",
    importBtn: "Importar",
    save: "Guardar",
    myBeats: "Mis ritmos",
    clear: "Borrar",
    undo: "Deshacer",
    kick: "Bombo",
    snare: "Caja",
    hats: "Charles",
    clap: "Palmas",
    studio: "Estudio",
    arcade: "Arcade",
    dream: "Sueño",
    boom: "Boom",
    bright: "Brillante",
    moody: "Oscuro",
    bars: "Barras",
    kaleido: "Caleidoscopio",
    clouds: "Nubes",
    stars: "Estrellas",
    code: "Código",
    rings: "Anillos",
    ripple: "Ondas",
    tiles: "Baldosas",
    orbit: "Órbita",
    rain: "Lluvia",
    tunnel: "Túnel",
    ribbon: "Cinta",
    bloom: "Flor",
    fireworks: "Fuegos",
    soft: "Suave",
    norm: "Normal",
    solo: "Solo",
    offWord: "apagado",
    bpm: "BPM",
    firstBeat: "Primer ritmo",
    clapClass: "Clase de palmas",
    recess: "Recreo",
    nightWalk: "Paseo de noche",
    lockerBoom: "Taquilla boom",
    blankPage: "Página en blanco",
    classBeat: "Ritmo de clase",
    seeMove: "Míralo moverse",
    noNames: "sin nombres",
    teacher: "Profe",
    privacy: "Privacidad",
    howTitle: "Cómo funciona",
    help2: "Toca un cuadrado para encender un sonido. Tócalo otra vez para apagarlo.",
    help3: "Pulsa Tocar. La columna que se mueve es el pulso caminando por la rejilla.",
    help4: "Las filas de arriba son tambores. Las de abajo son notas que siempre caben en la tonalidad.",
    help5: "Los chips de Aspecto cambian las imágenes — Barras, Caleidoscopio, Nubes, Estrellas, Código. El mismo ritmo, otras luces. Sin sonido también vale.",
    help6: "Pasar copia un código — sin nombres — para que el siguiente Chromebook abra el mismo ritmo.",
    helpFoot: "La barra espaciadora toca y para. Las teclas 1–5 cambian el Aspecto. Toca el nombre de una fila para oír ese sonido. Solo un título, nunca el nombre de un alumno.",
    lesBeatT: "El pulso",
    lesBeatB: "Pulsa Tocar. Cuenta la palabra: Pulso 1, Pulso 2, Pulso 3, Pulso 4. Esa cuenta fija es el pulso. El sonido puede quedar apagado.",
    lesBeatM: "Pulsa Tocar y mira la palabra.",
    lesStrongT: "El pulso fuerte",
    lesStrongB: "El pulso 1 es el fuerte. Es el que marcas con el pie. Espera a que la palabra diga Pulso 1.",
    lesStrongM: "Déjalo sonar hasta que la palabra diga Pulso 1.",
    lesPulseT: "El latido",
    lesPulseB: "Enciende el primer cuadrado de Bombo. Un bombo en el pulso 1 es el latido. Los otros tambores van alrededor.",
    lesPulseM: "Toca el primer cuadrado de Bombo para encenderlo.",
    lesTimeT: "Compás",
    lesTimeB: "4/4 son cuatro pulsos y vuelve a empezar. Toca 3/4. Cuenta 1, 2, 3. Las filas de abajo son notas: C, D, E, G y A.",
    lesTimeM: "Toca 3/4 en la fila Compás.",
    lesTempoT: "Tempo",
    lesTempoB: "Mueve Tempo. Más rápido o más lento es el tempo. Cuentas los mismos pulsos. Tempo es la velocidad. Compás es cuántos pulsos.",
    lesTempoM: "Mueve el control de Tempo.",
    gotIt: "Listo.",
    iDid: "Ya lo hice",
    done: "Hecho",
    skip: "Saltar",
    lesson: "Lección",
    of: "de",
    close: "Cerrar",
    saveBeat: "Guardar ritmo"
  };

  var AR = {
    gateLede: "المس المربعات. اصنع أغنية. شاهدها تصبح ضوءًا.",
    tapStart: "المس للبدء",
    gateHint: "يلزم لمسة واحدة حتى يعمل صوت Chromebook.",
    techRoom: "غرفة التقنية",
    menu: "القائمة",
    whatsNew: "ما الجديد",
    whats: "BertyBeatz يتكلم لغة المركز. القائمة أعلى اليسار، وتشغيل وإيقاف لهما اسم.",
    score: "النوتة",
    beats: "الإيقاعات",
    lights: "الأضواء",
    band: "الفرقة",
    play: "تشغيل",
    pause: "إيقاف مؤقت",
    stop: "إيقاف",
    soundOn: "الصوت يعمل",
    muted: "بلا صوت",
    stepsA: "خطوات ١–٨",
    stepsB: "خطوات ٩–١٦",
    nowIdle: "اضغط تشغيل. راقب العمود. يمكن أن يبقى الصوت مغلقًا.",
    nowPlay: "يعمل الآن. راقب العمود.",
    soundOff: "الصوت مغلق.",
    beat: "ضربة",
    rest: "صمت",
    how: "كيف",
    learn: "تعلّم",
    look: "المظهر",
    title: "العنوان",
    tempo: "السرعة",
    swing: "التأرجح",
    human: "بشري",
    vol: "الصوت",
    time: "الميزان",
    clickOn: "النقرة تعمل",
    clickOff: "النقرة متوقفة",
    record: "تسجيل",
    recording: "يسجّل",
    pattern: "جملة",
    loop: "حلقة",
    song: "أغنية",
    mixer: "المازج",
    mixHint: "كل صف صوت واحد. الإيقاف يخفيه. المنفرد يُبقي الصفوف التي تحددها فقط. ناعم وساطع يغيّران اللون. الأغنية تحفظ نفسها.",
    kit: "الطقم",
    surprise: "فاجئني",
    starter: "إيقاعات جاهزة",
    pass: "مرّر",
    exportBtn: "تصدير",
    importBtn: "استيراد",
    save: "حفظ",
    myBeats: "إيقاعاتي",
    clear: "مسح",
    undo: "تراجع",
    kick: "طبلة",
    snare: "صغيرة",
    hats: "صحون",
    clap: "تصفيق",
    studio: "استوديو",
    arcade: "أركيد",
    dream: "حلم",
    boom: "دوي",
    bright: "ساطع",
    moody: "داكن",
    bars: "أعمدة",
    kaleido: "مشكال",
    clouds: "غيوم",
    stars: "نجوم",
    code: "رمز",
    rings: "حلقات",
    ripple: "تموّج",
    tiles: "بلاط",
    orbit: "مدار",
    rain: "مطر",
    tunnel: "نفق",
    ribbon: "شريط",
    bloom: "زهرة",
    fireworks: "ألعاب نارية",
    soft: "ناعم",
    norm: "عادي",
    solo: "منفرد",
    offWord: "متوقف",
    bpm: "BPM",
    firstBeat: "أول إيقاع",
    clapClass: "صف التصفيق",
    recess: "الاستراحة",
    nightWalk: "مشي الليل",
    lockerBoom: "الخزانة تدوي",
    blankPage: "صفحة فارغة",
    classBeat: "إيقاع الصف",
    seeMove: "شاهده يتحرك",
    noNames: "بلا أسماء",
    teacher: "المعلم",
    privacy: "الخصوصية",
    howTitle: "كيف يعمل",
    help2: "المس مربعًا لتشغيل صوت. المس مرة أخرى لإيقافه.",
    help3: "اضغط تشغيل. العمود المتحرك هو الضربة تمشي على الشبكة.",
    help4: "الصفوف العليا طبول. الصفوف السفلى نوتات تناسب السلم دائمًا.",
    help5: "رقائق المظهر تغيّر الصور — أعمدة، مشكال، غيوم، نجوم، رمز. نفس الإيقاع، أضواء مختلفة. بلا صوت ممكن.",
    help6: "مرّر ينسخ رمزًا — بلا أسماء — حتى يفتح Chromebook التالي نفس الإيقاع.",
    helpFoot: "مسطرة المسافة تشغّل وتوقف. المفاتيح ١–٥ تبدّل المظهر. المس اسم الصف لتسمع الصوت. عنوان فقط، وليس اسم طالب.",
    lesBeatT: "الضربة",
    lesBeatB: "اضغط تشغيل. عدّ الكلمة: ضربة ١، ضربة ٢، ضربة ٣، ضربة ٤. هذا العدّ الثابت هو الضربة. يمكن أن يبقى الصوت مغلقًا.",
    lesBeatM: "اضغط تشغيل ثم راقب الكلمة.",
    lesStrongT: "الضربة القوية",
    lesStrongB: "ضربة ١ هي الضربة القوية. هي التي تطأ عليها بقدمك. انتظر حتى تقول الكلمة ضربة ١.",
    lesStrongM: "اتركه يعمل حتى تقول الكلمة ضربة ١.",
    lesPulseT: "النبض",
    lesPulseB: "أضئ أول مربع طبلة. طبلة على الضربة ١ هي النبض. الطبول الأخرى حولها.",
    lesPulseM: "المس أول مربع طبلة حتى يضيء.",
    lesTimeT: "الميزان",
    lesTimeB: "٤/٤ يعني أربع ضربات ثم يبدأ من جديد. المس ٣/٤. عدّ ١، ٢، ٣. الصفوف السفلى نوتات: C و D و E و G و A.",
    lesTimeM: "المس ٣/٤ في صف الميزان.",
    lesTempoT: "السرعة",
    lesTempoB: "حرّك السرعة. أسرع أو أبطأ هي السرعة. تعدّ نفس الضربات. السرعة هي الإيقاع الزمني. الميزان هو عدد الضربات.",
    lesTempoM: "حرّك شريط السرعة.",
    gotIt: "تم.",
    iDid: "فعلت هذا",
    done: "انتهى",
    skip: "تخطَّ",
    lesson: "درس",
    of: "من",
    close: "إغلاق",
    saveBeat: "حفظ الإيقاع"
  };

  var FA = {
    gateLede: "مربع‌ها را بزن. یک آهنگ بساز. ببین که نور می‌شود.",
    tapStart: "بزن تا شروع شود",
    gateHint: "یک لمس لازم است تا صدای Chromebook بیاید.",
    techRoom: "اتاق تخنیک",
    menu: "فهرست",
    whatsNew: "تازه‌ها",
    whats: "BertyBeatz به زبان هاب حرف می‌زند. فهرست بالا چپ است، و پخش و ایست نام دارند.",
    score: "نوت",
    beats: "ضرب‌ها",
    lights: "چراغ‌ها",
    band: "گروه",
    play: "پخش",
    pause: "مکث",
    stop: "ایست",
    soundOn: "صدا روشن",
    muted: "بی‌صدا",
    stepsA: "گام ۱–۸",
    stepsB: "گام ۹–۱۶",
    nowIdle: "پخش را بزن. ستون را ببین. صدا می‌تواند خاموش بماند.",
    nowPlay: "در حال پخش. ستون را ببین.",
    soundOff: "صدا خاموش است.",
    beat: "ضرب",
    rest: "سکوت",
    how: "چگونه",
    learn: "بیاموز",
    look: "نما",
    title: "عنوان",
    tempo: "تمپو",
    swing: "سویینگ",
    human: "زنده",
    vol: "بلندی",
    time: "میزان",
    clickOn: "کلیک روشن",
    clickOff: "کلیک خاموش",
    record: "ضبط",
    recording: "در حال ضبط",
    pattern: "جمله",
    loop: "حلقه",
    song: "آهنگ",
    mixer: "میکسر",
    mixHint: "هر ردیف یک صدا است. خاموش آن را پنهان می‌کند. تک فقط ردیف‌های نشان‌شده را نگه می‌دارد. نرم و روشن رنگ را عوض می‌کنند. آهنگ خودش ذخیره می‌شود.",
    kit: "ست",
    surprise: "سوپرایزم کن",
    starter: "ضرب‌های آماده",
    pass: "بفرست",
    exportBtn: "خروجی",
    importBtn: "ورودی",
    save: "ذخیره",
    myBeats: "ضرب‌های من",
    clear: "پاک",
    undo: "برگشت",
    kick: "کیک",
    snare: "سنیر",
    hats: "هت",
    clap: "کف",
    studio: "استودیو",
    arcade: "آرکید",
    dream: "خواب",
    boom: "بوم",
    bright: "روشن",
    moody: "تیره",
    bars: "میله‌ها",
    kaleido: "کالیدوسکوپ",
    clouds: "ابرها",
    stars: "ستاره‌ها",
    code: "کود",
    rings: "حلقه‌ها",
    ripple: "موج",
    tiles: "کاشی",
    orbit: "مدار",
    rain: "باران",
    tunnel: "تونل",
    ribbon: "نوار",
    bloom: "گل",
    fireworks: "آتش‌بازی",
    soft: "نرم",
    norm: "عادی",
    solo: "تک",
    offWord: "خاموش",
    bpm: "BPM",
    firstBeat: "ضرب اول",
    clapClass: "صنف کف",
    recess: "وقفه",
    nightWalk: "راه شب",
    lockerBoom: "الماری بوم",
    blankPage: "صفحه خالی",
    classBeat: "ضرب صنف",
    seeMove: "ببین که می‌جنبد",
    noNames: "بدون نام",
    teacher: "معلم",
    privacy: "محرمیت",
    howTitle: "چطور کار می‌کند",
    help2: "یک مربع را بزن تا صدا روشن شود. دوباره بزن تا خاموش شود.",
    help3: "پخش را بزن. ستون روان همان ضرب است که روی شبکه راه می‌رود.",
    help4: "ردیف‌های بالا طبل است. ردیف‌های پایین نوت‌هایی است که همیشه با گام می‌خواند.",
    help5: "دکمه‌های نما تصویر را عوض می‌کنند — میله‌ها، کالیدوسکوپ، ابرها، ستاره‌ها، کود. همان ضرب، چراغ دیگر. بی‌صدا هم درست است.",
    help6: "بفرست یک کود را کپی می‌کند — بدون نام — تا Chromebook بعدی همان ضرب را باز کند.",
    helpFoot: "کلید فاصله پخش و ایست می‌کند. کلیدهای ۱–۵ نما را عوض می‌کنند. نام ردیف را بزن تا آن صدا را بشنوی. فقط عنوان، هرگز نام شاگرد.",
    lesBeatT: "ضرب",
    lesBeatB: "پخش را بزن. کلمه را بشمار: ضرب ۱، ضرب ۲، ضرب ۳، ضرب ۴. این شمار ثابت همان ضرب است. صدا می‌تواند خاموش بماند.",
    lesBeatM: "پخش را بزن، بعد کلمه را ببین.",
    lesStrongT: "ضرب قوی",
    lesStrongB: "ضرب ۱ ضرب قوی است. همان است که با پا می‌زنی. صبر کن تا کلمه بگوید ضرب ۱.",
    lesStrongM: "بگذار پخش شود تا کلمه بگوید ضرب ۱.",
    lesPulseT: "نبض",
    lesPulseB: "مربع اول کیک را روشن کن. کیک روی ضرب ۱ نبض است. طبل‌های دیگر دور آن‌اند.",
    lesPulseM: "مربع اول کیک را بزن تا روشن شود.",
    lesTimeT: "میزان",
    lesTimeB: "۴/۴ یعنی چهار ضرب، بعد از نو. ۳/۴ را بزن. بشمار ۱، ۲، ۳. ردیف‌های پایین نوت است: C و D و E و G و A.",
    lesTimeM: "۳/۴ را در ردیف میزان بزن.",
    lesTempoT: "تمپو",
    lesTempoB: "تمپو را بجنبان. تیزتر یا آهسته‌تر تمپو است. همان ضرب‌ها را می‌شماری. تمپو سرعت است. میزان تعداد ضرب است.",
    lesTempoM: "لغزنده تمپو را بجنبان.",
    gotIt: "شد.",
    iDid: "این کار را کردم",
    done: "تمام",
    skip: "رد شو",
    lesson: "درس",
    of: "از",
    close: "بستن",
    saveBeat: "ذخیره ضرب"
  };

  var RW = {
    gateLede: "Kanda udukaro. Kora indirimbo. Reba uko ihinduka urumuri.",
    tapStart: "Kanda utangire",
    gateHint: "Ukeneye gukanda rimwe kugira ngo ijwi rya Chromebook ritangire.",
    techRoom: "Icyumba cya tekinike",
    menu: "Menyu",
    whatsNew: "Ibishya",
    whats: "BertyBeatz ivuga ururimi rwa Hub. Menyu iri hejuru ibumoso, na Kina na Hagarara bifite amazina.",
    score: "Inota",
    beats: "Imbyino",
    lights: "Amatara",
    band: "Itsinda",
    play: "Kina",
    pause: "Hagarika gato",
    stop: "Hagarara",
    soundOn: "Ijwi rirakora",
    muted: "Nta jwi",
    stepsA: "Intambwe 1–8",
    stepsB: "Intambwe 9–16",
    nowIdle: "Kanda Kina. Reba inkingi. Ijwi rishobora kuguma ritariho.",
    nowPlay: "Birakina. Reba inkingi.",
    soundOff: "Ijwi rirafunze.",
    beat: "Imbyino",
    rest: "icuze",
    how: "Uko",
    learn: "Wige",
    look: "Isura",
    title: "Umutwe",
    tempo: "Umuvuduko",
    swing: "Kunyeganyega",
    human: "Umuntu",
    vol: "Ubwirangire",
    time: "Igihe",
    clickOn: "Kanda birakora",
    clickOff: "Kanda birahagarara",
    record: "Fata",
    recording: "Ndafata",
    pattern: "Interuro",
    loop: "Uruziga",
    song: "Indirimbo",
    mixer: "Kuvanga",
    mixHint: "Umurongo wose ni ijwi rimwe. Kuzimya kurabisha. Solo isigaza imirongo wagaragaje gusa. Byoroshye na Byumye bihindura ibara. Indirimbo ibika ubwayo.",
    kit: "Agasanduku",
    surprise: "Ntangaze",
    starter: "Imbyino ziteguye",
    pass: "Ohereza",
    exportBtn: "Sohora",
    importBtn: "Injiza",
    save: "Bika",
    myBeats: "Imbyino zanjye",
    clear: "Siba",
    undo: "Subiza",
    kick: "Ingoma",
    snare: "Ntoya",
    hats: "Insahuro",
    clap: "Amashyi",
    studio: "Sitidiyo",
    arcade: "Arukade",
    dream: "Inzozi",
    boom: "Bumu",
    bright: "Byumye",
    moody: "Byijimye",
    bars: "Imirongo",
    kaleido: "Kaleyidoskope",
    clouds: "Ibicu",
    stars: "Inyenyeri",
    code: "Kode",
    rings: "Impeta",
    ripple: "Amakuzimu",
    tiles: "Amakaro",
    orbit: "Orubite",
    rain: "Imvura",
    tunnel: "Umuhunda",
    ribbon: "Iriba",
    bloom: "Ururabo",
    fireworks: "Imisanzu",
    soft: "Byoroshye",
    norm: "Bisanzwe",
    solo: "Solo",
    offWord: "kuzima",
    bpm: "BPM",
    firstBeat: "Imbyino ya mbere",
    clapClass: "Ishuri ry'amashyi",
    recess: "Ikiruhuko",
    nightWalk: "Kugenda nijoro",
    lockerBoom: "Agasanduku ka bum",
    blankPage: "Urupapuro rwisanzuye",
    classBeat: "Imbyino y'ishuri",
    seeMove: "Reba uko bigenda",
    noNames: "nta mazina",
    teacher: "Mwarimu",
    privacy: "Ibanga",
    howTitle: "Uko bikora",
    help2: "Kanda agakaro kugira ngo ijwi rizime. Ongera ukande ukarizimya.",
    help3: "Kanda Kina. Inkingi igenda ni imbyino yenda ku rubuga.",
    help4: "Imirongo yo hejuru ni ingoma. Iyo hasi ni inota zihura n'urufunguzo.",
    help5: "Utudomo tw'isura duhindura amashusho — Imirongo, Kaleyidoskope, Ibicu, Inyenyeri, Kode. Imbyino imwe, amatara atandukanye. Nta jwi birakunda.",
    help6: "Ohereza ikoporora kode — nta mazina — kugira ngo Chromebook ikurikira ifungure imbyino imwe.",
    helpFoot: "Umubare wo hagati ukina kandi uhagarara. Utubuto 1–5 bihindura Isura. Kanda izina ry'umurongo wumve ijwi. Umutwe gusa, nta zina ry'umunyeshuri.",
    lesBeatT: "Imbyino",
    lesBeatB: "Kanda Kina. Bara ijambo: Imbyino 1, Imbyino 2, Imbyino 3, Imbyino 4. Iyo mibare ihoraho ni imbyino. Ijwi rishobora kuguma ritariho.",
    lesBeatM: "Kanda Kina, hanyuma urebe ijambo.",
    lesStrongT: "Imbyino ikomeye",
    lesStrongB: "Imbyino 1 ni ikomeye. Niyo ukanda ukuguru. Tegereza ijambo rivuge Imbyino 1.",
    lesStrongM: "Reka bikine kugeza ijambo rivuga Imbyino 1.",
    lesPulseT: "Umugogo",
    lesPulseB: "Kingurira agakaro ka mbere k'Ingoma. Ingoma ku mbyino 1 ni umugogo. Izindi ngoma zikikije.",
    lesPulseM: "Kanda agakaro ka mbere k'Ingoma kugira ngo kizime.",
    lesTimeT: "Igihe",
    lesTimeB: "4/4 ni imbyino enye, hanyuma bitangira. Kanda 3/4. Bara 1, 2, 3. Imirongo yo hasi ni inota: C, D, E, G, na A.",
    lesTimeM: "Kanda 3/4 mu murongo w'Igihe.",
    lesTempoT: "Umuvuduko",
    lesTempoB: "Imura Umuvuduko. Byihuse cyangwa gahoro ni umuvuduko. Uhora ubara imbyino zimwe. Umuvuduko ni isuri. Igihe ni ingano y'imbyino.",
    lesTempoM: "Imura agafashwe k'Umuvuduko.",
    gotIt: "Byakunze.",
    iDid: "Nabikoze",
    done: "Byarangiye",
    skip: "Simbuka",
    lesson: "Isomo",
    of: "muri",
    close: "Funga",
    saveBeat: "Bika imbyino"
  };

  var TI = {
    gateLede: "ኣርባዕቲ ጠውቕ። ደርፊ ስራሕ። ብርሃን ከም ዝኸውን ርአ።",
    tapStart: "ንምጅማር ጠውቕ",
    gateHint: "ድምጺ Chromebook ንኽጻወት ሓንሳእ ምጥዋቕ የድሊ።",
    techRoom: "ክፍሊ ቴክኒክ",
    menu: "ዝርዝር",
    whatsNew: "እንታይ ሓድሽ ኣሎ",
    whats: "BertyBeatz ብቋንቋ ሃብ ትዛረብ። ዝርዝር ኣብ ላዕሊ ጸጋም እዩ፣ ኣጻውትን ደውን ስም ኣለዎም።",
    score: "ኖታ",
    beats: "ድቕድቕታት",
    lights: "መብራህቲ",
    band: "ጉጅለ",
    play: "ኣጻውት",
    pause: "ደው ኣብል",
    stop: "ደው",
    soundOn: "ድምጺ ተወሊዑ",
    muted: "ዘይድምጺ",
    stepsA: "ደረጃ 1–8",
    stepsB: "ደረጃ 9–16",
    nowIdle: "ኣጻውት ጠውቕ። ነቲ ዓምዲ ርአ። ድምጺ ክጠፍእ ይኽእል።",
    nowPlay: "ይጻወት ኣሎ። ነቲ ዓምዲ ርአ።",
    soundOff: "ድምጺ ጠፊኡ።",
    beat: "ድቕድቕ",
    rest: "ስቕታ",
    how: "ከመይ",
    learn: "ተማሃር",
    look: "ትርኢት",
    title: "ኣርእስቲ",
    tempo: "ፍጥነት",
    swing: "ምንቅጥቃጥ",
    human: "ሰብኣዊ",
    vol: "ዓቐን",
    time: "ግዜ",
    clickOn: "ጠውቃ ይሰርሕ",
    clickOff: "ጠውቃ ደው",
    record: "ቕረጽ",
    recording: "ይቕረጽ ኣሎ",
    pattern: "ሓረግ",
    loop: "ዓንኬል",
    song: "ደርፊ",
    mixer: "መሓወሲ",
    mixHint: "ነፍሲ ወከፍ መስመር ሓደ ድምጺ እዩ። ምጥፋእ ይሕብኦ። ሶሎ እቶም ዝመረጽካዮም መስመራት ጥራይ ይገድፍ። ልስሉስን ብርሃንን ሕብሪ ይቕይሩ። እታ ደርፊ ባዕላ ትዕቀብ።",
    kit: "ኪት",
    surprise: "ኣገርመኒ",
    starter: "ድቕድቕታት ድሉዋት",
    pass: "ኣሕልፍ",
    exportBtn: "ኣውጽእ",
    importBtn: "ኣእቱ",
    save: "ዕቀብ",
    myBeats: "ድቕድቕታተይ",
    clear: "ደምስስ",
    undo: "መለስ",
    kick: "ኪክ",
    snare: "ንእሽቶ",
    hats: "ሃት",
    clap: "ኣጻፍሕ",
    studio: "ስቱድዮ",
    arcade: "ኣርከድ",
    dream: "ሕልሚ",
    boom: "ቡም",
    bright: "ብርሃን",
    moody: "ጸልማት",
    bars: "ኣዕኑድ",
    kaleido: "ካሌይዶስኮፕ",
    clouds: "ደበናታት",
    stars: "ከዋኽብቲ",
    code: "ኮድ",
    rings: "ቀለቤታት",
    ripple: "ማዕበል",
    tiles: "ጣውላታት",
    orbit: "ኦርቢት",
    rain: "ዝናብ",
    tunnel: "ቶነል",
    ribbon: "ናይ ሪብን",
    bloom: "ዕምባባ",
    fireworks: "ሕንጻጽ",
    soft: "ልስሉስ",
    norm: "ንቡር",
    solo: "ሶሎ",
    offWord: "ጠፊኡ",
    bpm: "BPM",
    firstBeat: "ናይ መጀመርታ ድቕድቕ",
    clapClass: "ክፍሊ ኣጻፍሕ",
    recess: "ዕረፍቲ",
    nightWalk: "ናይ ለይቲ ምኻድ",
    lockerBoom: "ቡም ሳንዱቕ",
    blankPage: "ባዶ ገጽ",
    classBeat: "ድቕድቕ ክፍሊ",
    seeMove: "ከም ዝንቀሳቐስ ርአ",
    noNames: "ስም የለን",
    teacher: "መምህር",
    privacy: "ብሕታዊነት",
    howTitle: "ከመይ ይሰርሕ",
    help2: "ድምጺ ንምውላዕ ኣርባዕቲ ጠውቕ። ንምጥፋእ ደጊምካ ጠውቕ።",
    help3: "ኣጻውት ጠውቕ። እቲ ዝንቀሳቐስ ዓምዲ ድቕድቕ ኣብ መርበብ ዝኸይድ እዩ።",
    help4: "ናይ ላዕሊ መስመራት ከበሮ እዩ። ናይ ታሕቲ ንቑልጡፍ ዝኾኑ ኖታታት እዩ።",
    help5: "ናይ ትርኢት ቺፕ ስእልታት ይቕይር — ኣዕኑድ፣ ካሌይዶስኮፕ፣ ደበናታት፣ ከዋኽብቲ፣ ኮድ። ሓደ ድቕድቕ፣ ካልእ መብራህቲ። ዘይድምጺ እውን ጽቡቕ።",
    help6: "ኣሕልፍ ኮድ ይቅዳሕ — ስም የለን — ዝቕጽል Chromebook ነቲ ድቕድቕ ንኽከፍት።",
    helpFoot: "ቦታ ቁልፊ ይጻወትን ይቆምን። ቁልፍታት 1–5 ትርኢት ይቕይሩ። ንድምጺ ንምስማዕ ስም መስመር ጠውቕ። ኣርእስቲ ጥራይ፣ ስም ተማሃራይ ኣይኮነን።",
    lesBeatT: "ድቕድቕ",
    lesBeatB: "ኣጻውት ጠውቕ። ነቲ ቃል ቁጽር፦ ድቕድቕ 1፣ ድቕድቕ 2፣ ድቕድቕ 3፣ ድቕድቕ 4። እቲ ቀጻሊ ቁጽሪ ድቕድቕ እዩ። ድምጺ ክጠፍእ ይኽእል።",
    lesBeatM: "ኣጻውት ጠውቕ፣ ድሕሪኡ ነቲ ቃል ርአ።",
    lesStrongT: "ሓያል ድቕድቕ",
    lesStrongB: "ድቕድቕ 1 ሓያል ድቕድቕ እዩ። እቲ ብእግሪ እትጠውቖ እዩ። እቲ ቃል ድቕድቕ 1 ክብል ተጸበ።",
    lesStrongM: "እቲ ቃል ድቕድቕ 1 ክሳብ ዝብል ግደፎ ይጻወት።",
    lesPulseT: "ናህሪ",
    lesPulseB: "ነቲ ቀዳማይ ኣርባዕቲ ኪክ ኣብርህ። ኪክ ኣብ ድቕድቕ 1 ናህሪ እዩ። ካልኦት ከበሮታት ኣብ ዙርያኡ።",
    lesPulseM: "ነቲ ቀዳማይ ኣርባዕቲ ኪክ ጠውቕ ንኽበርህ።",
    lesTimeT: "ግዜ",
    lesTimeB: "4/4 ኣርባዕተ ድቕድቕ ማለት እዩ፣ ድሕሪኡ ይጅምር። 3/4 ጠውቕ። 1፣ 2፣ 3 ቁጽር። ናይ ታሕቲ መስመራት ኖታ እዩ፦ C፣ D፣ E፣ G፣ A።",
    lesTimeM: "ኣብ መስመር ግዜ 3/4 ጠውቕ።",
    lesTempoT: "ፍጥነት",
    lesTempoB: "ፍጥነት ኣንቀሳቕስ። ቀልጢፍ ወይ ቀስ እቲ ፍጥነት እዩ። ሓደ ዓይነት ድቕድቕ ትቁጽር። ፍጥነት ስጋዕ እዩ። ግዜ ክንደይ ድቕድቕ እዩ።",
    lesTempoM: "ነቲ ተንሸራታፊ ፍጥነት ኣንቀሳቕስ።",
    gotIt: "ኣተወ።",
    iDid: "እዚ ገይረዮ",
    done: "ተወዲኡ",
    skip: "ዝለል",
    lesson: "ትምህርቲ",
    of: "ካብ",
    close: "ዕጸው",
    saveBeat: "ድቕድቕ ዕቀብ"
  };

  var PACKS = { en: EN, uk: UK, ru: RU, es: ES, ar: AR, "fa-AF": FA, rw: RW, ti: TI };
  var OK = { en: 1, simple: 1, uk: 1, ru: 1, es: 1, ar: 1, "fa-AF": 1, rw: 1, ti: 1 };
  var followPrefs = false;

  function classic() {
    try {
      var q = new URLSearchParams(location.search);
      if (q.get("hub") === "classic" || q.get("theme") === "classic") return true;
      if (localStorage.getItem("tech-room-hub") === "classic") return true;
    } catch (e) {}
    return false;
  }
  function lang() {
    if (classic()) return "en";
    try {
      if (followPrefs && root.KulibertPrefs && OK[root.KulibertPrefs.lang]) return root.KulibertPrefs.lang;
      var q = new URLSearchParams(location.search).get("lang");
      if (q && OK[q]) return q;
      if (root.KulibertPrefs && OK[root.KulibertPrefs.lang]) return root.KulibertPrefs.lang;
    } catch (e2) {}
    return "en";
  }
  function packFor(code) {
    if (code === "simple" || !PACKS[code]) return EN;
    return PACKS[code];
  }
  function t(key) {
    var k = String(key == null ? "" : key);
    var pack = packFor(lang());
    if (pack && pack[k]) return pack[k];
    if (EN[k]) return EN[k];
    return "";
  }
  function paint() {
    var code = lang();
    var html = document.documentElement;
    html.lang = code === "simple" ? "en" : code;
    html.dir = code === "ar" || code === "fa-AF" ? "rtl" : "ltr";
    document.querySelectorAll("[data-bz]").forEach(function (node) {
      var v = t(node.getAttribute("data-bz"));
      if (v) node.textContent = v;
    });
    document.querySelectorAll("[data-bz-label]").forEach(function (node) {
      var v = t(node.getAttribute("data-bz-label"));
      if (v) node.setAttribute("aria-label", v);
    });
    if (typeof root.BzPaintLive === "function") {
      try { root.BzPaintLive(); } catch (e) {}
    }
  }
  root.addEventListener("kulibert-lang", function () {
    followPrefs = true;
    paint();
  });
  root.addEventListener("storage", function (ev) {
    if (!ev || ev.key !== "kulibert-prefs-v1") return;
    followPrefs = true;
  });
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", paint);
  else paint();
  root.BzI18n = { t: t, lang: lang, paint: paint };
})(window);
