// Farm pack. Block ids stay frozen. Water stays in the core.
import { registerPack } from '../registry.js'

const blocks = [
  [28, 'wheat', 'cotton_tan', 'Wh', 'cotton_tan'],
  [29, 'reed', 'leaves', 'Rd', 'leaves'],
  [49, 'farmland', 'dirt', 'Fm', null],
  [58, 'tuft', 'leaves', 'Tf', null],
  [59, 'cropSprout', 'leaves', 'Cs', null],
  [60, 'cropLeafy', 'leaves', 'Cl', null],
  [61, 'cropTall', 'leaves', 'Ct', null],
  [62, 'cropRipe', 'cotton_tan', 'Cr', null],
  [63, 'farmlandWet', 'dirt', 'Fw', null],
  [65, 'bushYoung', 'leaves', 'By', null],
  [66, 'bushLeaf', 'leaves', 'Bl', null],
  [67, 'bushFull', 'leaves', 'Bf', null],
  [68, 'bushFruit', 'leaves', 'Bu', null],
  [185, 'sapling', 'leaves', 'Sp', 'leaves'],
]

const items = [
  { key: 'hoe', after: 'stoneTool', def: { svg: 'hoe', letter: 'Ho', base: 2, sell: false, stack: 1 } },
  { key: 'sapling', after: 'clay', def: { block: 185, letter: 'Sp', base: 0, sell: false } },
  { key: 'berry', def: { svg: 'berry', letter: 'Be', cat: 'Food', base: 1, sell: true } },
  { key: 'wheat', def: { block: 28, letter: 'Wh', cat: 'Food', base: 2, sell: false } },
  { key: 'wheatSeeds', def: { svg: 'wheatSeeds', letter: 'Ws', base: 0, sell: false } },
  { key: 'bushSprout', def: { svg: 'bushSprout', letter: 'Bs', base: 0, sell: false } },
  { key: 'flour', def: { svg: 'flour', letter: 'Fl', cat: 'Food', base: 3, sell: true } },
  { key: 'sugar', def: { svg: 'sugar', letter: 'Su', cat: 'Food', base: 2, sell: true } },
  { key: 'cupcake', def: { svg: 'cupcake', letter: 'Cu', cat: 'Food', base: 6, sell: true } },
  { key: 'bread', def: { svg: 'bread', letter: 'Bd', cat: 'Food', base: 8, sell: true } },
]

const recipes = [
  { id: 'hoe', after: 'stick', at: 'bench', in: [['stick', 2], ['planks', 1]], out: ['hoe', 1], secs: 2 },
  { id: 'cupcake', at: 'oven', in: [['flour', 1], ['sugar', 1], ['berry', 2]], out: ['cupcake', 2], secs: 10, label: 'food' },
  { id: 'bread', at: 'oven', in: [['flour', 2]], out: ['bread', 1], secs: 8, label: 'food' },
  { id: 'flour', at: 'bench', in: [['wheat', 1]], out: ['flour', 1], secs: 2, label: 'food' },
]

const drops = [
  [59, 'wheatSeeds'], [60, 'wheatSeeds'], [61, 'wheatSeeds'], [62, 'wheatSeeds'],
  [65, 'bushSprout'], [66, 'bushSprout'], [67, 'bushSprout'], [68, 'bushSprout'],
  [28, 'wheat'], [29, 'sugar'],
  [49, 'dirt'], [63, 'dirt'],
  [58, null],
]

registerPack({
  id: 'farm',
  v: 1,
  blocks,
  items,
  recipes,
  drops,
  strings: {
  "en": {
    "berry": "Berry",
    "flour": "Flour",
    "sugar": "Sugar",
    "cupcake": "Cupcake",
    "bread": "Bread",
    "wheat": "Wheat",
    "reed": "Reed",
    "wheatSeeds": "Wheat Seeds",
    "hoe": "Hoe",
    "farmland": "Farmland",
    "tuft": "Grass",
    "digSoil": "Dig soil",
    "bushSprout": "Bush Sprout",
    "berryBush": "Berry Bush",
    "plantOnGrass": "Plant on grass",
    "regrowsIn": "Regrows in {t}",
    "bushNotFarm": "Bushes grow on grass, not farmland.",
    "bushNotWater": "Bushes cannot grow in water.",
    "bushNotStone": "Bushes cannot grow on stone.",
    "bushYoung": "Berry Bush",
    "bushLeaf": "Berry Bush",
    "bushFull": "Berry Bush",
    "bushFruit": "Berry Bush",
    "wildBush": "Wild Berry Bush",
    "bareBranches": "Bare branches",
    "berriesIn": "Berries in {t}",
    "wheatBack": "Wheat grows back here",
    "farmNote": "Farmers loosen soil so roots and water can get in.",
    "stageSprout": "Sprout",
    "stageLeafy": "Leafy",
    "stageTall": "Tall",
    "stageRipe": "Ripe",
    "ripeIn": "ripe in {time}",
    "drySoil": "Dry soil: grows slowly. Water nearby = 2x.",
    "farmSeed": "A seed holds a baby plant and the food to start it.",
    "farmWet": "Plants pull water up through their roots. No water means slow growth.",
    "farmRipe": "Crops take days to weeks for real. Bertopia speeds it up.",
    "farmlandWet": "Wet Farmland",
    "cropSprout": "Wheat",
    "cropLeafy": "Wheat",
    "cropTall": "Wheat",
    "cropRipe": "Wheat",
    "sapling": "Sapling",
    "saplingSoil": "Plant a sapling on grass or dirt.",
    "farmHarvest": "Wheat makes Flour at the Workbench. 2 Flour bakes Bread in the Oven.",
    "farmReplant": "Saving seed from your harvest is how farms kept going for 10,000 years.",
    "srcFarm": "grow it on Farmland",
    "replanted": "Replanted",
    "harvestedBare": "Harvested - no seed to replant"
  },
  "uk": {
    "berry": "Ягода",
    "flour": "Борошно",
    "sugar": "Цукор",
    "cupcake": "Кекс",
    "bread": "Хліб",
    "wheat": "Пшениця",
    "reed": "Очерет",
    "wheatSeeds": "Насіння пшениці",
    "hoe": "Мотика",
    "farmland": "Рілля",
    "tuft": "Трава",
    "digSoil": "Копай ґрунт",
    "bushSprout": "Паросток куща",
    "berryBush": "Ягідний кущ",
    "plantOnGrass": "Сади на траву",
    "regrowsIn": "Виросте знову за {t}",
    "bushNotFarm": "Кущі ростуть на траві, не на ріллі.",
    "bushNotWater": "Кущі не ростуть у воді.",
    "bushNotStone": "Кущі не ростуть на камені.",
    "bushYoung": "Ягідний кущ",
    "bushLeaf": "Ягідний кущ",
    "bushFull": "Ягідний кущ",
    "bushFruit": "Ягідний кущ",
    "wildBush": "Дикий ягідний кущ",
    "bareBranches": "Голі гілки",
    "berriesIn": "Ягоди за {t}",
    "wheatBack": "Пшениця виросте тут знову",
    "farmNote": "Фермери розпушують ґрунт, щоб коріння і вода могли пройти.",
    "stageSprout": "Паросток",
    "stageLeafy": "Листя",
    "stageTall": "Висока",
    "stageRipe": "Стигла",
    "ripeIn": "достигне за {time}",
    "drySoil": "Сухий ґрунт: росте повільно. Вода поруч = 2x.",
    "farmSeed": "Насінина тримає малу рослину і їжу, щоб почати.",
    "farmWet": "Рослини тягнуть воду корінням. Без води ріст повільний.",
    "farmRipe": "Справжні посіви ростуть дні й тижні. Bertopia пришвидшує це.",
    "farmlandWet": "Мокра рілля",
    "cropSprout": "Пшениця",
    "cropLeafy": "Пшениця",
    "cropTall": "Пшениця",
    "cropRipe": "Пшениця",
    "sapling": "Саджанець",
    "saplingSoil": "Сади саджанець на траву або землю.",
    "farmHarvest": "Пшениця стає борошном на верстаку. 2 борошна печуть хліб у печі.",
    "farmReplant": "Зберегти насіння з урожаю — так ферми жили 10 000 років.",
    "srcFarm": "вирости на ріллі",
    "replanted": "Посіяно знову",
    "harvestedBare": "Зібрано — немає насіння, щоб посіяти знову"
  },
  "ru": {
    "berry": "Ягода",
    "flour": "Мука",
    "sugar": "Сахар",
    "cupcake": "Кекс",
    "bread": "Хлеб",
    "wheat": "Пшеница",
    "reed": "Камыш",
    "wheatSeeds": "Семена пшеницы",
    "hoe": "Мотыга",
    "farmland": "Грядка",
    "tuft": "Трава",
    "digSoil": "Копай почву",
    "bushSprout": "Росток куста",
    "berryBush": "Ягодный куст",
    "plantOnGrass": "Сажай на траву",
    "regrowsIn": "Вырастет снова через {t}",
    "bushNotFarm": "Кусты растут на траве, не на грядке.",
    "bushNotWater": "Кусты не растут в воде.",
    "bushNotStone": "Кусты не растут на камне.",
    "bushYoung": "Ягодный куст",
    "bushLeaf": "Ягодный куст",
    "bushFull": "Ягодный куст",
    "bushFruit": "Ягодный куст",
    "wildBush": "Дикий ягодный куст",
    "bareBranches": "Голые ветки",
    "berriesIn": "Ягоды через {t}",
    "wheatBack": "Пшеница вырастет здесь снова",
    "farmNote": "Фермеры рыхлят почву, чтобы корни и вода могли пройти.",
    "stageSprout": "Росток",
    "stageLeafy": "Листья",
    "stageTall": "Высокая",
    "stageRipe": "Спелая",
    "ripeIn": "поспеет через {time}",
    "drySoil": "Сухая почва: растёт медленно. Вода рядом = 2x.",
    "farmSeed": "Семечко хранит маленькое растение и еду, чтобы начать.",
    "farmWet": "Растения тянут воду корнями. Без воды рост медленный.",
    "farmRipe": "Настоящие посевы растут дни и недели. Bertopia ускоряет это.",
    "farmlandWet": "Мокрая грядка",
    "cropSprout": "Пшеница",
    "cropLeafy": "Пшеница",
    "cropTall": "Пшеница",
    "cropRipe": "Пшеница",
    "sapling": "Саженец",
    "saplingSoil": "Сажай саженец на траву или землю.",
    "farmHarvest": "Пшеница становится мукой на верстаке. 2 муки пекут хлеб в печи.",
    "farmReplant": "Сохранять семя с урожая — так фермы жили 10 000 лет.",
    "srcFarm": "вырасти на грядке",
    "replanted": "Посажено снова",
    "harvestedBare": "Собрано — нет семени, чтобы посадить снова"
  },
  "es": {
    "berry": "Baya",
    "flour": "Harina",
    "sugar": "Azúcar",
    "cupcake": "Cupcake",
    "bread": "Pan",
    "wheat": "Trigo",
    "reed": "Caña",
    "wheatSeeds": "Semillas de trigo",
    "hoe": "Azada",
    "farmland": "Tierra de cultivo",
    "tuft": "Hierba",
    "digSoil": "Cava la tierra",
    "bushSprout": "Brote de arbusto",
    "berryBush": "Arbusto de bayas",
    "plantOnGrass": "Planta en la hierba",
    "regrowsIn": "Vuelve a crecer en {t}",
    "bushNotFarm": "Los arbustos crecen en la hierba, no en tierra de cultivo.",
    "bushNotWater": "Los arbustos no crecen en el agua.",
    "bushNotStone": "Los arbustos no crecen en la piedra.",
    "bushYoung": "Arbusto de bayas",
    "bushLeaf": "Arbusto de bayas",
    "bushFull": "Arbusto de bayas",
    "bushFruit": "Arbusto de bayas",
    "wildBush": "Arbusto de bayas silvestre",
    "bareBranches": "Ramas peladas",
    "berriesIn": "Bayas en {t}",
    "wheatBack": "El trigo vuelve a crecer aquí",
    "farmNote": "Los agricultores aflojan la tierra para que entren las raíces y el agua.",
    "stageSprout": "Brote",
    "stageLeafy": "Hojas",
    "stageTall": "Alto",
    "stageRipe": "Maduro",
    "ripeIn": "madura en {time}",
    "drySoil": "Tierra seca: crece lento. Agua cerca = 2x.",
    "farmSeed": "Una semilla guarda una planta bebé y la comida para empezar.",
    "farmWet": "Las plantas suben el agua por las raíces. Sin agua crecen lento.",
    "farmRipe": "Los cultivos tardan días o semanas de verdad. Bertopia lo acelera.",
    "farmlandWet": "Tierra húmeda",
    "cropSprout": "Trigo",
    "cropLeafy": "Trigo",
    "cropTall": "Trigo",
    "cropRipe": "Trigo",
    "sapling": "Plantón",
    "saplingSoil": "Planta un plantón en hierba o tierra.",
    "farmHarvest": "El trigo se hace harina en el banco. 2 harinas hornean pan en el horno.",
    "farmReplant": "Guardar semilla de la cosecha es como las granjas siguieron 10.000 años.",
    "srcFarm": "cultívalo en tierra de cultivo",
    "replanted": "Replantado",
    "harvestedBare": "Cosechado: no hay semilla para replantar"
  },
  "ar": {
    "berry": "توت",
    "flour": "دقيق",
    "sugar": "سكر",
    "cupcake": "كب كيك",
    "bread": "خبز",
    "wheat": "قمح",
    "reed": "قصب",
    "wheatSeeds": "بذور القمح",
    "hoe": "مجرفة",
    "farmland": "أرض زراعة",
    "tuft": "عشب",
    "digSoil": "احفر التربة",
    "bushSprout": "برعم شجيرة",
    "berryBush": "شجيرة توت",
    "plantOnGrass": "ازرع على العشب",
    "regrowsIn": "ينمو من جديد خلال {t}",
    "bushNotFarm": "الشجيرات تنمو على العشب، لا على أرض الزراعة.",
    "bushNotWater": "الشجيرات لا تنمو في الماء.",
    "bushNotStone": "الشجيرات لا تنمو على الحجر.",
    "bushYoung": "شجيرة توت",
    "bushLeaf": "شجيرة توت",
    "bushFull": "شجيرة توت",
    "bushFruit": "شجيرة توت",
    "wildBush": "شجيرة توت برية",
    "bareBranches": "أغصان عارية",
    "berriesIn": "التوت خلال {t}",
    "wheatBack": "القمح ينمو هنا من جديد",
    "farmNote": "المزارعون يفكّون التربة حتى تصل الجذور والماء.",
    "stageSprout": "برعم",
    "stageLeafy": "أوراق",
    "stageTall": "طويل",
    "stageRipe": "ناضج",
    "ripeIn": "ينضج خلال {time}",
    "drySoil": "تربة جافة: تنمو ببطء. الماء قريب = 2x.",
    "farmSeed": "البذرة تحمل نبتة صغيرة وطعاماً لتبدأ.",
    "farmWet": "النباتات تسحب الماء بجذورها. بلا ماء يكون النمو بطيئاً.",
    "farmRipe": "المحاصيل الحقيقية تأخذ أياماً أو أسابيع. بيرتوبيا تسرّع ذلك.",
    "farmlandWet": "أرض رطبة",
    "cropSprout": "قمح",
    "cropLeafy": "قمح",
    "cropTall": "قمح",
    "cropRipe": "قمح",
    "sapling": "شتلة",
    "saplingSoil": "ازرع شتلة على عشب أو تراب.",
    "farmHarvest": "القمح يصير دقيقاً على المنضدة. 2 من الدقيق يخبز خبزاً في الفرن.",
    "farmReplant": "حفظ البذرة من الحصاد هو كيف استمرت المزارع 10,000 سنة.",
    "srcFarm": "ازرعه في أرض الزراعة",
    "replanted": "زُرع من جديد",
    "harvestedBare": "حُصد — لا بذرة لإعادة الزرع"
  },
  "fa-AF": {
    "berry": "توت",
    "flour": "آرد",
    "sugar": "شکر",
    "cupcake": "کاپ‌کیک",
    "bread": "نان",
    "wheat": "گندم",
    "reed": "نی",
    "wheatSeeds": "دانه‌های گندم",
    "hoe": "بیلچه",
    "farmland": "زمین کشاورزی",
    "tuft": "چمن",
    "digSoil": "خاک را بکن",
    "bushSprout": "جوانه بوته",
    "berryBush": "بوته توت",
    "plantOnGrass": "روی چمن بکار",
    "regrowsIn": "دوباره می‌روید در {t}",
    "bushNotFarm": "بوتها روی چمن می‌رویند، نه روی زمین کشاورزی.",
    "bushNotWater": "بوتها در آب نمی‌رویند.",
    "bushNotStone": "بوتها روی سنگ نمی‌رویند.",
    "bushYoung": "بوته توت",
    "bushLeaf": "بوته توت",
    "bushFull": "بوته توت",
    "bushFruit": "بوته توت",
    "wildBush": "بوته توت وحشی",
    "bareBranches": "شاخه‌های لخت",
    "berriesIn": "توت در {t}",
    "wheatBack": "گندم اینجا دوباره می‌روید",
    "farmNote": "کشاورزان خاک را شل می‌کنند تا ریشه و آب داخل شوند.",
    "stageSprout": "جوانه",
    "stageLeafy": "برگ‌دار",
    "stageTall": "بلند",
    "stageRipe": "رسیده",
    "ripeIn": "می‌رسد در {time}",
    "drySoil": "خاک خشک: آهسته رشد می‌کند. آب نزدیک = 2x.",
    "farmSeed": "دانه یک گیاه کوچک و خوراک شروع را نگه می‌دارد.",
    "farmWet": "گیاهان آب را با ریشه بالا می‌کشند. بی‌آب رشد آهسته است.",
    "farmRipe": "کشت واقعی روزها و هفته‌ها می‌برد. برتوپیا آن را تند می‌کند.",
    "farmlandWet": "زمین خیس",
    "cropSprout": "گندم",
    "cropLeafy": "گندم",
    "cropTall": "گندم",
    "cropRipe": "گندم",
    "sapling": "نهال",
    "saplingSoil": "نهال را روی چمن یا خاک بکار.",
    "farmHarvest": "گندم روی میز کار آرد می‌شود. ۲ آرد در تنور نان می‌شود.",
    "farmReplant": "نگه داشتن دانه از برداشت، راهی است که کشتزارها ۱۰٬۰۰۰ سال ماندند.",
    "srcFarm": "روی زمین کشاورزی بکار",
    "replanted": "دوباره کاشته شد",
    "harvestedBare": "برداشته شد — دانه‌ای برای کاشتن دوباره نیست"
  },
  "rw": {
    "berry": "Imbuto",
    "flour": "Ifu",
    "sugar": "Isukari",
    "cupcake": "Kek",
    "bread": "Umugati",
    "wheat": "Ingano",
    "reed": "Urubingo",
    "wheatSeeds": "Imbuto z'ingano",
    "hoe": "Isuka",
    "farmland": "Ubutaka bw'imirima",
    "tuft": "Ibyatsi",
    "digSoil": "Kanda ubutaka",
    "bushSprout": "Ikime cy'igiti",
    "berryBush": "Igiti cy'imbuto",
    "plantOnGrass": "Tera ku byatsi",
    "regrowsIn": "Ikura nanone mu {t}",
    "bushNotFarm": "Ibiti bikura ku byatsi, ntabwo ku butaka bw'imirima.",
    "bushNotWater": "Ibiti ntibikura mu mazi.",
    "bushNotStone": "Ibiti ntibikura ku ibuye.",
    "bushYoung": "Igiti cy'imbuto",
    "bushLeaf": "Igiti cy'imbuto",
    "bushFull": "Igiti cy'imbuto",
    "bushFruit": "Igiti cy'imbuto",
    "wildBush": "Igiti cy'imbuto cy'ahantu",
    "bareBranches": "Amashami atagira ibibabi",
    "berriesIn": "Imbuto mu {t}",
    "wheatBack": "Ingano ikura hano nanone",
    "farmNote": "Abahinzi baratoha ubutaka kugira ngo imizi n'amazi binjire.",
    "stageSprout": "Ikime",
    "stageLeafy": "Amababi",
    "stageTall": "Ndeya",
    "stageRipe": "Yakuze",
    "ripeIn": "izakuka mu {time}",
    "drySoil": "Ubutaka bwumye: bukura buhoro. Amazi hafi = 2x.",
    "farmSeed": "Imbuto ifite ikimera gito n'ibiryo byo gutangira.",
    "farmWet": "Ibihingwa bikurura amazi binyuze mu mizi. Nta mazi ni ukukura buhoro.",
    "farmRipe": "Ibihingwa by'ukuri bifata iminsi cyangwa ibyumweru. Bertopia birihutisha.",
    "farmlandWet": "Ubutaka bumeze",
    "cropSprout": "Ingano",
    "cropLeafy": "Ingano",
    "cropTall": "Ingano",
    "cropRipe": "Ingano",
    "sapling": "Ingemwe",
    "saplingSoil": "Shyira ingemwe ku byatsi cyangwa ku butaka.",
    "farmHarvest": "Ingano iba ifu ku meza. Ifu 2 iteka umugati mu byoto.",
    "farmReplant": "Kubika imbuto yo gusarura ni uko imirima yakomeje imyaka 10.000.",
    "srcFarm": "yitera ku butaka bw'imirima",
    "replanted": "Yongeye gutera",
    "harvestedBare": "Yasaruriwe — nta mbuto yo kongera gutera"
  },
  "ti": {
    "berry": "ፍረ",
    "flour": "ዱቄት",
    "sugar": "ሽኮር",
    "cupcake": "ኬክ",
    "bread": "ባኒ",
    "wheat": "ስርናይ",
    "reed": "ቀጸል",
    "wheatSeeds": "ዘርኢ ስርናይ",
    "hoe": "መንኮስ",
    "farmland": "ሓረስቲ ምድሪ",
    "tuft": "ሳዕሪ",
    "digSoil": "ሓመድ እኸድ",
    "bushSprout": "ቡቕሊ ቁጽሪ",
    "berryBush": "ቁጽሪ ፍረ",
    "plantOnGrass": "ኣብ ሳዕሪ ተኽል",
    "regrowsIn": "ዳግማይ ኣብ {t} ይበቕል",
    "bushNotFarm": "ቁጽሪ ኣብ ሳዕሪ ይበቅል፡ ኣብ ሓረስቲ ምድሪ ኣይኮነን።",
    "bushNotWater": "ቁጽሪ ኣብ ማይ ኣይበቅልን።",
    "bushNotStone": "ቁጽሪ ኣብ እምኒ ኣይበቅልን።",
    "bushYoung": "ቁጽሪ ፍረ",
    "bushLeaf": "ቁጽሪ ፍረ",
    "bushFull": "ቁጽሪ ፍረ",
    "bushFruit": "ቁጽሪ ፍረ",
    "wildBush": "ናይ ዱር ቁጽሪ ፍረ",
    "bareBranches": "ባዶ ኣግራብ",
    "berriesIn": "ፍረ ኣብ {t}",
    "wheatBack": "ስርናይ ኣብዚ ዳግማይ ይበቕል",
    "farmNote": "ሓረስቶት ሓመድ የላላውዩ እሞ ሱርን ማይን ይኣትዉ።",
    "stageSprout": "ቡቕሊ",
    "stageLeafy": "ቆጽሊ",
    "stageTall": "ነዊሕ",
    "stageRipe": "በሲሉ",
    "ripeIn": "ኣብ {time} ይብስል",
    "drySoil": "ደረቅ ሓመድ፡ ቀስ ይዓቢ። ማይ ኣብ ጥቓ = 2x.",
    "farmSeed": "ዘርኢ ነእሽቶ ተኽሊን ንምጅማር መግብን ይሓዝ።",
    "farmWet": "ተኽሊ ማይ ብሱር የልዕል። ማይ እንተ ዘይሃለወ ቀስ ይዓቢ።",
    "farmRipe": "ሓቀኛ ምህርቲ መዓልትታት ወይ ሰሙናት ይውስድ። Bertopia የቀልጥፎ።",
    "farmlandWet": "ርጥብ ሓረስቲ ምድሪ",
    "cropSprout": "ስርናይ",
    "cropLeafy": "ስርናይ",
    "cropTall": "ስርናይ",
    "cropRipe": "ስርናይ",
    "sapling": "ቡቕሊ",
    "saplingSoil": "ቡቕሊ ኣብ ሳዕሪ ወይ መሬት ተኽል።",
    "farmHarvest": "ስርናይ ኣብ ሰደቓ ዱቄት ይኸውን። 2 ዱቄት ኣብ እቶን ባኒ ይብስል።",
    "farmReplant": "ዘርኢ ካብ ምእካብ ምዕቃብ እዩ ሓረስታት ን10,000 ዓመታት ዝቐጸሉ።",
    "srcFarm": "ኣብ ሓረስቲ ምድሪ ኣብቕል",
    "replanted": "ዳግማይ ተዘሪኡ",
    "harvestedBare": "ተኣኪቡ — ዘርኢ ንዳግማይ ምዝራእ የለን"
  }
},
})
