export const CHANGELOG = [
  { v: '2.5.27', date: '2026-10-04', lines: {
    en: ['Craft rows use the full width.', 'A recipe keeps its name when it needs a bench or an oven.'],
    uk: ['Рядки крафту на всю ширину.', 'Рецепт лишає назву, навіть якщо потрібен верстак чи піч.'],
    ru: ['Строки крафта на всю ширину.', 'Рецепт сохраняет имя, даже если нужен верстак или печь.'],
    es: ['Las recetas usan todo el ancho.', 'La receta conserva su nombre aunque necesite banco u horno.'],
    ar: ['صفوف الصنع بعرض الشاشة.', 'الوصفة تُبقي اسمها حتى لو احتاجت منضدة أو فرناً.'],
    'fa-AF': ['ردیف ساختن تمام عرض را می‌گیرد.', 'دستور نامش را نگه می‌دارد حتی اگر میز یا تنور بخواهد.'],
    rw: ['Imirongo ikoresha ubugari bwose.', 'Isosiyete isigara izina nubwo ikeneye ameza cyangwa ibyoto.'],
    ti: ['መስመራት ስራሕ ምሉእ ስፍሓት።', 'ዝርዝር ስሙ ይጸንሕ እንተደኣ እቶን ወይ ሰደቓ ዘድልዮ።'],
  }},
  { v: '2.5.26', date: '2026-10-04', lines: {
    en: ['Craft lists Can make now, Almost, and Show all.', '×Max makes as many as you can.', 'The shop sells a material only after you find it.', 'Settings has Look speed and Invert look.'],
    uk: ['Крафт: Можна зараз, Майже, Показати все.', '×Max робить скільки можеш.', 'Крамниця продає матеріал після того, як знайдеш.', 'У налаштуваннях швидкість і переворот огляду.'],
    ru: ['Крафт: Можно сейчас, Почти, Показать все.', '×Max делает сколько можешь.', 'Лавка продаёт материал после находки.', 'В настройках скорость и переворот взгляда.'],
    es: ['Fabricar: Puedes hacer, Casi y Ver todo.', '×Max hace todos los que puedas.', 'La tienda vende un material solo si ya lo encontraste.', 'Ajustes: velocidad de mirada e invertir.'],
    ar: ['الصنع: يمكنك الآن، تقريباً، وأظهر الكل.', '×Max يصنع كل ما تستطيع.', 'المتجر يبيع المادة بعد أن تجدها.', 'الإعدادات: سرعة النظر وعكسه.'],
    'fa-AF': ['ساختن: حالا، نزدیک، و همه.', '×Max هر چه بتوانی می‌سازد.', 'دکان ماده را بعد از پیدا کردن می‌فروشد.', 'تنظیمات: سرعت نگاه و برگرداندن.'],
    rw: ['Gukora: Ushobora ubu, Hafi, Erekana byose.', '×Max ikora ibyo ushobora.', 'Iduka rigurisha nyuma yo kubona.', 'Igenamiterere: umuvuduko n\'ihindura.'],
    ti: ['ስራሕ፡ ሕጂ፣ ዳርጋ፣ ኩሉ ኣርኢ።', '×Max ክንደይ ከም እትኽእል ይሰርሕ።', 'ድኳን ድሕሪ ምርካብ ይሸይጥ።', 'ቅንጅታት፡ ፍጥነትን ግልባጥን ምርኣይ።'],
  }},
  { v: '2.5.25', date: '2026-10-04', lines: {
    en: ['A drop hops into your bag when you walk up to it.', 'Counters and bunks stay until you pick them up.'],
    uk: ['Річ стрибає в сумку, коли підходиш.', 'Прилавки й ліжка лишаються, поки їх не забереш.'],
    ru: ['Вещь прыгает в сумку, когда подходишь.', 'Прилавки и кровати остаются, пока их не заберёшь.'],
    es: ['Lo que cae entra en la bolsa al acercarte.', 'Los mostradores y las literas se quedan hasta que los recoges.'],
    ar: ['ما يسقط يدخل الحقيبة حين تقترب.', 'المنضدة والسرير يبقيان حتى تلتقطهما.'],
    'fa-AF': ['چیز افتاده وقتی نزدیک شوی به بکس می‌آید.', 'پیشخوان و بستر تا وقتی برنداری می‌مانند.'],
    rw: ['Icyataye kiza mu gasaho niyo uhageze.', 'Counter na buriri bisigara kugeza ubitwaye.'],
    ti: ['ዝወደቐ ናብ ቦርሳ ይመጽእ ምስ ቀረብካ።', 'መደብን ዓራትን ክሳብ እትልዕሎም ይጸንሑ።'],
  }},
  { v: '2.5.24', date: '2026-10-04', lines: {
    en: ['A full bag still breaks the block.', 'The piece waits on the ground.', 'Q drops one. Shift+Q drops the stack.'],
    uk: ['Повна сумка все одно ламає блок.', 'Шматок чекає на землі.', 'Q кидає 1. Shift+Q кидає стос.'],
    ru: ['Полная сумка всё равно ломает блок.', 'Кусок ждёт на земле.', 'Q бросает 1. Shift+Q бросает стопку.'],
    es: ['La bolsa llena igual rompe el bloque.', 'La pieza espera en el suelo.', 'Q suelta uno. Mayús+Q suelta la pila.'],
    ar: ['الحقيبة الممتلئة تكسر المكعب أيضاً.', 'القطعة تنتظر على الأرض.', 'Q يُسقط واحداً. Shift+Q يُسقط الكومة.'],
    'fa-AF': ['بکس پر هم بلاک را می‌شکند.', 'تکه روی زمین می‌ماند.', 'Q یکی می‌اندازد. Shift+Q همه را.'],
    rw: ['Agasaho karuzuye karavunagura block.', 'Igice kitera hasi.', 'Q ikubita 1. Shift+Q ikubita byose.'],
    ti: ['ቦርሳ ምሉእ እኳ ብሎክ ይስብር።', 'እቲ ቁራጽ ኣብ መሬት ይጸንሕ።', 'Q ሓደ የውድቕ። Shift+Q ዓምቦ የውድቕ።'],
  }},
  { v: '2.5.23', date: '2026-10-04', lines: {
    en: ['A brighter sky and a soft horizon.', 'Berty wears a teal suit.', 'The block you hold shows its name.'],
    uk: ['Яскравіше небо і м’який обрій.', 'Берті в бірюзовому костюмі.', 'Блок у руці показує назву.'],
    ru: ['Ярче небо и мягкий горизонт.', 'Берти в бирюзовом костюме.', 'Блок в руке показывает имя.'],
    es: ['Un cielo más claro y un horizonte suave.', 'Berty lleva un traje verde azulado.', 'El bloque en la mano dice su nombre.'],
    ar: ['سماء أسطع وأفق ناعم.', 'بيرتي ببدلة فيروزية.', 'المكعب في يدك يُظهر اسمه.'],
    'fa-AF': ['آسمانی روشن‌تر و افق نرم.', 'برتی لباس تیل پوشیده است.', 'بلاک در دست نامش را نشان می‌دهد.'],
    rw: ['Ijuru rirakeye n’umupaka woroshye.', 'Berty yambaye ikositimu ya teal.', 'Block ufite yerekana izina.'],
    ti: ['ብርሃን ዝበለ ጠፈርን ልስሉስ ኣድማስን።', 'በርቲ ብቲል ክዳን ኣለዎ።', 'እቲ ብሎክ ስሙ የርኢ።'],
  }},
  { v: '2.5.22', date: '2026-10-04', lines: {
    en: ['One thumb stick and a one-block jump.', 'Hold to mine. A short tap places.', 'Walk, run, and crouch.'],
    uk: ['Один стік і стрибок на один блок.', 'Тримай щоб ламати. Короткий дотик ставить.', 'Крок, біг і присід.'],
    ru: ['Один стик и прыжок на один блок.', 'Держи чтобы ломать. Короткое касание ставит.', 'Шаг, бег и присед.'],
    es: ['Un stick y un salto de un bloque.', 'Mantén para romper. Un toque corto pone.', 'Caminar, correr y agacharse.'],
    ar: ['عصا بإبهام واحد وقفزة بارتفاع مكعب.', 'اضغط مطولاً للكسر. اللمسة القصيرة تضع.', 'مشي وجري وانحناء.'],
    'fa-AF': ['یک اهرم با یک شست و پرش به اندازه یک بلاک.', 'نگه دار تا بشکند. لمس کوتاه می‌گذارد.', 'راه رفتن، دویدن و خم شدن.'],
    rw: ['Agastike kamwe n’igisimbu cy’igice kimwe.', 'Fata uvune. Gukora gato gushyira.', 'Kugenda, kwiruka, kwicaramye.'],
    ti: ['ሓንቲ ስቲክን ሓደ ብሎክ ዝነጥ ጅምፕን።', 'ሓዝ ንምስባር። ሓጺር ምጥዋቕ የቐምጥ።', 'ምኻድ፣ ምጉያይ፣ ምድንጋር።'],
  }},
  { v: '2.5.21', date: '2026-10-04', lines: {
    en: ['Arabic and Dari menu taps open the menu.', 'The tour does not replace the menu.'],
    ar: ['نقرة القائمة تفتح القائمة.', 'الجولة لا تحل محل القائمة.'],
    'fa-AF': ['زدن فهرست، فهرست را باز می‌کند.', 'گشت جای فهرست را نمی‌گیرد.'],
  }},
  { v: '2.5.1', date: '2026-10-03', lines: {
    en: ['New name: Bertopia.', 'Same Bertyville world.', 'See every change here.'],
    uk: ['Нова назва: Бертопія.', 'Той самий Бертивіль.', 'Усі зміни тут.', 'Світ копіюється спершу.'],
    ru: ['Новое имя: Бертопия.', 'Тот же Бертивиль.', 'Все изменения здесь.', 'Мир копируется сначала.'],
    es: ['Nuevo nombre: Bertopia.', 'El mismo Bertyville.', 'Cada cambio está aquí.', 'El mundo se copia antes.'],
    ar: ['اسم جديد: بيرتوبيا.', 'نفس بيرتيفيل.', 'كل تغيير هنا.', 'يُنسخ العالم أولاً.'],
    'fa-AF': ['نام نو: برتوپیا.', 'همان برتی‌ویل.', 'هر تغییر اینجاست.', 'جهان اول رونویس می‌شود.'],
    rw: ['Izina rishya: Bertopia.', 'Bertyville ni yo.', 'Impinduka zose ziri hano.', 'Isi ikoporwa mbere.'],
    ti: ['ሓድሽ ስም: በርቶፕያ.', 'ሓደ በርቲቪል.', 'ኩሉ ለውጢ ኣብዚ.', 'ዓለም ቅድሚኡ ትቕዳሕ።'],
  }},
  { v: '2.5.0', date: '2026-10-03', lines: { en: ['A picture tour.', 'Try this goals.', 'No flying in Survival.', 'Send Cogs to your teacher.'] } },
  { v: '2.4.0', date: '2026-10-03', lines: { en: ['Build Tools do the edit.', 'Undo takes a whole Fill back.', 'The counter keeps its key.'] } },
  { v: '2.3.0', date: '2026-10-03', lines: { en: ['Esc stays in the menu.', 'Exit asks first.', 'Headers sit below the bar.'] } },
  { v: '2.2.0', date: '2026-10-03', lines: { en: ['A big menu.', 'A Coreplate floor.', 'A shop and a counter.'] } },
  { v: '2.1.0', date: '2026-10-03', lines: { en: ['Undo a whole step.', 'Inspect a block.', 'Pick a block.'] } },
  { v: '2.0.0', date: '2026-10-03', lines: { en: ['The first Bertopia door.', 'Bertyville starter world.', 'Build Table mode.'] } },
]
