export const CHANGELOG = [
  { v: '2.5.32', date: '2026-10-04', lines: {
    en: ['The bag is 9 in the hotbar and 6 pockets.', 'Older stacks that do not fit wait in Lost & Found. Nothing is deleted.', 'A new visit starts in Survival.', 'The build world is under Teacher. A student does not see it.'],
    uk: ['Сумка — 9 на панелі і 6 кишень.', 'Старі стоси, що не вмістились, чекають у Загубленому. Нічого не стерто.', 'Новий візит починається у Виживанні.', 'Світ будівлі під Вчителем. Учень його не бачить.'],
    ru: ['Сумка — 9 на панели и 6 карманов.', 'Старые стопки, которые не влезли, ждут в Потерянном. Ничего не стёрто.', 'Новый визит начинается в Выживании.', 'Мир стройки у Учителя. Ученик его не видит.'],
    es: ['La bolsa es 9 en la barra y 6 bolsillos.', 'Lo que no cabe espera en Perdidos. No se borra nada.', 'Una visita nueva empieza en Supervivencia.', 'El mundo de construir está en Profe. Un alumno no lo ve.'],
    ar: ['الحقيبة 9 في الشريط و6 جيوب.', 'ما لا يتسع ينتظر في المفقودات. لا شيء يُحذف.', 'الزيارة الجديدة تبدأ في البقاء.', 'عالم البناء عند المعلم. التلميذ لا يراه.'],
    'fa-AF': ['بکس ۹ در نوار و ۶ جیب است.', 'آنچه جا نمی‌شود در گم‌شده‌ها می‌ماند. هیچ چیز پاک نمی‌شود.', 'بازدید تازه در بقا شروع می‌شود.', 'جهان ساختن زیر معلم است. شاگرد آن را نمی‌بیند.'],
    rw: ['Agasaho ni 9 ku mukandara na 6 majepo.', 'Ibitageze bitegereje mu byabuze. Nta kigisibwaho.', 'Isura nshya itangira mu Bugingo.', 'Isi yo kubaka iri ku mwarimu. Umunyeshuri ntayibona.'],
    ti: ['ቦርሳ 9 ኣብ መስመርን 6 ጁባን እዩ።', 'ዘይኣቱ ኣብ ዝጠፍአ ይጽንሕ። ዝተደምሰሰ የለን።', 'ሓድሽ ምብጻሕ ኣብ ህይወት ይጅምር።', 'ዓለም ህንጻ ኣብ መምህር እዩ። ተምሃራይ ኣይርእዮን።'],
  }},
  { v: '2.5.31', date: '2026-10-04', lines: {
    en: ['Press the same number again to use that slot. Holding the key does not eat the stack.', 'A block no longer pops a toast just for being selected.', 'The name under Bertopia matches the lit slot.', 'Right click stops placing when you let go or open a menu.', 'Pick moves to the other side when the stick is on the right.', 'Pick follows the language.'],
    uk: ['Натисни той самий номер ще раз, щоб використати. Утримання не зʼїдає стос.', 'Блок більше не вигукує назву просто за вибір.', 'Права кнопка перестає ставити, коли відпускаєш або відкриваєш меню.', 'Взяти переходить на інший бік, якщо стик справа.', 'Взяти мовою гри.'],
    ru: ['Нажми тот же номер ещё раз, чтобы использовать. Удержание не съедает стопку.', 'Блок больше не кричит имя просто за выбор.', 'Правая кнопка перестаёт ставить, когда отпускаешь или открываешь меню.', 'Взять переходит на другую сторону, если стик справа.', 'Взять на языке игры.'],
    es: ['Pulsa el mismo número otra vez para usarlo. Mantenerlo no se come la pila.', 'Un bloque ya no grita su nombre solo por elegirlo.', 'El clic derecho deja de poner al soltar o al abrir un menú.', 'Tomar pasa al otro lado si el stick está a la derecha.', 'Tomar sigue el idioma.'],
    ar: ['اضغط الرقم نفسه مرة أخرى للاستخدام. الإمساك لا يأكل الكومة.', 'المكعب لم يعد يصرخ باسمه لمجرد اختياره.', 'الزر الأيمن يتوقف عن الوضع عند الترك أو فتح قائمة.', 'التقط ينتقل للجهة الأخرى إذا كانت العصا يميناً.', 'التقط يتبع اللغة.'],
    'fa-AF': ['همان شماره را دوباره بزن تا استفاده شود. نگه داشتن پشته را نمی‌خورد.', 'بلاک فقط برای انتخاب نامش را فریاد نمی‌زند.', 'کلیک راست با ول کردن یا باز کردن فهرست می‌ایستد.', 'بردار وقتی اهرم راست است به سمت دیگر می‌رود.', 'بردار زبان را دنبال می‌کند.'],
    rw: ['Kanda nomero nyayo nanone ukoreshe. Kuyikomeza ntibirya umufuka.', 'Block ntikivuga izina gusa kubera kuyihitamo.', 'Iburyo bihagarara iyo ubisezeraho cyangwa ukinguye ibikubiyemo.', 'Fata yimukira iyindi ruhande iyo agastike kari iburyo.', 'Fata ikurikira ururimi.'],
    ti: ['ተመሳሳሊ ቁጽሪ ደጊምካ ጠውቕ ንምጥቃም። ምሓዝ እቲ ዕስለ ኣይበልዖን።', 'ብሎክ ስለ ዝተመርጸ ስሙ ኣይጭርን።', 'የማናይ ምቕማጥ የቋርጽ ምስ እትለቕቆ ወይ ዝርዝር ምስ እትኸፍት።', 'ውሰድ እንተ የማናይ ስቲክ ናብ ኻሊእ ገጽ ይኸይድ።', 'ውሰድ ቋንቋ ይስዕብ።'],
  }},
  { v: '2.5.30', date: '2026-10-04', lines: {
    en: ['Hold right click to keep placing. A touch tap still places one.', 'Tap the selected slot again to use it. Bread, berry, and cupcake get eaten.', 'F does the same.', 'Crouch stops at a ledge.', 'Settings has Auto-climb. Phones start with it on.', 'Pick, then tap a block. Survival only picks a block you have.'],
    uk: ['Тримай праву кнопку, щоб ставити далі. Дотик ставить один.', 'Торкнись вибраного слота ще раз. Хліб, ягода і кекс зʼїдаються.', 'F теж.', 'Присід зупиняється на краю.', 'У налаштуваннях автосхід. На телефоні він увімкнений.', 'Взяти, потім торкнись блока. У Виживанні лише якщо він у сумці.'],
    ru: ['Держи правую кнопку, чтобы ставить дальше. Касание ставит один.', 'Нажми выбранный слот ещё раз. Хлеб, ягода и кекс съедаются.', 'F тоже.', 'Присед останавливается на краю.', 'В настройках автоподъём. На телефоне он включён.', 'Взять, потом нажми блок. В Выживании только если он в сумке.'],
    es: ['Mantén el clic derecho para seguir poniendo. Un toque pone uno.', 'Toca otra vez la casilla elegida. El pan, la baya y el cupcake se comen.', 'F hace lo mismo.', 'Agacharte para en un borde.', 'Ajustes tiene Auto-subir. En el teléfono empieza activo.', 'Tomar, luego toca un bloque. En Supervivencia solo si lo tienes.'],
    ar: ['اضغط الزر الأيمن مطولاً لتضع أكثر. اللمسة تضع واحداً.', 'اضغط الخانة المختارة مرة أخرى. الخبز والتوت والكعك تُؤكل.', 'F يفعل ذلك.', 'الانحناء يقف عند الحافة.', 'الإعدادات فيها تسلّق تلقائي. الهاتف يبدأ به.', 'التقط ثم المس مكعباً. في البقاء فقط إذا كان في حقيبتك.'],
    'fa-AF': ['کلیک راست را نگه دار تا بیشتر بگذاری. لمس یکی می‌گذارد.', 'خانهٔ انتخاب‌شده را دوباره بزن. نان، توت و کاپ‌کیک خورده می‌شوند.', 'F همان است.', 'خم شدن لبه‌ را رد نمی‌کند.', 'تنظیمات بالارفتن خودکار دارد. گوشی با آن روشن شروع می‌شود.', 'بردار، بعد بلاک را بزن. در بقا فقط اگر در بکس باشد.'],
    rw: ['Fata iburyo ushyire byinshi. Gutera gushyira kimwe.', 'Kanda akazu wahisemo nanone. Umugati, imbuto na kek biribwa.', 'F ni ko.', 'Kwicarama bihagarara ku musozi.', 'Igenamiterere ifite Kuzamuka. Telefoni itangira ikaye.', 'Fata, ukande block. Mu Bugingo ni iyo iri mu gasaho.'],
    ti: ['የማናይ ሓዝ ንዝያዳ ምቕማጥ። ምትንካእ ሓደ የቐምጥ።', 'ዝተመርጸ ቦታ ደጊምካ ጠውቕ። ባኒ፡ ፍረን ኬክን ይበላዕ።', 'F እውን።', 'ምድንጋር ኣብ ወሰን ይቁም።', 'ቅንጅታት ባዕሉ ምውጻእ ኣለዎ። ተሌፎን ብእዚ ይጅምር።', 'ውሰድ፡ ድሕሪኡ ብሎክ ጠውቕ። ኣብ ህይወት እንተ ኣብ ቦርሳ ጥራይ።'],
  }},
  { v: '2.5.29', date: '2026-10-04', lines: {
    en: ['Cracks grow in four steps.', 'Let go and the cracks fade. Press again and they come back.', 'Leaves break fast. Stone takes a copper tool hint after two seconds.', 'Settings has Wide view.'],
    uk: ['Тріщини ростуть у чотири кроки.', 'Відпусти — гаснуть. Натисни знову — повертаються.', 'Листя ламається швидко. Камінь через дві секунди нагадує про мідь.', 'У налаштуваннях широкий огляд.'],
    ru: ['Трещины растут в четыре шага.', 'Отпусти — гаснут. Нажми снова — возвращаются.', 'Листва ломается быстро. Камень через две секунды напоминает про медь.', 'В настройках широкий обзор.'],
    es: ['Las grietas crecen en cuatro pasos.', 'Suelta y se apagan. Pulsa otra vez y vuelven.', 'Las hojas se rompen rápido. La piedra avisa del cobre a los dos segundos.', 'Ajustes tiene Vista ancha.'],
    ar: ['الشقوق تكبر في أربع خطوات.', 'اتركها فتخبو. اضغط مرة أخرى فتعود.', 'الأوراق تنكسر بسرعة. الحجر ينبّه للنحاس بعد ثانيتين.', 'الإعدادات فيها عرض واسع.'],
    'fa-AF': ['ترک‌ها در چهار گام بزرگ می‌شوند.', 'ول کن، کم می‌شوند. دوباره فشار بده، برمی‌گردند.', 'برگ زود می‌شکند. سنگ بعد از دو ثانیه از مس می‌گوید.', 'تنظیمات نمای پهن دارد.'],
    rw: ['Ibisebe birakura mu ntambwe enye.', 'Reka bigabanuke. Kanda nanone bigaruke.', 'Amababi aravuna vuba. Ibuye nyuma y’amasegonda 2 kivuga copper.', 'Igenamiterere ifite Reba byagutse.'],
    ti: ['ስንጥቃት ብ4 ስጉምቲ ይዓቢ።', 'ሓድጎ ይጠፍእ። ደጊምካ ጠውቕ ይምለስ።', 'ቆጽሊ ብቕልጡፍ ይስበር። እምኒ ድሕሪ 2 ካልኢት ነሓስ የዘኻኽር።', 'ቅንጅታት ሰፊሕ ምርኣይ ኣለዎ።'],
  }},
  { v: '2.5.28', date: '2026-10-04', lines: {
    en: ['Menus are solid, so the world does not show through.', 'Craft names sit above the missing pieces, in gold.', 'Shop locks start on their own row, with a picture.'],
    uk: ['Меню щільне, світ не просвічує.', 'Назва рецепта над браком, золотим.', 'Замки крамниці з картинкою, окремим рядом.'],
    ru: ['Меню плотное, мир не просвечивает.', 'Имя рецепта над нехваткой, золотым.', 'Замки лавки с картинкой, отдельным рядом.'],
    es: ['Los menús son sólidos. El mundo no se ve detrás.', 'El nombre va arriba de lo que falta, en dorado.', 'La tienda pone los candados en su propia fila, con dibujo.'],
    ar: ['القوائم صلبة، العالم لا يظهر من خلفها.', 'اسم الوصفة فوق الناقص، بالذهبي.', 'أقفال المتجر في صف وحدها، مع صورة.'],
    'fa-AF': ['فهرست‌ها توپرند و جهان از پشت دیده نمی‌شود.', 'نام دستور بالای کمبود است، طلایی.', 'قفل‌های دکان در ردیف خود، با تصویر.'],
    rw: ['Ibikubiyemo biruzuye, isi ntigaragara.', 'Izina riri hejuru y’ibibura, mu zahabu.', 'Ibikoba by’iduka biri ku murongo wabyo, n’ishusho.'],
    ti: ['ዝርዝራት ጽኑዕ እዮም። ዓለም ኣይረአን።', 'ስም ኣብ ላዕሊ እቲ ዝጎደለ፣ ወርቂ።', 'መዕጸዊ ድኳን ኣብ መስመሩ፡ ምስ ስእሊ።'],
  }},
  { v: '2.5.27', date: '2026-10-04', lines: {
    en: ['Craft rows use the full width.', 'A recipe keeps its name when it needs a bench or an oven.'],
    uk: ['Рядки крафту на всю ширину.', 'Рецепт лишає назву, навіть якщо потрібен верстак чи піч.'],
    ru: ['Строки крафта на всю ширину.', 'Рецепт сохраняет имя, даже если нужен верстак или печь.'],
    es: ['Las recetas usan todo el ancho.', 'La receta conserva su nombre aunque necesite banco u horno.'],
    ar: ['صفوف الصنع بعرض الشاشة.', 'الوصفة تُبقي اسمها حتى لو احتاجت منضدة أو فرناً.'],
    'fa-AF': ['ردیف ساختن تمام عرض را می‌گیرد.', 'دستور نامش را نگه می‌دارد حتی اگر میز یا تنور بخواهد.'],
    rw: ['Imirongo ikoresha ubugari bwose.', 'Isosiyete isigara izina nubwo ikeneye ameza cyangwa ibyoto.'],
    ti: ['መስመራት ስራሕ ምሉእ ስፍሓት።', 'ዝርዝር ስሙ ይጸንሕ እንተደኣ እቶን ወይ ሰደቓ ዘድልዮ።'],
  }},
  { v: '2.5.26', date: '2026-10-04', lines: {
    en: ['Craft lists Can make now, Almost, and Show all.', '×Max makes as many as you can.', 'The shop sells a material only after you find it.', 'Settings has Look speed and Invert look.'],
    uk: ['Крафт: Можна зараз, Майже, Показати все.', '×Max робить скільки можеш.', 'Крамниця продає матеріал після того, як знайдеш.', 'У налаштуваннях швидкість і переворот огляду.'],
    ru: ['Крафт: Можно сейчас, Почти, Показать все.', '×Max делает сколько можешь.', 'Лавка продаёт материал после находки.', 'В настройках скорость и переворот взгляда.'],
    es: ['Fabricar: Puedes hacer, Casi y Ver todo.', '×Max hace todos los que puedas.', 'La tienda vende un material solo si ya lo encontraste.', 'Ajustes: velocidad de mirada e invertir.'],
    ar: ['الصنع: يمكنك الآن، تقريباً، وأظهر الكل.', '×Max يصنع كل ما تستطيع.', 'المتجر يبيع المادة بعد أن تجدها.', 'الإعدادات: سرعة النظر وعكسه.'],
    'fa-AF': ['ساختن: حالا، نزدیک، و همه.', '×Max هر چه بتوانی می‌سازد.', 'دکان ماده را بعد از پیدا کردن می‌فروشد.', 'تنظیمات: سرعت نگاه و برگرداندن.'],
    rw: ['Gukora: Ushobora ubu, Hafi, Erekana byose.', '×Max ikora ibyo ushobora.', 'Iduka rigurisha nyuma yo kubona.', 'Igenamiterere: umuvuduko n\'ihindura.'],
    ti: ['ስራሕ፡ ሕጂ፣ ዳርጋ፣ ኩሉ ኣርኢ።', '×Max ክንደይ ከም እትኽእል ይሰርሕ።', 'ድኳን ድሕሪ ምርካብ ይሸይጥ።', 'ቅንጅታት፡ ፍጥነትን ግልባጥን ምርኣይ።'],
  }},
  { v: '2.5.25', date: '2026-10-04', lines: {
    en: ['A drop hops into your bag when you walk up to it.', 'Counters and bunks stay until you pick them up.'],
    uk: ['Річ стрибає в сумку, коли підходиш.', 'Прилавки й ліжка лишаються, поки їх не забереш.'],
    ru: ['Вещь прыгает в сумку, когда подходишь.', 'Прилавки и кровати остаются, пока их не заберёшь.'],
    es: ['Lo que cae entra en la bolsa al acercarte.', 'Los mostradores y las literas se quedan hasta que los recoges.'],
    ar: ['ما يسقط يدخل الحقيبة حين تقترب.', 'المنضدة والسرير يبقيان حتى تلتقطهما.'],
    'fa-AF': ['چیز افتاده وقتی نزدیک شوی به بکس می‌آید.', 'پیشخوان و بستر تا وقتی برنداری می‌مانند.'],
    rw: ['Icyataye kiza mu gasaho niyo uhageze.', 'Counter na buriri bisigara kugeza ubitwaye.'],
    ti: ['ዝወደቐ ናብ ቦርሳ ይመጽእ ምስ ቀረብካ።', 'መደብን ዓራትን ክሳብ እትልዕሎም ይጸንሑ።'],
  }},
  { v: '2.5.24', date: '2026-10-04', lines: {
    en: ['A full bag still breaks the block.', 'The piece waits on the ground.', 'Q drops one. Shift+Q drops the stack.'],
    uk: ['Повна сумка все одно ламає блок.', 'Шматок чекає на землі.', 'Q кидає 1. Shift+Q кидає стос.'],
    ru: ['Полная сумка всё равно ломает блок.', 'Кусок ждёт на земле.', 'Q бросает 1. Shift+Q бросает стопку.'],
    es: ['La bolsa llena igual rompe el bloque.', 'La pieza espera en el suelo.', 'Q suelta uno. Mayús+Q suelta la pila.'],
    ar: ['الحقيبة الممتلئة تكسر المكعب أيضاً.', 'القطعة تنتظر على الأرض.', 'Q يُسقط واحداً. Shift+Q يُسقط الكومة.'],
    'fa-AF': ['بکس پر هم بلاک را می‌شکند.', 'تکه روی زمین می‌ماند.', 'Q یکی می‌اندازد. Shift+Q همه را.'],
    rw: ['Agasaho karuzuye karavunagura block.', 'Igice kitera hasi.', 'Q ikubita 1. Shift+Q ikubita byose.'],
    ti: ['ቦርሳ ምሉእ እኳ ብሎክ ይስብር።', 'እቲ ቁራጽ ኣብ መሬት ይጸንሕ።', 'Q ሓደ የውድቕ። Shift+Q ዓምቦ የውድቕ።'],
  }},
  { v: '2.5.23', date: '2026-10-04', lines: {
    en: ['A brighter sky and a soft horizon.', 'Berty wears a teal suit.', 'The block you hold shows its name.'],
    uk: ['Яскравіше небо і м’який обрій.', 'Берті в бірюзовому костюмі.', 'Блок у руці показує назву.'],
    ru: ['Ярче небо и мягкий горизонт.', 'Берти в бирюзовом костюме.', 'Блок в руке показывает имя.'],
    es: ['Un cielo más claro y un horizonte suave.', 'Berty lleva un traje verde azulado.', 'El bloque en la mano dice su nombre.'],
    ar: ['سماء أسطع وأفق ناعم.', 'بيرتي ببدلة فيروزية.', 'المكعب في يدك يُظهر اسمه.'],
    'fa-AF': ['آسمانی روشن‌تر و افق نرم.', 'برتی لباس تیل پوشیده است.', 'بلاک در دست نامش را نشان می‌دهد.'],
    rw: ['Ijuru rirakeye n’umupaka woroshye.', 'Berty yambaye ikositimu ya teal.', 'Block ufite yerekana izina.'],
    ti: ['ብርሃን ዝበለ ጠፈርን ልስሉስ ኣድማስን።', 'በርቲ ብቲል ክዳን ኣለዎ።', 'እቲ ብሎክ ስሙ የርኢ።'],
  }},
  { v: '2.5.22', date: '2026-10-04', lines: {
    en: ['One thumb stick and a one-block jump.', 'Hold to mine. A short tap places.', 'Walk, run, and crouch.'],
    uk: ['Один стік і стрибок на один блок.', 'Тримай щоб ламати. Короткий дотик ставить.', 'Крок, біг і присід.'],
    ru: ['Один стик и прыжок на один блок.', 'Держи чтобы ломать. Короткое касание ставит.', 'Шаг, бег и присед.'],
    es: ['Un stick y un salto de un bloque.', 'Mantén para romper. Un toque corto pone.', 'Caminar, correr y agacharse.'],
    ar: ['عصا بإبهام واحد وقفزة بارتفاع مكعب.', 'اضغط مطولاً للكسر. اللمسة القصيرة تضع.', 'مشي وجري وانحناء.'],
    'fa-AF': ['یک اهرم با یک شست و پرش به اندازه یک بلاک.', 'نگه دار تا بشکند. لمس کوتاه می‌گذارد.', 'راه رفتن، دویدن و خم شدن.'],
    rw: ['Agastike kamwe n’igisimbu cy’igice kimwe.', 'Fata uvune. Gukora gato gushyira.', 'Kugenda, kwiruka, kwicaramye.'],
    ti: ['ሓንቲ ስቲክን ሓደ ብሎክ ዝነጥ ጅምፕን።', 'ሓዝ ንምስባር። ሓጺር ምጥዋቕ የቐምጥ።', 'ምኻድ፣ ምጉያይ፣ ምድንጋር።'],
  }},
  { v: '2.5.21', date: '2026-10-04', lines: {
    en: ['Arabic and Dari menu taps open the menu.', 'The tour does not replace the menu.'],
    ar: ['نقرة القائمة تفتح القائمة.', 'الجولة لا تحل محل القائمة.'],
    'fa-AF': ['زدن فهرست، فهرست را باز می‌کند.', 'گشت جای فهرست را نمی‌گیرد.'],
  }},
  { v: '2.5.1', date: '2026-10-03', lines: {
    en: ['New name: Bertopia.', 'Same Bertyville world.', 'See every change here.'],
    uk: ['Нова назва: Бертопія.', 'Той самий Бертивіль.', 'Усі зміни тут.', 'Світ копіюється спершу.'],
    ru: ['Новое имя: Бертопия.', 'Тот же Бертивиль.', 'Все изменения здесь.', 'Мир копируется сначала.'],
    es: ['Nuevo nombre: Bertopia.', 'El mismo Bertyville.', 'Cada cambio está aquí.', 'El mundo se copia antes.'],
    ar: ['اسم جديد: بيرتوبيا.', 'نفس بيرتيفيل.', 'كل تغيير هنا.', 'يُنسخ العالم أولاً.'],
    'fa-AF': ['نام نو: برتوپیا.', 'همان برتی‌ویل.', 'هر تغییر اینجاست.', 'جهان اول رونویس می‌شود.'],
    rw: ['Izina rishya: Bertopia.', 'Bertyville ni yo.', 'Impinduka zose ziri hano.', 'Isi ikoporwa mbere.'],
    ti: ['ሓድሽ ስም: በርቶፕያ.', 'ሓደ በርቲቪል.', 'ኩሉ ለውጢ ኣብዚ.', 'ዓለም ቅድሚኡ ትቕዳሕ።'],
  }},
  { v: '2.5.0', date: '2026-10-03', lines: { en: ['A picture tour.', 'Try this goals.', 'No flying in Survival.', 'Send Cogs to your teacher.'] } },
  { v: '2.4.0', date: '2026-10-03', lines: { en: ['Build Tools do the edit.', 'Undo takes a whole Fill back.', 'The counter keeps its key.'] } },
  { v: '2.3.0', date: '2026-10-03', lines: { en: ['Esc stays in the menu.', 'Exit asks first.', 'Headers sit below the bar.'] } },
  { v: '2.2.0', date: '2026-10-03', lines: { en: ['A big menu.', 'A Coreplate floor.', 'A shop and a counter.'] } },
  { v: '2.1.0', date: '2026-10-03', lines: { en: ['Undo a whole step.', 'Inspect a block.', 'Pick a block.'] } },
  { v: '2.0.0', date: '2026-10-03', lines: { en: ['The first Bertopia door.', 'Bertyville starter world.', 'Build Table mode.'] } },
]
