export const CHANGELOG = [
  { v: '2.5.37', date: '2026-10-05', lines: {
    en: ['The shop has a workbench, an oven, the store, and a bunk.', 'The shop, the road, the pond, and the plot edges stay unless a teacher allows this device to change the town.', 'Students build on the marked plots, or outside town.'],
    uk: ['У крамниці є верстат, піч, крамниця і ліжко.', 'Крамниця, дорога, ставок і краї ділянок лишаються, доки вчитель не дозволить цьому пристрою змінювати місто.', 'Учні будують на ділянках або за містом.'],
    ru: ['В лавке есть верстак, печь, прилавок и кровать.', 'Лавка, дорога, пруд и края участков остаются, пока учитель не разрешит этому устройству менять город.', 'Ученики строят на участках или за городом.'],
    es: ['La tienda tiene mesa, horno, mostrador y litera.', 'La tienda, el camino, el estanque y los bordes se quedan, salvo que el profe deje que este aparato cambie el pueblo.', 'Los alumnos construyen en los solares o fuera del pueblo.'],
    ar: ['في الدكان طاولة عمل وفرن ومتجر وسرير.', 'الدكان والطريق والبركة وحواف القطع تبقى، إلا إذا سمح المعلم لهذا الجهاز بتغيير البلدة.', 'التلاميذ يبنون على القطع أو خارج البلدة.'],
    'fa-AF': ['در دکان میز کار، تنور، دکان و بستر است.', 'دکان، راه، حوض و لبه قطعه‌ها می‌مانند، مگر معلم به این دستگاه اجازه تغییر شهر بدهد.', 'شاگردان روی قطعه‌ها یا بیرون شهر می‌سازند.'],
    rw: ['Iduka rifite akameza, ifuru, iduka n\'uburiri.', 'Iduka, umuhanda, ikiyaga n\'impera z\'ibice biguma, keretse umwarimu yemeye iki gikoresho guhindura umudugudu.', 'Abanyeshuri babaka ku bice cyangwa hanze.'],
    ti: ['ኣብ ድኳን መደብይ፡ እቶን፡ መደብርን ዓራትን ኣሎ።', 'ድኳን፡ መንገዲ፡ ቀላይን ወሰን መሬትን ይቕጽሉ፡ እንተዘይ ኮይኑ መምህር ነዚ መሳርሒ ከተማ ክቅይር ምስ ፈቐደ።', 'ተምሃሮ ኣብ መሬት ወይ ወጻኢ ይሃንጹ።'],
  }},
  { v: '2.5.36', date: '2026-10-05', lines: {
    en: ['The corner says Survival, not Survival practice.', 'The bag lines up as 3 by 3 and 3 by 2.', 'The lit hotbar slot is marked in the bag.', 'What\'s new describes this game, not an old note.'],
    uk: ['У куті написано Виживання, без слова про навчання.', 'Сумка рівна: 3 на 3 і 3 на 2.', 'Обране місце панелі позначене в сумці.', 'Що нового описує цю гру, не стару нотатку.'],
    ru: ['В углу написано Выживание, без слова про учёбу.', 'Сумка ровная: 3 на 3 и 3 на 2.', 'Выбранное место панели отмечено в сумке.', 'Что нового описывает эту игру, не старую заметку.'],
    es: ['La esquina dice Supervivencia, no práctica.', 'La bolsa queda en 3 por 3 y 3 por 2.', 'El hueco elegido de la barra se marca en la bolsa.', 'Novedades describe este juego, no una nota vieja.'],
    ar: ['الزاوية تقول البقاء، لا تدريب.', 'الحقيبة تصطف 3 في 3 و3 في 2.', 'خانة الشريط المضاءة معلّمة في الحقيبة.', 'ما الجديد يصف هذه اللعبة، لا ملاحظة قديمة.'],
    'fa-AF': ['گوشه بقا می‌گوید، نه تمرین.', 'بکس ۳ در ۳ و ۳ در ۲ ردیف می‌شود.', 'خانه روشن نوار در بکس نشان داده می‌شود.', 'تازه‌ها همین بازی را می‌گوید، نه یک یادداشت کهنه.'],
    rw: ['Ahantu havuga Ubugingo, ntabwo havuga imyitozo.', 'Agasaho gitegeka 3 ku 3 na 3 ku 2.', 'Akanya gatoranyijwe kagaragara mu gasaho.', 'Ibishya bivuga uyu mukino, ntabwo ari inyandiko ishaje.'],
    ti: ['ኩርናዕ ህይወት ይብል እምበር ምልምማድ ኣይብልን።', 'ቦርሳ 3 ብ 3ን 3 ብ 2ን ትሰለፍ።', 'ዝበርሀ መስመር ኣብ ቦርሳ ይረአ።', 'ሓድሽ ነዚ ጸወታ እዩ ዝገልጽ እምበር ነቲ ናይ ቀደም ጽሑፍ ኣይኮነን።'],
  }},
  { v: '2.5.35', date: '2026-10-05', lines: {
    en: ['The game stops copying a long list every frame after it has been open a while.', 'Loose items no longer build throwaway lists every frame.', 'The camera updates only when the view actually changes.'],
    uk: ['Гра більше не копіює довгий список щокадру, коли вона довго відкрита.', 'Речі на землі не створюють зайві списки щокадру.', 'Камера оновлюється лише коли вигляд справді змінюється.'],
    ru: ['Игра больше не копирует длинный список каждый кадр, когда она долго открыта.', 'Вещи на земле не создают лишние списки каждый кадр.', 'Камера обновляется только когда вид правда меняется.'],
    es: ['El juego deja de copiar una lista larga cada cuadro cuando lleva un rato abierto.', 'Los objetos en el suelo ya no arman listas de más cada cuadro.', 'La cámara cambia solo cuando la vista cambia de verdad.'],
    ar: ['اللعبة تتوقف عن نسخ قائمة طويلة كل إطار بعد أن تبقى مفتوحة.', 'الأشياء على الأرض لا تصنع قوائم زائدة كل إطار.', 'المنظر يتحدث فقط عندما يتغير فعلاً.'],
    'fa-AF': ['بازی بعد از مدتی باز بودن، دیگر هر فریم یک فهرست بلند را کپی نمی‌کند.', 'چیزهای روی زمین دیگر هر فریم فهرست اضافی نمی‌سازند.', 'دوربین فقط وقتی نما واقعاً عوض شود تازه می‌شود.'],
    rw: ['Umukino uhagaze gukoporora urutonde rurerure buri kadr iyo wamaze igihe ufunguye.', 'Ibintu hasi ntibikora izindi lisiti buri kadr.', 'Kamera ihinduka gusa iyo uko ureba byahindutse.'],
    ti: ['ጸወታ ድሕሪ ምጽናሕ ነዊሕ ዝርዝር ኣብ ነፍሲ ወከፍ ፍሬም ኣይቅዳሕን።', 'ኣብ መሬት ዘለዉ ነገራት ተወሳኺ ዝርዝር ኣብ ነፍሲ ወከፍ ፍሬም ኣይሰርሑን።', 'ካሜራ ኣብ እዋን እቲ ምርኢት ምስ ተቐየረ ጥራይ ይመሓየሽ።'],
  }},
  { v: '2.5.34', date: '2026-10-05', lines: {
    en: ['Hold this takes the stack you tapped, not the first one.', 'Tapping Survival again does not reload the world.', 'An empty slot no longer says you are out of stone.', 'A standing jump cannot turn into a sprint in the air.'],
    uk: ['Тримати бере той стос, який ти натиснув.', 'Повторне Виживання не перезавантажує світ.', 'Порожнє місце не каже, що немає каменю.', 'Стрибок з місця не стає бігом у повітрі.'],
    ru: ['Держать берёт ту стопку, которую ты нажал.', 'Повторное Выживание не перезагружает мир.', 'Пустое место не говорит, что нет камня.', 'Прыжок с места не становится бегом в воздухе.'],
    es: ['Sostener toma la pila que tocaste, no la primera.', 'Tocar Supervivencia otra vez no recarga el mundo.', 'Un hueco vacío ya no dice que no tienes piedra.', 'Un salto quieto no se vuelve carrera en el aire.'],
    ar: ['أمسك هذا يأخذ الكومة التي لمستها، لا الأولى.', 'لمس البقاء مرة أخرى لا يعيد تحميل العالم.', 'الخانة الفارغة لا تقول إنك بلا حجر.', 'القفز من الوقوف لا يصير جرياً في الهواء.'],
    'fa-AF': ['این را بگیر همان پشته‌ای را می‌گیرد که زدی، نه اولی را.', 'زدن دوباره بقا جهان را از نو بار نمی‌کند.', 'خانه خالی دیگر نمی‌گوید سنگ نداری.', 'پریدن از ایستادن در هوا دویدن نمی‌شود.'],
    rw: ['Fata iki ifata umufuka wagukande, si uwa mbere.', 'Gukanda Ubugingo kandi ntabwo bisubiza isi.', 'Akanya karimo ubusa ntikivuga ko udafite ibuye.', 'Gusimbuka uhagaze ntibiba kwiruka mu kirere.'],
    ti: ['እዚ ሓዝ ነቲ ዝጠወቕካዮ ዕስለ እዩ ዝወስድ።', 'ህይወት ደጊምካ ምጥዋቕ ዓለም ኣይመልስን።', 'ባዶ ቦታ ድምጺ ከም ዘይብልካ ኣይብልን።', 'ካብ ምጽናሕ ምንጻ ኣብ ኣየር ምጉያይ ኣይኸውንን።'],
  }},
  { v: '2.5.33', date: '2026-10-05', lines: {
    en: ['Older stacks say they are in Lost & Found.', 'The keys no longer promise flight. A slow block no longer promises a copper tool.', 'You cannot go faster in the air than you were going.', 'Hold this moves a pocket stack onto the hotbar.', 'Survival is the mode. Creative stays hidden unless this device can build.'],
    uk: ['Старі стоси кажуть, що вони в Загубленому.', 'Клавіші більше не обіцяють політ. Повільний блок не обіцяє мідь.', 'У повітрі не швидше, ніж ти йшов.', 'Тримати переносить стос із кишені на панель.', 'Режим — Виживання. Творчий схований, якщо пристрій не для будівлі.'],
    ru: ['Старые стопки говорят, что они в Потерянном.', 'Клавиши больше не обещают полёт. Медленный блок не обещает медь.', 'В воздухе не быстрее, чем ты шёл.', 'Держать переносит стопку из кармана на панель.', 'Режим — Выживание. Творческий спрятан, если устройство не для стройки.'],
    es: ['Las pilas viejas dicen que están en Perdidos.', 'Las teclas ya no prometen volar. Un bloque lento no promete cobre.', 'En el aire no vas más rápido de lo que ibas.', 'Sostener pasa una pila del bolsillo a la barra.', 'El modo es Supervivencia. Creativo sigue oculto si este aparato no puede construir.'],
    ar: ['الأكوام القديمة تقول إنها في المفقودات.', 'المفاتيح لم تعد تعد بالطيران. المكعب البطيء لا يعد بالنحاس.', 'في الهواء لست أسرع مما كنت.', 'أمسك هذا ينقل كومة من الجيب إلى الشريط.', 'الوضع هو البقاء. الإبداعي مخفي إلا إذا كان الجهاز يبني.'],
    'fa-AF': ['پشته‌های قدیمی می‌گویند در گم‌شده‌ها هستند.', 'کلیدها دیگر پرواز را وعده نمی‌دهند. بلاک کند مس را وعده نمی‌دهد.', 'در هوا از سرعتی که داشتی تندتر نمی‌شوی.', 'این را بگیر پشته را از جیب به نوار می‌برد.', 'حالت بقا است. خلاق پنهان است مگر این دستگاه بسازد.'],
    rw: ['Imifuka ishaje ivuga ko iri mu byabuze.', 'Utubuto ntikivuga kuguruka. Block idatevya ntivuga copper.', 'Mu kirere ntiwiruka kurusha uko wari.', 'Fata iki imura umufuka ku majepo ujye ku mukandara.', 'Uburyo ni Ubugingo. Creative ihishe keretse iki gikoresho gishobora kubaka.'],
    ti: ['ናይ ቀደም ዕስለ ኣብ ዝጠፍአ ከም ዘሎ ይብል።', 'መጠወቒታት ምንፋስ ኣይቃረጹን። ዝንጋገ ብሎክ ነሓስ ኣይቃረጽን።', 'ኣብ ኣየር ካብቲ ዝነበርካ ፍጥነት ኣይትሓልፍን።', 'እዚ ሓዝ ዕስለ ካብ ጁባ ናብ መስመር የሕልፍ።', 'ኩነታት ህይወት እዩ። ፈጣሪ ተሓቢኡ እዩ እንተ ኣይሃንጽን እዚ መሳርሒ።'],
  }},
  { v: '2.5.32', date: '2026-10-04', lines: {
    en: ['The bag is 9 in the hotbar and 6 pockets.', 'Older stacks that do not fit wait in Lost & Found. Nothing is deleted.', 'A new visit starts in Survival.', 'The build world is under Teacher. A student does not see it.'],
    uk: ['Сумка — 9 на панелі і 6 кишень.', 'Старі стоси, що не вмістились, чекають у Загубленому. Нічого не стерто.', 'Новий візит починається у Виживанні.', 'Світ будівлі під Вчителем. Учень його не бачить.'],
    ru: ['Сумка — 9 на панели и 6 карманов.', 'Старые стопки, которые не влезли, ждут в Потерянном. Ничего не стёрто.', 'Новый визит начинается в Выживании.', 'Мир стройки у Учителя. Ученик его не видит.'],
    es: ['La bolsa es 9 en la barra y 6 bolsillos.', 'Lo que no cabe espera en Perdidos. No se borra nada.', 'Una visita nueva empieza en Supervivencia.', 'El mundo de construir está en Profe. Un alumno no lo ve.'],
    ar: ['الحقيبة 9 في الشريط و6 جيوب.', 'ما لا يتسع ينتظر في المفقودات. لا شيء يُحذف.', 'الزيارة الجديدة تبدأ في البقاء.', 'عالم البناء عند المعلم. التلميذ لا يراه.'],
    'fa-AF': ['بکس ۹ در نوار و ۶ جیب است.', 'آنچه جا نمی‌شود در گم‌شده‌ها می‌ماند. هیچ چیز پاک نمی‌شود.', 'بازدید تازه در بقا شروع می‌شود.', 'جهان ساختن زیر معلم است. شاگرد آن را نمی‌بیند.'],
    rw: ['Agasaho ni 9 ku mukandara na 6 majepo.', 'Ibitageze bitegereje mu byabuze. Nta kigisibwaho.', 'Isura nshya itangira mu Bugingo.', 'Isi yo kubaka iri ku mwarimu. Umunyeshuri ntayibona.'],
    ti: ['ቦርሳ 9 ኣብ መስመርን 6 ጁባን እዩ።', 'ዘይኣቱ ኣብ ዝጠፍአ ይጽንሕ። ዝተደምሰሰ የለን።', 'ሓድሽ ምብጻሕ ኣብ ህይወት ይጅምር።', 'ዓለም ህንጻ ኣብ መምህር እዩ። ተምሃራይ ኣይርእዮን።'],
  }},
  { v: '2.5.31', date: '2026-10-04', lines: {
    en: ['Press the same number again to use that slot. Holding the key does not eat the stack.', 'A block no longer pops a toast just for being selected.', 'The name under Bertopia matches the lit slot.', 'Right click stops placing when you let go or open a menu.', 'Pick moves to the other side when the stick is on the right.', 'Pick follows the language.'],
    uk: ['Натисни той самий номер ще раз, щоб використати. Утримання не зʼїдає стос.', 'Блок більше не вигукує назву просто за вибір.', 'Права кнопка перестає ставити, коли відпускаєш або відкриваєш меню.', 'Взяти переходить на інший бік, якщо стик справа.', 'Взяти мовою гри.'],
    ru: ['Нажми тот же номер ещё раз, чтобы использовать. Удержание не съедает стопку.', 'Блок больше не кричит имя просто за выбор.', 'Правая кнопка перестаёт ставить, когда отпускаешь или открываешь меню.', 'Взять переходит на другую сторону, если стик справа.', 'Взять на языке игры.'],
    es: ['Pulsa el mismo número otra vez para usarlo. Mantenerlo no se come la pila.', 'Un bloque ya no grita su nombre solo por elegirlo.', 'El clic derecho deja de poner al soltar o al abrir un menú.', 'Tomar pasa al otro lado si el stick está a la derecha.', 'Tomar sigue el idioma.'],
    ar: ['اضغط الرقم نفسه مرة أخرى للاستخدام. الإمساك لا يأكل الكومة.', 'المكعب لم يعد يصرخ باسمه لمجرد اختياره.', 'الزر الأيمن يتوقف عن الوضع عند الترك أو فتح قائمة.', 'التقط ينتقل للجهة الأخرى إذا كانت العصا يميناً.', 'التقط يتبع اللغة.'],
    'fa-AF': ['همان شماره را دوباره بزن تا استفاده شود. نگه داشتن پشته را نمی‌خورد.', 'بلاک فقط برای انتخاب نامش را فریاد نمی‌زند.', 'کلیک راست با ول کردن یا باز کردن فهرست می‌ایستد.', 'بردار وقتی اهرم راست است به سمت دیگر می‌رود.', 'بردار زبان را دنبال می‌کند.'],
    rw: ['Kanda nomero nyayo nanone ukoreshe. Kuyikomeza ntibirya umufuka.', 'Block ntikivuga izina gusa kubera kuyihitamo.', 'Iburyo bihagarara iyo ubisezeraho cyangwa ukinguye ibikubiyemo.', 'Fata yimukira iyindi ruhande iyo agastike kari iburyo.', 'Fata ikurikira ururimi.'],
    ti: ['ተመሳሳሊ ቁጽሪ ደጊምካ ጠውቕ ንምጥቃም። ምሓዝ እቲ ዕስለ ኣይበልዖን።', 'ብሎክ ስለ ዝተመርጸ ስሙ ኣይጭርን።', 'የማናይ ምቕማጥ የቋርጽ ምስ እትለቕቆ ወይ ዝርዝር ምስ እትኸፍት።', 'ውሰድ እንተ የማናይ ስቲክ ናብ ኻሊእ ገጽ ይኸይድ።', 'ውሰድ ቋንቋ ይስዕብ።'],
  }},
  { v: '2.5.30', date: '2026-10-04', lines: {
    en: ['Hold right click to keep placing. A touch tap still places one.', 'Tap the selected slot again to use it. Bread, berry, and cupcake get eaten.', 'F does the same.', 'Crouch stops at a ledge.', 'Settings has Auto-climb. Phones start with it on.', 'Pick, then tap a block. Survival only picks a block you have.'],
    uk: ['Тримай праву кнопку, щоб ставити далі. Дотик ставить один.', 'Торкнись вибраного слота ще раз. Хліб, ягода і кекс зʼїдаються.', 'F теж.', 'Присід зупиняється на краю.', 'У налаштуваннях автосхід. На телефоні він увімкнений.', 'Взяти, потім торкнись блока. У Виживанні лише якщо він у сумці.'],
    ru: ['Держи правую кнопку, чтобы ставить дальше. Касание ставит один.', 'Нажми выбранный слот ещё раз. Хлеб, ягода и кекс съедаются.', 'F тоже.', 'Присед останавливается на краю.', 'В настройках автоподъём. На телефоне он включён.', 'Взять, потом нажми блок. В Выживании только если он в сумке.'],
    es: ['Mantén el clic derecho para seguir poniendo. Un toque pone uno.', 'Toca otra vez la casilla elegida. El pan, la baya y el cupcake se comen.', 'F hace lo mismo.', 'Agacharte para en un borde.', 'Ajustes tiene Auto-subir. En el teléfono empieza activo.', 'Tomar, luego toca un bloque. En Supervivencia solo si lo tienes.'],
    ar: ['اضغط الزر الأيمن مطولاً لتضع أكثر. اللمسة تضع واحداً.', 'اضغط الخانة المختارة مرة أخرى. الخبز والتوت والكعك تُؤكل.', 'F يفعل ذلك.', 'الانحناء يقف عند الحافة.', 'الإعدادات فيها تسلّق تلقائي. الهاتف يبدأ به.', 'التقط ثم المس مكعباً. في البقاء فقط إذا كان في حقيبتك.'],
    'fa-AF': ['کلیک راست را نگه دار تا بیشتر بگذاری. لمس یکی می‌گذارد.', 'خانهٔ انتخاب‌شده را دوباره بزن. نان، توت و کاپ‌کیک خورده می‌شوند.', 'F همان است.', 'خم شدن لبه‌ را رد نمی‌کند.', 'تنظیمات بالارفتن خودکار دارد. گوشی با آن روشن شروع می‌شود.', 'بردار، بعد بلاک را بزن. در بقا فقط اگر در بکس باشد.'],
    rw: ['Fata iburyo ushyire byinshi. Gutera gushyira kimwe.', 'Kanda akazu wahisemo nanone. Umugati, imbuto na kek biribwa.', 'F ni ko.', 'Kwicarama bihagarara ku musozi.', 'Igenamiterere ifite Kuzamuka. Telefoni itangira ikaye.', 'Fata, ukande block. Mu Bugingo ni iyo iri mu gasaho.'],
    ti: ['የማናይ ሓዝ ንዝያዳ ምቕማጥ። ምትንካእ ሓደ የቐምጥ።', 'ዝተመርጸ ቦታ ደጊምካ ጠውቕ። ባኒ፡ ፍረን ኬክን ይበላዕ።', 'F እውን።', 'ምድንጋር ኣብ ወሰን ይቁም።', 'ቅንጅታት ባዕሉ ምውጻእ ኣለዎ። ተሌፎን ብእዚ ይጅምር።', 'ውሰድ፡ ድሕሪኡ ብሎክ ጠውቕ። ኣብ ህይወት እንተ ኣብ ቦርሳ ጥራይ።'],
  }},
  { v: '2.5.29', date: '2026-10-04', lines: {
    en: ['Cracks grow in four steps.', 'Let go and the cracks fade. Press again and they come back.', 'Leaves break fast. Stone takes a copper tool hint after two seconds.', 'Settings has Wide view.'],
    uk: ['Тріщини ростуть у чотири кроки.', 'Відпусти — гаснуть. Натисни знову — повертаються.', 'Листя ламається швидко. Камінь через дві секунди нагадує про мідь.', 'У налаштуваннях широкий огляд.'],
    ru: ['Трещины растут в четыре шага.', 'Отпусти — гаснут. Нажми снова — возвращаются.', 'Листва ломается быстро. Камень через две секунды напоминает про медь.', 'В настройках широкий обзор.'],
    es: ['Las grietas crecen en cuatro pasos.', 'Suelta y se apagan. Pulsa otra vez y vuelven.', 'Las hojas se rompen rápido. La piedra avisa del cobre a los dos segundos.', 'Ajustes tiene Vista ancha.'],
    ar: ['الشقوق تكبر في أربع خطوات.', 'اتركها فتخبو. اضغط مرة أخرى فتعود.', 'الأوراق تنكسر بسرعة. الحجر ينبّه للنحاس بعد ثانيتين.', 'الإعدادات فيها عرض واسع.'],
    'fa-AF': ['ترک‌ها در چهار گام بزرگ می‌شوند.', 'ول کن، کم می‌شوند. دوباره فشار بده، برمی‌گردند.', 'برگ زود می‌شکند. سنگ بعد از دو ثانیه از مس می‌گوید.', 'تنظیمات نمای پهن دارد.'],
    rw: ['Ibisebe birakura mu ntambwe enye.', 'Reka bigabanuke. Kanda nanone bigaruke.', 'Amababi aravuna vuba. Ibuye nyuma y’amasegonda 2 kivuga copper.', 'Igenamiterere ifite Reba byagutse.'],
    ti: ['ስንጥቃት ብ4 ስጉምቲ ይዓቢ።', 'ሓድጎ ይጠፍእ። ደጊምካ ጠውቕ ይምለስ።', 'ቆጽሊ ብቕልጡፍ ይስበር። እምኒ ድሕሪ 2 ካልኢት ነሓስ የዘኻኽር።', 'ቅንጅታት ሰፊሕ ምርኣይ ኣለዎ።'],
  }},
  { v: '2.5.28', date: '2026-10-04', lines: {
    en: ['Menus are solid, so the world does not show through.', 'Craft names sit above the missing pieces, in gold.', 'Shop locks start on their own row, with a picture.'],
    uk: ['Меню щільне, світ не просвічує.', 'Назва рецепта над браком, золотим.', 'Замки крамниці з картинкою, окремим рядом.'],
    ru: ['Меню плотное, мир не просвечивает.', 'Имя рецепта над нехваткой, золотым.', 'Замки лавки с картинкой, отдельным рядом.'],
    es: ['Los menús son sólidos. El mundo no se ve detrás.', 'El nombre va arriba de lo que falta, en dorado.', 'La tienda pone los candados en su propia fila, con dibujo.'],
    ar: ['القوائم صلبة، العالم لا يظهر من خلفها.', 'اسم الوصفة فوق الناقص، بالذهبي.', 'أقفال المتجر في صف وحدها، مع صورة.'],
    'fa-AF': ['فهرست‌ها توپرند و جهان از پشت دیده نمی‌شود.', 'نام دستور بالای کمبود است، طلایی.', 'قفل‌های دکان در ردیف خود، با تصویر.'],
    rw: ['Ibikubiyemo biruzuye, isi ntigaragara.', 'Izina riri hejuru y’ibibura, mu zahabu.', 'Ibikoba by’iduka biri ku murongo wabyo, n’ishusho.'],
    ti: ['ዝርዝራት ጽኑዕ እዮም። ዓለም ኣይረአን።', 'ስም ኣብ ላዕሊ እቲ ዝጎደለ፣ ወርቂ።', 'መዕጸዊ ድኳን ኣብ መስመሩ፡ ምስ ስእሊ።'],
  }},
  { v: '2.5.27', date: '2026-10-04', lines: {
    en: ['Craft rows use the full width.', 'A recipe keeps its name when it needs a bench or an oven.'],
    uk: ['Рядки крафту на всю ширину.', 'Рецепт лишає назву, навіть якщо потрібен верстак чи піч.'],
    ru: ['Строки крафта на всю ширину.', 'Рецепт сохраняет имя, даже если нужен верстак или печь.'],
    es: ['Las recetas usan todo el ancho.', 'La receta conserva su nombre aunque necesite banco u horno.'],
    ar: ['صفوف الصنع بعرض الشاشة.', 'الوصفة تُبقي اسمها حتى لو احتاجت منضدة أو فرناً.'],
    'fa-AF': ['ردیف ساختن تمام عرض را می‌گیرد.', 'دستور نامش را نگه می‌دارد حتی اگر میز یا تنور بخواهد.'],
    rw: ['Imirongo ikoresha ubugari bwose.', 'Isosiyete isigara izina nubwo ikeneye ameza cyangwa ibyoto.'],
    ti: ['መስመራት ስራሕ ምሉእ ስፍሓት።', 'ዝርዝር ስሙ ይጸንሕ እንተደኣ እቶን ወይ ሰደቓ ዘድልዮ።'],
  }},
  { v: '2.5.26', date: '2026-10-04', lines: {
    en: ['Craft lists Can make now, Almost, and Show all.', '×Max makes as many as you can.', 'The shop sells a material only after you find it.', 'Settings has Look speed and Invert look.'],
    uk: ['Крафт: Можна зараз, Майже, Показати все.', '×Max робить скільки можеш.', 'Крамниця продає матеріал після того, як знайдеш.', 'У налаштуваннях швидкість і переворот огляду.'],
    ru: ['Крафт: Можно сейчас, Почти, Показать все.', '×Max делает сколько можешь.', 'Лавка продаёт материал после находки.', 'В настройках скорость и переворот взгляда.'],
    es: ['Fabricar: Puedes hacer, Casi y Ver todo.', '×Max hace todos los que puedas.', 'La tienda vende un material solo si ya lo encontraste.', 'Ajustes: velocidad de mirada e invertir.'],
    ar: ['الصنع: يمكنك الآن، تقريباً، وأظهر الكل.', '×Max يصنع كل ما تستطيع.', 'المتجر يبيع المادة بعد أن تجدها.', 'الإعدادات: سرعة النظر وعكسه.'],
    'fa-AF': ['ساختن: حالا، نزدیک، و همه.', '×Max هر چه بتوانی می‌سازد.', 'دکان ماده را بعد از پیدا کردن می‌فروشد.', 'تنظیمات: سرعت نگاه و برگرداندن.'],
    rw: ['Gukora: Ushobora ubu, Hafi, Erekana byose.', '×Max ikora ibyo ushobora.', 'Iduka rigurisha nyuma yo kubona.', 'Igenamiterere: umuvuduko n\'ihindura.'],
    ti: ['ስራሕ፡ ሕጂ፣ ዳርጋ፣ ኩሉ ኣርኢ።', '×Max ክንደይ ከም እትኽእል ይሰርሕ።', 'ድኳን ድሕሪ ምርካብ ይሸይጥ።', 'ቅንጅታት፡ ፍጥነትን ግልባጥን ምርኣይ።'],
  }},
  { v: '2.5.25', date: '2026-10-04', lines: {
    en: ['A drop hops into your bag when you walk up to it.', 'Counters and bunks stay until you pick them up.'],
    uk: ['Річ стрибає в сумку, коли підходиш.', 'Прилавки й ліжка лишаються, поки їх не забереш.'],
    ru: ['Вещь прыгает в сумку, когда подходишь.', 'Прилавки и кровати остаются, пока их не заберёшь.'],
    es: ['Lo que cae entra en la bolsa al acercarte.', 'Los mostradores y las literas se quedan hasta que los recoges.'],
    ar: ['ما يسقط يدخل الحقيبة حين تقترب.', 'المنضدة والسرير يبقيان حتى تلتقطهما.'],
    'fa-AF': ['چیز افتاده وقتی نزدیک شوی به بکس می‌آید.', 'پیشخوان و بستر تا وقتی برنداری می‌مانند.'],
    rw: ['Icyataye kiza mu gasaho niyo uhageze.', 'Counter na buriri bisigara kugeza ubitwaye.'],
    ti: ['ዝወደቐ ናብ ቦርሳ ይመጽእ ምስ ቀረብካ።', 'መደብን ዓራትን ክሳብ እትልዕሎም ይጸንሑ።'],
  }},
  { v: '2.5.24', date: '2026-10-04', lines: {
    en: ['A full bag still breaks the block.', 'The piece waits on the ground.', 'Q drops one. Shift+Q drops the stack.'],
    uk: ['Повна сумка все одно ламає блок.', 'Шматок чекає на землі.', 'Q кидає 1. Shift+Q кидає стос.'],
    ru: ['Полная сумка всё равно ломает блок.', 'Кусок ждёт на земле.', 'Q бросает 1. Shift+Q бросает стопку.'],
    es: ['La bolsa llena igual rompe el bloque.', 'La pieza espera en el suelo.', 'Q suelta uno. Mayús+Q suelta la pila.'],
    ar: ['الحقيبة الممتلئة تكسر المكعب أيضاً.', 'القطعة تنتظر على الأرض.', 'Q يُسقط واحداً. Shift+Q يُسقط الكومة.'],
    'fa-AF': ['بکس پر هم بلاک را می‌شکند.', 'تکه روی زمین می‌ماند.', 'Q یکی می‌اندازد. Shift+Q همه را.'],
    rw: ['Agasaho karuzuye karavunagura block.', 'Igice kitera hasi.', 'Q ikubita 1. Shift+Q ikubita byose.'],
    ti: ['ቦርሳ ምሉእ እኳ ብሎክ ይስብር።', 'እቲ ቁራጽ ኣብ መሬት ይጸንሕ።', 'Q ሓደ የውድቕ። Shift+Q ዓምቦ የውድቕ።'],
  }},
  { v: '2.5.23', date: '2026-10-04', lines: {
    en: ['A brighter sky and a soft horizon.', 'Berty wears a teal suit.', 'The block you hold shows its name.'],
    uk: ['Яскравіше небо і м’який обрій.', 'Берті в бірюзовому костюмі.', 'Блок у руці показує назву.'],
    ru: ['Ярче небо и мягкий горизонт.', 'Берти в бирюзовом костюме.', 'Блок в руке показывает имя.'],
    es: ['Un cielo más claro y un horizonte suave.', 'Berty lleva un traje verde azulado.', 'El bloque en la mano dice su nombre.'],
    ar: ['سماء أسطع وأفق ناعم.', 'بيرتي ببدلة فيروزية.', 'المكعب في يدك يُظهر اسمه.'],
    'fa-AF': ['آسمانی روشن‌تر و افق نرم.', 'برتی لباس تیل پوشیده است.', 'بلاک در دست نامش را نشان می‌دهد.'],
    rw: ['Ijuru rirakeye n’umupaka woroshye.', 'Berty yambaye ikositimu ya teal.', 'Block ufite yerekana izina.'],
    ti: ['ብርሃን ዝበለ ጠፈርን ልስሉስ ኣድማስን።', 'በርቲ ብቲል ክዳን ኣለዎ።', 'እቲ ብሎክ ስሙ የርኢ።'],
  }},
  { v: '2.5.22', date: '2026-10-04', lines: {
    en: ['One thumb stick and a one-block jump.', 'Hold to mine. A short tap places.', 'Walk, run, and crouch.'],
    uk: ['Один стік і стрибок на один блок.', 'Тримай щоб ламати. Короткий дотик ставить.', 'Крок, біг і присід.'],
    ru: ['Один стик и прыжок на один блок.', 'Держи чтобы ломать. Короткое касание ставит.', 'Шаг, бег и присед.'],
    es: ['Un stick y un salto de un bloque.', 'Mantén para romper. Un toque corto pone.', 'Caminar, correr y agacharse.'],
    ar: ['عصا بإبهام واحد وقفزة بارتفاع مكعب.', 'اضغط مطولاً للكسر. اللمسة القصيرة تضع.', 'مشي وجري وانحناء.'],
    'fa-AF': ['یک اهرم با یک شست و پرش به اندازه یک بلاک.', 'نگه دار تا بشکند. لمس کوتاه می‌گذارد.', 'راه رفتن، دویدن و خم شدن.'],
    rw: ['Agastike kamwe n’igisimbu cy’igice kimwe.', 'Fata uvune. Gukora gato gushyira.', 'Kugenda, kwiruka, kwicaramye.'],
    ti: ['ሓንቲ ስቲክን ሓደ ብሎክ ዝነጥ ጅምፕን።', 'ሓዝ ንምስባር። ሓጺር ምጥዋቕ የቐምጥ።', 'ምኻድ፣ ምጉያይ፣ ምድንጋር።'],
  }},
  { v: '2.5.21', date: '2026-10-04', lines: {
    en: ['Arabic and Dari menu taps open the menu.', 'The tour does not replace the menu.'],
    ar: ['نقرة القائمة تفتح القائمة.', 'الجولة لا تحل محل القائمة.'],
    'fa-AF': ['زدن فهرست، فهرست را باز می‌کند.', 'گشت جای فهرست را نمی‌گیرد.'],
  }},
  { v: '2.5.1', date: '2026-10-03', lines: {
    en: ['New name: Bertopia.', 'Same Bertyville world.', 'See every change here.'],
    uk: ['Нова назва: Бертопія.', 'Той самий Бертивіль.', 'Усі зміни тут.', 'Світ копіюється спершу.'],
    ru: ['Новое имя: Бертопия.', 'Тот же Бертивиль.', 'Все изменения здесь.', 'Мир копируется сначала.'],
    es: ['Nuevo nombre: Bertopia.', 'El mismo Bertyville.', 'Cada cambio está aquí.', 'El mundo se copia antes.'],
    ar: ['اسم جديد: بيرتوبيا.', 'نفس بيرتيفيل.', 'كل تغيير هنا.', 'يُنسخ العالم أولاً.'],
    'fa-AF': ['نام نو: برتوپیا.', 'همان برتی‌ویل.', 'هر تغییر اینجاست.', 'جهان اول رونویس می‌شود.'],
    rw: ['Izina rishya: Bertopia.', 'Bertyville ni yo.', 'Impinduka zose ziri hano.', 'Isi ikoporwa mbere.'],
    ti: ['ሓድሽ ስም: በርቶፕያ.', 'ሓደ በርቲቪል.', 'ኩሉ ለውጢ ኣብዚ.', 'ዓለም ቅድሚኡ ትቕዳሕ።'],
  }},
  { v: '2.5.0', date: '2026-10-03', lines: { en: ['A picture tour.', 'Try this goals.', 'No flying in Survival.', 'Send Cogs to your teacher.'] } },
  { v: '2.4.0', date: '2026-10-03', lines: { en: ['Build Tools do the edit.', 'Undo takes a whole Fill back.', 'The counter keeps its key.'] } },
  { v: '2.3.0', date: '2026-10-03', lines: { en: ['Esc stays in the menu.', 'Exit asks first.', 'Headers sit below the bar.'] } },
  { v: '2.2.0', date: '2026-10-03', lines: { en: ['A big menu.', 'A Coreplate floor.', 'A shop and a counter.'] } },
  { v: '2.1.0', date: '2026-10-03', lines: { en: ['Undo a whole step.', 'Inspect a block.', 'Pick a block.'] } },
  { v: '2.0.0', date: '2026-10-03', lines: { en: ['The first Bertopia door.', 'Bertyville starter world.', 'Build Table mode.'] } },
]
