// Extra 2.2.0 strings. Dari is Dari, not Arabic.
export const EXTRA = {
  en: {
    berry: 'Berry', flour: 'Flour', sugar: 'Sugar', cupcake: 'Cupcake', bread: 'Bread', coreplate: 'Coreplate', workbench: 'Workbench', oven: 'Oven', vend: 'Vending Counter', storeCounter: 'Store Counter', bunk: 'Bunk',
    whatsNewBody: 'Bloxbert 2.2.0: A big ☰ menu (or press Esc). A Survival world with a bag, crafting and practice Cogs. Sell to Tally at the General Store, run your own Vending Counter, and a Coreplate floor keeps you safe.',
    menuHint: 'Tap ☰ or press Esc for menu', menuHintTouch: 'Tap ☰ for menu', resume: 'Resume', inventory: 'Inventory', crafting: 'Crafting', shop: 'Shop', wallet: 'Wallet',
    practice: 'practice', worth: 'Worth', tallyPays: 'Tally pays', youHave: 'You have', usedIn: 'Used in', make: 'Make', bagFull: 'Bag full', noItem: 'You have no {item}.',
    coreplateToast: 'Coreplate. Nothing gets through.', poofTown: 'Poof! Back at Bertyville.', poofBunk: 'Poof! Back at your Bunk.', alreadyLeft: 'That block already left your bag.',
    needsOven: 'Needs an Oven nearby', needsBench: 'Needs a Workbench nearby', tallyEnough: 'Tally has enough {item} today', cantSell: '⚙ 0 · can\'t sell',
    sold: 'Sold {n} {item} to Tally', bought: 'Bought {n} {item}', townBought: 'A townsperson bought {n} {item} for ⚙ {cogs}',
    setHome: 'Set home here?', yes: 'Yes', no: 'No', teacher: 'Teacher', pin: 'PIN', priceDial: 'Price dial', dailyCap: 'Daily cap', startCogs: 'Start Cogs',
    townsfolk: 'Townsfolk', resetWallet: 'Reset wallet', onDevice: 'On this device only', pricesChanged: 'Prices changed', fair: 'Fair', yours: 'Yours',
    takeTill: 'Take till', soldOut: 'Sold out: restock', profit: 'Profit', spent: 'Spent', cogsIn: 'In', backMenu: 'Menu', survival: 'Survival',
    myCounter: 'My Counter', bunk: 'Bunk', prices: 'Prices', stock: 'Stock', needMore: 'Need ⚙ {n} more', shopProtected: 'That building stays.',
    ingredients: 'Ingredients: flour, sugar, berries · Bake 10 s', breadLabel: 'Ingredients: flour · Bake 8 s', versionSkew: 'That world uses a different version',
  },
  uk: {
    berry: 'Ягода', flour: 'Борошно', sugar: 'Цукор', cupcake: 'Кекс', bread: 'Хліб', coreplate: 'Підлога-ядро', workbench: 'Верстак', oven: 'Піч', vend: 'Прилавок', storeCounter: 'Прилавок крамниці', bunk: 'Ліжко',
    whatsNewBody: 'Bloxbert 2.2.0: Велике меню ☰ (або Esc). Світ Виживання з сумкою, крафтом і навчальними Шестернями. Продай Таллі, веди свій Прилавок, а Підлога-ядро береже тебе.',
    menuHint: 'Торкнись ☰ або Esc для меню', menuHintTouch: 'Торкнись ☰ для меню', resume: 'Далі', inventory: 'Сумка', crafting: 'Крафт', shop: 'Крамниця', wallet: 'Гаманець',
    practice: 'навчання', worth: 'Варто', tallyPays: 'Таллі платить', youHave: 'У тебе', usedIn: 'Входить у', make: 'Зробити', bagFull: 'Сумка повна', noItem: 'Немає: {item}.',
    coreplateToast: 'Підлога-ядро. Нічого не проходить.', poofTown: 'Пуф! Знову в Бертівіллі.', poofBunk: 'Пуф! Знову в ліжку.', alreadyLeft: 'Цей блок уже пішов із сумки.',
    needsOven: 'Потрібна піч поруч', needsBench: 'Потрібен верстак поруч', tallyEnough: 'Таллі досить {item} сьогодні', cantSell: '⚙ 0 · не продається',
    sold: 'Продано {n} {item} Таллі', bought: 'Куплено {n} {item}', townBought: 'Містянин купив {n} {item} за ⚙ {cogs}',
    setHome: 'Дім тут?', yes: 'Так', no: 'Ні', teacher: 'Вчитель', pin: 'PIN', priceDial: 'Ціна', dailyCap: 'Ліміт дня', startCogs: 'Старт',
    townsfolk: 'Містяни', resetWallet: 'Скинути гаманець', onDevice: 'Лише на цьому пристрої', pricesChanged: 'Ціни змінено', fair: 'Чесно', yours: 'Твоя',
    takeTill: 'Забрати касу', soldOut: 'Немає: поповни', profit: 'Прибуток', spent: 'Витрачено', cogsIn: 'Надходження', backMenu: 'Меню', survival: 'Виживання',
    myCounter: 'Мій прилавок', bunk: 'Ліжко', prices: 'Ціни', stock: 'Запас', needMore: 'Ще ⚙ {n}', shopProtected: 'Ця будівля лишається.',
    ingredients: 'Склад: борошно, цукор, ягоди · Випічка 10 с', breadLabel: 'Склад: борошно · Випічка 8 с', versionSkew: 'Цей світ іншої версії',
  },
  ru: {
    berry: 'Ягода', flour: 'Мука', sugar: 'Сахар', cupcake: 'Кекс', bread: 'Хлеб', coreplate: 'Пол-ядро', workbench: 'Верстак', oven: 'Печь', vend: 'Прилавок', storeCounter: 'Прилавок лавки', bunk: 'Кровать',
    whatsNewBody: 'Bloxbert 2.2.0: Большое меню ☰ (или Esc). Мир Выживания с сумкой, крафтом и учебными Шестернями. Продай Талли, веди свой Прилавок, а Пол-ядро бережёт тебя.',
    menuHint: 'Нажми ☰ или Esc для меню', menuHintTouch: 'Нажми ☰ для меню', resume: 'Дальше', inventory: 'Сумка', crafting: 'Крафт', shop: 'Лавка', wallet: 'Кошелёк',
    practice: 'учёба', worth: 'Цена', tallyPays: 'Талли платит', youHave: 'У тебя', usedIn: 'Нужен в', make: 'Сделать', bagFull: 'Сумка полна', noItem: 'Нет: {item}.',
    coreplateToast: 'Пол-ядро. Ничего не проходит.', poofTown: 'Пуф! Снова в Бертивилле.', poofBunk: 'Пуф! Снова у кровати.', alreadyLeft: 'Этот блок уже ушёл из сумки.',
    needsOven: 'Нужна печь рядом', needsBench: 'Нужен верстак рядом', tallyEnough: 'Талли хватит {item} сегодня', cantSell: '⚙ 0 · нельзя продать',
    sold: 'Продано {n} {item} Талли', bought: 'Куплено {n} {item}', townBought: 'Житель купил {n} {item} за ⚙ {cogs}',
    setHome: 'Дом здесь?', yes: 'Да', no: 'Нет', teacher: 'Учитель', pin: 'PIN', priceDial: 'Цена', dailyCap: 'Лимит дня', startCogs: 'Старт',
    townsfolk: 'Жители', resetWallet: 'Сбросить кошелёк', onDevice: 'Только на этом устройстве', pricesChanged: 'Цены изменены', fair: 'Честно', yours: 'Твоя',
    takeTill: 'Забрать кассу', soldOut: 'Нет: пополни', profit: 'Прибыль', spent: 'Потрачено', cogsIn: 'Приход', backMenu: 'Меню', survival: 'Выживание',
    myCounter: 'Мой прилавок', bunk: 'Кровать', prices: 'Цены', stock: 'Запас', needMore: 'Ещё ⚙ {n}', shopProtected: 'Это здание остаётся.',
    ingredients: 'Состав: мука, сахар, ягоды · Выпечка 10 с', breadLabel: 'Состав: мука · Выпечка 8 с', versionSkew: 'Этот мир другой версии',
  },
  es: {
    berry: 'Baya', flour: 'Harina', sugar: 'Azúcar', cupcake: 'Cupcake', bread: 'Pan', coreplate: 'Núcleo', workbench: 'Banco', oven: 'Horno', vend: 'Mostrador', storeCounter: 'Mostrador de Tally', bunk: 'Litera',
    whatsNewBody: 'Bloxbert 2.2.0: Un menú ☰ grande (o Esc). Un mundo Supervivencia con bolsa, fabricación y Engranajes de práctica. Vende a Tally, abre tu Mostrador, y un suelo Núcleo te cuida.',
    menuHint: 'Toca ☰ o pulsa Esc para el menú', menuHintTouch: 'Toca ☰ para el menú', resume: 'Seguir', inventory: 'Bolsa', crafting: 'Fabricar', shop: 'Tienda', wallet: 'Bolsillo',
    practice: 'práctica', worth: 'Vale', tallyPays: 'Tally paga', youHave: 'Tienes', usedIn: 'Se usa en', make: 'Hacer', bagFull: 'Bolsa llena', noItem: 'No tienes {item}.',
    coreplateToast: 'Núcleo. Nada pasa.', poofTown: '¡Puf! De vuelta en Bertyville.', poofBunk: '¡Puf! De vuelta en tu litera.', alreadyLeft: 'Ese bloque ya salió de tu bolsa.',
    needsOven: 'Necesitas un horno cerca', needsBench: 'Necesitas un banco cerca', tallyEnough: 'Tally ya tiene {item} hoy', cantSell: '⚙ 0 · no se vende',
    sold: 'Vendiste {n} {item} a Tally', bought: 'Compraste {n} {item}', townBought: 'Un vecino compró {n} {item} por ⚙ {cogs}',
    setHome: '¿Casa aquí?', yes: 'Sí', no: 'No', teacher: 'Profe', pin: 'PIN', priceDial: 'Precio', dailyCap: 'Tope del día', startCogs: 'Inicio',
    townsfolk: 'Vecinos', resetWallet: 'Reiniciar bolsillo', onDevice: 'Solo en este aparato', pricesChanged: 'Precios cambiados', fair: 'Justo', yours: 'Tuyo',
    takeTill: 'Cobrar caja', soldOut: 'Agotado: repón', profit: 'Ganancia', spent: 'Gastado', cogsIn: 'Entró', backMenu: 'Menú', survival: 'Supervivencia',
    myCounter: 'Mi mostrador', bunk: 'Litera', prices: 'Precios', stock: 'Stock', needMore: 'Faltan ⚙ {n}', shopProtected: 'Ese edificio se queda.',
    ingredients: 'Ingredientes: harina, azúcar, bayas · Hornear 10 s', breadLabel: 'Ingredientes: harina · Hornear 8 s', versionSkew: 'Ese mundo usa otra versión',
  },
  ar: {
    berry: 'توت', flour: 'دقيق', sugar: 'سكر', cupcake: 'كب كيك', bread: 'خبز', coreplate: 'النواة', workbench: 'منضدة', oven: 'فرن', vend: 'مِنضدة بيع', storeCounter: 'مِنضدة المتجر', bunk: 'سرير',
    whatsNewBody: 'بلوكسبيرت 2.2.0: قائمة ☰ كبيرة (أو Esc). عالم بقاء بحقيبة وصنع وتروس تدريب. بِع لتالي، أدر مِنضدة البيع، وأرضية النواة تحميك.',
    menuHint: 'اضغط ☰ أو Esc للقائمة', menuHintTouch: 'اضغط ☰ للقائمة', resume: 'متابعة', inventory: 'حقيبة', crafting: 'صنع', shop: 'متجر', wallet: 'محفظة',
    practice: 'تدريب', worth: 'القيمة', tallyPays: 'تالي يدفع', youHave: 'معك', usedIn: 'يُستخدم في', make: 'اصنع', bagFull: 'الحقيبة ممتلئة', noItem: 'ليس معك {item}.',
    coreplateToast: 'النواة. لا شيء يمر.', poofTown: 'بوف! عدت إلى بيرتيفيل.', poofBunk: 'بوف! عدت إلى سريرك.', alreadyLeft: 'هذا المكعب غادر حقيبتك.',
    needsOven: 'يلزم فرن قريب', needsBench: 'يلزم منضدة قريبة', tallyEnough: 'تالي اكتفى من {item} اليوم', cantSell: '⚙ 0 · لا يُباع',
    sold: 'بعت {n} {item} لتالي', bought: 'اشتريت {n} {item}', townBought: 'اشترى أحد السكان {n} {item} بـ ⚙ {cogs}',
    setHome: 'البيت هنا؟', yes: 'نعم', no: 'لا', teacher: 'المعلم', pin: 'رمز', priceDial: 'السعر', dailyCap: 'حد اليوم', startCogs: 'البداية',
    townsfolk: 'السكان', resetWallet: 'تصفير المحفظة', onDevice: 'على هذا الجهاز فقط', pricesChanged: 'تغيّرت الأسعار', fair: 'عادل', yours: 'سعرك',
    takeTill: 'خذ الصندوق', soldOut: 'نفد: أعد التعبئة', profit: 'الربح', spent: 'المصروف', cogsIn: 'الداخل', backMenu: 'القائمة', survival: 'بقاء',
    myCounter: 'مِنضدتي', bunk: 'سرير', prices: 'الأسعار', stock: 'المخزون', needMore: 'يلزم ⚙ {n}', shopProtected: 'هذا المبنى يبقى.',
    ingredients: 'المكونات: دقيق وسكر وتوت · خبز 10 ث', breadLabel: 'المكونات: دقيق · خبز 8 ث', versionSkew: 'هذا العالم نسخة مختلفة',
  },
  'fa-AF': {
    berry: 'توت', flour: 'آرد', sugar: 'شکر', cupcake: 'کاپ‌کیک', bread: 'نان', coreplate: 'کف هسته', workbench: 'میز کار', oven: 'تنور', vend: 'پیشخوان فروش', storeCounter: 'پیشخوان دکان', bunk: 'بستر',
    whatsNewBody: 'بلاکسبرت ۲.۲.۰: فهرست بزرگ ☰ (یا Esc). جهان بقا با بکس، ساختن و چرخ‌دنده‌های تمرین. به تالی بفروش، پیشخوان خود را بچرخان، و کف هسته تو را نگه می‌دارد.',
    menuHint: '☰ یا Esc را برای فهرست بزن', menuHintTouch: '☰ را برای فهرست بزن', resume: 'ادامه', inventory: 'بکس', crafting: 'ساختن', shop: 'دکان', wallet: 'کیسه',
    practice: 'تمرین', worth: 'ارزش', tallyPays: 'تالی می‌پردازد', youHave: 'داری', usedIn: 'در این به کار می‌رود', make: 'بساز', bagFull: 'بکس پر است', noItem: '{item} نداری.',
    coreplateToast: 'کف هسته. چیزی رد نمی‌شود.', poofTown: 'پوف! دوباره در برتی‌ویل.', poofBunk: 'پوف! دوباره کنار بستر.', alreadyLeft: 'این بلاک از بکس رفته است.',
    needsOven: 'تنور نزدیک می‌خواهد', needsBench: 'میز کار نزدیک می‌خواهد', tallyEnough: 'تالی امروز {item} بس است', cantSell: '⚙ ۰ · فروخته نمی‌شود',
    sold: '{n} {item} به تالی فروختی', bought: '{n} {item} خریدی', townBought: 'یک شهریان {n} {item} را به ⚙ {cogs} خرید',
    setHome: 'خانه اینجا؟', yes: 'بله', no: 'نه', teacher: 'معلم', pin: 'رمز', priceDial: 'نرخ', dailyCap: 'سقف روز', startCogs: 'آغاز',
    townsfolk: 'شهریان', resetWallet: 'کیسه را صفر کن', onDevice: 'فقط روی این دستگاه', pricesChanged: 'نرخ‌ها عوض شد', fair: 'منصفانه', yours: 'مال تو',
    takeTill: 'صندوق را بگیر', soldOut: 'تمام شد: دوباره بگذار', profit: 'سود', spent: 'خرج', cogsIn: 'درآمد', backMenu: 'فهرست', survival: 'بقا',
    myCounter: 'پیشخوان من', bunk: 'بستر', prices: 'نرخ‌ها', stock: 'ذخیره', needMore: '⚙ {n} دیگر لازم است', shopProtected: 'این ساختمان می‌ماند.',
    ingredients: 'مواد: آرد، شکر، توت · پخت ۱۰ ث', breadLabel: 'مواد: آرد · پخت ۸ ث', versionSkew: 'این جهان نسخه دیگر است',
  },
  rw: {
    berry: 'Imbuto', flour: 'Ifu', sugar: 'Isukari', cupcake: 'Kek', bread: 'Umugati', coreplate: 'Uruhome', workbench: 'Ameza', oven: 'Ibyoto', vend: 'Counter', storeCounter: 'Counter y\'iduka', bunk: 'Buriri',
    whatsNewBody: 'Bloxbert 2.2.0: Menu ☰ nini (cyangwa Esc). Isi y\'Ubugingo ifite agasaho, gukora, n\'amapine y\'imyitozo. Gurisha Tally, koresha counter yawe, n\'urutare rw\'uruhome rukurinda.',
    menuHint: 'Kanda ☰ cyangwa Esc ku menu', menuHintTouch: 'Kanda ☰ ku menu', resume: 'Komeza', inventory: 'Agasaho', crafting: 'Kora', shop: 'Iduka', wallet: 'Ikibanza',
    practice: 'imyitozo', worth: 'Agaciro', tallyPays: 'Tally yishyura', youHave: 'Ufite', usedIn: 'Ikoreshwa muri', make: 'Kora', bagFull: 'Agasaho karuzuye', noItem: 'Nta {item} ufite.',
    coreplateToast: 'Uruhome. Ntacyo kirengana.', poofTown: 'Poof! Subira i Bertyville.', poofBunk: 'Poof! Subira ku buriri.', alreadyLeft: 'Iyo block yavuye mu gasaho.',
    needsOven: 'Ukeneye ibuye ry\'ububiko hafi', needsBench: 'Ukeneye ameza hafi', tallyEnough: 'Tally ahaze {item} uyu munsi', cantSell: '⚙ 0 · ntigurishwa',
    sold: 'Wagurishije {n} {item} kuri Tally', bought: 'Waguze {n} {item}', townBought: 'Umuturage yaguze {n} {item} ⚙ {cogs}',
    setHome: 'Inzu hano?', yes: 'Yego', no: 'Oya', teacher: 'Umwarimu', pin: 'PIN', priceDial: 'Igiciro', dailyCap: 'Umupaka w\'umunsi', startCogs: 'Intangiriro',
    townsfolk: 'Abaturage', resetWallet: 'Subiza ikibanza', onDevice: 'Kuri iki gikoresho gusa', pricesChanged: 'Ibiciro byahindutse', fair: 'Ukuri', yours: 'Iyawe',
    takeTill: 'Fata keshye', soldOut: 'Byarangiye: ongera', profit: 'Inyungu', spent: 'Byakoreshejwe', cogsIn: 'Byinjiye', backMenu: 'Menu', survival: 'Ubugingo',
    myCounter: 'Counter yanjye', bunk: 'Buriri', prices: 'Ibiciro', stock: 'Ibyo ufite', needMore: 'Ukeneye ⚙ {n}', shopProtected: 'Iyo nyubako isigara.',
    ingredients: 'Ibikoresho: ifu, isukari, imbuto · Oteka 10s', breadLabel: 'Ibikoresho: ifu · Oteka 8s', versionSkew: 'Isi ikoresha indi verisiyo',
  },
  ti: {
    berry: 'ፍረ', flour: 'ዱቄት', sugar: 'ሽኮር', cupcake: 'ኬክ', bread: 'ባኒ', coreplate: 'ኮርፕሌት', workbench: 'ሰደቓ', oven: 'እቶን', vend: 'መደብ መሸጢ', storeCounter: 'መደብ ድኳን', bunk: 'ዓራት',
    whatsNewBody: 'ብሎክስበርት 2.2.0፡ ዓቢ ☰ መእተዊ (ወይ Esc)። ዓለም ህይወት ምስ ቦርሳ፡ ምስራሕን ናይ ምልምማድ ኮግን። ንታሊ ሸይጥ፡ ናይኻ መደብ ክፈት፡ ወለል ኮርፕሌት የዕቅበካ።',
    menuHint: '☰ ወይ Esc ንመእተዊ', menuHintTouch: '☰ ንመእተዊ', resume: 'ቀጽል', inventory: 'ቦርሳ', crafting: 'ምስራሕ', shop: 'ድኳን', wallet: 'ኪስ',
    practice: 'ምልምማድ', worth: 'ዋጋ', tallyPays: 'ታሊ ይከፍል', youHave: 'ኣለካ', usedIn: 'ይውዕል ኣብ', make: 'ግበር', bagFull: 'ቦርሳ መሊኡ', noItem: '{item} የብልካን።',
    coreplateToast: 'ኮርፕሌት። ዝኾነ ኣይሓልፍን።', poofTown: 'ፑፍ! ናብ በርቲቪል ተመሊስካ።', poofBunk: 'ፑፍ! ናብ ዓራትካ ተመሊስካ።', alreadyLeft: 'እዚ ብሎክ ካብ ቦርሳኻ ወጺኡ።',
    needsOven: 'እቶን ኣብ ቀረባ የድሊ', needsBench: 'ሰደቓ ኣብ ቀረባ የድሊ', tallyEnough: 'ታሊ ሎሚ {item} እኹል ኣሎ', cantSell: '⚙ 0 · ኣይሽየጥን',
    sold: '{n} {item} ንታሊ ሸይጥካ', bought: '{n} {item} ገዚእካ', townBought: 'ሓደ ሰብ {n} {item} ብ ⚙ {cogs} ገዚኡ',
    setHome: 'ገዛ ኣብዚ?', yes: 'እወ', no: 'ኣይፋል', teacher: 'መምህር', pin: 'PIN', priceDial: 'ዋጋ', dailyCap: 'ዕለታዊ ደረት', startCogs: 'መጀመርታ',
    townsfolk: 'ሰባት', resetWallet: 'ኪስ ዳግማይ', onDevice: 'ኣብዚ መሳርሒ ጥራይ', pricesChanged: 'ዋጋ ተቐይሩ', fair: 'ፍትሓዊ', yours: 'ናትካ',
    takeTill: 'ሳንዱቅ ውሰድ', soldOut: 'ተወዲኡ፡ መልእ', profit: 'መእገዲ', spent: 'ዝወጸ', cogsIn: 'ዝኣተወ', backMenu: 'መእተዊ', survival: 'ህይወት',
    myCounter: 'መደብይ', bunk: 'ዓራት', prices: 'ዋጋታት', stock: 'ኣቕሓ', needMore: '⚙ {n} የድሊ', shopProtected: 'እቲ ህንጻ ይቕጽል።',
    ingredients: 'ኣቕሑ፡ ዱቄት፡ ሽኮር፡ ፍረ · ምሕሳስ 10 ሰ', breadLabel: 'ኣቕሑ፡ ዱቄት · ምሕሳስ 8 ሰ', versionSkew: 'እዚ ዓለም ካልእ ስሪት እዩ',
  },
}
