// Extra 2.2.0 strings. Dari is Dari, not Arabic.
export const EXTRA = {
  en: {
    changelog: 'Журнал', youAreHere: 'Ти тут', tourMove: 'Move with the pads', tourLook: 'Drag to look', tourPlace: 'Place and break', tourBar: 'Open your bag', tourShop: 'Sell to Tally', tourTools: 'Fill a box', place10: 'Place 10 blocks', fillBox: 'Fill a box', sell3: 'Sell 3 logs', helpBody: 'Tap a tile to learn', tour: 'Tour', next: 'Далі', skip: 'Пропустити', tryThis: 'Спробуй', a11y: 'Accessibility', goalDone: 'Goal done', highContrast: 'High Contrast', gentle: 'Gentle Mode', sendTeacher: 'Send To Teacher', sentTeacher: 'Sent to Mr. Kulibert', noFly: 'No flying in Survival', tapCorner: 'Tap Corner A first', cornerA: 'Corner A set',
    tryThis: 'Попробуй', tour: 'Tour', a11y: 'Accessibility', next: 'Дальше', skip: 'Пропустить', goalDone: 'Goal done', highContrast: 'High Contrast', gentle: 'Gentle Mode', sendTeacher: 'Send To Teacher', sentTeacher: 'Sent ⚙ 1 to Mr. Kulibert', noFly: 'No flying in Survival', cornerA: 'Corner A set',
    tapCorner: 'Tap Corner A first', filled: 'Filled {n} blocks', homeSet: 'Home set', homeCleared: 'Home cleared', pickup: 'Pick up', paste: 'Paste',
    buildTools: 'Build Tools', exitApp: 'Exit', leaveAsk: 'Leave Bertopia? Your world is saved.', leave: 'Leave', stay: 'Stay', myBuilds: 'My Builds', undoMinutes: 'Undo Minutes', snapshots: 'Snapshots', emptyBag: 'Empty bag: break blocks or buy at Tally\'s', emptySlot: 'Empty slot', tooBig: 'Too big: max 64 × 32 × 64', badBuild: 'That file is not a Bertopia build', fineLater: 'Fine-scale decor comes later', changedTo: 'Changed:',
    berry: 'Berry', flour: 'Flour', sugar: 'Sugar', cupcake: 'Cupcake', bread: 'Bread', coreplate: 'Coreplate', workbench: 'Workbench', oven: 'Oven', vend: 'Vending Counter', storeCounter: 'Store Counter', bunk: 'Bunk',
    whatsNewBody: 'Bertopia 2.5.2: The menu opens again. Creative has a bag of every block. Tap an oven to bake. Save a build to My Builds.',
    menuHint: 'Tap ☰ or press Esc for menu', menuHintTouch: 'Tap ☰ for menu', resume: 'Resume', inventory: 'Inventory', crafting: 'Crafting', shop: 'Shop', wallet: 'Wallet',
    practice: 'practice', worth: 'Worth', tallyPays: 'Tally pays', youHave: 'You have', usedIn: 'Used in', make: 'Make', bagFull: 'Bag full', noItem: 'You have no {item}.',
    coreplateToast: 'Coreplate. Nothing gets through.', poofTown: 'Poof! Back at Bertyville.', poofBunk: 'Poof! Back at your Bunk.', alreadyLeft: 'That block already left your bag.',
    needsOven: 'Needs an Oven nearby', needsBench: 'Needs a Workbench nearby', tallyEnough: 'Tally has enough {item} today', cantSell: '⚙ 0 · can\'t sell',
    sold: 'Sold {n} {item} to Tally', bought: 'Bought {n} {item}', townBought: 'A townsperson bought {n} {item} for ⚙ {cogs}',
    setHome: 'Set home here?', yes: 'Yes', no: 'No', teacher: 'Teacher', pin: 'PIN', priceDial: 'Price dial', dailyCap: 'Daily cap', startCogs: 'Start Cogs',
    townsfolk: 'Townsfolk', resetWallet: 'Reset wallet', onDevice: 'On this device only', pricesChanged: 'Prices changed', fair: 'Fair', yours: 'Yours',
    takeTill: 'Take till', soldOut: 'Sold out: restock', profit: 'Profit', spent: 'Spent', cogsIn: 'In', backMenu: 'Menu', survival: 'Survival',
    myCounter: 'My Counter', bunk: 'Bunk', prices: 'Prices', stock: 'Stock', needMore: 'Need ⚙ {n} more', shopProtected: 'That building stays.',
    ingredients: 'Ingredients: flour, sugar, berries · Bake 10 s', breadLabel: 'Ingredients: flour · Bake 8 s', versionSkew: 'That world uses a different version',
  },
  uk: {
    changelog: 'Журнал', youAreHere: 'Ты здесь', tourMove: 'Move with the pads', tourLook: 'Drag to look', tourPlace: 'Place and break', tourBar: 'Open your bag', tourShop: 'Sell to Tally', tourTools: 'Fill a box', place10: 'Place 10 blocks', fillBox: 'Fill a box', sell3: 'Sell 3 logs', helpBody: 'Tap a tile to learn', tour: 'Tour', next: 'Siguiente', skip: 'Saltar', tryThis: 'Prueba esto', a11y: 'Accessibility', goalDone: 'Goal done', highContrast: 'High Contrast', gentle: 'Gentle Mode', sendTeacher: 'Send To Teacher', sentTeacher: 'Sent to Mr. Kulibert', noFly: 'No flying in Survival', tapCorner: 'Tap Corner A first', cornerA: 'Corner A set',
    buildTools: 'Інструменти', exitApp: 'Вихід', leaveAsk: 'Вийти з Bertopia? Світ збережено.', leave: 'Вийти', stay: 'Лишитись', myBuilds: 'Мої будови', undoMinutes: 'Хвилини назад', snapshots: 'Знімки', emptyBag: 'Сумка порожня: ламай блоки або купи в Таллі', emptySlot: 'Порожня клітинка', tooBig: 'Завелике: макс 64 × 32 × 64', badBuild: 'Це не файл будови Bertopia', fineLater: 'Дрібний декор буде пізніше', changedTo: 'Змінено:',
    berry: 'Ягода', flour: 'Борошно', sugar: 'Цукор', cupcake: 'Кекс', bread: 'Хліб', coreplate: 'Підлога-ядро', workbench: 'Верстак', oven: 'Піч', vend: 'Прилавок', storeCounter: 'Прилавок крамниці', bunk: 'Ліжко',
    whatsNewBody: 'Bertopia 2.5.0: Картинний тур і цілі «Спробуй» показують, як грати. Обери свою панель будови. У Виживанні немає польоту. Є Допомога і Доступність, і можна надіслати Шестерні вчителю.',
    menuHint: 'Торкнись ☰ або Esc для меню', menuHintTouch: 'Торкнись ☰ для меню', resume: 'Далі', inventory: 'Сумка', crafting: 'Крафт', shop: 'Крамниця', wallet: 'Гаманець',
    practice: 'навчання', worth: 'Варто', tallyPays: 'Таллі платить', youHave: 'У тебе', usedIn: 'Входить у', make: 'Зробити', bagFull: 'Сумка повна', noItem: 'Немає: {item}.',
    coreplateToast: 'Підлога-ядро. Нічого не проходить.', poofTown: 'Пуф! Знову в Бертівіллі.', poofBunk: 'Пуф! Знову в ліжку.', alreadyLeft: 'Цей блок уже пішов із сумки.',
    needsOven: 'Потрібна піч поруч', needsBench: 'Потрібен верстак поруч', tallyEnough: 'Таллі досить {item} сьогодні', cantSell: '⚙ 0 · не продається',
    sold: 'Продано {n} {item} Таллі', bought: 'Куплено {n} {item}', townBought: 'Містянин купив {n} {item} за ⚙ {cogs}',
    setHome: 'Дім тут?', yes: 'Так', no: 'Ні', teacher: 'Вчитель', pin: 'PIN', priceDial: 'Ціна', dailyCap: 'Ліміт дня', startCogs: 'Старт',
    townsfolk: 'Містяни', resetWallet: 'Скинути гаманець', onDevice: 'Лише на цьому пристрої', pricesChanged: 'Ціни змінено', fair: 'Чесно', yours: 'Твоя',
    takeTill: 'Забрати касу', soldOut: 'Немає: поповни', profit: 'Прибуток', spent: 'Витрачено', cogsIn: 'Надходження', backMenu: 'Меню', survival: 'Виживання',
    myCounter: 'Мій прилавок', bunk: 'Ліжко', prices: 'Ціни', stock: 'Запас', needMore: 'Ще ⚙ {n}', shopProtected: 'Ця будівля лишається.',
    ingredients: 'Склад: борошно, цукор, ягоди · Випічка 10 с', breadLabel: 'Склад: борошно · Випічка 8 с', versionSkew: 'Цей світ іншої версії',
  },
  ru: {
    changelog: 'Registro', youAreHere: 'Estás aquí', tourMove: 'Move with the pads', tourLook: 'Drag to look', tourPlace: 'Place and break', tourBar: 'Open your bag', tourShop: 'Sell to Tally', tourTools: 'Fill a box', place10: 'Place 10 blocks', fillBox: 'Fill a box', sell3: 'Sell 3 logs', helpBody: 'Tap a tile to learn', tour: 'Tour', next: 'التالي', skip: 'تخطَّ', tryThis: 'جرّب هذا', a11y: 'Accessibility', goalDone: 'Goal done', highContrast: 'High Contrast', gentle: 'Gentle Mode', sendTeacher: 'Send To Teacher', sentTeacher: 'Sent to Mr. Kulibert', noFly: 'No flying in Survival', tapCorner: 'Tap Corner A first', cornerA: 'Corner A set',
    buildTools: 'Инструменты', exitApp: 'Выход', leaveAsk: 'Выйти из Bertopia? Мир сохранён.', leave: 'Выйти', stay: 'Остаться', myBuilds: 'Мои стройки', undoMinutes: 'Минуты назад', snapshots: 'Снимки', emptyBag: 'Сумка пуста: ломай блоки или купи у Талли', emptySlot: 'Пустая ячейка', tooBig: 'Слишком большое: макс 64 × 32 × 64', badBuild: 'Это не файл стройки Bertopia', fineLater: 'Мелкий декор будет позже', changedTo: 'Изменено:',
    berry: 'Ягода', flour: 'Мука', sugar: 'Сахар', cupcake: 'Кекс', bread: 'Хлеб', coreplate: 'Пол-ядро', workbench: 'Верстак', oven: 'Печь', vend: 'Прилавок', storeCounter: 'Прилавок лавки', bunk: 'Кровать',
    whatsNewBody: 'Bertopia 2.5.0: Картинный тур и цели «Попробуй» показывают, как играть. Выбери свою панель стройки. В Выживании нет полёта. Есть Помощь и Доступность, и можно отправить Шестерни учителю.',
    menuHint: 'Нажми ☰ или Esc для меню', menuHintTouch: 'Нажми ☰ для меню', resume: 'Дальше', inventory: 'Сумка', crafting: 'Крафт', shop: 'Лавка', wallet: 'Кошелёк',
    practice: 'учёба', worth: 'Цена', tallyPays: 'Талли платит', youHave: 'У тебя', usedIn: 'Нужен в', make: 'Сделать', bagFull: 'Сумка полна', noItem: 'Нет: {item}.',
    coreplateToast: 'Пол-ядро. Ничего не проходит.', poofTown: 'Пуф! Снова в Бертивилле.', poofBunk: 'Пуф! Снова у кровати.', alreadyLeft: 'Этот блок уже ушёл из сумки.',
    needsOven: 'Нужна печь рядом', needsBench: 'Нужен верстак рядом', tallyEnough: 'Талли хватит {item} сегодня', cantSell: '⚙ 0 · нельзя продать',
    sold: 'Продано {n} {item} Талли', bought: 'Куплено {n} {item}', townBought: 'Житель купил {n} {item} за ⚙ {cogs}',
    setHome: 'Дом здесь?', yes: 'Да', no: 'Нет', teacher: 'Учитель', pin: 'PIN', priceDial: 'Цена', dailyCap: 'Лимит дня', startCogs: 'Старт',
    townsfolk: 'Жители', resetWallet: 'Сбросить кошелёк', onDevice: 'Только на этом устройстве', pricesChanged: 'Цены изменены', fair: 'Честно', yours: 'Твоя',
    takeTill: 'Забрать кассу', soldOut: 'Нет: пополни', profit: 'Прибыль', spent: 'Потрачено', cogsIn: 'Приход', backMenu: 'Меню', survival: 'Выживание',
    myCounter: 'Мой прилавок', bunk: 'Кровать', prices: 'Цены', stock: 'Запас', needMore: 'Ещё ⚙ {n}', shopProtected: 'Это здание остаётся.',
    ingredients: 'Состав: мука, сахар, ягоды · Выпечка 10 с', breadLabel: 'Состав: мука · Выпечка 8 с', versionSkew: 'Этот мир другой версии',
  },
  es: {
    changelog: 'السجل', youAreHere: 'أنت هنا', tourMove: 'Move with the pads', tourLook: 'Drag to look', tourPlace: 'Place and break', tourBar: 'Open your bag', tourShop: 'Sell to Tally', tourTools: 'Fill a box', place10: 'Place 10 blocks', fillBox: 'Fill a box', sell3: 'Sell 3 logs', helpBody: 'Tap a tile to learn', tour: 'Tour', next: 'بعدی', skip: 'بگذر', tryThis: 'این را بیازما', a11y: 'Accessibility', goalDone: 'Goal done', highContrast: 'High Contrast', gentle: 'Gentle Mode', sendTeacher: 'Send To Teacher', sentTeacher: 'Sent to Mr. Kulibert', noFly: 'No flying in Survival', tapCorner: 'Tap Corner A first', cornerA: 'Corner A set',
    buildTools: 'Herramientas', exitApp: 'Salir', leaveAsk: '¿Salir de Bertopia? Tu mundo está guardado.', leave: 'Salir', stay: 'Quedarme', myBuilds: 'Mis construcciones', undoMinutes: 'Minutos atrás', snapshots: 'Instantáneas', emptyBag: 'Bolsa vacía: rompe bloques o compra a Tally', emptySlot: 'Casilla vacía', tooBig: 'Demasiado grande: máx 64 × 32 × 64', badBuild: 'Ese archivo no es una construcción Bertopia', fineLater: 'El decorado fino llega después', changedTo: 'Cambiado:',
    berry: 'Baya', flour: 'Harina', sugar: 'Azúcar', cupcake: 'Cupcake', bread: 'Pan', coreplate: 'Núcleo', workbench: 'Banco', oven: 'Horno', vend: 'Mostrador', storeCounter: 'Mostrador de Tally', bunk: 'Litera',
    whatsNewBody: 'Bertopia 2.5.0: Un recorrido con dibujos y metas Prueba esto muestran cómo jugar. Elige tu barra de construcción. Supervivencia no vuela. Ayuda y Accesibilidad son nuevas, y puedes enviar Engranajes a tu maestro.',
    menuHint: 'Toca ☰ o pulsa Esc para el menú', menuHintTouch: 'Toca ☰ para el menú', resume: 'Seguir', inventory: 'Bolsa', crafting: 'Fabricar', shop: 'Tienda', wallet: 'Bolsillo',
    practice: 'práctica', worth: 'Vale', tallyPays: 'Tally paga', youHave: 'Tienes', usedIn: 'Se usa en', make: 'Hacer', bagFull: 'Bolsa llena', noItem: 'No tienes {item}.',
    coreplateToast: 'Núcleo. Nada pasa.', poofTown: '¡Puf! De vuelta en Bertyville.', poofBunk: '¡Puf! De vuelta en tu litera.', alreadyLeft: 'Ese bloque ya salió de tu bolsa.',
    needsOven: 'Necesitas un horno cerca', needsBench: 'Necesitas un banco cerca', tallyEnough: 'Tally ya tiene {item} hoy', cantSell: '⚙ 0 · no se vende',
    sold: 'Vendiste {n} {item} a Tally', bought: 'Compraste {n} {item}', townBought: 'Un vecino compró {n} {item} por ⚙ {cogs}',
    setHome: '¿Casa aquí?', yes: 'Sí', no: 'No', teacher: 'Profe', pin: 'PIN', priceDial: 'Precio', dailyCap: 'Tope del día', startCogs: 'Inicio',
    townsfolk: 'Vecinos', resetWallet: 'Reiniciar bolsillo', onDevice: 'Solo en este aparato', pricesChanged: 'Precios cambiados', fair: 'Justo', yours: 'Tuyo',
    takeTill: 'Cobrar caja', soldOut: 'Agotado: repón', profit: 'Ganancia', spent: 'Gastado', cogsIn: 'Entró', backMenu: 'Menú', survival: 'Supervivencia',
    myCounter: 'Mi mostrador', bunk: 'Litera', prices: 'Precios', stock: 'Stock', needMore: 'Faltan ⚙ {n}', shopProtected: 'Ese edificio se queda.',
    ingredients: 'Ingredientes: harina, azúcar, bayas · Hornear 10 s', breadLabel: 'Ingredientes: harina · Hornear 8 s', versionSkew: 'Ese mundo usa otra versión',
  },
  ar: {
    changelog: 'فهرست تغییر', youAreHere: 'اینجا هستی', tourMove: 'Move with the pads', tourLook: 'Drag to look', tourPlace: 'Place and break', tourBar: 'Open your bag', tourShop: 'Sell to Tally', tourTools: 'Fill a box', place10: 'Place 10 blocks', fillBox: 'Fill a box', sell3: 'Sell 3 logs', helpBody: 'Tap a tile to learn', tour: 'Tour', next: 'Ikurikira', skip: 'Simbuka', tryThis: 'Gerageza', a11y: 'Accessibility', goalDone: 'Goal done', highContrast: 'High Contrast', gentle: 'Gentle Mode', sendTeacher: 'Send To Teacher', sentTeacher: 'Sent to Mr. Kulibert', noFly: 'No flying in Survival', tapCorner: 'Tap Corner A first', cornerA: 'Corner A set',
    buildTools: 'أدوات البناء', exitApp: 'خروج', leaveAsk: 'مغادرة بيرتوبيا؟ عالمك محفوظ.', leave: 'غادر', stay: 'ابق', myBuilds: 'مبانيي', undoMinutes: 'دقائق سابقة', snapshots: 'لقطات', emptyBag: 'الحقيبة فارغة: اكسر مكعبات أو اشتر من تالي', emptySlot: 'خانة فارغة', tooBig: 'كبير جداً: الحد 64 × 32 × 64', badBuild: 'هذا الملف ليس بناء بيرتوبيا', fineLater: 'الزخرفة الدقيقة لاحقاً', changedTo: 'تغيّر:',
    berry: 'توت', flour: 'دقيق', sugar: 'سكر', cupcake: 'كب كيك', bread: 'خبز', coreplate: 'النواة', workbench: 'منضدة', oven: 'فرن', vend: 'مِنضدة بيع', storeCounter: 'مِنضدة المتجر', bunk: 'سرير',
    whatsNewBody: 'بيرتوبيا 2.5.0: جولة بالصور وأهداف جرّب هذا تعلّمك اللعب. اختر شريط البناء من الحقيبة. البقاء بلا طيران. المساعدة وسهولة الوصول جديدتان، ويمكنك إرسال التروس إلى معلمك.',
    menuHint: 'اضغط ☰ أو Esc للقائمة', menuHintTouch: 'اضغط ☰ للقائمة', resume: 'متابعة', inventory: 'حقيبة', crafting: 'صنع', shop: 'متجر', wallet: 'محفظة',
    practice: 'تدريب', worth: 'القيمة', tallyPays: 'تالي يدفع', youHave: 'معك', usedIn: 'يُستخدم في', make: 'اصنع', bagFull: 'الحقيبة ممتلئة', noItem: 'ليس معك {item}.',
    coreplateToast: 'النواة. لا شيء يمر.', poofTown: 'بوف! عدت إلى بيرتيفيل.', poofBunk: 'بوف! عدت إلى سريرك.', alreadyLeft: 'هذا المكعب غادر حقيبتك.',
    needsOven: 'يلزم فرن قريب', needsBench: 'يلزم منضدة قريبة', tallyEnough: 'تالي اكتفى من {item} اليوم', cantSell: '⚙ 0 · لا يُباع',
    sold: 'بعت {n} {item} لتالي', bought: 'اشتريت {n} {item}', townBought: 'اشترى أحد السكان {n} {item} بـ ⚙ {cogs}',
    setHome: 'البيت هنا؟', yes: 'نعم', no: 'لا', teacher: 'المعلم', pin: 'رمز', priceDial: 'السعر', dailyCap: 'حد اليوم', startCogs: 'البداية',
    townsfolk: 'السكان', resetWallet: 'تصفير المحفظة', onDevice: 'على هذا الجهاز فقط', pricesChanged: 'تغيّرت الأسعار', fair: 'عادل', yours: 'سعرك',
    takeTill: 'خذ الصندوق', soldOut: 'نفد: أعد التعبئة', profit: 'الربح', spent: 'المصروف', cogsIn: 'الداخل', backMenu: 'القائمة', survival: 'بقاء',
    myCounter: 'مِنضدتي', bunk: 'سرير', prices: 'الأسعار', stock: 'المخزون', needMore: 'يلزم ⚙ {n}', shopProtected: 'هذا المبنى يبقى.',
    ingredients: 'المكونات: دقيق وسكر وتوت · خبز 10 ث', breadLabel: 'المكونات: دقيق · خبز 8 ث', versionSkew: 'هذا العالم نسخة مختلفة',
  },
  'fa-AF': {
    changelog: 'Inkururagamba', youAreHere: 'Uri hano', tourMove: 'Move with the pads', tourLook: 'Drag to look', tourPlace: 'Place and break', tourBar: 'Open your bag', tourShop: 'Sell to Tally', tourTools: 'Fill a box', place10: 'Place 10 blocks', fillBox: 'Fill a box', sell3: 'Sell 3 logs', helpBody: 'Tap a tile to learn', tour: 'Tour', next: 'ዝቕጽል', skip: 'ዝለል', tryThis: 'ፈትን እዚ', a11y: 'Accessibility', goalDone: 'Goal done', highContrast: 'High Contrast', gentle: 'Gentle Mode', sendTeacher: 'Send To Teacher', sentTeacher: 'Sent to Mr. Kulibert', noFly: 'No flying in Survival', tapCorner: 'Tap Corner A first', cornerA: 'Corner A set',
    buildTools: 'ابزار ساخت', exitApp: 'خروج', leaveAsk: 'از برتوپیا بیرون می‌روی؟ جهان ذخیره شد.', leave: 'برو', stay: 'بمان', myBuilds: 'ساخت‌های من', undoMinutes: 'دقیقه‌های پیش', snapshots: 'نسخه‌ها', emptyBag: 'بکس خالی است: بلاک بشکن یا از تالی بخر', emptySlot: 'خانه خالی', tooBig: 'خیلی بزرگ: حد ۶۴ × ۳۲ × ۶۴', badBuild: 'این فایل ساخت برتوپیا نیست', fineLater: 'آرایش ریز بعداً می‌آید', changedTo: 'عوض شد:',
    berry: 'توت', flour: 'آرد', sugar: 'شکر', cupcake: 'کاپ‌کیک', bread: 'نان', coreplate: 'کف هسته', workbench: 'میز کار', oven: 'تنور', vend: 'پیشخوان فروش', storeCounter: 'پیشخوان دکان', bunk: 'بستر',
    whatsNewBody: 'برتوپیا ۲.۵.۰: یک گشت تصویری و هدف‌های «این را بیازما» بازی را نشان می‌دهند. نوار ساخت را خود برگزین. بقا پرواز ندارد. رهنما و دسترسی نو اند، و می‌توانی چرخ‌دنده به معلم بفرستی.',
    menuHint: '☰ یا Esc را برای فهرست بزن', menuHintTouch: '☰ را برای فهرست بزن', resume: 'ادامه', inventory: 'بکس', crafting: 'ساختن', shop: 'دکان', wallet: 'کیسه',
    practice: 'تمرین', worth: 'ارزش', tallyPays: 'تالی می‌پردازد', youHave: 'داری', usedIn: 'در این به کار می‌رود', make: 'بساز', bagFull: 'بکس پر است', noItem: '{item} نداری.',
    coreplateToast: 'کف هسته. چیزی رد نمی‌شود.', poofTown: 'پوف! دوباره در برتی‌ویل.', poofBunk: 'پوف! دوباره کنار بستر.', alreadyLeft: 'این بلاک از بکس رفته است.',
    needsOven: 'تنور نزدیک می‌خواهد', needsBench: 'میز کار نزدیک می‌خواهد', tallyEnough: 'تالی امروز {item} بس است', cantSell: '⚙ ۰ · فروخته نمی‌شود',
    sold: '{n} {item} به تالی فروختی', bought: '{n} {item} خریدی', townBought: 'یک شهریان {n} {item} را به ⚙ {cogs} خرید',
    setHome: 'خانه اینجا؟', yes: 'بله', no: 'نه', teacher: 'معلم', pin: 'رمز', priceDial: 'نرخ', dailyCap: 'سقف روز', startCogs: 'آغاز',
    townsfolk: 'شهریان', resetWallet: 'کیسه را صفر کن', onDevice: 'فقط روی این دستگاه', pricesChanged: 'نرخ‌ها عوض شد', fair: 'منصفانه', yours: 'مال تو',
    takeTill: 'صندوق را بگیر', soldOut: 'تمام شد: دوباره بگذار', profit: 'سود', spent: 'خرج', cogsIn: 'درآمد', backMenu: 'فهرست', survival: 'بقا',
    myCounter: 'پیشخوان من', bunk: 'بستر', prices: 'نرخ‌ها', stock: 'ذخیره', needMore: '⚙ {n} دیگر لازم است', shopProtected: 'این ساختمان می‌ماند.',
    ingredients: 'مواد: آرد، شکر، توت · پخت ۱۰ ث', breadLabel: 'مواد: آرد · پخت ۸ ث', versionSkew: 'این جهان نسخه دیگر است',
  },
  rw: {
    changelog: 'ዝርዝር', youAreHere: 'ኣብዚ ኢኻ', tourMove: 'Move with the pads', tourLook: 'Drag to look', tourPlace: 'Place and break', tourBar: 'Open your bag', tourShop: 'Sell to Tally', tourTools: 'Fill a box', place10: 'Place 10 blocks', fillBox: 'Fill a box', sell3: 'Sell 3 logs', helpBody: 'Tap a tile to learn', tour: 'Tour', next: 'Next', skip: 'Skip', tryThis: 'Try This', a11y: 'Accessibility', goalDone: 'Goal done', highContrast: 'High Contrast', gentle: 'Gentle Mode', sendTeacher: 'Send To Teacher', sentTeacher: 'Sent to Mr. Kulibert', noFly: 'No flying in Survival', tapCorner: 'Tap Corner A first', cornerA: 'Corner A set',
    buildTools: 'Ibikoresho', exitApp: 'Sohoka', leaveAsk: 'Sohoka muri Bertopia? Isi yawe yabitswe.', leave: 'Sohoka', stay: 'Guma', myBuilds: 'Imyubakire yanjye', undoMinutes: 'Iminota ishize', snapshots: 'Amafoto', emptyBag: 'Agasaho karimo ubusa: vuna block cyangwa ugure kwa Tally', emptySlot: 'Akazu ubusa', tooBig: 'Kinini cyane: max 64 × 32 × 64', badBuild: 'Iyi dosiye si iyubakwa rya Bertopia', fineLater: 'Ibitangaje bito bizaza nyuma', changedTo: 'Byahindutse:',
    berry: 'Imbuto', flour: 'Ifu', sugar: 'Isukari', cupcake: 'Kek', bread: 'Umugati', coreplate: 'Uruhome', workbench: 'Ameza', oven: 'Ibyoto', vend: 'Counter', storeCounter: 'Counter y\'iduka', bunk: 'Buriri',
    whatsNewBody: 'Bertopia 2.5.0: Urugendo rwamashusho nintego Gerageza bigaragaza uko ukina. Hitamo umurongo wawe. Ubugingo ntibura kuguruka. Ubufasha nUbushobozi bishya, kandi wohereza amapine ku mwarimu.',
    menuHint: 'Kanda ☰ cyangwa Esc ku menu', menuHintTouch: 'Kanda ☰ ku menu', resume: 'Komeza', inventory: 'Agasaho', crafting: 'Kora', shop: 'Iduka', wallet: 'Ikibanza',
    practice: 'imyitozo', worth: 'Agaciro', tallyPays: 'Tally yishyura', youHave: 'Ufite', usedIn: 'Ikoreshwa muri', make: 'Kora', bagFull: 'Agasaho karuzuye', noItem: 'Nta {item} ufite.',
    coreplateToast: 'Uruhome. Ntacyo kirengana.', poofTown: 'Poof! Subira i Bertyville.', poofBunk: 'Poof! Subira ku buriri.', alreadyLeft: 'Iyo block yavuye mu gasaho.',
    needsOven: 'Ukeneye ibuye ry\'ububiko hafi', needsBench: 'Ukeneye ameza hafi', tallyEnough: 'Tally ahaze {item} uyu munsi', cantSell: '⚙ 0 · ntigurishwa',
    sold: 'Wagurishije {n} {item} kuri Tally', bought: 'Waguze {n} {item}', townBought: 'Umuturage yaguze {n} {item} ⚙ {cogs}',
    setHome: 'Inzu hano?', yes: 'Yego', no: 'Oya', teacher: 'Umwarimu', pin: 'PIN', priceDial: 'Igiciro', dailyCap: 'Umupaka w\'umunsi', startCogs: 'Intangiriro',
    townsfolk: 'Abaturage', resetWallet: 'Subiza ikibanza', onDevice: 'Kuri iki gikoresho gusa', pricesChanged: 'Ibiciro byahindutse', fair: 'Ukuri', yours: 'Iyawe',
    takeTill: 'Fata keshye', soldOut: 'Byarangiye: ongera', profit: 'Inyungu', spent: 'Byakoreshejwe', cogsIn: 'Byinjiye', backMenu: 'Menu', survival: 'Ubugingo',
    myCounter: 'Counter yanjye', bunk: 'Buriri', prices: 'Ibiciro', stock: 'Ibyo ufite', needMore: 'Ukeneye ⚙ {n}', shopProtected: 'Iyo nyubako isigara.',
    ingredients: 'Ibikoresho: ifu, isukari, imbuto · Oteka 10s', breadLabel: 'Ibikoresho: ifu · Oteka 8s', versionSkew: 'Isi ikoresha indi verisiyo',
  },
  ti: {
    changelog: 'Changelog', youAreHere: 'You are here', tourMove: 'Move with the pads', tourLook: 'Drag to look', tourPlace: 'Place and break', tourBar: 'Open your bag', tourShop: 'Sell to Tally', tourTools: 'Fill a box', place10: 'Place 10 blocks', fillBox: 'Fill a box', sell3: 'Sell 3 logs', helpBody: 'Tap a tile to learn', tour: 'Tour', next: 'Next', skip: 'Skip', tryThis: 'Try This', a11y: 'Accessibility', goalDone: 'Goal done', highContrast: 'High Contrast', gentle: 'Gentle Mode', sendTeacher: 'Send To Teacher', sentTeacher: 'Sent to Mr. Kulibert', noFly: 'No flying in Survival', tapCorner: 'Tap Corner A first', cornerA: 'Corner A set',
    buildTools: 'መሳርሒ', exitApp: 'ውጻእ', leaveAsk: 'ካብ በርቶፕያ ትወጽእ? ዓለምካ ተዓቂቡ።', leave: 'ውጻእ', stay: 'ጽናሕ', myBuilds: 'ህንጻታተይ', undoMinutes: 'ደቒቕ ዝሓለፈ', snapshots: 'ስእልታት', emptyBag: 'ቦርሳ ባዶ እዩ፡ ብሎክ ሰብር ወይ ካብ ታሊ ግዛእ', emptySlot: 'ባዶ ቦታ', tooBig: 'ዝያዳ ዓቢ፡ ደረት 64 × 32 × 64', badBuild: 'እዚ ፋይል ህንጻ በርቶፕያ ኣይኮነን', fineLater: 'ዝርዝር ጌጣ ጌጣ ድሒሩ', changedTo: 'ተቐይሩ:',
    berry: 'ፍረ', flour: 'ዱቄት', sugar: 'ሽኮር', cupcake: 'ኬክ', bread: 'ባኒ', coreplate: 'ኮርፕሌት', workbench: 'ሰደቓ', oven: 'እቶን', vend: 'መደብ መሸጢ', storeCounter: 'መደብ ድኳን', bunk: 'ዓራት',
    whatsNewBody: 'በርቶፕያ 2.5.0፡ ስእላዊ ዙርን ንቕሓት ፈትን እዚን ከመይ ከም ትጻወት የርእዩ። ናይ ህንጻ መስመር ምረጽ። ህይወት ኣይነፍርን። ሓገዝን ተበጻሕነትን ሓደሽቲ እዮም፡ ኮግ ናብ መምህርካ ስደድ።',
    menuHint: '☰ ወይ Esc ንመእተዊ', menuHintTouch: '☰ ንመእተዊ', resume: 'ቀጽል', inventory: 'ቦርሳ', crafting: 'ምስራሕ', shop: 'ድኳን', wallet: 'ኪስ',
    practice: 'ምልምማድ', worth: 'ዋጋ', tallyPays: 'ታሊ ይከፍል', youHave: 'ኣለካ', usedIn: 'ይውዕል ኣብ', make: 'ግበር', bagFull: 'ቦርሳ መሊኡ', noItem: '{item} የብልካን።',
    coreplateToast: 'ኮርፕሌት። ዝኾነ ኣይሓልፍን።', poofTown: 'ፑፍ! ናብ በርቲቪል ተመሊስካ።', poofBunk: 'ፑፍ! ናብ ዓራትካ ተመሊስካ።', alreadyLeft: 'እዚ ብሎክ ካብ ቦርሳኻ ወጺኡ።',
    needsOven: 'እቶን ኣብ ቀረባ የድሊ', needsBench: 'ሰደቓ ኣብ ቀረባ የድሊ', tallyEnough: 'ታሊ ሎሚ {item} እኹል ኣሎ', cantSell: '⚙ 0 · ኣይሽየጥን',
    sold: '{n} {item} ንታሊ ሸይጥካ', bought: '{n} {item} ገዚእካ', townBought: 'ሓደ ሰብ {n} {item} ብ ⚙ {cogs} ገዚኡ',
    setHome: 'ገዛ ኣብዚ?', yes: 'እወ', no: 'ኣይፋል', teacher: 'መምህር', pin: 'PIN', priceDial: 'ዋጋ', dailyCap: 'ዕለታዊ ደረት', startCogs: 'መጀመርታ',
    townsfolk: 'ሰባት', resetWallet: 'ኪስ ዳግማይ', onDevice: 'ኣብዚ መሳርሒ ጥራይ', pricesChanged: 'ዋጋ ተቐይሩ', fair: 'ፍትሓዊ', yours: 'ናትካ',
    takeTill: 'ሳንዱቅ ውሰድ', soldOut: 'ተወዲኡ፡ መልእ', profit: 'መእገዲ', spent: 'ዝወጸ', cogsIn: 'ዝኣተወ', backMenu: 'መእተዊ', survival: 'ህይወት',
    myCounter: 'መደብይ', bunk: 'ዓራት', prices: 'ዋጋታት', stock: 'ኣቕሓ', needMore: '⚙ {n} የድሊ', shopProtected: 'እቲ ህንጻ ይቕጽል።',
    ingredients: 'ኣቕሑ፡ ዱቄት፡ ሽኮር፡ ፍረ · ምሕሳስ 10 ሰ', breadLabel: 'ኣቕሑ፡ ዱቄት · ምሕሳስ 8 ሰ', versionSkew: 'እዚ ዓለም ካልእ ስሪት እዩ',
  },
}
