// Bloxbert student strings. Dari (fa-AF) is Dari, not a copy of Arabic.
export const STR = {
  en: {
    menu: 'Menu', close: 'Close', settings: 'Settings', whatsNew: "What's new", help: 'Help',
    whatsNewBody: 'The Oven fire is big and lively, and new things you craft go where you can find them.',
    redo: 'Redo', undid: 'Undid {n} blocks', redid: 'Redid {n} blocks', inspect: 'Inspect', inspectEmpty: 'No changes here yet. The world made this.', you: 'You', placed: 'placed', broke: 'broke', changed: 'changed', picked: 'Picked:',
    world: 'World', saveNow: 'Save now', loadSaved: 'Load my saved world', exportWorld: 'Export world file', importWorld: 'Import world file', freshWorld: 'Fresh world',
    mode: 'Mode', creative: 'Creative', buildTable: 'Build Table', survival: 'Survival', contest: 'Build contest', later: 'later cut',
    auto: 'Auto', lite: 'Lite', full: 'Full',
    autoHint: 'Best for most. Lowers detail if it gets slow.', liteHint: 'Fastest. For slow Chromebooks and phones.', fullHint: 'Sharpest look, farther view. Needs a fast device.',
    showSpeed: 'Show speed', textSize: 'Text size', textS: 'Small', textM: 'Medium', textL: 'Large',
    about: 'About', aboutBody: 'Bloxbert is a Solvay Tech Room build lab. The 3D engine is noa (MIT) and Babylon.js (Apache-2.0). Block art is the Kenney Voxel Pack (CC0).',
    fs: 'Full screen', fsExit: 'Exit full screen',
    fsIphone: 'For full screen on iPhone: tap Share, then Add to Home Screen.',
    flyOn: 'Flying. Double-tap Jump to land.', flyOff: 'Walking again.',
    undo: 'Undo', save: 'Save', place: 'Place', break: 'Break', jump: 'Jump',
    forward: 'Forward', left: 'Left', back: 'Back', right: 'Right',
    hub: 'Back to the Hub',
    nothingUndo: 'Nothing to undo', saved: 'Saved', loaded: 'Loaded your saved world', imported: 'World imported',
    fresh: 'Fresh Bertyville (not saved yet)', notSaved: 'Not saved yet', loading: 'Loading…',
    bertyville: 'Bertyville',
    confirmFresh: 'Start a fresh Bertyville? Your saved copy stays until you press Save.',
    lowerDetail: 'Lower detail for speed',
    tableHint: 'Build Table: drag to orbit, tap a face to place. Arrow keys move the cursor. Enter places.',
    keysHint: 'Click the world to aim. WASD move. Space jump (double-tap to fly). Left click break. Right click place.',
    creditEngine: 'Engine: noa (MIT) + Babylon.js (Apache-2.0). Block art: Kenney Voxel Pack (CC0).',
    grass: 'Grass', dirt: 'Dirt', stone: 'Stone', slate: 'Slate', coal: 'Coal stone', sand: 'Sand', gravel: 'Gravel',
    brickRed: 'Red brick', brickGrey: 'Grey brick', planks: 'Planks', log: 'Log', leaves: 'Leaves',
    woolBlue: 'Blue wool', woolGreen: 'Green wool', woolRed: 'Red wool', woolTan: 'Tan wool', snow: 'Snow', ice: 'Ice', redSand: 'Red sand', glass: 'Glass',
    needsFuel: 'Needs fuel', bakingNow: 'Baking...', takeYour: 'Take your {item}', inPockets: '{item} is in your Bag pockets',
    doorHint: 'Hold left click for door options', doorHintTouch: 'Hold on the door for options', clickToPlay: 'Click to play', showHand: 'Show hand', mainHand: 'Main hand', crouchPlace: 'Crouch + right click to place next to it.', signIn: 'Sign in', code: 'Code', signNote: 'The code and the PIN come from your teacher. Your name shows after they match.',    floorLamp: 'Floor Lamp', wallLamp: 'Wall Lamp', rug: 'Rug', placeOnWall: 'Place on a wall', decorJust: 'Just make', decorDesign: 'Design it',

  },
  uk: {
    menu: 'Меню', close: 'Закрити', settings: 'Налаштування', whatsNew: 'Що нового', help: 'Допомога',
    whatsNewBody: 'Вогонь печі великий і живий, і нові речі, які ти робиш, лягають туди, де їх знайти.',
    redo: 'Повторити', undid: 'Скасовано {n} блоків', redid: 'Повторено {n} блоків', inspect: 'Огляд', inspectEmpty: 'Тут ще немає змін. Це зробив світ.', you: 'Ви', placed: 'поставив', broke: 'зламав', changed: 'змінив', picked: 'Обрано:',
    world: 'Світ', saveNow: 'Зберегти зараз', loadSaved: 'Завантажити мій світ', exportWorld: 'Експорт файлу світу', importWorld: 'Імпорт файлу світу', freshWorld: 'Новий світ',
    mode: 'Режим', creative: 'Creative', buildTable: 'Build Table', survival: 'Виживання', contest: 'Конкурс будівель', later: 'пізніше',
    auto: 'Авто', lite: 'Легкий', full: 'Повний',
    autoHint: 'Для більшості. Зменшує деталі, якщо стає повільно.', liteHint: 'Найшвидше. Для повільних Chromebook і телефонів.', fullHint: 'Найчіткіше, далі видно. Потрібен швидкий пристрій.',
    showSpeed: 'Показати швидкість', textSize: 'Розмір тексту', textS: 'Малий', textM: 'Середній', textL: 'Великий',
    about: 'Про програму', aboutBody: 'Bloxbert — лабораторія будівництва Tech Room у Солвеї. Рушій 3D: noa (MIT) і Babylon.js (Apache-2.0). Блоки: Kenney Voxel Pack (CC0).',
    fs: 'Повний екран', fsExit: 'Вийти з повного екрана',
    fsIphone: 'Для повного екрана на iPhone: торкніть Поділитися, потім На початковий екран.',
    flyOn: 'Політ. Подвійний стрибок, щоб сісти.', flyOff: 'Знову ходьба.',
    undo: 'Скасувати', save: 'Зберегти', place: 'Поставити', break: 'Зламати', jump: 'Стрибок',
    forward: 'Вперед', left: 'Ліворуч', back: 'Назад', right: 'Праворуч',
    hub: 'Назад до Hub',
    nothingUndo: 'Нічого скасовувати', saved: 'Збережено', loaded: 'Завантажено ваш світ', imported: 'Світ імпортовано',
    fresh: 'Новий Бертівіль (ще не збережено)', notSaved: 'Ще не збережено', loading: 'Завантаження…',
    bertyville: 'Бертівіль',
    confirmFresh: 'Почати новий Бертівіль? Збережена копія лишається, доки не натиснете Зберегти.',
    lowerDetail: 'Менше деталей заради швидкості',
    tableHint: 'Build Table: тягніть, щоб обертати, торкніть грань, щоб поставити. Стрілки рухають курсор. Enter ставить.',
    keysHint: 'Клацніть світ, щоб цілитися. WASD рух. Пробіл стрибок (двічі — політ). Ліва кнопка ламає. Права ставить.',
    creditEngine: 'Рушій: noa (MIT) + Babylon.js (Apache-2.0). Блоки: Kenney Voxel Pack (CC0).',
    grass: 'Трава', dirt: 'Земля', stone: 'Камінь', slate: 'Сланець', coal: 'Вугілля', sand: 'Пісок', gravel: 'Гравій',
    brickRed: 'Червона цегла', brickGrey: 'Сіра цегла', planks: 'Дошки', log: 'Колода', leaves: 'Листя',
    woolBlue: 'Синя вовна', woolGreen: 'Зелена вовна', woolRed: 'Червона вовна', woolTan: 'Пісочна вовна', snow: 'Сніг', ice: 'Лід', redSand: 'Рудий пісок', glass: 'Скло',
    needsFuel: 'Потрібне паливо', bakingNow: 'Печеться...', takeYour: 'Забери свій {item}', inPockets: '{item} у кишенях сумки',
    doorHint: 'Тримай ліву кнопку для опцій дверей', doorHintTouch: 'Тримай на дверях для опцій', clickToPlay: 'Натисни, щоб грати', showHand: 'Показати руку', mainHand: 'Основна рука', crouchPlace: 'Присід і права кнопка, щоб поставити поруч.', signIn: 'Увійти', code: 'Код', signNote: 'Код і ПІН дає вчитель. Ім’я з’явиться, коли вони збіжаться.',
  },
  ru: {
    menu: 'Меню', close: 'Закрыть', settings: 'Настройки', whatsNew: 'Что нового', help: 'Помощь',
    whatsNewBody: 'Огонь печи большой и живой, и новые вещи, которые ты делаешь, ложатся туда, где их найти.',
    redo: 'Повтор', undid: 'Отменено {n} блоков', redid: 'Повторено {n} блоков', inspect: 'Осмотр', inspectEmpty: 'Здесь ещё нет изменений. Это сделал мир.', you: 'Вы', placed: 'поставил', broke: 'сломал', changed: 'изменил', picked: 'Выбрано:',
    world: 'Мир', saveNow: 'Сохранить сейчас', loadSaved: 'Загрузить мой мир', exportWorld: 'Экспорт файла мира', importWorld: 'Импорт файла мира', freshWorld: 'Новый мир',
    mode: 'Режим', creative: 'Creative', buildTable: 'Build Table', survival: 'Выживание', contest: 'Конкурс построек', later: 'позже',
    auto: 'Авто', lite: 'Лёгкий', full: 'Полный',
    autoHint: 'Для большинства. Уменьшает детали, если становится медленно.', liteHint: 'Самый быстрый. Для медленных Chromebook и телефонов.', fullHint: 'Самый чёткий, видно дальше. Нужно быстрое устройство.',
    showSpeed: 'Показать скорость', textSize: 'Размер текста', textS: 'Малый', textM: 'Средний', textL: 'Большой',
    about: 'О программе', aboutBody: 'Bloxbert — лаборатория стройки Tech Room в Солвее. Движок 3D: noa (MIT) и Babylon.js (Apache-2.0). Блоки: Kenney Voxel Pack (CC0).',
    fs: 'Полный экран', fsExit: 'Выйти из полного экрана',
    fsIphone: 'Для полного экрана на iPhone: нажмите Поделиться, затем На экран Домой.',
    flyOn: 'Полёт. Двойной прыжок, чтобы сесть.', flyOff: 'Снова ходьба.',
    undo: 'Отменить', save: 'Сохранить', place: 'Поставить', break: 'Сломать', jump: 'Прыжок',
    forward: 'Вперёд', left: 'Влево', back: 'Назад', right: 'Вправо',
    hub: 'Назад в Hub',
    nothingUndo: 'Нечего отменять', saved: 'Сохранено', loaded: 'Загружен ваш мир', imported: 'Мир импортирован',
    fresh: 'Новый Бертивиль (ещё не сохранён)', notSaved: 'Ещё не сохранено', loading: 'Загрузка…',
    bertyville: 'Бертивиль',
    confirmFresh: 'Начать новый Бертивиль? Сохранённая копия останется, пока не нажмёте Сохранить.',
    lowerDetail: 'Меньше деталей ради скорости',
    tableHint: 'Build Table: тяните, чтобы вращать, коснитесь грани, чтобы поставить. Стрелки двигают курсор. Enter ставит.',
    keysHint: 'Щёлкните мир, чтобы целиться. WASD движение. Пробел прыжок (дважды — полёт). Левая кнопка ломает. Правая ставит.',
    creditEngine: 'Движок: noa (MIT) + Babylon.js (Apache-2.0). Блоки: Kenney Voxel Pack (CC0).',
    grass: 'Трава', dirt: 'Земля', stone: 'Камень', slate: 'Сланец', coal: 'Уголь', sand: 'Песок', gravel: 'Гравий',
    brickRed: 'Красный кирпич', brickGrey: 'Серый кирпич', planks: 'Доски', log: 'Бревно', leaves: 'Листва',
    woolBlue: 'Синяя шерсть', woolGreen: 'Зелёная шерсть', woolRed: 'Красная шерсть', woolTan: 'Песочная шерсть', snow: 'Снег', ice: 'Лёд', redSand: 'Рыжий песок', glass: 'Стекло',
    needsFuel: 'Нужно топливо', bakingNow: 'Печётся...', takeYour: 'Забери свой {item}', inPockets: '{item} в карманах сумки',
    doorHint: 'Держи левую кнопку для опций двери', doorHintTouch: 'Держи на двери для опций', clickToPlay: 'Нажми, чтобы играть', showHand: 'Показать руку', mainHand: 'Основная рука', crouchPlace: 'Присед и правая кнопка, чтобы поставить рядом.', signIn: 'Войти', code: 'Код', signNote: 'Код и ПИН даёт учитель. Имя появится, когда они совпадут.',
  },
  es: {
    menu: 'Menú', close: 'Cerrar', settings: 'Ajustes', whatsNew: 'Novedades', help: 'Ayuda',
    whatsNewBody: 'El fuego del horno es grande y vivo, y lo nuevo que fabricas va donde puedes encontrarlo.',
    redo: 'Rehacer', undid: 'Deshiciste {n} bloques', redid: 'Rehiciste {n} bloques', inspect: 'Inspeccionar', inspectEmpty: 'Aquí no hay cambios todavía. El mundo hizo esto.', you: 'Tú', placed: 'puso', broke: 'rompió', changed: 'cambió', picked: 'Elegido:',
    world: 'Mundo', saveNow: 'Guardar ahora', loadSaved: 'Cargar mi mundo', exportWorld: 'Exportar archivo', importWorld: 'Importar archivo', freshWorld: 'Mundo nuevo',
    mode: 'Modo', creative: 'Creative', buildTable: 'Build Table', survival: 'Supervivencia', contest: 'Concurso', later: 'más tarde',
    auto: 'Auto', lite: 'Lite', full: 'Full',
    autoHint: 'Para la mayoría. Baja el detalle si va lento.', liteHint: 'El más rápido. Para Chromebooks y teléfonos lentos.', fullHint: 'El más nítido, se ve más lejos. Necesita un aparato rápido.',
    showSpeed: 'Mostrar velocidad', textSize: 'Tamaño del texto', textS: 'Pequeño', textM: 'Mediano', textL: 'Grande',
    about: 'Acerca de', aboutBody: 'Bloxbert es el laboratorio de construcción del Tech Room de Solvay. El motor 3D es noa (MIT) y Babylon.js (Apache-2.0). Los bloques son Kenney Voxel Pack (CC0).',
    fs: 'Pantalla completa', fsExit: 'Salir de pantalla completa',
    fsIphone: 'Para pantalla completa en iPhone: toca Compartir y luego Añadir a pantalla de inicio.',
    flyOn: 'Volando. Doble toque en Saltar para aterrizar.', flyOff: 'Caminando otra vez.',
    undo: 'Deshacer', save: 'Guardar', place: 'Poner', break: 'Romper', jump: 'Saltar',
    forward: 'Adelante', left: 'Izquierda', back: 'Atrás', right: 'Derecha',
    hub: 'Volver al Hub',
    nothingUndo: 'Nada que deshacer', saved: 'Guardado', loaded: 'Mundo cargado', imported: 'Mundo importado',
    fresh: 'Bertyville nuevo (aún no guardado)', notSaved: 'Aún no guardado', loading: 'Cargando…',
    bertyville: 'Bertyville',
    confirmFresh: '¿Empezar un Bertyville nuevo? La copia guardada se queda hasta que pulses Guardar.',
    lowerDetail: 'Menos detalle para ir más rápido',
    tableHint: 'Build Table: arrastra para girar, toca una cara para poner. Las flechas mueven el cursor. Enter pone.',
    keysHint: 'Haz clic en el mundo para apuntar. WASD mueve. Espacio salta (dos veces para volar). Clic izquierdo rompe. Clic derecho pone.',
    creditEngine: 'Motor: noa (MIT) + Babylon.js (Apache-2.0). Bloques: Kenney Voxel Pack (CC0).',
    grass: 'Césped', dirt: 'Tierra', stone: 'Piedra', slate: 'Pizarra', coal: 'Piedra con carbón', sand: 'Arena', gravel: 'Grava',
    brickRed: 'Ladrillo rojo', brickGrey: 'Ladrillo gris', planks: 'Tablas', log: 'Tronco', leaves: 'Hojas',
    woolBlue: 'Lana azul', woolGreen: 'Lana verde', woolRed: 'Lana roja', woolTan: 'Lana arena', snow: 'Nieve', ice: 'Hielo', redSand: 'Arena roja', glass: 'Vidrio',
    needsFuel: 'Necesita combustible', bakingNow: 'Horneando...', takeYour: 'Toma tu {item}', inPockets: '{item} está en los bolsillos de la bolsa',
    doorHint: 'Mantén el clic izquierdo para las opciones de la puerta', doorHintTouch: 'Mantén el dedo en la puerta para las opciones', clickToPlay: 'Haz clic para jugar', showHand: 'Mostrar la mano', mainHand: 'Mano principal', crouchPlace: 'Agáchate y clic derecho para poner al lado.', signIn: 'Entrar', code: 'Código', signNote: 'El código y el PIN los da tu profe. Tu nombre sale cuando coinciden.',
  },
  ar: {
    menu: 'القائمة', close: 'إغلاق', settings: 'الإعدادات', whatsNew: 'ما الجديد', help: 'مساعدة',
    whatsNewBody: 'نار الفرن كبيرة وحية، والأشياء الجديدة التي تصنعها تذهب حيث تجدها.',
    redo: 'إعادة', undid: 'تراجعت عن {n} مكعبًا', redid: 'أعدت {n} مكعبًا', inspect: 'فحص', inspectEmpty: 'لا تغييرات هنا بعد. العالم صنع هذا.', you: 'أنت', placed: 'وضع', broke: 'كسر', changed: 'غيّر', picked: 'تم الاختيار:',
    world: 'العالم', saveNow: 'احفظ الآن', loadSaved: 'حمّل عالمي المحفوظ', exportWorld: 'تصدير ملف العالم', importWorld: 'استيراد ملف العالم', freshWorld: 'عالم جديد',
    mode: 'الوضع', creative: 'إبداعي', buildTable: 'طاولة البناء', survival: 'بقاء', contest: 'مسابقة بناء', later: 'لاحقًا',
    auto: 'تلقائي', lite: 'خفيف', full: 'كامل',
    autoHint: 'الأنسب لمعظم الأجهزة. يقلل التفاصيل إذا بطؤ.', liteHint: 'الأسرع. لأجهزة كروم بوك والهواتف البطيئة.', fullHint: 'الأوضح ورؤية أبعد. يحتاج جهازًا سريعًا.',
    showSpeed: 'أظهر السرعة', textSize: 'حجم النص', textS: 'صغير', textM: 'وسط', textL: 'كبير',
    about: 'حول', aboutBody: 'بلوكسبيرت مختبر بناء في غرفة التقنية بسولفاي. محرك الثلاثي الأبعاد هو noa (MIT) و Babylon.js (Apache-2.0). رسوم المكعبات من حزمة Kenney Voxel (CC0).',
    fs: 'ملء الشاشة', fsExit: 'الخروج من ملء الشاشة',
    fsIphone: 'لملء الشاشة على آيفون: اضغط مشاركة، ثم أضف إلى الشاشة الرئيسية.',
    flyOn: 'تطير. اضغط القفز مرتين للهبوط.', flyOff: 'تمشي من جديد.',
    undo: 'تراجع', save: 'حفظ', place: 'ضع', break: 'اكسر', jump: 'قفز',
    forward: 'أمام', left: 'يسار', back: 'خلف', right: 'يمين',
    hub: 'العودة إلى الهاب',
    nothingUndo: 'لا شيء للتراجع', saved: 'تم الحفظ', loaded: 'تم تحميل عالمك', imported: 'تم استيراد العالم',
    fresh: 'بيرتيفيل جديدة (لم تُحفظ بعد)', notSaved: 'لم يُحفظ بعد', loading: 'جارٍ التحميل…',
    bertyville: 'بيرتيفيل',
    confirmFresh: 'تبدأ بيرتيفيل جديدة؟ النسخة المحفوظة تبقى حتى تضغط حفظ.',
    lowerDetail: 'تفاصيل أقل من أجل السرعة',
    tableHint: 'طاولة البناء: اسحب للدوران، المس وجهًا لتضع. الأسهم تحرّك المؤشر. Enter يضع.',
    keysHint: 'انقر العالم للتصويب. WASD للحركة. المسافة للقفز (مرتان للطيران). النقر الأيسر يكسر. الأيمن يضع.',
    creditEngine: 'المحرك: noa (MIT) + Babylon.js (Apache-2.0). الرسوم: Kenney Voxel Pack (CC0).',
    grass: 'عشب', dirt: 'تراب', stone: 'حجر', slate: 'أردواز', coal: 'حجر فحم', sand: 'رمل', gravel: 'حصى',
    brickRed: 'طوب أحمر', brickGrey: 'طوب رمادي', planks: 'ألواح', log: 'جذع', leaves: 'أوراق',
    woolBlue: 'صوف أزرق', woolGreen: 'صوف أخضر', woolRed: 'صوف أحمر', woolTan: 'صوف ترابي', snow: 'ثلج', ice: 'جليد', redSand: 'رمل أحمر', glass: 'زجاج',
    needsFuel: 'يحتاج وقوداً', bakingNow: 'يُخبز...', takeYour: 'خذ {item}', inPockets: '{item} في جيوب الحقيبة',
    doorHint: 'أبقِ النقر الأيسر لخيارات الباب', doorHintTouch: 'أبقِ إصبعك على الباب للخيارات', clickToPlay: 'انقر للعب', showHand: 'أظهر اليد', mainHand: 'اليد الأساسية', crouchPlace: 'انحنِ وانقر يميناً لتضع بجانبه.', signIn: 'تسجيل الدخول', code: 'الرمز', signNote: 'الرمز والرقم السري من معلمك. يظهر اسمك بعد أن يتطابقا.',
  },
  'fa-AF': {
    menu: 'فهرست', close: 'بستن', settings: 'تنظیمات', whatsNew: 'تازه‌ها', help: 'کمک',
    whatsNewBody: 'آتش تنور بزرگ و زنده است، و چیزهای تازه‌ای که می‌سازی جایی می‌روند که پیدایشان کنی.',
    redo: 'دوباره', undid: '{n} بلاک واپس شد', redid: '{n} بلاک دوباره شد', inspect: 'بررسی', inspectEmpty: 'اینجا هنوز تغییری نیست. جهان این را ساخته.', you: 'تو', placed: 'گذاشت', broke: 'شکست', changed: 'عوض کرد', picked: 'برگزیده:',
    world: 'جهان', saveNow: 'همین حالا ذخیره کن', loadSaved: 'جهان ذخیره‌شده‌ام را باز کن', exportWorld: 'بیرون بردن فایل جهان', importWorld: 'آوردن فایل جهان', freshWorld: 'جهان تازه',
    mode: 'حالت', creative: 'خلاق', buildTable: 'میز ساخت', survival: 'بقا', contest: 'مسابقه ساخت', later: 'بعدتر',
    auto: 'خودکار', lite: 'سبک', full: 'کامل',
    autoHint: 'برای بیشتر دستگاه‌ها. اگر آهسته شد جزئیات را کم می‌کند.', liteHint: 'سریع‌ترین. برای کروم‌بوک و تلفن آهسته.', fullHint: 'واضح‌ترین و دید دورتر. دستگاه تیز می‌خواهد.',
    showSpeed: 'سرعت را نشان بده', textSize: 'اندازه متن', textS: 'خرد', textM: 'میانه', textL: 'بزرگ',
    about: 'درباره', aboutBody: 'بلاکسبرت آزمایشگاه ساخت اتاق تخنیک سولوی است. موتور سه‌بعدی noa (MIT) و Babylon.js (Apache-2.0) است. نقش بلاک‌ها بسته Kenney Voxel (CC0) است.',
    fs: 'تمام‌صفحه', fsExit: 'بیرون شدن از تمام‌صفحه',
    fsIphone: 'برای تمام‌صفحه در آیفون: سهم را بزن، سپس به صفحه خانه اضافه کن.',
    flyOn: 'در پرواز هستی. دو بار پرش بزن تا فرود بیایی.', flyOff: 'دوباره راه می‌روی.',
    undo: 'واپس', save: 'ذخیره', place: 'بگذار', break: 'بشکن', jump: 'پرش',
    forward: 'پیش', left: 'چپ', back: 'پس', right: 'راست',
    hub: 'بازگشت به هاب',
    nothingUndo: 'چیزی برای واپس نیست', saved: 'ذخیره شد', loaded: 'جهان ذخیره‌ات باز شد', imported: 'جهان آورده شد',
    fresh: 'برتی‌ویل تازه (هنوز ذخیره نشده)', notSaved: 'هنوز ذخیره نشده', loading: 'در حال بار شدن…',
    bertyville: 'برتی‌ویل',
    confirmFresh: 'برتی‌ویل تازه شروع شود؟ نسخه ذخیره‌شده می‌ماند تا ذخیره را بزنی.',
    lowerDetail: 'جزئیات کمتر برای سرعت',
    tableHint: 'میز ساخت: بکش تا بچرخی، روی یک رخ بزن تا بگذاری. تیرها نشانگر را می‌برند. Enter می‌گذارد.',
    keysHint: 'روی جهان کلیک کن تا نشانه بگیری. WASD حرکت. فاصله پرش (دو بار برای پرواز). کلیک چپ می‌شکند. راست می‌گذارد.',
    creditEngine: 'موتور: noa (MIT) + Babylon.js (Apache-2.0). نقش بلاک: Kenney Voxel Pack (CC0).',
    grass: 'چمن', dirt: 'خاک', stone: 'سنگ', slate: 'تخته‌سنگ', coal: 'سنگ زغال', sand: 'ریگ', gravel: 'جغل',
    brickRed: 'خشت سرخ', brickGrey: 'خشت خاکستری', planks: 'تخته', log: 'تنه', leaves: 'برگ',
    woolBlue: 'پشم آبی', woolGreen: 'پشم سبز', woolRed: 'پشم سرخ', woolTan: 'پشم نخودی', snow: 'برف', ice: 'یخ', redSand: 'ریگ سرخ', glass: 'شیشه',
    needsFuel: 'سوخت لازم است', bakingNow: 'در حال پختن...', takeYour: '{item} را بردار', inPockets: '{item} در جیب‌های بکس است',
    doorHint: 'برای گزینه‌های در، کلیک چپ را نگه دار', doorHintTouch: 'برای گزینه‌ها انگشت را روی در نگه دار', clickToPlay: 'برای بازی کلیک کن', showHand: 'دست را نشان بده', mainHand: 'دست اصلی', crouchPlace: 'خم شو و راست کلیک کن تا کنارش بگذاری.', signIn: 'ورود', code: 'کود', signNote: 'کود و پین را معلم می دهد. نامت وقتی درست باشد دیده می شود.',
  },
  rw: {
    menu: 'Ibikubiyemo', close: 'Funga', settings: 'Igenamiterere', whatsNew: 'Ibishya', help: 'Ubufasha',
    whatsNewBody: 'Umuriro w\'icyoto ni munini kandi urimo ubuzima, kandi ibishya ukora bijya aho ushobora kubibona.',
    redo: 'Ongera', undid: 'Wasubije inyuma block {n}', redid: 'Wongereye block {n}', inspect: 'Suzuma', inspectEmpty: 'Nta mpinduka ziri hano. Isi ni yo yabikoze.', you: 'Wowe', placed: 'yashyize', broke: 'yavunaguye', changed: 'yahinduye', picked: 'Byahiswemo:',
    world: 'Isi', saveNow: 'Bika ubu', loadSaved: 'Fungura isi nabitse', exportWorld: 'Sohora dosiye y’isi', importWorld: 'Injiza dosiye y’isi', freshWorld: 'Isi nshya',
    mode: 'Uburyo', creative: 'Creative', buildTable: 'Build Table', survival: 'Kubaho', contest: 'Marushanwa', later: 'nyuma',
    auto: 'Auto', lite: 'Yoroheje', full: 'Yuzuye',
    autoHint: 'Ni yo myiza ku benshi. Igabanya ibisobanuro niba itinda.', liteHint: 'Ni yo yihuta. Ku Chromebook n’iterefone bitinda.', fullHint: 'Iragaragara neza, ureba kure. Ikeneye igikoresho cyihuta.',
    showSpeed: 'Erekana umuvuduko', textSize: 'Ingano y’inyandiko', textS: 'Ntoya', textM: 'Hagati', textL: 'Nini',
    about: 'Ibyerekeye', aboutBody: 'Bloxbert ni laboratoire yo kubaka ya Tech Room muri Solvay. Moteri ya 3D ni noa (MIT) na Babylon.js (Apache-2.0). Ibishushanyo bya block ni Kenney Voxel Pack (CC0).',
    fs: 'Ekarani yuzuye', fsExit: 'Sohoka mu ekarani yuzuye',
    fsIphone: 'Ku ekarani yuzuye kuri iPhone: kanda Sangiza, hanyuma Ongeraho ku rupapuro rw’urugo.',
    flyOn: 'Urimo kuguruka. Kanda kabiri ku Gusimbuka kugira ngo umanuke.', flyOff: 'Ongera kugenda.',
    undo: 'Subiza inyuma', save: 'Bika', place: 'Shyira', break: 'Vunagura', jump: 'Simbuka',
    forward: 'Imbere', left: 'Ibumoso', back: 'Inyuma', right: 'Iburyo',
    hub: 'Subira kuri Hub',
    nothingUndo: 'Nta kintu cyo gusubiza inyuma', saved: 'Byabitswe', loaded: 'Isi yawe yafunguwe', imported: 'Isi yinjiye',
    fresh: 'Bertyville nshya (ntarabikwa)', notSaved: 'Ntirabikwa', loading: 'Birimo gutunganywa…',
    bertyville: 'Bertyville',
    confirmFresh: 'Tangira Bertyville nshya? Ikopi yabitswe igumaho kugeza ukande Bika.',
    lowerDetail: 'Ibisobanuro bike kugira ngo bihute',
    tableHint: 'Build Table: kurura kugira ngo uzunguruke, kanda ku ruhande ushyire. Utwaro duhindura akerekezo. Enter ishyira.',
    keysHint: 'Kanda ku isi kugira ngo utegure. WASD igenda. Umwanya usimbuka (kabiri kuguruka). Kanda ibumoso uvunagure. Iburyo ushyire.',
    creditEngine: 'Moteri: noa (MIT) + Babylon.js (Apache-2.0). Ibishushanyo: Kenney Voxel Pack (CC0).',
    grass: 'Ibyatsi', dirt: 'Ubutaka', stone: 'Ibuye', slate: 'Ikibuye cyijimye', coal: 'Amakara', sand: 'Umucanga', gravel: 'Amabuye mato',
    brickRed: 'Itarafuri itukura', brickGrey: 'Itarafuri y’ikigina', planks: 'Imbaho', log: 'Igiti', leaves: 'Amababi',
    woolBlue: 'Ubwoya bw’ubururu', woolGreen: 'Ubwoya bw’icyatsi', woolRed: 'Ubwoya bw’umutuku', woolTan: 'Ubwoya bw’umuhondo', snow: 'Urubura', ice: 'Urubura rukomeye', redSand: 'Umucanga utukura', glass: 'Ikirahure',
    needsFuel: 'Ikeneye amakara', bakingNow: 'Birateka...', takeYour: 'Fata {item} yawe', inPockets: '{item} iri mu mifuka y\'agasaho',
    doorHint: 'Fata ibumoso ku mahitamo y\'urugi', doorHintTouch: 'Fata ku rugi ku mahitamo', clickToPlay: 'Kanda ukine', showHand: 'Erekana ukuboko', mainHand: 'Ukuboko nyamukuru', crouchPlace: 'Icarama ukande iburyo ushyire iruhande.', signIn: 'Injira', code: 'Kode', signNote: 'Kode na PIN biva ku mwarimu. Izina ryawe rigaragara nibyo bihuye.',
  },
  ti: {
    menu: 'ዝርዝር', close: 'ዕጸው', settings: 'ቅጥዕታት', whatsNew: 'ሓድሽ', help: 'ሓገዝ',
    whatsNewBody: 'ሓዊ እቶን ዓቢን ህያውን እዩ፡ ሓደሽቲ እተሰርሖም ድማ ናብ እተረኽቦም ቦታ ይኸዱ።',
    redo: 'ደጊም', undid: '{n} ብሎክ ተመሊሱ', redid: '{n} ብሎክ ደጊሙ', inspect: 'ምርምር', inspectEmpty: 'ኣብዚ ገና ለውጢ የለን። ዓለም እያ ዝሰርሓቶ።', you: 'ንስኻ', placed: 'ኣቐመጠ', broke: 'ሰበረ', changed: 'ቀየረ', picked: 'ተመሪጹ:',
    world: 'ዓለም', saveNow: 'ሕጂ ዓቅብ', loadSaved: 'ዝዓቀብኩዎ ዓለም ክፈት', exportWorld: 'ፋይል ዓለም ኣውጽእ', importWorld: 'ፋይል ዓለም ኣእቱ', freshWorld: 'ሓድሽ ዓለም',
    mode: 'ኩነታት', creative: 'Creative', buildTable: 'Build Table', survival: 'ምንባር', contest: 'ውድድር ህንጻ', later: 'ድሕሪት',
    auto: 'Auto', lite: 'ቀሊል', full: 'ምሉእ',
    autoHint: 'ንመብዛሕቱ ዝሓሸ። እንተ ዝሓለአ ዝርዝር ይቐንስ።', liteHint: 'ዝቐልጠፈ። ንዝሓለኡ Chromebookን ተለፎንን።', fullHint: 'ዝጭበጠ፡ ርሒቕ ትሪኢ። ቀልጢፍ መሳርሒ የድሊ።',
    showSpeed: 'ፍጥነት ኣርኢ', textSize: 'መጠን ጽሑፍ', textS: 'ንእሽተይ', textM: 'ማእከላይ', textL: 'ዓቢ',
    about: 'ብዛዕባ', aboutBody: 'ብሎክስበርት ናይ ሶልቬይ ቴክ ሩም ላብራቶሪ ህንጻ እዩ። ናይ 3D ሞተር noa (MIT)ን Babylon.js (Apache-2.0)ን እዩ። ስእሊ ብሎክ Kenney Voxel Pack (CC0) እዩ።',
    fs: 'ምሉእ ስክሪን', fsExit: 'ካብ ምሉእ ስክሪን ውጻእ',
    fsIphone: 'ኣብ iPhone ምሉእ ስክሪን፡ Share ጠውቕ፡ ድሕሪኡ ናብ መጀመርታ ስክሪን ወስኽ።',
    flyOn: 'ትነፍስ ኣለኻ። ንምውራድ ጅምፕ ክልተ ግዜ ጠውቕ።', flyOff: 'ደጊምካ ትኸይድ።',
    undo: 'ምለስ', save: 'ዓቅብ', place: 'ኣቐምጥ', break: 'ስበር', jump: 'ንጻ',
    forward: 'እቲ ቅድሚት', left: 'ጸጋም', back: 'ድሕሪት', right: 'የማን',
    hub: 'ናብ Hub ተመለስ',
    nothingUndo: 'ዝምለስ የለን', saved: 'ተዓቂቡ', loaded: 'ዓለምካ ተኸፊቱ', imported: 'ዓለም ኣትዩ',
    fresh: 'ሓድሽ በርቲቪል (ገና ኣይተዓቐበን)', notSaved: 'ገና ኣይተዓቐበን', loading: 'ይጽዕን ኣሎ…',
    bertyville: 'በርቲቪል',
    confirmFresh: 'ሓድሽ በርቲቪል ትጅምር? እቲ ዝዓቀብካዮ ቅዳሕ ይጸንሕ፡ ክሳብ ዓቅብ እትጠውቕ።',
    lowerDetail: 'ንፍጥነት ዝርዝር ይቐንስ',
    tableHint: 'Build Table፡ ጎተት ንምዝዋር፡ ገጽ ጠውቕ ንምቕማጥ። ቀስታት ነቲ መመልከቲ የንቀሳቕስዎ። Enter የቐምጥ።',
    keysHint: 'ዓለም ጠውቕ ንምእላይ። WASD ምንቅስቓስ። Space ምንጻ (ክልተ ግዜ ንምንፋስ)። ጸጋማይ ጠውቕ ይስብር። የማናይ የቐምጥ።',
    creditEngine: 'ሞተር: noa (MIT) + Babylon.js (Apache-2.0)። ስእሊ: Kenney Voxel Pack (CC0)።',
    grass: 'ሳዕሪ', dirt: 'ሓመድ', stone: 'እምኒ', slate: 'ጽላት', coal: 'እምኒ ከሰል', sand: 'ሑጻ', gravel: 'ጸርኒ',
    brickRed: 'ቀይሕ ሽቡክ', brickGrey: 'ሃሞሽ ሽቡክ', planks: 'ጣውላ', log: 'ጉንዲ', leaves: 'ቆጽሊ',
    woolBlue: 'ሰማያዊ ጸምሪ', woolGreen: 'ቀጠልያ ጸምሪ', woolRed: 'ቀያሕ ጸምሪ', woolTan: 'ቡናዊ ጸምሪ', snow: 'በረድ', ice: 'በረድ ዕሩይ', redSand: 'ቀያሕ ሑጻ', glass: 'መስታወት',
    needsFuel: 'ነዳዲ የድሊ', bakingNow: 'ይጥበስ ኣሎ...', takeYour: '{item} ኣውጽእ', inPockets: '{item} ኣብ ጁባ ቦርሳኻ ኣሎ',
    doorHint: 'ንኣማራጺ ማዕጾ ጸጋማይ ጠውቕ ሓዝ', doorHintTouch: 'ንኣማራጺ ኣብ ማዕጾ ሓዝ', clickToPlay: 'ጠውቕ ንምጻወት', showHand: 'ኢድ ኣርኢ', mainHand: 'ቀንዲ ኢድ', crouchPlace: 'ድንጋርን የማናይ ጠውቕ ኣብ ጥቓኡ ንምቕማጥ.', signIn: 'እቶ', code: 'ኮድ', signNote: 'ኮድን ፒንን መምህር እዩ ዝህብ። ስምካ ምስ ዝሰማማዑ ይረአ።',
  },
}
const PRACTICE_TIP = {
  en: 'Practice points: you earn them by doing new things.',
  uk: 'Очки практики: ти отримуєш їх, роблячи нове.',
  ru: 'Очки учёбы: ты получаешь их, делая новое.',
  es: 'Puntos de práctica: los ganas haciendo cosas nuevas.',
  ar: 'نقاط التدريب: تكسبها حين تفعل أشياء جديدة.',
  'fa-AF': 'امتیاز تمرین: با کار تازه به دست می‌آید.',
  rw: 'Amanota y\'imyitozo: uyabonera ukora ibishya.',
  ti: 'ነጥቢ ምልምማድ፡ ሓድሽ ነገር ብምግባር ትረኽቦ።',
}
for (const lang of Object.keys(STR)) STR[lang].practiceTip = PRACTICE_TIP[lang] || PRACTICE_TIP.en
const SLOT_COPY = {
  willMake: {
    en: 'will make {item}',
    uk: 'буде {item}',
    ru: 'будет {item}',
    es: 'hará {item}',
    ar: 'سيصنع {item}',
    'fa-AF': 'خواهد ساخت {item}',
    rw: 'bizakora {item}',
    ti: 'ክገብር {item}',
  },
  boxSlots: {
    en: '{n} of {max} slots used',
    uk: '{n} з {max} слотів зайнято',
    ru: '{n} из {max} слотов занято',
    es: '{n} de {max} huecos usados',
    ar: '{n} من {max} خانات مستخدمة',
    'fa-AF': '{n} از {max} خانه پر است',
    rw: '{n} muri {max} byuzuye',
    ti: '{n} ካብ {max} ቦታታት ተቐሚጡ',
  },
}
for (const key of Object.keys(SLOT_COPY)) for (const lang of Object.keys(STR)) STR[lang][key] = SLOT_COPY[key][lang] || SLOT_COPY[key].en
