/* Short labels the game packs do not already cover.
   fa-AF, rw, and ti need a native check. */
export const EXTRA = {
  en: {
    job: "Job", big: "Big text",
    done: "Done", locked: "Locked", now: "Now", open: "Open",
    afterPath: "After the path",
    starsJob: "Stars belong to this job",
    pathTitle: "Truss path",
    isleWallSpan: "Triangles hold. Build, then Test. On later jobs the truck stops in every bay.",
    isleWallSpire: "Triangles hold. Build, then Test. Later jobs push the top.",
    metersSpan: " m span", metersHeight: " m height",
    readOn: "Read aloud is on.", readOff: "Read aloud is off.",
    yourBuild: "Your build",
    passBuild: "Your build passed the test. ",
    passTruss: "Your truss passed the test. ",
    betHoldSoft: "You bet the truss will hold. Press Test.",
    betFallSoft: "You bet the truss will fold. Press Test.",
    thSpan: "Span", thTruck: "Truck", thWatch: "Watch", thLoad: "Load", thPush: "Push",
    truckBay: "It stops in every bay.",
    watchFold: "A missing triangle folds.",
    loadBridge: "One load hangs on the bridge.",
    loadTruss: "One load hangs on the truss.",
    watchTri: "Triangles stay. Squares fold.",
    pushTop: "The test pushes the top.",
    watchStory: "A diagonal keeps that story from folding.",
    watchDiag: "A diagonal keeps the story from folding.",
    loadTop: "A weight sits on the top.",
    goalTail: " m goal.",
    freeBuild: "Free build",
    freeLead: "Free build. Stretch beams between the dots, then Test. Levels are in ☰.",
    overBudget: "Over budget: {n} / {max} beams.",
    clearBuild: "Clear",
    clearAsk: "Clear this build?",
    myBuilds: "My builds",
    saveBuild: "Save",
    loadBuild: "Load",
    copyCode: "Copy code",
    deleteBuild: "Delete",
    deleteAsk: "Delete this build?",
    reroll: "New name",
    codeBad: "That code doesn't look right",
    codeForSpan: "This code is for Span",
    codeForSpire: "This code is for Spire",
    codeWord: "Code",
  },
  simple: {
    job: "Job", big: "Big text",
    done: "Done", locked: "Locked", now: "Now", open: "Open",
    afterPath: "After the jobs",
    starsJob: "Stars stay on this job",
    pathTitle: "Jobs",
    isleWallSpan: "Triangles hold. Build, then Test. The truck stops in every part.",
    isleWallSpire: "Triangles hold. Build, then Test. Later jobs push the top.",
    yourBuild: "Your build",
    passBuild: "Your build held. ",
    passTruss: "Your build held. ",
    betHoldSoft: "You said it will hold. Press Test.",
    betFallSoft: "You said it will fall. Press Test.",
    thSpan: "Length", thTruck: "Truck", thWatch: "Watch", thLoad: "Weight", thPush: "Push",
    truckBay: "It stops in every part.",
    watchFold: "A missing triangle folds.",
    loadBridge: "One weight hangs on the bridge.",
    loadTruss: "One weight hangs on the build.",
    watchTri: "Triangles stay. Squares fold.",
    pushTop: "The test pushes the top.",
    watchStory: "A diagonal keeps that story from folding.",
    watchDiag: "A diagonal keeps the story from folding.",
    loadTop: "A weight sits on the top.",
    goalTail: " m goal.",
    "name.span.tri": "Triangle", "name.span.deck": "Road", "name.span.diag": "Diagonal",
    "name.span.two": "Two parts", "name.span.stops": "Stops", "name.span.endbay": "End part",
    "name.span.tight": "Fewer bars", "name.span.arch": "Arch", "name.span.pier": "Post",
    "name.span.spare": "Just enough", "name.span.yours": "Your build",
    "name.spire.tri": "Triangle", "name.spire.diag": "Diagonal", "name.spire.stack": "Two stories",
    "name.spire.add": "Three stories", "name.spire.cross": "Braced", "name.spire.floors": "Taller",
    "name.spire.limit": "Fewer bars", "name.spire.shove": "Side push", "name.spire.climb": "Tall",
    "name.spire.spare": "Just enough", "name.spire.yours": "Your tower",
    freeBuild: "Free build",
    freeLead: "Free build. Stretch beams between the dots, then Test. Levels are in ☰.",
    overBudget: "Over budget: {n} / {max} beams.",
    clearBuild: "Clear", clearAsk: "Clear this build?", myBuilds: "My builds",
    saveBuild: "Save", loadBuild: "Load", copyCode: "Copy code",
    deleteBuild: "Delete", deleteAsk: "Delete this build?", reroll: "New name",
    codeBad: "That code doesn't look right",
    codeForSpan: "This code is for Span", codeForSpire: "This code is for Spire",
    codeWord: "Code",
  },
  es: {
    job: "Reto", big: "Texto grande",
    done: "Hecho", locked: "Cerrado", now: "Ahora", open: "Abierto",
    afterPath: "Después del camino",
    starsJob: "Las estrellas son de este reto",
    pathTitle: "Camino",
    isleWallSpan: "Los triángulos aguantan. Construye y prueba. El camión para en cada tramo.",
    isleWallSpire: "Los triángulos aguantan. Construye y prueba. Luego el empuje va arriba.",
    metersSpan: " m de luz", metersHeight: " m de alto",
    readOn: "Lectura en voz alta activada.", readOff: "Lectura en voz alta apagada.",
    yourBuild: "Tu construcción",
    passBuild: "Tu construcción pasó la prueba. ",
    passTruss: "Tu armadura pasó la prueba. ",
    betHoldSoft: "Apuestas a que aguanta. Pulsa Probar.",
    betFallSoft: "Apuestas a que se dobla. Pulsa Probar.",
    thSpan: "Luz", thTruck: "Camión", thWatch: "Mira", thLoad: "Carga", thPush: "Empuje",
    truckBay: "Para en cada tramo.",
    watchFold: "Si falta un triángulo, se dobla.",
    loadBridge: "Una carga cuelga del puente.",
    loadTruss: "Una carga cuelga de la armadura.",
    watchTri: "Los triángulos quedan. Los cuadrados se doblan.",
    pushTop: "La prueba empuja la cima.",
    watchStory: "Una diagonal evita que ese piso se doble.",
    watchDiag: "Una diagonal evita que el piso se doble.",
    loadTop: "Un peso está en la cima.",
    goalTail: " m de meta.",
    "name.span.tri": "Triángulo", "name.span.deck": "Tablero", "name.span.diag": "Diagonal",
    "name.span.two": "Dos tramos", "name.span.stops": "Paradas", "name.span.endbay": "Tramo final",
    "name.span.tight": "Presupuesto", "name.span.arch": "Arco", "name.span.pier": "Pilar",
    "name.span.spare": "Eficiente", "name.span.yours": "Tu puente",
    "name.spire.tri": "Triángulo", "name.spire.diag": "Diagonal", "name.spire.stack": "Dos pisos",
    "name.spire.add": "Tres pisos", "name.spire.cross": "Arriostrada", "name.spire.floors": "Más alta",
    "name.spire.limit": "Presupuesto", "name.spire.shove": "Empuje lateral", "name.spire.climb": "30 m",
    "name.spire.spare": "Eficiente", "name.spire.yours": "Tu torre",
    freeBuild: "Construcción libre",
    freeLead: "Construcción libre. Estira barras entre los puntos y pulsa Probar. Los niveles están en ☰.",
    overBudget: "Sobre el presupuesto: {n} / {max} barras.",
    clearBuild: "Vaciar", clearAsk: "¿Vaciar esta construcción?", myBuilds: "Mis construcciones",
    saveBuild: "Guardar", loadBuild: "Cargar", copyCode: "Copiar código",
    deleteBuild: "Borrar", deleteAsk: "¿Borrar esta construcción?", reroll: "Otro nombre",
    codeBad: "Ese código no parece correcto",
    codeForSpan: "Este código es de Span", codeForSpire: "Este código es de Spire",
    codeWord: "Código",
  },
  uk: {
    job: "Завдання", big: "Великий текст",
    done: "Готово", locked: "Закрито", now: "Зараз", open: "Відкрито",
    afterPath: "Після шляху",
    starsJob: "Зірки цього завдання",
    pathTitle: "Шлях",
    isleWallSpan: "Трикутники тримають. Збудуй і перевір. Вантажівка стає в кожному прольоті.",
    isleWallSpire: "Трикутники тримають. Збудуй і перевір. Далі поштовх угорі.",
    metersSpan: " м проліт", metersHeight: " м висота",
    readOn: "Читання вголос увімкнено.", readOff: "Читання вголос вимкнено.",
    yourBuild: "Твоя будова",
    passBuild: "Твоя будова витримала перевірку. ",
    passTruss: "Твоя ферма витримала перевірку. ",
    betHoldSoft: "Ти кажеш, що встоїть. Натисни Перевірити.",
    betFallSoft: "Ти кажеш, що складеться. Натисни Перевірити.",
    thSpan: "Проліт", thTruck: "Вантажівка", thWatch: "Дивись", thLoad: "Вантаж", thPush: "Поштовх",
    truckBay: "Вона стає в кожному прольоті.",
    watchFold: "Без трикутника складається.",
    loadBridge: "Один вантаж висить на мості.",
    loadTruss: "Один вантаж висить на фермі.",
    watchTri: "Трикутники стоять. Квадрати складаються.",
    pushTop: "Перевірка штовхає верх.",
    watchStory: "Діагональ не дає тому поверху скластися.",
    watchDiag: "Діагональ не дає поверху скластися.",
    loadTop: "Вага стоїть на верху.",
    goalTail: " м ціль.",
    "name.span.tri": "Трикутник", "name.span.deck": "Настил", "name.span.diag": "Діагональ",
    "name.span.two": "Два прольоти", "name.span.stops": "Зупинки", "name.span.endbay": "Крайній проліт",
    "name.span.tight": "Бюджет", "name.span.arch": "Арка", "name.span.pier": "Опора",
    "name.span.spare": "Економно", "name.span.yours": "Твій міст",
    "name.spire.tri": "Трикутник", "name.spire.diag": "Діагональ", "name.spire.stack": "Два поверхи",
    "name.spire.add": "Три поверхи", "name.spire.cross": "Розкіс", "name.spire.floors": "Вище",
    "name.spire.limit": "Бюджет", "name.spire.shove": "Боковий поштовх", "name.spire.climb": "30 м",
    "name.spire.spare": "Економно", "name.spire.yours": "Твоя вежа",
    freeBuild: "Вільна будова",
    freeLead: "Вільна будова. Протягни стрижні між точками, потім Тест. Рівні в ☰.",
    overBudget: "Понад бюджет: {n} / {max} стрижнів.",
    clearBuild: "Очистити", clearAsk: "Очистити цю будову?", myBuilds: "Мої будови",
    saveBuild: "Зберегти", loadBuild: "Відкрити", copyCode: "Копіювати код",
    deleteBuild: "Видалити", deleteAsk: "Видалити цю будову?", reroll: "Інше ім’я",
    codeBad: "Цей код не схожий на правильний",
    codeForSpan: "Цей код для Span", codeForSpire: "Цей код для Spire",
    codeWord: "Код",
  },
  ru: {
    job: "Задание", big: "Крупный текст",
    done: "Готово", locked: "Закрыто", now: "Сейчас", open: "Открыто",
    afterPath: "После пути",
    starsJob: "Звёзды этого задания",
    pathTitle: "Путь",
    isleWallSpan: "Треугольники держат. Построй и проверь. Грузовик встаёт в каждом пролёте.",
    isleWallSpire: "Треугольники держат. Построй и проверь. Дальше толчок наверху.",
    metersSpan: " м пролёт", metersHeight: " м высота",
    readOn: "Чтение вслух включено.", readOff: "Чтение вслух выключено.",
    yourBuild: "Твоя постройка",
    passBuild: "Твоя постройка выдержала проверку. ",
    passTruss: "Твоя ферма выдержала проверку. ",
    betHoldSoft: "Ты ставишь, что устоит. Нажми Проверить.",
    betFallSoft: "Ты ставишь, что сложится. Нажми Проверить.",
    thSpan: "Пролёт", thTruck: "Грузовик", thWatch: "Смотри", thLoad: "Груз", thPush: "Толчок",
    truckBay: "Он встаёт в каждом пролёте.",
    watchFold: "Без треугольника складывается.",
    loadBridge: "Один груз висит на мосте.",
    loadTruss: "Один груз висит на ферме.",
    watchTri: "Треугольники стоят. Квадраты складываются.",
    pushTop: "Проверка толкает верх.",
    watchStory: "Диагональ не даёт этому этажу сложиться.",
    watchDiag: "Диагональ не даёт этажу сложиться.",
    loadTop: "Груз стоит наверху.",
    goalTail: " м цель.",
    "name.span.tri": "Треугольник", "name.span.deck": "Настил", "name.span.diag": "Диагональ",
    "name.span.two": "Два пролёта", "name.span.stops": "Остановки", "name.span.endbay": "Крайний пролёт",
    "name.span.tight": "Бюджет", "name.span.arch": "Арка", "name.span.pier": "Опора",
    "name.span.spare": "Экономно", "name.span.yours": "Твой мост",
    "name.spire.tri": "Треугольник", "name.spire.diag": "Диагональ", "name.spire.stack": "Два этажа",
    "name.spire.add": "Три этажа", "name.spire.cross": "Раскос", "name.spire.floors": "Выше",
    "name.spire.limit": "Бюджет", "name.spire.shove": "Боковой толчок", "name.spire.climb": "30 м",
    "name.spire.spare": "Экономно", "name.spire.yours": "Твоя башня",
    freeBuild: "Свободная стройка",
    freeLead: "Свободная стройка. Протяни стержни между точками, затем Тест. Уровни в ☰.",
    overBudget: "Сверх бюджета: {n} / {max} стержней.",
    clearBuild: "Очистить", clearAsk: "Очистить эту стройку?", myBuilds: "Мои стройки",
    saveBuild: "Сохранить", loadBuild: "Открыть", copyCode: "Копировать код",
    deleteBuild: "Удалить", deleteAsk: "Удалить эту стройку?", reroll: "Другое имя",
    codeBad: "Этот код не похож на верный",
    codeForSpan: "Этот код для Span", codeForSpire: "Этот код для Spire",
    codeWord: "Код",
  },
  ar: {
    job: "مهمة", big: "خط أكبر",
    done: "تم", locked: "مغلق", now: "الآن", open: "مفتوح",
    afterPath: "بعد المسار",
    starsJob: "النجوم لهذه المهمة",
    pathTitle: "المسار",
    isleWallSpan: "المثلثات تثبت. ابنِ ثم اختبر. الشاحنة تقف في كل فتحة.",
    isleWallSpire: "المثلثات تثبت. ابنِ ثم اختبر. لاحقًا الدفع من الأعلى.",
    metersSpan: " م بحر", metersHeight: " م ارتفاع",
    readOn: "القراءة بصوت عالٍ تعمل.", readOff: "القراءة بصوت عالٍ متوقفة.",
    yourBuild: "بناؤك",
    passBuild: "بناؤك نجح في الاختبار. ",
    passTruss: "جمّلك نجح في الاختبار. ",
    betHoldSoft: "رهانك أنه يثبت. اضغط اختبار.",
    betFallSoft: "رهانك أنه ينطوي. اضغط اختبار.",
    thSpan: "البحر", thTruck: "الشاحنة", thWatch: "شاهد", thLoad: "الحمل", thPush: "الدفع",
    truckBay: "تقف في كل فتحة.",
    watchFold: "المثلث الناقص ينطوي.",
    loadBridge: "حمل واحد معلّق على الجسر.",
    loadTruss: "حمل واحد معلّق على الجملون.",
    watchTri: "المثلثات تبقى. المربعات تنطوي.",
    pushTop: "الاختبار يدفع القمة.",
    watchStory: "القطر يمنع ذلك الطابق من الانطواء.",
    watchDiag: "القطر يمنع الطابق من الانطواء.",
    loadTop: "وزن يجلس على القمة.",
    goalTail: " م هدف.",
    "name.span.tri": "مثلث", "name.span.deck": "سطح", "name.span.diag": "قطر",
    "name.span.two": "فتحتان", "name.span.stops": "وقفات", "name.span.endbay": "الفتحة الأخيرة",
    "name.span.tight": "الميزانية", "name.span.arch": "قوس", "name.span.pier": "ركيزة",
    "name.span.spare": "كفء", "name.span.yours": "جسرك",
    "name.spire.tri": "مثلث", "name.spire.diag": "قطر", "name.spire.stack": "طابقان",
    "name.spire.add": "ثلاثة طوابق", "name.spire.cross": "مدعّم", "name.spire.floors": "أطول",
    "name.spire.limit": "الميزانية", "name.spire.shove": "دفع جانبي", "name.spire.climb": "30 م",
    "name.spire.spare": "كفء", "name.spire.yours": "برجك",
    freeBuild: "بناء حر",
    freeLead: "بناء حر. مدّ القضبان بين النقاط ثم اختبر. المستويات في ☰.",
    overBudget: "فوق الميزانية: {n} / {max} قضبان.",
    clearBuild: "مسح", clearAsk: "مسح هذا البناء؟", myBuilds: "بناياتي",
    saveBuild: "حفظ", loadBuild: "فتح", copyCode: "نسخ الرمز",
    deleteBuild: "حذف", deleteAsk: "حذف هذا البناء؟", reroll: "اسم آخر",
    codeBad: "هذا الرمز لا يبدو صحيحًا",
    codeForSpan: "هذا الرمز لـ Span", codeForSpire: "هذا الرمز لـ Spire",
    codeWord: "الرمز",
  },
  "fa-AF": {
    job: "کار", big: "خط بزرگ",
    done: "تمام", locked: "بسته", now: "اکنون", open: "باز",
    afterPath: "بعد از راه",
    starsJob: "ستاره‌ها مال همین کار است",
    pathTitle: "راه",
    isleWallSpan: "سه‌گوش‌ها محکم است. بساز و امتحان کن. موتر در هر بخش می‌ایستد.",
    isleWallSpire: "سه‌گوش‌ها محکم است. بساز و امتحان کن. بعد سر را فشار می‌دهد.",
    metersSpan: " متر دهانه", metersHeight: " متر بلندی",
    readOn: "خواندن با صدا روشن است.", readOff: "خواندن با صدا خاموش است.",
    yourBuild: "ساخت تو",
    passBuild: "ساخت تو امتحان را پاس شد. ",
    passTruss: "خرپای تو امتحان را پاس شد. ",
    betHoldSoft: "گفتی می‌ماند. امتحان را بزن.",
    betFallSoft: "گفتی می‌افتد. امتحان را بزن.",
    thSpan: "دهانه", thTruck: "موتر", thWatch: "ببین", thLoad: "بار", thPush: "فشار",
    truckBay: "در هر بخش می‌ایستد.",
    watchFold: "سه‌گوش ناقص تا می‌شود.",
    loadBridge: "یک بار از پل آویزان است.",
    loadTruss: "یک بار از خرپا آویزان است.",
    watchTri: "سه‌گوش‌ها می‌مانند. چهارگوش‌ها تا می‌شوند.",
    pushTop: "امتحان سر را فشار می‌دهد.",
    watchStory: "یک کج‌خط آن طبقه را از تا شدن نگه می‌دارد.",
    watchDiag: "یک کج‌خط طبقه را از تا شدن نگه می‌دارد.",
    loadTop: "یک وزن روی سر است.",
    goalTail: " متر هدف.",
    "name.span.tri": "سه‌گوش", "name.span.deck": "کف", "name.span.diag": "کج‌خط",
    "name.span.two": "دو بخش", "name.span.stops": "ایست‌ها", "name.span.endbay": "بخش آخر",
    "name.span.tight": "بودجه", "name.span.arch": "طاق", "name.span.pier": "پایه",
    "name.span.spare": "کم‌مصرف", "name.span.yours": "پل تو",
    "name.spire.tri": "سه‌گوش", "name.spire.diag": "کج‌خط", "name.spire.stack": "دو طبقه",
    "name.spire.add": "سه طبقه", "name.spire.cross": "محکم‌شده", "name.spire.floors": "بلندتر",
    "name.spire.limit": "بودجه", "name.spire.shove": "فشار پهلو", "name.spire.climb": "30 متر",
    "name.spire.spare": "کم‌مصرف", "name.spire.yours": "برج تو",
    freeBuild: "ساخت آزاد",
    freeLead: "ساخت آزاد. میله‌ها را بین نقطه‌ها بکش، بعد امتحان کن. مرحله‌ها در ☰ است.",
    overBudget: "بیش از بودجه: {n} / {max} میله.",
    clearBuild: "پاک کردن", clearAsk: "این ساخت پاک شود؟", myBuilds: "ساخت‌های من",
    saveBuild: "ذخیره", loadBuild: "باز کردن", copyCode: "کاپی رمز",
    deleteBuild: "حذف", deleteAsk: "این ساخت حذف شود؟", reroll: "نام دیگر",
    codeBad: "این رمز درست به نظر نمی‌رسد",
    codeForSpan: "این رمز برای Span است", codeForSpire: "این رمز برای Spire است",
    codeWord: "رمز",
  },
  rw: {
    job: "Akazi", big: "Inyandiko nini",
    done: "Byarangiye", locked: "Bifunze", now: "Ubu", open: "Bifunguye",
    afterPath: "Nyuma y'inzira",
    starsJob: "Inyenyeri ni iz'iki kazi",
    pathTitle: "Inzira",
    isleWallSpan: "Amashariki araguma. Ubake uhitemo. Imodoka ihagarara muri buri gice.",
    isleWallSpire: "Amashariki araguma. Ubake uhitemo. Nyuma haterwa hejuru.",
    metersSpan: " m ubugari", metersHeight: " m uburebure",
    readOn: "Gusoma mu ijwi birakora.", readOff: "Gusoma mu ijwi birahagaze.",
    yourBuild: "Icyubatswe cyawe",
    passBuild: "Icyubatswe cyawe cyaratsinze. ",
    passTruss: "Urusenge rwawe rwaratsinze. ",
    betHoldSoft: "Wavuze ko ruzaguma. Kanda Gerageza.",
    betFallSoft: "Wavuze ko ruzagwa. Kanda Gerageza.",
    thSpan: "Ubugari", thTruck: "Imodoka", thWatch: "Reba", thLoad: "Umuzigo", thPush: "Gusunika",
    truckBay: "Ihagarara muri buri gice.",
    watchFold: "Ishariki ribuze rihinduka.",
    loadBridge: "Umuzigo umwe urarambika ku kiraro.",
    loadTruss: "Umuzigo umwe urarambika ku rusenge.",
    watchTri: "Amashariki araguma. Udushariki duciye dunahinduka.",
    pushTop: "Ikizamini gisunika hejuru.",
    watchStory: "Umurongo w'akagambane ubuza icyo kigero guhinduka.",
    watchDiag: "Umurongo w'akagambane ubuza urugero guhinduka.",
    loadTop: "Ibiro biri hejuru.",
    goalTail: " m intego.",
    "name.span.tri": "Ishariki", "name.span.deck": "Umusozi", "name.span.diag": "Akagambane",
    "name.span.two": "Ibice bibiri", "name.span.stops": "Ahahagarara", "name.span.endbay": "Igice cya nyuma",
    "name.span.tight": "Ingengo", "name.span.arch": "Umuheto", "name.span.pier": "Inkingi",
    "name.span.spare": "Ikaye", "name.span.yours": "Ikiraro cyawe",
    "name.spire.tri": "Ishariki", "name.spire.diag": "Akagambane", "name.spire.stack": "Amagorofa abiri",
    "name.spire.add": "Amagorofa atatu", "name.spire.cross": "Yashyizweho", "name.spire.floors": "Ndende",
    "name.spire.limit": "Ingengo", "name.spire.shove": "Gusunika ku ruhande", "name.spire.climb": "30 m",
    "name.spire.spare": "Ikaye", "name.spire.yours": "Umunara wawe",
    freeBuild: "Kubaka ku buntu",
    freeLead: "Kubaka ku buntu. Kurura inkingi hagati y'utudomo, hanyuma Gerageza. Ibyiciro biri muri ☰.",
    overBudget: "Hejuru y'ingengo: {n} / {max} inkingi.",
    clearBuild: "Gusiba", clearAsk: "Gusiba iki kibaho?", myBuilds: "Ibyo nakoze",
    saveBuild: "Bika", loadBuild: "Fungura", copyCode: "Kopi ya kode",
    deleteBuild: "Siba", deleteAsk: "Siba iki kibaho?", reroll: "Irindi zina",
    codeBad: "Iyi kode ntiyisa neza",
    codeForSpan: "Iyi kode ni iya Span", codeForSpire: "Iyi kode ni iya Spire",
    codeWord: "Kode",
  },
  ti: {
    job: "ስራሕ", big: "ዓቢ ጽሑፍ",
    done: "ተወዲኡ", locked: "ተዓጽዩ", now: "ሕጂ", open: "ኽፉት",
    afterPath: "ድሕሪ መንገዲ",
    starsJob: "ኮኾብ ናይዚ ስራሕ እዩ",
    pathTitle: "መንገዲ",
    isleWallSpan: "ሶስት ኩርናዕ የጸንሕ። ሰርሕ እሞ ፈትን። መኪና ኣብ ነፍሲ ወከፍ ክፋል ትዕርፍ።",
    isleWallSpire: "ሶስት ኩርናዕ የጸንሕ። ሰርሕ እሞ ፈትን። ድሒር ርእሲ ይድፋእ።",
    metersSpan: " ሜ ስፍሓት", metersHeight: " ሜ ቁመት",
    readOn: "ምንባብ ብድምጺ ይሰርሕ።", readOff: "ምንባብ ብድምጺ ጠፊኡ።",
    yourBuild: "ህንጻኻ",
    passBuild: "ህንጻኻ ፈተና ሓሊፉ። ",
    passTruss: "ትራስካ ፈተና ሓሊፉ። ",
    betHoldSoft: "ክጸንሕ እዩ ኢልካ። ፈትን ጠውቕ።",
    betFallSoft: "ክወድቕ እዩ ኢልካ። ፈትን ጠውቕ።",
    thSpan: "ስፍሓት", thTruck: "መኪና", thWatch: "ርአ", thLoad: "ጽዕነት", thPush: "ድፋእ",
    truckBay: "ኣብ ነፍሲ ወከፍ ክፋል ትዕርፍ።",
    watchFold: "ዝጎደለ ሶስት ኩርናዕ ይዛረብ።",
    loadBridge: "ሓደ ጽዕነት ኣብ ድልድል ተንጠልጢሉ።",
    loadTruss: "ሓደ ጽዕነት ኣብ ትራስ ተንጠልጢሉ።",
    watchTri: "ሶስት ኩርናዕ ይጸንሕ። ርብዒ ይዛረብ።",
    pushTop: "ፈተና ርእሲ ይድፋእ።",
    watchStory: "ሰያፍ ነቲ ደርቢ ካብ ምዝራብ የዕርፎ።",
    watchDiag: "ሰያፍ ነቲ ደርቢ ካብ ምዝራብ የዕርፎ።",
    loadTop: "ከብዲ ኣብ ርእሲ ኣሎ።",
    goalTail: " ሜ ዕላማ።",
    "name.span.tri": "ሶስት ኩርናዕ", "name.span.deck": "መንገዲ", "name.span.diag": "ሰያፍ",
    "name.span.two": "ክልተ ክፋላት", "name.span.stops": "ዕረፍቲ", "name.span.endbay": "ናይ መወዳእታ",
    "name.span.tight": "ገደብ", "name.span.arch": "ቅስቲ", "name.span.pier": "ዓምዲ",
    "name.span.spare": "ቁጠባ", "name.span.yours": "ድልድልኻ",
    "name.spire.tri": "ሶስት ኩርናዕ", "name.spire.diag": "ሰያፍ", "name.spire.stack": "ክልተ ደርብታት",
    "name.spire.add": "ሰለስተ ደርብታት", "name.spire.cross": "ተዓጊቱ", "name.spire.floors": "ነዊሕ",
    "name.spire.limit": "ገደብ", "name.spire.shove": "ድፋእ ጎኒ", "name.spire.climb": "30 ሜ",
    "name.spire.spare": "ቁጠባ", "name.spire.yours": "ግምብኻ",
    freeBuild: "ናጻ ህንጻ",
    freeLead: "ናጻ ህንጻ። ዕንጨይቲ ኣብ መንጎ ነጥብታት ሰዓብ እሞ ፈትን። ደረጃታት ኣብ ☰ እዮም።",
    overBudget: "ልዕሊ ገደብ: {n} / {max} ዕንጨይቲ።",
    clearBuild: "አጽዲ", clearAsk: "እዚ ህንጻ ይጸዳ?", myBuilds: "ህንጻታተይ",
    saveBuild: "ዓቅብ", loadBuild: "ክፈት", copyCode: "ኮድ ቅዳሕ",
    deleteBuild: "ደምስስ", deleteAsk: "እዚ ህንጻ ይደምሰስ?", reroll: "ካልእ ስም",
    codeBad: "እዚ ኮድ ጽቡቕ ኣይመስልን",
    codeForSpan: "እዚ ኮድ ናይ Span እዩ", codeForSpire: "እዚ ኮድ ናይ Spire እዩ",
    codeWord: "ኮድ",
  },
};
